### ISSUE TITLE
Transaction tab missing filter type: Minted 

### ISSUE THREAD

**Issue by lekanovic** [PIVX-Project/PIVX#100]
Under transaction tab in the second column there is a list of different types of transactions that can be filtered out. However one type that is missing is the "Minted" type, there is one called "Mined" but that one does not apply to the Pivx wallet.

**Comment by Mrs-X** [comment]
This is already addressed with the next release: https://github.com/PIVX-Project/PIVX/pull/63

Thanks a lot for your participation :+1:

**Comment by lekanovic** [comment]
Thanks Mrs-X, I will check existing issues before I file a ticket next time.
