### ISSUE TITLE
Unsupported SSL version Debian Buster

### ISSUE THREAD

**Issue by andi448** [PIVX-Project/PIVX#1020]
If i want to ./configure the source, it tells me that:

> configure: error: Detected unsupported SSL version: This is NOT supported, and may break consensus compatibility! Use '--with-unsupported-ssl' if you don't care

In your [build-unix.md](https://github.com/PIVX-Project/PIVX/blob/master/doc/build-unix.md) is written:

> sudo apt-get install **libssl-dev** libgmp-dev libevent-dev libboost-all-dev

If I install that on my system, it is version 1.1.1c-1.

Also it says:

> Note: For Ubuntu versions starting with Bionic (18.04), or Debian versions starting with Stretch, use libssl1.0-dev above instead of libssl-dev.

But there's no libssl1.0-dev package anymore for Debian Buster.

#### If so, please list the steps to reproduce below:
1. Get the recommended packages for building from [here](https://github.com/PIVX-Project/PIVX/blob/master/doc/build-unix.md)
2. ./autogen.sh
3. ./configure

### Expected behavior
The configuring should run through and should support the newer version of libssl-dev.

### Actual behavior
It throws me the error, because of the wrong libssl-dev version.

### What version of PIVX Core are you using?
Git cloned branch v.3.4.0 trying to self compile.

### Machine specs:
- OS: Debian Buster

**Comment by Warrows** [comment]
Either use the flag as suggested in the error message or use master instead of 3.4 release because the problem has been fixed.
