### ISSUE TITLE
2019-10-19 10:37:02 ERROR: CheckBlockHeader() : block version must be above 4 after ZerocoinStartHeight 2019-10-19 10:37:02 ERROR: CheckBlock() : CheckBlockHeader failed

### ISSUE THREAD

**Issue by Sabbir0174** [PIVX-Project/PIVX#1046]
I am trying to fork pivx 3.1 .After make everything when i start qt it just stucked on loading blocks .After i see debug.log and see huge this message .How can i fix this problem

**Comment by Warrows** [comment]
Sorry but this is an issue tracker for PIVX, not a fork support.
Moreover 3.1 is outdated.
