### ISSUE TITLE
File dialogue disappears prior to completing backup.

### ISSUE THREAD

**Issue by lukestokes** [PIVX-Project/PIVX#107]
I noticed this in the previous version as well, but was hoping it would go away with the latest update. I just noticed it again and mentioned it in the slack channel. I'm not sure how helpful this issue report will be since I can't really provide steps to reproduce it nor do I know what log files might be helpful to figure out what's going on.

Version: PIVX Core version v2.1.7.0-7c4e25a (64-bit) (Mac)

Problem: While staking, try to do a wallet backup. Sometimes while navigating to a save folder, the window just closes automatically prior to completing the save. I'm not sure if QT is repainting or what, but it's quite alarming when it happens, especially if you're not sure if your backup completed or not.

**Comment by sabhiram** [comment]
I just noticed the same after opening the backup dialog. If you keep the dialog open for long enough, eventually it will close :) I will try debug this later after work.

**Comment by rejectedpromise** [comment]
still relevant?

**Comment by Fuzzbawls** [comment]
this appears to no longer be an issue with my local testing on `master` again.

**Comment by Sieres** [comment]
ACK - could not reproduce on Ubuntu, PIVX 3.1.0
