### ISSUE TITLE
[GUI] Transaction details are not shown properly when hovering with mouse cursor over it

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1076]
Can you reliably reproduce the issue?
Yes.

It happens when hovering with mouse cursor over the transaction name, date or icon. Sometimes it shows full details, sometimes it is a bug like this.

What version of PIVX Core are you using?
v3.4.99 (v4.0 segregated testnet)

Machine specs:
- OS: Windows 10 Pro
- CPU: Intel i7
- RAM: 16 GB
- Disk Type (HD/SDD): SSD

![visualBug1](https://user-images.githubusercontent.com/57232689/67974239-6247e300-fc12-11e9-8977-5d9a15ecd5db.jpg)

**Comment by NoobieDev12** [comment]
One more:

![visualBug3](https://user-images.githubusercontent.com/57232689/68445643-c2262700-01da-11ea-81c9-a0fd4cb8cf23.jpg)

**Comment by NoobieDev12** [comment]
Testnet v4.0.0 RC2

OS: Windows 10 Pro

![check](https://user-images.githubusercontent.com/57232689/69685759-d795bf00-10bd-11ea-85d5-e07eca755a97.JPG)

**Comment by random-zebra** [comment]
in #1156
