### ISSUE TITLE
Recognize comma (,) as a dot (.) when typing an Amount in Send tab in 4.0 PIVX Core wallet

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1077]
Recognize/convert comma (,) into a dot (.) when typing a transaction Amount in Send tab in new PIVX 4.0 wallet.

Currently pressing a comma does not write anything. It simplifies the wallet usage.
This is a standard feature in old PIVX 3.4.0 wallet version, both comma (,) and dot (.) buttons on keyboard are recognized as dot (.) separator.

**Comment by furszy** [comment]
It's the expected behavior, only dot accepted. No need to confuse people converting characters behind scenes. The comma and the dot are not the same conceptually.

**Comment by random-zebra** [comment]
Well to be fair, it should be locale-dependent (in many countries the comma is used as decimal separator).

**Comment by furszy** [comment]
That is another point, which I'm agree (feature request). I'm not in favor of converting a character into another one behind scenes.

**Comment by NoobieDev12** [comment]
I have US keyboard, with regular numpad with dot next to 0 button. Although Windows on my PC are in English, keyboard is set to my local language to have special characters (like many non-english languages have). Imagine writing fast 10.15 PIVs that you want to send to someone quickly with such numpad, and pressing dot on numpad (which is actually comma) not getting recognized at all, it might end up sending 1015 PIVs for someone doing it in hurry with unlocked wallet.

If it’s a complicated implementation, maybe kind of a sound feedback for not recognized buttons might be first step solution. Like “error sound” for all non-numeric signs except dot. Just thinking out loud.

**Comment by NoobieDev12** [comment]
Comma (,) and Addition (+) can be recognized in Amount box if there are no numeric signs.

![comma1](https://user-images.githubusercontent.com/57232689/69766291-a974b580-1177-11ea-8503-068941a6a040.jpg)

**Comment by NoobieDev12** [comment]
This is actually solved in some of the PRs, not sure which one, but both comma and dot fully work in 4.0 wallet. Probably in 1124.

**Comment by random-zebra** [comment]
Yes https://github.com/PIVX-Project/PIVX/pull/1124.
Both comma and dot are accepted as decimal separators now.
