### ISSUE TITLE
Expanding a Settings screen to show all the options without the need for scrolling

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1078]
There is enough empty space below to expand the options, so when some of the Wallet Data, Tools, Options, Debug or Help get clicked, that it expands completely without the need of scrolling up or down, which may lead to some people being unable to find Help option after opening any of the dropping menus above.

v3.4.99 (v4.0 segregated testnet)

![check](https://user-images.githubusercontent.com/57232689/67975799-134f7d00-fc15-11e9-8c9f-22997a3689a4.JPG)

**Comment by NoobieDev12** [comment]
Issue seems to be occurring only on Windows (10). I don't have this case on Ubuntu 18.04 (same PC).
Solution should not be too complex as both Ubuntu and Windows have enough space below to expand whole menu even at smallest window size.

**Comment by random-zebra** [comment]
Closed with #1454
