### ISSUE TITLE
Complete wallet load during the initial loading phase

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1080]
Would it be possible to load the wallet completely during the initial loading process after starting up, so that users can use it as soon as it loads up (if it sync successfully), otherwise it returns feedback message that wallet did not properly synchronize.

This would skip the additional time needed when wallet is loaded and says "Synchronizing additional data..." as seen in the attached screenshot. This would be an adoption friendly feature.

![check12](https://user-images.githubusercontent.com/57232689/67978554-ac34c700-fc1a-11e9-9163-360768ae3bf0.jpg)

**Comment by Fuzzbawls** [comment]
I addressed this in Discord, but just to restart it here for historical purposes:

Yes it would be **possible** to block the loading of the wallet's main UI until layer 2 data was synchronized, but doing so would also block one's ability to do simple transactions (which do not depend on layer 2 data), as well as introduce a significant and needless waiting period in situations when the wallet is in IBD or a catching-up state.
