### ISSUE TITLE
Blank recipient field (missing addresses) when sending to 4 different addresses

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1086]
When I'm trying to send random amounts to 4 different addresses (all 4 are personal addresses), field below "Sending to: 4 recipients" is blank, I guess it should contain 4 addresses where I'm intending to send?

![multisend1](https://user-images.githubusercontent.com/57232689/68133448-ac85d880-ff20-11e9-8a2e-ec1b8af0b7e5.JPG)

**Comment by furszy** [comment]
#1126 fixes it.

**Comment by random-zebra** [comment]
Fixed in #1126
