### ISSUE TITLE
Visual bug, 3 dots between addresses

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1087]
Not sure if this is a visual bug or these 3 dots between addresses are intended to be there.

![multisend2](https://user-images.githubusercontent.com/57232689/68133747-43eb2b80-ff21-11e9-894a-2b44ca8423f8.JPG)

**Comment by furszy** [comment]
Yes, they are.

**Comment by NoobieDev12** [comment]
Alright, closing an issue then.
