### ISSUE TITLE
Clickable link to PIVX website from Core wallet

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1088]
Would it be good to put that URL to PIVX website as clickable/linkable?

![clickable1](https://user-images.githubusercontent.com/57232689/68133869-7ac14180-ff21-11e9-8b95-e1997507f3b9.JPG)

**Comment by random-zebra** [comment]
NACK.
I personally wouldn't put any clickable link inside the wallet.
Further, that would require a system call to open a web browser (which, technically, could even not be installed on the system).

**Comment by NoobieDev12** [comment]
Not a purposeful feature request, with potential security vulnerabilities. Closing.
