### ISSUE TITLE
"Synchronized" and "Cold Staking" buttons visual bug in new 4.0 wallet

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1090]
"Synchronized" when expanded by hovering the mouse cursor over it does not have the full line under it like all the other icons. Not important, but might look like it's not fully synced yet.

Also, Cold Staking icon when activated, snowflake light is turned on, but there is no line below it like there is on all the others.

![visualBug1](https://user-images.githubusercontent.com/57232689/68134042-cd9af900-ff21-11e9-978e-fcc6ff631788.jpg)

**Comment by NoobieDev12** [comment]
Just to add, visual bug exists on all different messages, including "22 hours behind…", or "Synchronizing additional data.." as it is visible in attached screenshot.

![visualBug2](https://user-images.githubusercontent.com/57232689/68443601-a881e100-01d4-11ea-9c09-9c0af7983389.jpg)

**Comment by random-zebra** [comment]
Fixed in #1133
