### ISSUE TITLE
Segfault when syncing macOS Binary 

### ISSUE THREAD

**Issue by akshaynexus** [PIVX-Project/PIVX#1092]
This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Discord](https://discord.pivx.org).

#### If so, please list the steps to reproduce below:
1. Download the segregated testnet bins
2. Wait for it to sync

### Expected behavior
should sync without segaults
### Actual behavior
Segfaults in the middle of the sync
### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of PIVX Core are you using?
3.4.99
### Machine specs:
- OS:macOS 10.14.6
- CPU:3.8 GHz Intel Core i5
- RAM:8 GB 2400 MHz DDR4
- Disk size: 1.5 tb
- Disk Type (HD/SDD): SSHD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.
https://pastebin.com/sKSMS07g

**Comment by furszy** [comment]
@akshaynexus please run latest TESTNET_multi_pr_4.0 branch. Your log is not saying why it crashed but I have possibly fixed it.

**Comment by furszy** [comment]
Fixed by #1123.

**Comment by furszy** [comment]
Closing this, issue solved.
