### ISSUE TITLE
[GUI] Transactions are changing colors red/green bug in Home Tab in 4.0 segregated testnet wallet

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1093]
Initial situation:
First transaction is Red color (although it should be green, as it was received (+300.00 zPIV))

![Situation1](https://user-images.githubusercontent.com/57232689/68165294-5d12cd00-ff5f-11e9-939e-bc6fa8907be0.jpg)

Second situation:
After hovering the mouse cursor over it, it changes color to Green (+ again visual bug from issue #1076)

![Situation2](https://user-images.githubusercontent.com/57232689/68165423-b2e77500-ff5f-11e9-88c6-9498f6f21200.jpg)

Final situation:
After moving away mouse cursor from the transaction, it stays Green.

![Situation3](https://user-images.githubusercontent.com/57232689/68165526-f510b680-ff5f-11e9-99d9-6a5a1d17771a.jpg)

This visual bug can be reproduced endlessly. To successfully reproduce the bug, point the mouse cursor on one transaction, then go with cursor to another transaction and then go back to the initial transaction. Visual bug appears with all other transactions, not just the particular one mentioned in this issue.

**Comment by random-zebra** [comment]
Fixed in #1132
