### ISSUE TITLE
Wallet Conf button within Settings->Debug->Information is unresponsive

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1095]
As title says, indefinite mouse clicking of Wallet Conf button is possible without conf file actually open.

![walletConfBug](https://user-images.githubusercontent.com/57232689/68166782-b8df5500-ff63-11e9-8cdc-e9ebb0736b72.jpg)

**Comment by random-zebra** [comment]
In #1125
