### ISSUE TITLE
Internal error when trying to change wallet passphrase (4.0 segregated testnet)

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1100]
Unable to change the wallet passphrase in 4.0 segregated testnet wallet. Returning internal error.

Can you reliably reproduce the issue?
Yes

OS: Windows 10 Pro

![internalError](https://user-images.githubusercontent.com/57232689/68443506-5476fc80-01d4-11ea-8b58-7dec0625a7fc.jpg)

**Comment by random-zebra** [comment]
Can confirm it happens on Linux as well. Nice find.
