### ISSUE TITLE
[Feature request] Restarting the wallet instead of closing after initial wallet encryption

### ISSUE THREAD

**Issue by ambassador000** [PIVX-Project/PIVX#1102]
Would it be better to shutdown and automatically restart the wallet after clicking "OK" button after initial wallet encryption, instead of shutting it down only? Assumption is that user intented to keep using the wallet after setting up a password. Restart process same as the restarting process after changing language in wallet.

![WalletRestart](https://user-images.githubusercontent.com/57232689/68445039-07e1f000-01d9-11ea-8e9d-d27182a4bf1e.jpg)

**Comment by furszy** [comment]
#2648 makes possible to encrypt the wallet without requiring a follow-up shutdown.

**Comment by furszy** [comment]
2648 merged, closing..
