### ISSUE TITLE
Unable to open payment request from file

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1103]
I created a random .txt file with an exact content inside:
pivx:y2j4SK2s8hyGm57GXYfnGEZjgLAxGMBxAi?amount=2.00

When I tried to upload that file in wallet here:

![paymentRequest2](https://user-images.githubusercontent.com/57232689/68446357-bd627280-01dc-11ea-8204-7609494ce893.jpg)

I got the following message:

![Invalid address in URI](https://user-images.githubusercontent.com/57232689/68446372-ca7f6180-01dc-11ea-83e6-892daa034e00.jpg)

Shouldn't it work that way if it is uploaded from file?

4.0 segregated testnet wallet
OS: Windows 10 Pro

**Comment by furszy** [comment]
yes.

`pivx:%address%?amount=%number%?label=%text%?message=%text%`

Will give a look.

**Comment by random-zebra** [comment]
fixed in #1131
