### ISSUE TITLE
[Feature request] Higher resolution PIVX taskbar logo

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1108]
It would be good to use highest possible quality PIVX taskbar logo to maximize the professional look:

![higherRes1](https://user-images.githubusercontent.com/57232689/68521949-3b3e8080-02a6-11ea-8f8b-7bb2c95b276e.jpg)

Also, in Send tab, I'd suggest replacement of PIVX logo with higher resolution one, and probably thinking of another logo at this place:

![higherRes](https://user-images.githubusercontent.com/57232689/68521989-b4d66e80-02a6-11ea-8643-daa391f3bd0a.jpg)

**Comment by random-zebra** [comment]
In #1127
