### ISSUE TITLE
[Feature Request] Don't force a wallet restart when saving settings

### ISSUE THREAD

**Issue by Fuzzbawls** [PIVX-Project/PIVX#1114]
Opening up this feature request for tracking/discussion as I feel it isn't of critical importance at the moment.

Currently, when saving a setting that requires a wallet restart, there is no option to postpone the restart, and the only progression path is to force the user to allow the wallet to restart itself at the time of settings save.

I think this goes against what has become accepted as "standard practice" (think OS updates), and I can see situations where a user may not wish to restart their wallet right away, and simply choose to have the new settings applied when they themselves choose to restart the wallet.

For reference, here is a list of all settings that set the `fRestartRequired` flag:

- All settings relating to proxy use and/or values (IP address/port).
- Spend zero-conf change.
- Decimal digits
- Language
- DB Cache value
- Number of script verification threads
- Allow incoming connections

Deprecated or otherwise not currently used settings:
- Show masternodes tab (depreciated/not in use).
- 3rd party transaction URLs (not in use).
- Theme (depreciated. we use a different theme system now).

**Comment by furszy** [comment]
As #1113 was merged, closing this issue.
