### ISSUE TITLE
[GUI] Visual bug, text is not shown properly in Custom Change Address window

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1144]
Text is not shown properly within Send -> Change Address window, as visible on screenshot.

![visualBug1](https://user-images.githubusercontent.com/57232689/69763952-18014580-116f-11ea-848c-c080d0211311.jpg)

**Comment by NoobieDev12** [comment]
Fixed in #1510.

**Comment by random-zebra** [comment]
closed with #1510
