### ISSUE TITLE
[Feature request] Accept Enter button same as clicking OK button

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1146]
Accepting Enter button on keyboard same as left mouse click on OK button while attempting to unlock wallet/unlock for staking.

![featureRequest5](https://user-images.githubusercontent.com/57232689/69765374-df179f80-1173-11ea-9a17-13668f7dfc07.jpg)

**Comment by NoobieDev12** [comment]
Is this solved in pull request #1163?

**Comment by akshaynexus** [comment]
Should be,yep

**Comment by random-zebra** [comment]
Yes it is. :+1: Closing.
