### ISSUE TITLE
[Feature request] Allow immediate typing after clicking Change Label button

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1150]
Allow immediate typing in Edit Address Label window after clicking Change Label button by placing cursor within text input box. Saves 1 unnecessary mouse click to that box.

![featureRequest9](https://user-images.githubusercontent.com/57232689/69769814-bcdb4d00-1186-11ea-9566-b2945612ad85.jpg)

**Comment by Fuzzbawls** [comment]
good quality-of-life request. there are other instances where the same ideology could be applied (MN setup wizard comes to mind)

**Comment by NoobieDev12** [comment]
Same thing while encrypting wallet, I'm reporting just in case issue is not solved widely within wallet.

![check14](https://user-images.githubusercontent.com/57232689/70192195-447f0980-16fb-11ea-9591-a3590a5abf22.jpg)
