### ISSUE TITLE
[Feature request] Offer checkbox option in Settings for automatic wallet locking after 30 minutes of idle

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1152]
Idea for brainstorming.

Additional checkbox option in Settings to automatically lock the wallet after 30 minutes of idle, great in cases of leaving the wallet unlocked unintentionally after sending a transaction.

2nd option:

Additional checkbox option in Settings to automatically lock the wallet after transaction has been successfully sent/completed.

**Comment by Fuzzbawls** [comment]
From a high-level standpoint, I think that it would be better to offer an option in the settings UI that would act as a catch-all option to forcibly re-lock the wallet after a send operation as opposed to starting a timer that may or may not result in an unintended re-lock.

However, an alternative approach to this could be automatic prompting of the wallet passphrase on initiating a send operation whilst the wallet is locked, which then results in an automatic re-lock once that particular send operation is completed. In this way, explicit wallet unlocks are kept separate from consequential wallet unlocks.

**Comment by NoobieDev12** [comment]
I like the second solution very much, simple and effective.

**Comment by furszy** [comment]
I opened a backport from upstream issue to add exactly this functionality 2 months ago. #1035 
No need to re-invent the wheel ;) .

**Comment by random-zebra** [comment]
Second option has been implemented in #1387 .
Should we close this one?
