### ISSUE TITLE
[GUI] Visual bug, sometimes the text is not shown properly when hovering with mouse over it

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1153]
Self-explanatory from title and screenshot below.

![visualBug2](https://user-images.githubusercontent.com/57232689/69773892-84db0680-1194-11ea-8e88-a16b75f202e4.jpg)

**Comment by furszy** [comment]
This is a redundant issue, same as #1076  . All of the tooltips have the same style. 

Closing it.
