### ISSUE TITLE
[GUI] Visual bug, sometimes the textbox is not expanded enough to show the full 3 rows of text

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1154]
Self-explanatory from title and screenshot below.

![visualBug3](https://user-images.githubusercontent.com/57232689/69774072-22ced100-1195-11ea-98bd-d8695db8082d.jpg)

**Comment by furszy** [comment]
This is a redundant issue, same as #1076 . All of the tooltips have the same style. 

Closing it.
