### ISSUE TITLE
[Feature request] If wallet is Unlocked, don't ask for a password to unlock the wallet for staking only

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1155]
If wallet is already Unlocked, makes no sense asking for a password to unlock the wallet for staking only.

![featureRequest10](https://user-images.githubusercontent.com/57232689/69775347-bd7cdf00-1198-11ea-9c64-9678cb3d3196.jpg)

**Comment by furszy** [comment]
Makes sense only when the wallet is not encrypted, otherwise it cannot be locked. Will do some modifications.

**Comment by random-zebra** [comment]
In #1160
