### ISSUE TITLE
[GUI][Feature request] Number of confirmations shown directly on transaction

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1168]
Feature request to show the number of confirmations directly on transaction **_until_** transaction is fully confirmed (number of confirmations from 0 to 6). After that, it is removed and visible same as it is right now, only by hovering the mouse cursor over it or clicking directly on each and every transaction for more details.

![featureRequest20](https://user-images.githubusercontent.com/57232689/70192803-3d58fb00-16fd-11ea-9f78-327c29a1301d.jpg)

**Comment by furszy** [comment]
NACK, it doesn't make sense at all.
The number of confirmations is not useful for the user in 99% of the occasions. It's more than fine in the tooltip as is now.

**Comment by CaveSpectre11** [comment]
I think he's referring to the box size compared to the font and text not fitting in the box.

**Comment by furszy** [comment]
Closing this.
