### ISSUE TITLE
[GUI][Feature request] Fixed/non-moving Cold Staking addresses and Contacts

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1170]
Feature request for removal of hovering the amounts in Cold Staking tab and the addresses in Contacts tab. Showing the three dots full time, removing the moving objects, visually it's just confusing.

![featureRequest22](https://user-images.githubusercontent.com/57232689/70196519-3a640780-1709-11ea-8a32-cb459450cdc7.jpg)

**Comment by random-zebra** [comment]
Agreed on this one. Especially since the three dots hovering effect sometimes get "stuck"

![Screenshot from 2019-12-05 11-23-01](https://user-images.githubusercontent.com/18186894/70226825-ce59c180-1751-11ea-8cf1-14ba20e8592f.png)

**Comment by random-zebra** [comment]
Since the stuck hovering effect is fixed, I guess we can close this one.
