### ISSUE TITLE
Impossible to send transaction larger than 7 numbers in new GUI wallet

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1182]
Unlike the old 3.4.0 wallet, the new wallet does not allow to send transaction larger than 7 numbers in total, including numbers after decimal point. Pretty much important thing to solve prior to 4.0 release.

Using the latest build from master.

![bugSendAmount](https://user-images.githubusercontent.com/57232689/70395134-0e43d180-19fc-11ea-9396-9ece122dc4fd.JPG)

**Comment by akshaynexus** [comment]
what error is given on trying to send?

**Comment by NoobieDev12** [comment]
Not an error when sending coins. Only impossibility to type in more than 7 numbers in Amount box.

**Comment by random-zebra** [comment]
It's being fixed in #1124

**Comment by random-zebra** [comment]
Fixed in #1124
