### ISSUE TITLE
2.1.7 Crashing

### ISSUE THREAD

**Issue by lekanovic** [PIVX-Project/PIVX#120]
This is what I have done
1. Installed 2.1.7
2. Removed everything from ~/.pivx folder except wallet.dat and pivx.conf
3. Synced the blockchain(took very long time)
4. Backed up the folders "blocks" and "chainstate"

Last night my wallet crashed, when I tried to start it aging, it crashed again. I removed everything from ~/.pivx and copied back the folders "blocks" and "chainstate" that I had backed up. The wallet is still crashing and I cannot use it at all.

OS: Ubuntu 14
PIVX: 2.1.7

**debug.log:**
2017-04-18 12:16:52 *** System error while flushing: CDB : Error -30974, can't open database 
2017-04-18 12:16:57 ERROR: ProcessNewBlock : ActivateBestChain failed
2017-04-18 12:16:57 ConnectBlock:

**Comment by presstab** [comment]
Are you building from source or using a binary?

**Comment by lekanovic** [comment]
I am using the binaries from the release

**Comment by lekanovic** [comment]
This looks to be a problem with my current pivx.conf file, when I have the config file below my wallet keeps crashing. Now I have removed everything except staking, and it's not crashing anymore.

rpcuser=name
rpcpassword=password
rpcallowip=127.0.0.1
listen=0
server=1
daemon=1
logtimestamps=1
maxconnections=256
staking=1
txindex=1

**Comment by lekanovic** [comment]
No, I was wrong this did not solve the problem

**Comment by presstab** [comment]
I think I have encountered problems with 'rpcallowip=127.0.0.1' before.

**Comment by lekanovic** [comment]
Should I remove it or change it to something else?

**Comment by Fuzzbawls** [comment]
Closing this since v2.1.7 is scheduled for depreciation, and an updated issue #128 has been created for the same thing in the current version.
