### ISSUE TITLE
Error creating masternode

### ISSUE THREAD

**Issue by DeanSparrow** [PIVX-Project/PIVX#1210]
![PIVX MN fail](https://user-images.githubusercontent.com/35233654/71105237-31ece180-218b-11ea-99bb-7c1f2b6674c2.jpg)

This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Discord](https://discord.pivx.org).

#### If so, please list the steps to reproduce below:
1. I follow the precise direction for creating a masternode
2. Error creating masternode  Prepare master node failed...
3.

### Expected behavior
Masternode should be created

### Actual behavior
ERROR

### Screenshots.
![PIVX MN fail](https://user-images.githubusercontent.com/35233654/71105237-31ece180-218b-11ea-99bb-7c1f2b6674c2.jpg)

### What version of PIVX Core are you using?
V4.0.0rc2  pre-compiled binary

### Machine specs:
- OS: Windows
- CPU:i5-4570 
- RAM:8GB
- Disk size:%))GB
- Disk Type (HD/SDD):HD

### Any extra information that might be useful in the debugging process.

[debug.log](https://github.com/PIVX-Project/PIVX/files/3979512/debug.log)

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by furszy** [comment]
Hi, it seems that the issue is on the tx creation. Will add proper visual explanation there to understand why your wallet was not able to create it.

**Comment by furszy** [comment]
@DeanSparrow if you can, compile master + #1211 and run the creation again. It will show you the cause of the problem in the dialog. Once you have it, paste it here and, if it's an issue, will solve it too :) .

**Comment by DeanSparrow** [comment]
@furszy I do not have the capability to compile for windows. I could never get the environment set up correctly.

**Comment by DeanSparrow** [comment]
@furszy  I tried just sending  10000 PIV and get an error 
![image](https://user-images.githubusercontent.com/35233654/71180153-95d0e200-223f-11ea-8529-eac0b414287c.png)
I have  had issues with the old wallet complaining the transaction is too large. 

This wallet does not give me an error message

**Comment by furszy** [comment]
Ok, then that is why the MN creation wizard is failing too.

You wallet has and is selecting a big number of small utxo to create the 10k tx, exceeding the max amount of permitted inputs.

You will see the error message in the next wallet version, i added it on #1211. 

Meanwhile, use the coin control and start merging your small utxo into larger ones.

**Comment by DeanSparrow** [comment]
@furszy That fixed it! Thank you!

**Comment by furszy** [comment]
good. Activate the auto-combine feature to not have to do it manually anymore.

**Comment by random-zebra** [comment]
in #1211
