### ISSUE TITLE
[Bug] Automatically scroll down to the bottom of debug console after entered command

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1214]
Feature request to return in 4.0 what 3.4.0 wallet had: automatically scroll down to the bottom after the command is typed in in debug console. Helpful when many things are already written in console. This was available in 3.4.0:

![FeatureRequest2](https://user-images.githubusercontent.com/57232689/71142577-0fed7080-2218-11ea-8b56-5c7f8683d9fe.jpg)

In 4.0 after typing a command it stays where it was and it does not show instantly the result of entered command. It currently requires mouse click first to even be able to scroll (otherwise it's "stuck" in typing box, and then has to be manually scrolled down to see the output of entered command:

![FeatureRequest1](https://user-images.githubusercontent.com/57232689/71142746-9a35d480-2218-11ea-85bf-50696ca7ce00.jpg)

**Comment by NoobieDev12** [comment]
Hmmm weird. It works now after multiple wallet restarts. Not sure what was causing an issue at the beginning. I cannot reproduce an issue again so closing the issue.

**Comment by random-zebra** [comment]
still happening some times. Leaving this open

**Comment by random-zebra** [comment]
I've noticed that this happens when the messages widget has focus (e.g. highlighting something in the output of a command). At that point the auto-scroll stops working properly.

![Screenshot from 2020-04-08 12-37-03](https://user-images.githubusercontent.com/18186894/78775095-f2ded800-7995-11ea-8fde-dff019b4dc31.png)


@NoobieDev12 , do you confirm?

**Comment by NoobieDev12** [comment]
@random-zebra not only when you select something, even when you click anywhere within the console output window. Bug occurs both on Linux and Windows. Everything else behaves like you described.

**Comment by NoobieDev12** [comment]
This seems to be working now on my end even when running 4.3.0
I'm not sure if this was intentionally fixed somewhere or it was unintentionally fixed after some recent changes in this area.

If you guys also cannot reproduce it anymore, this issue can be closed.

**Comment by random-zebra** [comment]
> This seems to be working now on my end even when running 4.3.0
> I'm not sure if this was intentionally fixed somewhere or it was unintentionally fixed after some recent changes in this area.
> 
> If you guys also cannot reproduce it anymore, this issue can be closed.

Yes, fixed on master. closing.
