### ISSUE TITLE
Wallet closes itself

### ISSUE THREAD

**Issue by vampyren** [PIVX-Project/PIVX#1216]
This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Discord](https://discord.pivx.org).

### Describe the issue
From time to time the wallet closes. Like last night i left the wallet open and this morning it was closed. It done seem to be a crash that shows any error or i would have seen a window showing some sort of error (unless its silenced). 
### Can you reliably reproduce the issue?
No
#### If so, please list the steps to reproduce below:
1. Jus start the wallet with some coins
2. Leave it be
3. Wallet closes after some time

### Expected behavior
Wallet stays open

### Actual behavior
Wallet shuts down

### Screenshots.
not much to screenshot really, using 4.0 wallet

### What version of PIVX Core are you using?
4.0.0

### Machine specs:
- OS: Win10 x64 Pro
- CPU: i7 8559U
- RAM: 32GB
- Disk size: 1GB
- Disk Type (HD/SDD): M2 Samsung 960 Evo

### Any extra information that might be useful in the debugging process.
Let me know what i can provide.

**Comment by vampyren** [comment]
[debug.log](https://github.com/PIVX-Project/PIVX/files/3983212/debug.log)

**Comment by akshaynexus** [comment]
Does it not respond before crashing or just crashes?

**Comment by vampyren** [comment]
It never happened when i was watching. Even during beta i leave it open and next day its closed.

**Comment by vampyren** [comment]
has been working fine for several days. The difference is i have taken down windows antimalware and related services. Maybe that caused the issue..... Should we close this for now?

**Comment by random-zebra** [comment]
Thanks @vampyren we can leave it open for now.
If anything related pops out, feel free to add comments here.

**Comment by random-zebra** [comment]
@vampyren is this still an issue with either 4.0.2 or 4.1 ?

**Comment by vampyren** [comment]
> @vampyren is this still an issue with either 4.0.2 or 4.1 ?

@random-zebra I dont think so, i have never seen it again, tried 4.1.99 for some time now and never crashed so we can perhaps close it if you agree.

**Comment by random-zebra** [comment]
Sure, let's close it for now. We can always re-open if it presents again.
Thanks.
