### ISSUE TITLE
[Feature request] Don't spend the previously created Masternode coins for creating a new Masternode with creation wizard

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1219]
Current Masternode Creation Wizard doesn't have any kind of coin control, so creating a 2 masternodes in a row without starting the first one will probably end up in a way that (collateral) coins from first masternode will be used/spent to create a 10.000 PIVs collateral for new (second) masternode. If wallet have more than 30k coins, is there a way for creation wizard to recognize it and use other coins from wallet instead of these 10.000 PIVs used in last transaction for first masternode creation?

**Comment by random-zebra** [comment]
Fixed in #1389
