### ISSUE TITLE
Pivx' Linux Snap unable to switch Datadir - add removable-media interface

### ISSUE THREAD

**Issue by BassHunger** [PIVX-Project/PIVX#1220]
All Snap images are isolated by default, which is good for security but Pivx 4 is compiled only with the following 4 interfaces: desktop, network, network-bind + x11  all only depending to network + graphics.

There are 2 possibilities to get the Datadir working on another HDD.

1. Recompile the Snap with removable-media, then it's easy to mount HDDs to /media and get them included.

(2. way isn't secure, cause it would need the arguments for a Snap classic install)

https://snapcraft.io/docs/supported-interfaces

Would be glad if the "removable-media" interface would be added with the next PIVX Version. Ppl can still decide on their own if they want to plug the interface on.

**Comment by Fuzzbawls** [comment]
Which channel (stable or beta)? if you haven't tried the beta channel yet, could you?

**Comment by BassHunger** [comment]
tried only the stable - will try beta in the coming days

merry Xmas

**Comment by Fuzzbawls** [comment]
@BassHunger requesting an update to this. I have gone ahead and added the `removable-media` plug to the stable channel for the `v4.0.2` release, if you would rather test it with that instead of the beta channel.
