### ISSUE TITLE
Hot wallet is returning "waiting for remote activation" while it's not fully synced

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1226]
There is a weird thing when setting up a Masternode that should be changed I guess, as it doesn't make much sense. After starting a hot wallet on Linux VPS, after it successfully loads all blocks it returns:

```
2019-12-19 13:27:58 ProcessNewBlock : ACCEPTED Block 2126550 in 6 milliseconds with size=983
2019-12-19 13:27:58 CActiveMasternode::ManageStatus() - not capable: Hot node, waiting for remote activation.
```

However, if you try to start the Masternode from remote (controller) wallet right after that message, it will NOT start successfully, it will probably get stuck or even freeze the wallet so it needs a restart. Or even worse, you might end up needing to create a whole new masternode.

Why is the wallet returning this message "Hot node, waiting for remote activation.", if the ONLY right message when masternode should be started from remote wallet is:

```
2019-12-19 13:31:01 CMasternodeSync::GetNextAsset - Sync has finished
2019-12-19 13:31:01 CActiveMasternode::ManageStatus() - not capable: Hot node, waiting for remote activation.
```

**Comment by random-zebra** [comment]
What is the issue here?
"Hot node, waiting for remote activation." means that `masternode=1` but no mnb has been received from controller yet. If the collateral tx has enough confirmations, the masternode will successfully activate upon receiving the start from the controller.
I don't see how you could possibly "end up needing to create a whole new masternode".

**Comment by NoobieDev12** [comment]
Doesn't "Hot node, waiting for remote activation." sounds like it is waiting for a Cold wallet to click Start a masternode? IMO, to average people it sounds like it is expecting Start All to be clicked in Controller wallet, which wouldn't do anything prior to enough collateral tx confirmations.

Wouldn't be better not to confuse people, either return message to wait 15 confirmations or so, or just return message when masternode is ready to be started from Controller wallet?


> I don't see how you could possibly "end up needing to create a whole new masternode".
It happened to me while there was still 3.X.X wallet in use. I cannot replicate it anymore so can't say a reason why it got "stuck". Anyways, above is the suggestion to prevent possible doubts and questions, which might be happening as it basically needs to wait ~15 minutes prior to starting a masternode. With new wallet, loading up will be faster and more people will get into that situation more often, IMHO.

**Comment by random-zebra** [comment]
A warning about the need for confirmations is now presented __in the controller__ after creation with the wizard. Further, the controller now **cannot** send the start message when the collateral is not mature (#1389 point 2).
I don't think that MNO should rely on the hot node debug for this.

**Comment by random-zebra** [comment]
Closing with #1508

**Comment by lucablighthl** [comment]
Is it possible to save something on the VPS for when the masternode isn't enabled anymore before 1 hour, then that can make the masternode becomes enabled again without a restart it in the control wallet?
