### ISSUE TITLE
Staking reward with 1 confirmation on blockchain got removed from transaction list

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1227]
There is a weird thing happened 2 times now in front of my eyes, I noticed it unintentionally. I won a staking reward and it showed up in my 4.0 wallet transactions list. Although it was immature, it had 1 confirmation on blockchain. After couple minutes, that reward got erased from the transaction list completely, just like it never happened. Neither stayed as orphan stake neither as conflicted, just removed completely.

Before:
![before](https://user-images.githubusercontent.com/57232689/71324314-c766d900-24dd-11ea-81b6-b140013b75ed.jpg)

After couple minutes:
![after](https://user-images.githubusercontent.com/57232689/71324320-ce8de700-24dd-11ea-92b1-d22a9db494aa.jpg)

Debug log is also attached.
[debug.txt](https://github.com/PIVX-Project/PIVX/files/3992659/debug.txt)

**Comment by furszy** [comment]
Orphans are not shown in the GUI by default now (no need to as them adds really nothing to the whole user experience and only confuse them with a transaction that will never be part of the chain -- users cannot do really much to "correct orphans" now, and this will be much tight once the new time protocol gets enforced).

So well, most likely your transaction orphaned and the wallet hided it.

Possibly, need to add a new label on stakes with less than 6 confirmations (as minimum) to let the users know that this could happen. The node is always following the largest chain, and reorganizing if them find a larger one. It's the blockchain behavior, forks are part of the design.

**Comment by NoobieDev12** [comment]
Got it. Then this issue is ready for closing, except you guys want it to stay opened until this last part of the furszy's comment get implemented.
