### ISSUE TITLE
[GUI] Staking Rewards Chart counts Orphan Stakes

### ISSUE THREAD

**Issue by CaveSpectre11** [PIVX-Project/PIVX#1232]
### Describe the issue

Staking statistics doesn't remove orphan stakes from the counts.

### Expected behavior

Counts should only show stakes in the main chain, and not stakes that have been determined to be orphans.

### Actual behavior
Counts show orphan stakes (in daily, monthly and annual numbers).  One other strange thing is that it occasionally pops up that I received a stake, perhaps a stale message but it doesn't show in the transactions list, and the staking statistics bump up one.  When I go to a different tab, and back, the extra stake goes away.  However the count is still the total of stakes received and orphan stakes.

### What version of PIVX Core are you using?
4.0

### Machine specs:
- OS: Windows 7 Pro

**Comment by furszy** [comment]
Hey @CaveSpectre11, when you can, please run #1240 and let me know if this was solved.

**Comment by random-zebra** [comment]
Closed in #1240
