### ISSUE TITLE
Version 2.2.0 arm version Crash.

### ISSUE THREAD

**Issue by dsutil** [PIVX-Project/PIVX#124]
After update to the last version 2.2.0 from 2.1.7 my raspberry, I'm getting the following error:

pivxd: main.cpp:2300: bool ConnectBlock(const CBlock&, CValidationState&, CBlockIndex*, CCoinsViewCache&, bool): Assertion `hashPrevBlock == view.GetBestBlock()' failed.

After the error the process crash.

My raspberry is a raspberry 2 Modelo B with raspbian version 8

**Comment by dsutil** [comment]
I have tried also a -reindex and the program return a segfault.

**Comment by dsutil** [comment]
I'm syncing from scratch. I will update with the result.

**Comment by sabhiram** [comment]
`-reindex` segfaults immediately? Can you post any other details on the fault etc?

**Comment by dsutil** [comment]
Yes. Immediately. After sync from scratch I don't get the error. I have lost the logs (I don't know why because I don't delete the logs, but the logs only has few lines). So I can give little help, sorry.
