### ISSUE TITLE
My PIVX address (DTufZ2KFCE94yAbEBXHNWih6z3vsz5pCxx)  not found in new blockchain explorer 

### ISSUE THREAD

**Issue by khomauthiensu** [PIVX-Project/PIVX#1244]
This is my PIVX address (old)  : DTufZ2KFCE94yAbEBXHNWih6z3vsz5pCxx
It has history transaction on this address but I not found this address in blockchain now.
I has just send some PIVX from Cobo wallet (mobi wallet service) to my desktop wallet (GUI) V4.0.0 with that address but my transaction not confirm.
Pls give me advice

**Comment by random-zebra** [comment]
The transaction is shown on block explorers. Your wallet probably needs to finish the sync.
Please don't use github issue tracker for support questions, join discord if you need help-
