### ISSUE TITLE
Windows wallet - Staking Disabled

### ISSUE THREAD

**Issue by mountassir** [PIVX-Project/PIVX#1246]
Hello, my v4.0 wallet has been running and staking since the wallet was released (a few weeks ago).

The wallet however has stopped staking since yesterday 7th Jan and it now shows "Staking Disabled" in the GUI.

This is on Windows 10, the wallet is unlocked for staking and has been fully synced (checked against the PIVX explorer). 

I tried restarting the wallet multiple times but that did not help. I don't see anything related to staking in debug.log.

Is there a way to find out what is preventing the wallet from staking? It would actually be useful if the wallet provides such info in the GUI.

**Comment by random-zebra** [comment]
Hi @mountassir 
It could be a visual bug, we are currently looking into it (https://github.com/PIVX-Project/PIVX/pull/1245).
What is the output of `getstakingstatus` command (settings-->debug-->console)?

**Comment by mountassir** [comment]
Interesting, this is the output I get from `getstakingstatus`

`{
  "validtime": true,
  "haveconnections": true,
  "walletunlocked": true,
  "mintablecoins": true,
  "enoughcoins": true,
  "mnsync": true,
  "staking status": true
}`

**Comment by random-zebra** [comment]
Yes, then it should be just a visual issue in the GUI but the wallet is actually staking.
Will be fixed in next version.

**Comment by mountassir** [comment]
Thanks!
