### ISSUE TITLE
Can't unlock remote masternode with version 2.2.0

### ISSUE THREAD

**Issue by dsutil** [PIVX-Project/PIVX#125]
After migrated remote masternode an client to 2.2.0. I can't start remote masternode because it gives the error Wallet is locked. In the client 2.2.0 I unlock wallet but when I execute masternode start-all the wallet lock and returns the error wallet is locked. With masternode version  2.2.0 and client 2.1.7 I can start remote masternode without problem.
The OS of the masternode is Debian and the OS of the client is Debian also.

**Comment by Fuzzbawls** [comment]
Need to have the controller wallet fully unlocked, not just unlocked for anonymization and staking only

**Comment by dsutil** [comment]
Yes. I know. I think that I tried to full unlock the wallet (with the 2.1.7 I have no problem). I'll retry and paste more data.

**Comment by dsutil** [comment]
I have tried again and now it works ok with 2.2.0 version QT. It seems like a puntual problem.
