### ISSUE TITLE
Transactions screen not showing recent

### ISSUE THREAD

**Issue by borris345** [PIVX-Project/PIVX#1257]
Used an old backup from 2016. When wallet has rescanned and loaded it is only showing the transactions that are stored in the backup - 2016 ones.

When I receive a reward using that backup it then shows a single 2020 transaction and the 2016 ones but no others from 2020, 2019, 2018, 2017.

Chain was synced.

Funds are correct just GUI transaction problem.

**Comment by random-zebra** [comment]
Candidate fix: #1267

**Comment by random-zebra** [comment]
Closed with #1267
