### ISSUE TITLE
Invisible checkbox for anonymization and staking only

### ISSUE THREAD

**Issue by claydigger** [PIVX-Project/PIVX#127]
Checkbox is invisible in the Unlock section entitled: For anonymization and staking only
Issue was present in both 2.1.7 and 2.2.0 wallets under arm-linux build running on Raspberry Pi ver 3b
 
![image](https://cloud.githubusercontent.com/assets/11659040/25207789/c4b555ac-253e-11e7-8b06-adb983d44ee3.png)

PIVX bug bounty address D6wdF9EAznavqt5kdtA8aYQimTkkLsJsJ4

**Comment by ryanwdavies** [comment]
I have the same experience with 2.2.0 on Linux 64-bit.

The checkbox is invisible (although can be "ticked"), and once unlocked the Wallet indicates that it is steaking, regardless of the checkbox status.

**Comment by Mrs-X** [comment]
This issue depends on the combination of operating system, desktop (e.g. KDE, Unity, etc...) and chosen desktop theme, and a couple of additional desktop settings, so it's difficult the find the real reason behind this.

However, https://github.com/PIVX-Project/PIVX/pull/131 will most probably fix the issue.
If not feel free to reopen this issue or create a new one.
