### ISSUE TITLE
[POW][Bug] Mining does not work

### ISSUE THREAD

**Issue by inshakovav** [PIVX-Project/PIVX#1285]
**Summary:**
The Wallet app (pivx-qt) gives the mining error after a restart.

**Steps to Reproduce:**
1. Start the wallet pivx-qt
2. Start mining using the command:
setgenerate true
3. Restart the pivx-qt
4. Start mining again.

**Expected Results:**
Generate next block

**Actual Results:**
We get the error: "_**ERROR: PIVXMiner : generated block is stale**_"

Most likely the error appeared after the commit:
furszy committed on 17 Dec 2019
4976c0a7ecaacd62e4b97086a32c9a3f1f0627a1

Perhaps, after the wallet reboots, the variable
g_best_block in file src/miner.cpp
is not correctly initialized at startup.

**Comment by random-zebra** [comment]
PoW phase has ended both on mainnet and testnet. Only staking allowed now.
You can mine on regtest with the `generate` RPC.
