### ISSUE TITLE
2.2 is stuck in "Synchronizing additional data: 50%" forever and not moving to staking

### ISSUE THREAD

**Issue by akhavr** [PIVX-Project/PIVX#129]
Initially mentioned [here](https://github.com/PIVX-Project/PIVX/issues/106#issuecomment-295658757).

Nothing unusual in the `.debug.log`

**Comment by presstab** [comment]
Try restarting the wallet. I have seen people report that a restart got the wallet over the 50% mark, and others that said waiting it out is what worked.

**Comment by baltcoinh** [comment]
Don't know if a code issue itself or related to any trial of net attack or similar, But you can read a solution in:
https://forum.pivx.org/t/wallet-stuck-while-synchronizing-masternodes/852

Salute

**Comment by Fuzzbawls** [comment]
`mnsync reset` is an option that resets the syncing of the additional data.

**Comment by akhavr** [comment]
Well, `mnsync reset` doesn't help unless I artificially limit the set of nodes, I connect to, to the ones, specified on [the forum](https://forum.pivx.org/t/wallet-stuck-while-synchronizing-masternodes/852/9)
