### ISSUE TITLE
[RFC] Bump Minimum Qt Version to 5.5

### ISSUE THREAD

**Issue by Fuzzbawls** [PIVX-Project/PIVX#1292]
We currently only support Qt 5's major version and above, however that minimum version requirement is now sorely outdated and could benefit from additional minimum version scrutiny so as to allow for newer functionalities.

Qt itself no longer supports versions prior to 5.9, and we use 5.9 in our gitian release process. However, **we** must take into consideration the latest version that is available to various OS distros (mainly linux) and come up with a reasonable minimum supported Qt version for ourselves.

Here are various distro versions and their latest Qt versions, and their end of standard support (or EOL dates), for reference. Any more recent version not listed below already provides a Qt version at or above 5.9:

Ubuntu "Trusty" 14.04 - Qt 5.2 - standard support **ended** in April 2019
Ubuntu "Xenial" 16.04 - Qt 5.5 - standard support until April 2021
Ubuntu "Bionic" 18.04 - Qt 5.9 - standard support until April 2023

Debian "Jessie" 8 - Qt 5.3 - standard support **ended** June 2018
Debian "Stretch" 9 - Qt 5.7 - standard support until ~2020
Debian "Buster" 10 - Qt 5.11 - standard support until ~2022

Fedora 22 - Qt 5.4 - EOL'd in July 2016
Fedora 23 - Qt 5.6 - EOL'd in December 2016
Fedora 24 - Qt 5.6 - EOL'd in August 2017
Fedora 25 - Qt 5.7 - EOL'd in December 2017
Fedora 26 - Qt 5.9 - EOL'd in May 2018

CentOS 6 - Qt 5.6 - EOL in November 2020
CentOS 7 - Qt 5.9 - EOL in June 2024
CentOS 8 - Qt 5.11 - EOL in May 2029

Given the above information, I think a "safe" minimum supported Qt version would be Qt 5.5 for the time being, with followup future review as the need arrises.

**Comment by akshaynexus** [comment]
macos seems to give 5.1x qt versions ,ie from Homebrew,maybe it should be supported ?if s minimum is set that is

**Comment by Fuzzbawls** [comment]
@akshaynexus not sure I understand what you're saying/asking. AFAIK **newer** versions of Qt work. This is about removing support for long outdated versions of Qt so we don't need to maintain pre-compiler workarounds or use old/outdated methods for such old versions.

**Comment by random-zebra** [comment]
I fully agree with bumping the minimum supported Qt version to 5.5

**Comment by furszy** [comment]
Me too, fully agree on 5.5 minimum version. Cleaner code.
