### ISSUE TITLE
[Feature request] Ask if user have previous wallet backup during the initial wallet startup

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1310]
Example: I have a friend that is complete newbie in crypto and I gifted him brand new encrypted wallet.dat with some coins on it. Seeing what "regular users" have to go through to only import wallet.dat file is not much user friendly IMHO. Two examples:
1. On Windows, AppData folder is hidden by default, so an average user could spend a lot of time until he realizes he should go to View -> and check "Hidden items" in order to see it.
![check1](https://user-images.githubusercontent.com/57232689/73293109-93c94e00-4203-11ea-8c4c-0b58b2bbe883.JPG)

2. If that gift/backup is not named already "wallet.dat", newbie will probably copy-paste it without renaming it. Even if he renames the file, he might do mistake with name like "wallet.dat.dat" or something similar.

**Solution and feature request:** 

During the initial wallet startup, ask the user if he has previous wallet backup or not. **If user clicks "Yes"**, it will open up new window similar to the one that currently opens up in 4.0 wallet when user clicks "Where - > Select folder..." for choosing a location for creating wallet backup. So, then the user selects where is his "wallet.dat" file and then click "Import". After that, wallet will automatically copy, rename and paste that selected backup file to PIVX directory (so it doesn't matter if file was initially named as "pivxwalletbackup123.dat")
This step skips the step where wallet automatically creates new wallet.dat file that user have to delete later when replacing it with backup wallet file.

**If user clicks "No"**, wallet will act same as it acts right now.

**Comment by random-zebra** [comment]
NACK.

First of all, I don't think that gifting a pre-loaded wallet to a newbie is a good introduction.
First rule to learn is "not your keys, not your coins": he cannot be sure that you didn't make a copy of that wallet, and with HD wallets, you would be able to spend not only the gifted coins, but also any other coin that he would later send to any of the addresses derived from the seed.
It would be much better to teach him how to create (and backup) an empty wallet, get a receiving address, and then **send** some coins to him.

Second, the flow you describe is not immediately implementable, as the empty wallet.dat is created *before* launching the GUI interface.
