### ISSUE TITLE
[GUI] Transaction date issue

### ISSUE THREAD

**Issue by CaveSpectre11** [PIVX-Project/PIVX#1346]
### Describe the issue
Sending a transaction showed on the Transactions page with the wrong date.

### Can you reliably reproduce the issue?
I have not tried

### Expected behavior
Correct date should be shown

### Actual behavior
Incorrect date is shown on the windows Qt Wallet; but not an Ubuntu Qt Wallet

### Additional details
The problem seems to be related to the transaction timestamp:
Block Explorer:
```
  "time": 1581386295,
  "blocktime": 1581386295
```
Ubuntu `gettransaction`:
```
  "blocktime": 1581386295,
  "time": 1581386293,
  "timereceived": 1581386293,
```
Windows `gettransaction`:
```
  "blocktime": 1581386295,
  "time": 1578904590,
  "timereceived": 1581386284,
```

Note the time difference in the Windows `gettransaction` vs. the timereceived; so likely the root of the issue is somewhere in `CWallet::ComputeTimeSmart()`

### What version of PIVX Core are you using?
4.0.2

### Machine specs:
- OS: Windows 7

**Comment by random-zebra** [comment]
@CaveSpectre11 thanks for the report: pretty detailed and useful as usual.

Would you mind trying again with #1565 ?
Ideally, the behavior (for sendToSelf txes) should be `time = timereceived` until the tx is in the mempool, then, as soon as its included in a block, should change to `time = blocktime`
