### ISSUE TITLE
[RPC] masternodecurrent != getmasternodewinners

### ISSUE THREAD

**Issue by stakecube** [PIVX-Project/PIVX#1348]
### Describe the issue 
'masternodecurrent' returns the first mn from list, but this is not the actual current winner. 

### Can you reliably reproduce the issue?
1. getblockcount
2. masternodecurrent
3. getmasternodewinners
4. listmasternodes

### Expected behavior
Should masternodecurrent not return the winner instead of the mn on rank 1?

### What version of PIVX Core are you using?
v4.0.2, v2.3 tested

```
09:08:37
getblockcount

09:08:37
2217343


09:08:41
getmasternodewinners

09:08:41
[
  {
    "nHeight": 2217343,
    "winner": {
      "address": "D5CmbndCXiBUdjyV67oEvkKMd12nf3XRmv",
      "nVotes": 10
    }
  },
]


09:08:44
masternodecurrent

09:08:44
{
  "protocol": 70918,
  "txhash": "460be84bb8e881a242c3c251f49705471d3a1a5e35c9f37781ecf7c8cf2a39f8",
  "pubkey": "DPTUe1AXFe4TGPwkWsVfk6iUZmekQ7suoN",
  "lastseen": 1582275712,
  "activeseconds": 3953846
}


09:10:12
listmasternodes

09:10:12
[
  {
    "rank": 1,
    "network": "ipv4",
    "txhash": "460be84bb8e881a242c3c251f49705471d3a1a5e35c9f37781ecf7c8cf2a39f8",
    "outidx": 1,
    "pubkey": "04b85bf9fc5123db77afdc8bf2f812835f7cf44cbea64c5786f9352ac68712736d14ea0b72bab682fde242bd950f3089f705fe4b35e5a02cae5a4761f8833cb369",
    "status": "ENABLED",
    "addr": "DPTUe1AXFe4TGPwkWsVfk6iUZmekQ7suoN",
    "version": 70918,
    "lastseen": 1582275712,
    "activetime": 3953846,
    "lastpaid": 1582167351
  },
]
```
https://explorer.pivx.link/block/8428984bf10fed26cdac6b172bb0c609f463a220e6f4eb0d7b08e3980df96510

**Comment by random-zebra** [comment]
> Should masternodecurrent not return the winner instead of the mn on rank 1?

Yes. It should return the next masternode scheduled to be paid. Not the rank-1 masternode. This is indeed a bug. Thanks for pointing it out.
