### ISSUE TITLE
[Feature request] Don't spent Cold Stake delegations if there are available (and non-staking) coins in wallet

### ISSUE THREAD

**Issue by innocent-saeed36** [PIVX-Project/PIVX#1349]
This issue is partially related to #1219. Problem is that I had in wallet significantly larger amount of coins than were needed to create a Masternode collateral, but although coins that were "free" with 50+ confirmations on blockchain...they weren't used. Masternode Creation Wizard took the coins that were "locked" and delegated for Cold Staking instead. So, this feature request is to make Masternode Creation Wizard "smarter" or simply allow Coin Control feature in Masternodes tab to prevent such scenarios.

**Comment by random-zebra** [comment]
Fixed in #1391
