### ISSUE TITLE
[RFC] Lower default value for nStakeSplitThreshold

### ISSUE THREAD

**Issue by random-zebra** [PIVX-Project/PIVX#1350]
Given the much higher min depth required for stake eligibility (introduced with time protocol v2) it is advisable for stakers to lower the average size of their utxos accordingly.
Current default value for the stake-split threshold 2000 seems a bit high for the average user. I suggest to set it to something lower, e.g. 500.

**Comment by Fuzzbawls** [comment]
Since this is ultimately a user-configurable setting, i've no issue with lowering the default value, as long as it is documented.

**Comment by furszy** [comment]
Agree on decrease it to 500 by default.

And something else that has little to do with the value decrease but we shouldn't forget.

We should move the splitThreshold storage place. From the QSettings to the internal wallet. 
It's not QSettings responsibility to manage the internal wallet's behavior and our current QSettings path is the same for every instance running in the same machine (changing one params there will change every other instance).

**Comment by random-zebra** [comment]
@furszy it is actually stored in both places (QSettings and walletdb)
ref: https://github.com/PIVX-Project/PIVX/blob/c992fc1523018fa98694a0106a22b3c8176a5e8f/src/qt/optionsmodel.cpp#L361

Agreed that saving in QSettings is bad/not needed and should be removed.
