### ISSUE TITLE
[UX Enhancement]  Wallet unlock option upon hitting Send PIV, then re-lock to last state.

### ISSUE THREAD

**Issue by jakimanboy** [PIVX-Project/PIVX#1365]
**Aim:** To be able to hit Send PIV button, get a popup unlock to send password prompt, and after entering password and hitting OK, for it to send PIVX, then automatically lock the wallet back to its last known state.  

**Why:** This would significantly improve the user experience and flow when sending coins using the PIVX core wallet. (which is an often used key function of the wallet)

**Steps Required Currently:** 
(requires **7** clicks, or 6 Clicks + Enter)
1. Click Send PIV
2. Get told to unlock wallet - Click OK
3. Click lock icon in status bar and select Unlock wallet.
4. Enter password, hit Enter or Click OK.
5. Click Send PIV again.
6. Get confirmation prompt. Click OK to finally send.
7. Click lock icon in status bar and Click Lock wallet to re-lock. (or Staking Only to stake)

**Proposed Change 1** - Original Qt wallet behavior
(requires **3** clicks, or 2 Clicks + Enter) 
1. Click Send PIV
2. If wallet is locked/staking-only, popup appears to enter password. Enter password, hit Enter or Click OK. 
3. Get confirmation prompt. Click OK. Coin gets sent and wallet automatically gets locked to previous status. (locked or staking only)

**Proposed Change 2** - Combined confirmation & unlock password prompt
(requires **2** clicks, or 1 Click + Enter) 
1. Click Send PIV
2. If wallet is locked/staking-only, confirmation prompt popup appears along with a field to enter password to send. Enter password, hit Enter or Click OK. Coin gets sent and wallet automatically gets locked to previous status. (locked or staking only)

Obviously, change 2 would be best, with the least clicks required to send. But even change 1 would be a significant reduction in required user interaction to just send some coins.

**Comment by random-zebra** [comment]
Related to #1152 (second  option here: https://github.com/PIVX-Project/PIVX/issues/1152#issuecomment-561599569), #1035 , and somewhat also to #1171 (same flow)
