### ISSUE TITLE
[GUI][Feature request] Full time expansion of wallet topbar icons

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1370]
Full time expansion of wallet topbar icons. Currently it can "stuck" if you are hovering quickly over the icons from left to right (or right to left as well). Complete removal of "movable icons" and improves the user friendliness by giving out instant information about the wallet status on the first look.

There is enough space above "Available" even if we end up with 10+ icons sometime in the future and all are expanded whole time. It works even with the smallest window size of the wallet.

![featureRequestGUI1](https://user-images.githubusercontent.com/57232689/75705100-fad29a80-5cba-11ea-9721-9af2282cbfa4.jpg)

**Comment by furszy** [comment]
NACK for the full time expanded icons. 

You are not thinking on what the user needs and just thinking on remove the expandable buttons (only checking the dashboard and not the rest of the screens, which your proposal will not fit properly)

Side from that and going to the topic: UX wise, it's bad to have so much information. Nobody needs to know everything at every time, flooding the user with useless information (design principle, less is always better and cleaner). 

In fact, the topbar information is barely needed, only used in specific situations.

We are already thinking on move it to hover tooltips in the future, which would replace the expandable buttons and show the information only when the user request it.

**Comment by NoobieDev12** [comment]
Agreed. It needs some changes in the future. Current design results with often being stuck for "too speedy users".

This issue can be closed now, or used as a reference for future changes.
