### ISSUE TITLE
[Feature Request] API access to know Vote Finalization details would support Governance.

### ISSUE THREAD

**Issue by EricStanek** [PIVX-Project/PIVX#1379]
### Describe the issue

During the last 48 hrs prior to a Superblock, the Governance Proposal votes can be finalized at any time. However, there is not way to know if this has happened or not during that 48 hrs, or what the votes for the proposals were at that time.

After the Superblock, it can be indirectly determined which proposals won, by checking to see which were paid out. However, in that time, votes could have changed.

I see a future where it is incredibly easy to create a proposal and vote for proposals in the desktop core wallet. The only thing missing then is a legacy record of what transpired. We can't store all that data in the PIVX blockchain. But, perhaps we can make it easy for multiple 3rd party sites to do that.

Frankly, I would like to completely rewrite the current PIVXcentral.org site. Proposal creation and voting should be done in the wallet. Then 3rd party sites like PIVXcentral.org can track all the legacy data.

Not sure how to best implement it ... but all Proposals should be submitted in Markdown too. That makes it really easy for the 3rd party sites. But, that is just a reference comment and not part of this Github issue.

Thanks!

**Comment by Fuzzbawls** [comment]
`mnfinalbudget show` will provide information on which proposals are going to be paid in the upcoming budget cycle (after finalization), plus the last two cycles' worth of paid proposals.
