### ISSUE TITLE
[GUI][Trivial] Masternode reward box icons are grey both for immature and mature/confirmed rewards

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1380]
Sorry for opening many minor GUI "bugs", if they can even be called bugs, rather requests. But try to help reaching wallet perfectionism :)

As visible on screenshot below, **mature** Cold Stake rewards are with white box icon, while **mature** Masternode rewards are with grey box icon, same as immature Masternode rewards icon.

Things are working perfectly for Cold Staking icons. I haven't tested normal staking icons yet, but I think they are **not working** same as Masternode reward icons. I'll test it out and post update once I get a successful normal stake reward.

OS: Windows 10 Pro

![GUIbug1](https://user-images.githubusercontent.com/57232689/75996158-bdaa1a80-5efd-11ea-8f5a-51e401d3b753.JPG)

**EDIT:** Confirming a visual bug (inconsistency) with normal staking reward icons as well.

![bug1](https://user-images.githubusercontent.com/57232689/76135947-432be880-602c-11ea-8709-471099eb36d0.JPG)

**Comment by random-zebra** [comment]
this seems to only affect the dark theme. @NoobieDev12 can you confirm?

**Comment by NoobieDev12** [comment]
Yes, confirming. Only on dark theme. @random-zebra 

![bug1](https://user-images.githubusercontent.com/57232689/76952074-d1497e00-690c-11ea-9c15-92792f0b27aa.png)
