### ISSUE TITLE
Debug file

### ISSUE THREAD

**Issue by borris345** [PIVX-Project/PIVX#1384]
Anyway to make it prune some of the data after a certain amount of time? When loading the file it is taking a huge amount of time.

It's 385mb file!

That's alot of wasted hard drive space.

**Comment by random-zebra** [comment]
@borris345 you can use `--shrinkdebugfile` on startup, which will prune it to 200Kb if it's over 1Mb.

Also, from 4.1, you'll be able to use `-debugexclude` to exclude specific debug categories (when using `-debug=1`) which is handy to remove spammy categories such as "libevent" or "leveldb" (or even "net").
