### ISSUE TITLE
Crashing QT Wallet 2.2.0

### ISSUE THREAD

**Issue by borris345** [PIVX-Project/PIVX#139]
Random crashes. was staking fine for a few days and then has shut down. This was using the latest x86 64bit QT wallet and a fresh sync.

The debug.log said absolutely nothing out of the ordinary. the last section log was of a new masternode entry. browsed up and could see no errors what so ever.

I did however find this in my sys log when fuzzballs said a segfault usually would be shown.

Apr 20 09:38:46 james-pc kernel: [4119915.138705] pivx-qt[31302]: segfault at f31ff01c ip 000000000836d8c2 sp 00000000ff9ce4d0 error 6 in pivx-qt[8048000+1d97000]

I am testing again. deleted everything and starting a sync from scratch again. Same wallet.dat.

This crashing has happened with me with all new pivx wallets i have tested. I have tried ubuntu 14, 16 and have gone back to linux mint for ease of use. It was the same issue with all of them but never checked logs (or knew how, Linux noob) so not sure if it was same issue.

### Machine specs:
- OS: Linux mint 18.1 but tried with ubuntu 14 and 16
- CPU: 6800k
- RAM: 128gb
- Disk size/type: 3 x 500gb ssds

**Comment by lekanovic** [comment]
Are you using a backup "wallet.dat" file, or are you creating a new one? Because I had problems with a corrupt "wallet.dat" file, so I had to generate a new one. Now my wallet is stable.

**Comment by borris345** [comment]
It's the same wallet i used for 2.1.7 that wallet crashed as well. Was fresh then. The older qt version branded pivx wallets all crashed as well so it's not a corrupt wallet.dat. presstab mentioned something about a memory leak in the qt wallet.

**Comment by lekanovic** [comment]
For this helped:
1. remove ~/.pivx folder(Backup wallet.dat)
2. start pivx-qt
3. wait for the wallet to download the whole blockchain
4. when syncing is done, exit wallet, add the backup wallet.dat to ~/.pivx
5. start pivx-qt

**Comment by borris345** [comment]
Crashed again. Nothing in any logs this time. Don't know how to make it show more info for Devs to see what prob is. I using Daemon for masternodes and they are ok so far. Qt wallet is unstable for staking ATM.

**Comment by borris345** [comment]
2017-04-23 21:56:57 GUI: QIODevice::write (QTcpSocket): device not open

2017-04-24 06:31:13 getblocks 320164 to 81c7d9074bc8a8e96a8563410019831ae2af04193bcdde6bbc5d242f455d4d1e limit 500 from peer=37

2017-04-24 06:41:20 mnb - Got NEW Masternode entry - c7d51ecfe7e9d67bf8bd638dfc4058baee770b77f4bd8011d7ab8302658806b6 - yk2ile5ilhw2ie25.onion:51472 - CTxIn(COutPoint(9f9a78ddf6c53f5e672a2db722f72e3c83815a7895f76e10952e53ef447ade54, 1), scriptSig=) - 1488472482 
GUI: QIODevice::write (QTcpSocket): device not open
GUI: QIODevice::write (QTcpSocket): device not open
GUI: QIODevice::write (QTcpSocket): device not open
GUI: QIODevice::write (QTcpSocket): device not open
2017-04-24 08:59:39 

seeing these in log. the last bit was just at the crash.

**Comment by presstab** [comment]
This is likely due to the Trading Dialog... which runs in the background. We are disabling it as it has caused many problems. There are few other things in the code that use QIODevice. Thanks for posting this, very helpful.

**Comment by lekanovic** [comment]
I got the same crash, and I just checked the debug.log there is no info on the crash. I checked the db.log and it's empty

**Comment by presstab** [comment]
@lekanovic please try building from https://github.com/PIVX-Project/PIVX/pull/146 and letting me know if this takes care of the crash.

**Comment by presstab** [comment]
@borris345 confirmed that the wallet is no longer crashing with the latest commits.
