### ISSUE TITLE
Wallet gets stuck on block 2153199 re built index 

### ISSUE THREAD

**Issue by bryn9157** [PIVX-Project/PIVX#1394]
Wallet gets stuck on block 2153199 re built index

**Comment by random-zebra** [comment]
2153200 is an hard fork block.
If you didn't upgrade to version 4.0 in time, then your chain is forked and will not pass the new validations.
Reindexing won't fix in this case.
You need to resync.

Please join the PIVX Discord server if you need support.
Closing.
