### ISSUE TITLE
[Feature request] Make English as default language during initial wallet startup if language is not translated enough

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1420]
As of right now, wallet starts with somehow weird translations in some cases. I'm from country which has semi-translated language, which ends up with half translated and half english words, which ends up completely weird. Is it possible to keep the current logic which recognizes OS settings/language to choose "native language", but **ONLY** if native language is translated at least 90% on Transifex, otherwise make english as a default wallet language?

![englishDefaultLang](https://user-images.githubusercontent.com/57232689/76807255-11611180-67e4-11ea-837b-607234e10b16.JPG)

Also, as visible on the second screenshot, some words/translations of non-english languages that have more words than original English word(s) ends up with not being fitted into a button. Probably a fix needed for some other PRs in the future.

![bug1](https://user-images.githubusercontent.com/57232689/76807806-e081dc00-67e5-11ea-8257-7f6ff9018f66.JPG)

**Comment by random-zebra** [comment]
Cosed with #1432 / #1433
