### ISSUE TITLE
[Feature request] Set Dark Theme as a default theme after first wallet startup

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1422]
Default Dark Mode makes more sense for PIVX for couple reasons:

1) Closer to PIVX branding colors
2) Prevents "tired eye" problems
3) Objectively, it looks more compact than light theme, which looks more like a bunch of separated objects.

**Comment by furszy** [comment]
NACK. Not everyone can use the dark theme (Most of the time, depends on users' age).

And well, based on the UX design guidelines and conventions: the dark theme is designed to be a supplemental mode to the default (or light) theme.

**Comment by random-zebra** [comment]
Agree with furszy. Closing.
