### ISSUE TITLE
[RFC] Enforcing minimum translation completion

### ISSUE THREAD

**Issue by Fuzzbawls** [PIVX-Project/PIVX#1432]
As #1420 points out, there are a number of localizations that do not have a high completion percentage, leading to a "mixed" user experience (any untranslated string defaults to english).

This issue will serve as a discussion/reference point for plan(s) to remedy that situation.

------

We cannot ascertain at compile-time nor run-time the completion percentage of any given localization, and even attempting to do so would be a needless waste of time and resources. What we **can** do, however, is update the translation process to only fetch localizations that meet a minimum completion percentage threshold.

This would effectively **remove** any localization from the wallet that does not meet the completion percentage threshold, thus reducing the number of occurrences where a user is faced with mixed locales.

The primary drawback to this approach is that there would no longer be a user-facing indication of how much of the wallet's strings have been translated, in-wallet, for locales that are below the threshold. Users would need to refer to Transifex in order to see a language's completion percentage, and take additional steps to see which strings are yet to be translated, without much context as to where those strings fit in the wallet's UI.

A possible solution to this drawback could be making further adjustments to the `update-translations.py` script to allow for fetching and processing **ALL** localizations, even those that don't meet the completion threshold, by adding an optional script argument. This would allow testers and self-compilers a viable avenue to see translated strings in their fully functional context within a running wallet, no matter the completion percentage.

------

Initial internal discussion about exactly what the completion threshold should be set at leaned towards the higher end (80% - 95%). However, at the time of writing (March 18, 2020), such high thresholds would result in the exclusion of a number of locals, most notably German and Korean.

It is not our intention to remove any existing translations from the wallet, but we also recognize that incomplete/partial translations can lead to a sub-optimal, confusing, or even problematic user experience, and have to draw a line *somewhere*.

No matter what the threshold ends up being set at, we'd always like to encourage those capable of translating wallet strings from English to another language to contribute their efforts on [Transifex](https://www.transifex.com/pivx-project/pivx-project-translations) with the goal of completion.

**Comment by random-zebra** [comment]
Very much agree with this one.
Partially completed localizations (sometimes as low as 10-30%) really don't provide any benefit to the user-experience, quite the opposite: besides being confusing, they also give the impression of a sloppy / unprofessional / unfinished product.

My preference for the threshold leans towards the very high end (90%). I'd like to encourage the translation for those languages that are almost reaching it (Korean, German, etc).
