### ISSUE TITLE
[Feature Request] Add 'Backup Chain' (AKA Snapshot) functionality.

### ISSUE THREAD

**Issue by EricStanek** [PIVX-Project/PIVX#1478]
With the massive block chain sync time improvements, we have made a BIG step from requiring snapshots, to getting back to people sync'ing their chain from scratch each time they need it.

We've see reports of a sync taking 21 times what a snapshot takes. Now, it is 12 times.

If we add functionality to the core wallet, to make it easy for the user to create their own snapshot, this could much more quickly get us to the point where in the worst case, an organized user, will only ever have to sync the full chain ONCE.

Guessing that when they click the 'Backup Chain' button, we warn them about how much disk space is required. We should also provide the option to overwrite the prior chain backup. Of course, we should also allow for a chain restore.

Adding the same functionality to pivxd will mean that official backup services such as snapshot.PIVX.org can create and provide snapshots for new people too - that are prepared the same way and easily restored using the wallet functionality.

**Comment by random-zebra** [comment]
NACK. I don't think it's a good idea to (try to) copy/restore the chain DB and indexes at *runtime*.

**Comment by Fuzzbawls** [comment]
gunna NACK this one as well, LevelDB is a fickle beast that is not intended for copying whilst in use
