### ISSUE TITLE
[GUI][Visual bug] Transaction details shown TWICE.

### ISSUE THREAD

**Issue by EricStanek** [PIVX-Project/PIVX#1480]
### Describe the issue

This is a display issue only. May be isolated to my obscure OS. I'm OK if this is treated as an 'edge case' and left as low priority. But, it may be a good issue for a new 'Community Dev' to tackle.

When sending rewards from my MN wallet to a staking wallet, the transaction is displayed TWICE (Sometimes 3 times) in the 'Transactions' section of the 'Home' screen in the wallet. Clicking on each transaction shows the exact same details including the TxID. The balance is correct for it being sent once. The exact same scenario is on the receiving wallet;  transaction shown twice, details exact same, balance adjusted correctly. Only difference is that the description is 'Received from ...'
Restarting the wallet makes no difference.

### Can you reliably reproduce the issue?

Yes.

#### If so, please list the steps to reproduce below:
1. Send from 1 MN controller wallet to a staking wallet.
2. Note transaction shown 2 or 3 times in sending wallet.
3. Note transaction shown 2 or 3 times in receiving wallet.

### Expected behavior

Transaction should be displayed once in each wallet.

### Actual behavior

Transaction is shown 2 or 3 times in each wallet.

### Screenshots.

Issue is self explanatory. I can easily send screen shots, but if attached here would have to be so highly edited to protect privacy, they would be useless. Will DM them to a dev if needed.

### What version of PIVX Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

Official compiled binary for 4.0.2. Noticed issue in 4.0.0 I think. Was certainly in 4.0.1 though.

### Machine specs:
- OS: PureOS
- CPU: Intel Core i7-6500 @ 2.50 GHz x 4
- RAM: 16GB
- Disk size: 1.9 TB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

Happy to provide if needed.

**Comment by JSKitty** [comment]
I have this same issue on Windows 10 and a handful of others in the PIVX discord have reported this too.

**Comment by furszy** [comment]
Tackling it.

**Comment by furszy** [comment]
Please try #2209, it's based on 2203 which changed the validation interface signaling and wallet & GUI event handling processes.
