### ISSUE TITLE
[GUI][Visual bug][Trivial] The icons are overwritten when selecting the folder.

### ISSUE THREAD

**Issue by boldsuck** [PIVX-Project/PIVX#1482]
Select folder: (Backup Wallet, Export Accounting & Address Book)

![PIVX-testnet4](https://user-images.githubusercontent.com/33176683/78187001-f7733000-746d-11ea-8e5b-7dbfd0953858.png)

What version of PIVX Core are you using?
4.0.99.1

Machine specs:
- OS: Debian GNU/Linux

**Comment by random-zebra** [comment]
@boldsuck what kind of Desktop environment are you using?
This is not reproducible on Gnome.

**Comment by boldsuck** [comment]
Yes, because the problem is fixed since Wallet v4.1.0rc1. ;-)
Desktop environment here is KDE 4.14.2 & KDE 5.54.0

Sorry, wanted to close the issue 2 days ago.
I have not yet got it, Corona holidays are over in Germany :-(
