### ISSUE TITLE
Hot staking stops getting rewards

### ISSUE THREAD

**Issue by misternode** [PIVX-Project/PIVX#1500]
#833 # Describe the issue
After some time, GUI client stops hot staking.  Icons say staking, but I get no rewards.  I usually get them every X hours.  Most recently went several days with no stakes.

After stopping and restarting, got stake within a few hours.

### Can you reliably reproduce the issue?
I would not say "reliably" but have noticed this twice in the past 2 weeks.

#### If so, please list the steps to reproduce below:
1. Let GUI client run hot staking (on MacOS)
2. Speculatively it may be something in the OS (memory? though I have copious. Sleeping? though I have turned off all energy-saving mechanisms. GUI indicators show no sign that staking has stopped, and chain remains fully synched), but I have not figured anything out that may be related
3. Wait (about 2 days?) to see if rewards stop coming in

### Expected behavior
Staking every X hours, with some amount of variance.

### Actual behavior
No stakes for 3+ days

### Screenshots.
Not GUI related

### What version of PIVX Core are you using?
v4.0.2 PIVX Core, GUI

### Machine specs:
- OS: macOS Mojave 10.14.6
- CPU: 3GHz Intel Core i5
- RAM: 16 Gb (4 Gb free)
- Disk size: 1Tb (20% free)
- Disk Type (HD/SDD): Fusion (hard disk + ssd)

### Any extra information that might be useful in the debugging process.
debug log is currently truncated to last few days. if it happens again, I'll see if there's anything in the log about ThreadStakeMinter dying, etc.

**Comment by random-zebra** [comment]
Hi @misternode , if you could run with `-debug=staking` and provide relevant log lines, that would help.

**Comment by robert-n-cristof** [comment]
I don't think I can add command line flags on the MacOs version (dmg|Applications). Does MacOs honor the conf file (I've noted some other coin wallets don't, on Mac); can I put that flag there?

Else I might just close this ticket. Though it's not very likely to go that long without a stake, it is  possible -- and I can't find anything definitive to demonstrate that this is a fault in the application.

**Comment by random-zebra** [comment]
Sure, you can either add the option in the pivx.conf file, or launch the app from the terminal, using the flag directly.

**Comment by misternode** [comment]
enabled debug=staking. will keep monitoring.

**Comment by misternode** [comment]
Unable to reproduce. Going to close this.

most likely possibilities:

- lengths of time to stake were outliers
- energy-saving mechanisms in OS interfering with PIVX
