### ISSUE TITLE
[Bug] Unable to return Change Address to default

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1526]
After setting up Change Address for the first time, it is impossible to delete the address, leave it blank and click Save, so that it returns to Default. It returns `Invalid change address`.

![warning2](https://user-images.githubusercontent.com/57232689/79243427-e535c080-7e75-11ea-8b5a-c8169a5e4c9c.png)

![warning3](https://user-images.githubusercontent.com/57232689/79243434-e7981a80-7e75-11ea-9160-edad12ceb5a2.jpg)

**Comment by furszy** [comment]
need to touch "reset to default" in the send screen.

**Comment by JSKitty** [comment]
Shall we close this issue? As hitting "Reset to default" in the Send widget already has the functionality wanted in this issue, or are we wanting to make it slightly more user friendly by adding an additional change-address-only "Reset" button to the above widget?

**Comment by random-zebra** [comment]
I think it could be good to have an additional "Reset" button as proposed, but making it visible only when there's actually a custom change-address already set.
