### ISSUE TITLE
[GUI][Visual bug] Notification message in systembar

### ISSUE THREAD

**Issue by BayerTM** [PIVX-Project/PIVX#1541]
This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Discord](https://discord.pivx.org).

### Describe the issue : 

Please refer to the firtst screenshot below. Note the notification information at the bottom right in systembar. Why is the Type “Received with”? I assume this is a bug. Please refer to the second screenshot below. Note that Type “Received with” is not part of the pull-down selection which seems to indicate it is not a valid option. 

#### If so, please list the steps to reproduce below:

1 When incoming transaction 
2
3

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

![ice_screenshot_20200419-234905](https://user-images.githubusercontent.com/59299109/79700765-6f2bc200-8298-11ea-9dd0-1c30952a5b9a.png)

![ice_screenshot_20200419-235318](https://user-images.githubusercontent.com/59299109/79700866-0729ab80-8299-11ea-9694-2070b4b4c4c6.png)

### What version of PIVX Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package. : Self compiled 4.1.0

Machine specs:

OS: Windows 10
CPU: Intel Pentium i9
RAM: 8 GB
Disk size: 512 GB
Disk Type (HD/SDD): SSD

Any extra information that might be useful in the debugging process.
This is normally the contents of a debug.log, db.log or config.log file. Raw text or a link to a pastebin type site are preferred.

**Comment by random-zebra** [comment]
Not sure I understand the issue.
The TxType description is "Received with address: default".
While the TxType itself (in the dropdown) is "Received".
