### ISSUE TITLE
[Bug] Include delegated checkbox goes missing after sending new delegation

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1544]
After sending new delegation to existing or new Cold Staking address by selecting **non-delegated** coins in Coin Control, then navigating back to Send tab, `Include delegated` checkbox option is missing, although there are still already delegated coins in Coin Control from earlier.

Initial state in Send tab:
![0-0](https://user-images.githubusercontent.com/57232689/79817066-dfb00d00-8384-11ea-80d5-9028b433234b.jpg)

Then going to Cold Staking tab, selecting non-delegated UTXO, clicking OK -> Delegate:
![1-](https://user-images.githubusercontent.com/57232689/79817104-f5253700-8384-11ea-9708-a85390c964b8.jpg)

Now going back to Send tab, `Include delegated` is missing, although there are delegated coins (UTXOs) still in there:
![4](https://user-images.githubusercontent.com/57232689/79817293-6cf36180-8385-11ea-94da-38fe3af1e28e.jpg)

This is mostly visual bug, that fixes itself sometimes by switching through tabs or selecting/deselecting various UTXOs. (EDIT: `Include delegation` checkbox appears again when selecting none of the UTXOs in Coin Control and clicking OK)

**NOTE:** `Include delegation` also goes missing when trying to spend delegation in Send tab by sending it to your own address (not sure if this bug is possibly fixed in 1543)

**Comment by random-zebra** [comment]
`Include delegated` checkbox is only meant for the automatic input selection algorithm.
When selecting **any** utxo from coincontrol, it gets hidden, because in that case there is no automatic selection (the inputs are those checked with coin control, them being delegated coins or not).

**Comment by NoobieDev12** [comment]
This can be closed as it's an intended behavior.
