### ISSUE TITLE
[GUI][Visual bug] Pull down menu / transactions disapears.

### ISSUE THREAD

**Issue by BayerTM** [PIVX-Project/PIVX#1546]
This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Discord](https://discord.pivx.org).

### Describe the issue

Please refer to the first screenshot below and note all 9 pull-down Transactions Types. Randomly select one Transactions Type, followed by another, and a third/forth/fifth. At some point the pull-down menu disappears (refer to the second screenshot below). The only way to recover (to my knowledge) is to close/open the wallet. 

#### If so, please list the steps to reproduce below:

I have reproduced this issue twice today. Randomly select a Transaction Type in the pull-down menu and ensure the proper information is displayed. Repeat several times (4-6) with different Transaction Types. At some point the pull-down menu will disappear. 

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

![ice_screenshot_20200421-212341](https://user-images.githubusercontent.com/59299109/79905514-ac1dc300-8416-11ea-91fa-49d53b05b532.png)

![ice_screenshot_20200420-001502](https://user-images.githubusercontent.com/59299109/79905485-9f996a80-8416-11ea-9f31-3d913bf50e9d.png)

### What version of PIVX Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package. Self compiled 4.1.0

### Machine specs:
- OS: Windows 10
- CPU: i9
- RAM: 8GB
- Disk size: 512 GB
- Disk Type (HD/SDD): SDD

**Comment by random-zebra** [comment]
possibly related to #1172

**Comment by furszy** [comment]
This was solved in #2073, closing.
