### ISSUE TITLE
GUI: "Payment to yourself" did not make entry in Home/Transactions

### ISSUE THREAD

**Issue by misternode** [PIVX-Project/PIVX#1555]
### Describe the issue

Sent coins from one of my addresses to a (new) address, with no change.

Home tab, Transactions, does not show a transaction (expected "payment to yourself")

Though I was worried about having lost coins, the address is in my coin control with the expected balance.

### Can you reliably reproduce the issue?

I'm not about to try again. Worried about losing coins.

### Expected behavior
Should see an entry "Payment to yourself"

I made a SECOND transaction, in this case with change and using an existing address that had some prior transactions; this time it DID show that "Payment to yourself" entry.

### Actual behavior
Nothing in GUI.

Though I was worried about having lost coins [heart attack!], the address is in my coin control and console with the expected balance.

### Screenshots.
<img width="712" alt="Pivx_screenshot_no_tx" src="https://user-images.githubusercontent.com/41598501/80233854-c7f2b600-861c-11ea-8cb6-3737bd122ac2.png">

### What version of PIVX Core are you using?
4.0.2

### Machine specs:
- OS: Mac 
- CPU: ? 
- RAM: 16 Gb
- Disk size:  1Tb
- Disk Type (HD/SDD): hybrid (fusion)

**Comment by random-zebra** [comment]
Could be related to https://github.com/PIVX-Project/PIVX/issues/1346 (i.e. display an incorrect date, thus be further below in the list) maybe?

**Comment by misternode** [comment]
Correct. it got listed as 8/20/2019, further down in the list.

This is a duplicate.
