### ISSUE TITLE
[Bug] Multisend button stays Active although it wasn't activated

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1560]
Would it make more sense to stay in "Disable" mode, if it is unable to activate Multisend option?

![multisendBug1](https://user-images.githubusercontent.com/57232689/80266490-7b4ebf80-869c-11ea-8ca0-a0854b1d40e9.jpg)

**Comment by random-zebra** [comment]
Closing with #1577 for now.
