### ISSUE TITLE
[Bug] Receive tab shows the address outside the wallet

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1561]
Initial state in `RECEIVE` tab, showing the only receiving address in the wallet:
![111](https://user-images.githubusercontent.com/57232689/80267492-940da400-86a1-11ea-9523-6a4695d9eeff.JPG)

`SETTINGS` tab -> `Wallet Data` -> `MultiSend` -> setup multisend to an outside PIVX address -> `ADD`:
![222](https://user-images.githubusercontent.com/57232689/80267502-9c65df00-86a1-11ea-8715-e2b21758ddc7.jpg)

Go back to `RECEIVE` tab -> main address that is being showed is the address **outside** the wallet.
![333](https://user-images.githubusercontent.com/57232689/80267504-9f60cf80-86a1-11ea-91d2-b602829d7ae1.JPG)

**Comment by random-zebra** [comment]
Closing with #1577 for now.
