### ISSUE TITLE
[Bug] MultiSend send rewards for each newly created UTXO after stake-split

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1563]
I'm staking on one testnet wallet (1st picture) and I've setup MultiSend to another testnet wallet (2nd picture) to send 100% of the rewards. Problem is that MultiSend + stake-split feature together end up with bug, in which MultiSend sends 2 PIV reward ( - fees) for **each new UTXO** created after stake-split.

**Edge case:** _Wallet have 50tPIV in total. It would be interesting to see winning a block with that only UTXO of 50 tPIV with stake split threshold set to 1 tPIV + MultiSend feature turned ON setup to send 100% of rewards to an address outside of the wallet. What would be an error, as MultiSend would want to send automatically more than there are funds available in the wallet?_

![multisendNewBug1](https://user-images.githubusercontent.com/57232689/80270312-0a68d100-86b7-11ea-8949-99651ea508e5.jpg)

![multisendNewBug2](https://user-images.githubusercontent.com/57232689/80270313-0c329480-86b7-11ea-8f45-8c542c9d5483.JPG)

**Comment by NoobieDev12** [comment]
Issue happened in this block:
https://blockbook-testnet.pivx.link/block/1552471

**Comment by random-zebra** [comment]
Closing with #1577 for now.
