### ISSUE TITLE
[Feature request] Allow MultiSend to remove particular address only instead of all

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1567]
Currently it is impossible to remove particular address from MultiSend address list, it is possible to `CLEAR ALL` only.

![multisend22](https://user-images.githubusercontent.com/57232689/80290100-7c86f780-8743-11ea-9af1-ec44f2a88b5e.JPG)

**Comment by random-zebra** [comment]
Closing with #1577 for now.
