### ISSUE TITLE
[Feature Request] Add warning for a Custom Fee selected too high

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1570]
It is possible to set **Custom Fee** to `9999999` PIV/kilobyte **without a warning**. This feature request is to add warning when user wants to set Custom Fee way above any normal level.

**NOTE:** `99999999` is **NOT** allowed to set, but `9999999` **IS** allowed to set.

![customFeeNoWarning1](https://user-images.githubusercontent.com/57232689/80292721-b9a9b480-8758-11ea-9ddc-888970b121f3.JPG)

**Comment by random-zebra** [comment]
The wallet already blocks the send of a transaction with "insane" fee.
Instead of a warning, should just prevent the user from saving such high fee.
