### ISSUE TITLE
[Bug] Stake split splitted an UTXO on lower UTXOs than it was set

### ISSUE THREAD

**Issue by ambassador000** [PIVX-Project/PIVX#1571]
Although `Stake split threshold` was set to 1.000 (1, not 1k), it divided initial UTXO on sub 1 tPIV UTXOs:
https://blockbook-testnet.pivx.link/tx/ea69251a41aaa6c0350523bb9410fa943cae2aff16112f692c09eef7b38aee53

**NOTE:** Possibly irrelevant info, but MultiSend feature was activated with 50+ different addresses.

Also, Custom Fee was set to 1 tPIV/kb.

**Comment by random-zebra** [comment]
This happens because the number of outputs for the split is calculated considering the whole block reward value (without excluding the 3 PIV for the masternode).
