### ISSUE TITLE
[Feature Request] Don't allow creation of proposals with the same name and URL

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1572]
It is possible to create 2 proposals with the same name and URL. Feature request to prevent it.

**Comment by furszy** [comment]
NACK, it will introduce an attack into the network. An users knowing the URL of a certain proposal and broadcasting it before the proposal owner, blocking the URL.

**Comment by random-zebra** [comment]
I'm going to NACK as well.
There are also legit use cases for proposals with same name and/or url.
