### ISSUE TITLE
Syncing fails at block 2308853 with cold staking error

### ISSUE THREAD

**Issue by Crypto2** [PIVX-Project/PIVX#1582]
Syncing refuses block 9e3fc3c3ee1a94524fef3733ca775259f8e3c755ebee553b367fb50fdeecabd6 and is stuck there:

2020-04-27 13:02:55 ERROR: CheckTransaction: cold staking not active
2020-04-27 13:02:55 ERROR: CheckBlock : CheckTransaction failed
2020-04-27 13:02:55 ERROR: ProcessNewBlock : CheckBlock FAILED for block 9e3fc3c3ee1a94524fef3733ca775259f8e3c755ebee553b367fb50fdeecabd6

**Comment by random-zebra** [comment]
Hi @Crypto2, it seems that you spork list is not properly synced.
Please do as follows:
1) close the wallet
2) delete the `sporks` folder
3) restart the wallet with `-maxtipage=1800` (either as startup flag or additional line in `pivx.conf`, that can be removed after the wallet has fully synced).

**Comment by Crypto2** [comment]
Even with that it's still fighting, it will sync for a bit then back to 'cold staking not active' never syncing fully.

**Comment by Crypto2** [comment]
Any update on this? Every time it gets close to the head it's just done and back to the cold staking errors.
