### ISSUE TITLE
PIVX Core Version v2.2.0  i18n GUI Problem: german caption overlaying radio button 

### ISSUE THREAD

**Issue by phinzphinz** [PIVX-Project/PIVX#160]
### Describe the issue
In the german version of "PIVX Core Version v2.2.0 (64-Bit)" pivx-qt wallet, you cannot click on intelligent transaction fees because the german caption of this radio button is too long.

### Expected behavior
You should be able to select intelligent fees but when you click on the corresponding radio button, nothing happens because it is overlayed by its caption.

### Actual behavior
You cannot select intelligent transaction fees with the mouse, the only way is to use the keyboard (TABs and arrow keys). Resizing the window does not help.

### Screenshot.
![unbenannt](https://cloud.githubusercontent.com/assets/28191932/25555684/463e0a46-2ced-11e7-86af-8d1d6bff109b.png)

### Proposal 
You should make the caption clickable, like in HTML (http://stackoverflow.com/questions/6293588/how-to-create-an-html-checkbox-with-a-clickable-label). This would be much more user-friendly.

### What version of PIVX Core are you using?
PIVX Core Version v2.2.0 (64-Bit)
I downloaded it today (29 April 2017) from the PIVX website.

### Machine specs:
- OS: Debian 8

**Comment by Mrs-X** [comment]
Thanks for reporting 👍 

I'll have a look at the issue tomorrow.

**Comment by Mrs-X** [comment]
Will be fixed with the next release, see https://github.com/PIVX-Project/PIVX/pull/165
