### ISSUE TITLE
[Bug] Transifex isn't taking all translations properly

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1600]
There are some words that has been translated on Transifex, but aren't showed within wallet.

![translationsBug2](https://user-images.githubusercontent.com/57232689/81075517-c2ce1a80-8eea-11ea-8bbb-79ded3d61421.jpg)

**Comment by random-zebra** [comment]
Yes. This is not a transifex issue, but a trivial fix in QT: it happens because some labels in the GUI hven't been set with `tr()`.

**Comment by NoobieDev12** [comment]
Is it needed to make a list of words/positions where is the issue appearing?

**Comment by random-zebra** [comment]
Closed with #1604
