### ISSUE TITLE
[Bug] autocombinerewards command isn't working as expected

### ISSUE THREAD

**Issue by ambassador000** [PIVX-Project/PIVX#1603]
It seems like `autocombinerewards` command isn't working as intended. It surely requires some further review. Sometimes it gets stuck for weird reason, or it simply does work as intended, because there are many UTXOs in wallet that should be combined, but they are not. They are partially getting combined only. I've added a **testnet** wallet.dat file as well, which is also working laggy to some extent if it will be used for any testing.

I have also noticed that after you turn ON `autocombinerewards` and then `autocombinerewards false`, it starts working unexpectedly after whenever you turn it back ON.

![autocombinerewardsBug02](https://user-images.githubusercontent.com/57232689/81127365-48c78100-8f3e-11ea-93b4-4f6a1a1cc03d.JPG)

Testnet wallet.dat file with 1000+ UTXOs can be downloaded here within next 30 days since opening this issue:
https://easyupload.io/fqe1c2
Password: 123

**Comment by CaveSpectre11** [comment]
@NoobieDev12 see: #953 .  Seems I need to rebase it though.

**Comment by panleone** [comment]
This should have been fixed by #2812
