### ISSUE TITLE
[Feature request] Prevent going next step if initial wallet encryption passphrases do not match

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1605]
Although it would return an error if passphrases do not match while saving it, wallet allows proceeding first step with non-matching passphrases. Feature request to prevent it in the first step.

![encryptionBug1](https://user-images.githubusercontent.com/57232689/81252221-a71b5f00-9025-11ea-888f-d7dbbd96a4c4.JPG)

![encryptionBug2](https://user-images.githubusercontent.com/57232689/81252224-a97db900-9025-11ea-9a27-33d2a679cdf2.JPG)

**Comment by JSKitty** [comment]
After you hit "ENCRYPT" with mismatched passphrases, the wallet will return an error: "The supplied passphrases do not match".

![image](https://user-images.githubusercontent.com/42538664/81290311-c33bf200-905f-11ea-8c4b-9cd966ee823e.png)

So it's not possible to encrypt without matching passphrases, however, the UX could be improved by simply silently returning/breaking the "ENCRYPT" button if they don't match, as the UI already warns about it, it just doesn't prevent "ENCRYPT" being hit.

Thoughts? I can PR the above proposal if it has consensus(?).
