### ISSUE TITLE
[GUI][Cold Staking] Oddities with Cold Staking Coin Control

### ISSUE THREAD

**Issue by CaveSpectre11** [PIVX-Project/PIVX#1609]
Ran into a few strange behaviors with coin control.
1) Selecting outputs doesn't propagate the value into the Cold Staking field (I think this is a known issue)
2) cutting and pasting the "after fee" and using that, is not fee taken out (have to deduct more to have enough balance to do the transaction)
3) "Select all" doesn't reset.  When you wait for the change to come back (when not using all of it for the delegation), "Unselect all" is now selected, but the received UTXO isn't selected.  You have to click it twice to select the transaction(s) again.

#### If so, please list the steps to reproduce below:
1. select all with coin control in cold staking
2. cut and paste the "after fee"
3. hit okay
4. paste the after fee into the amount
5. try to delegate;  not enough balance error comes up
6. deduct enough to delegate the transaction
7. wait for the change to become available
8. enter coin control again; select "unselect all", "select all" to get it to select all again.

### Machine specs:
- OS: Ubuntu 18-04
- PIVX v4.1

**Comment by random-zebra** [comment]
1. is a feature request. The value selected from coincontrol isn't meant to propagate to the output value field. I'm not sure we want to change this.
As with regular spends, the input value (selected in coincontrol) isn't necessarily equal to the output value (in fact it isn't, given the fee).

2. proposed fix in #1611

3. proposed fix in #1612

**Comment by random-zebra** [comment]
Guess we can close this one?

**Comment by furszy** [comment]
closing for now.
