### ISSUE TITLE
[Bug][GUI][Trivial] Set language isn't showing

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1615]
When you select any langugage in the wallet, SAVE it and restart the wallet, language that is being chosen isn't showed up in Settings, it stands "Default" translated to language that is presented.

![language1](https://user-images.githubusercontent.com/57232689/81516739-4350a900-9339-11ea-8d10-bb003f22f37d.JPG)

**Comment by furszy** [comment]
already fixed on master, closing.
