### ISSUE TITLE
[Bug][GUI] Add/Edit Label button isn't showing as expected

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1617]
1. Start wallet from scratch
2. Go to Receive tab
3. Assuming Receiving address that got showed up first had no label, button would be `Add Label`
4. When you click on a Receiving address that is already labeled, button will change to `Edit Label`, and when you select again an address **without** label, button will stay `Edit Label` instead of `Add Label`.

![addLabelBug1](https://user-images.githubusercontent.com/57232689/81588569-02987480-93b9-11ea-997f-ac864a9be798.JPG)

**Comment by NoobieDev12** [comment]
Issue is also in the following case:
(unlock the wallet for easier reproduction)

1. In Receive tab, click `Generate Address`, new address will be created
2. Now click again `Generate Address`, new address will be created, but button will remain `Edit Label`, although freshly generated address does not have any label yet 


Tried with 5.0.0

**Comment by furszy** [comment]
solved on #2128, closing.
