### ISSUE TITLE
[GUI][Trivial] Unselected Custom shows lower fee than possibly accepted

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1621]
When `Recommended` is selected in Customize Fee dialog, `Custom` below shows `0.000001`, but when you select `Custom` fee as an option, it immediately shows your last saved Custom Fee.
Problem: unselected Custom below should show `0.0001`, because that is the lowest possible fee that can be saved.

![customFee1](https://user-images.githubusercontent.com/57232689/81742115-de639300-949f-11ea-84e8-9ab785599f31.JPG)

**Comment by random-zebra** [comment]
Technically, the value of `0.0001` PIV/kB for `CWallet::minTxFee` is only a default. It can be overridden with a startup flag (`-mintxfee=<amt>`), so maybe that could be used as placeholder.
