### ISSUE TITLE
[Bug] Wallet returns Restart required when it's not needed

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1622]
1. In Settings -> Options -> Display -> select `American English (en)`
2. Click SAVE (Restart required dialog will show up -> click Restart Now)
3. After wallet loads up, go again Settings -> Options -> Display -> Language will show `(default)` (issue already reported in #1615 and it is related to this)
Nothing has been changed in Settings after restarting the wallet…
4. Click SAVE -> Restart required dialog will show up again (automatic switch after wallet restart from `American English (en)` to `(default)` has been recognized as a change in settings.

![restartNowBug1](https://user-images.githubusercontent.com/57232689/81747505-82513c80-94a8-11ea-9a17-d3ac44f95077.JPG)

**Comment by furszy** [comment]
this should be fine now with the language initialization fix.

**Comment by NoobieDev12** [comment]
Yes, tested and works. This issue is fixed in 4.2.0. It can be closed.
