### ISSUE TITLE
[GUI][Feature Request] Add search option to My Addresses list

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1635]
In situation where there is a long list of receiving addresses in My Addresses list, it's hard to scroll manually through the list to check and verify manually if some random address belongs to the wallet. This feature request is to implement search box somewhere there to make the search more user friendly.

It's possible to check the address by copy-pasting an address into Send box, but only if an address is labeled. Otherwise this method isn't helpful.

![search1](https://user-images.githubusercontent.com/57232689/82517830-478d7b00-9b1e-11ea-85c4-46d80bf271fe.JPG)

**Comment by random-zebra** [comment]
@NoobieDev12 for the use-case you describe, you can (at least for now) use `validateaddress`. 
With this rpc, you can see whether an address belongs to the wallet and what's its label (named "account" in `validateaddress` output).

**Comment by random-zebra** [comment]
Added in #2353
