### ISSUE TITLE
[GUI][Trivial] Box outside of the PIVX address stays red when it's empty

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1639]
Pretty useless, but this opened issue is only to achieve perfectionism.

**Working scenario:**
Go to Send tab -> click on the arrow next to the Address book icon -> click on any address with label -> now delete the `Address label` field and then delete the `PIVX address` field. Everything will be fine (Outside of the box will be white/grey color).

**Non-working scenario:**
Go to Send tab -> click on the arrow next to the Address book icon -> click on any address with label -> now type any character in PIVX address field (outside box will become red) -> delete the `Address label` field and delete the `PIVX address` field. Outside box will stay red, although it is empty and `Send PIV` button wasn't clicked.

![sendBug1](https://user-images.githubusercontent.com/57232689/82716179-6f9fea00-9c96-11ea-8d8a-47447a2499f6.JPG)

**Comment by random-zebra** [comment]
Closed in #2249
