### ISSUE TITLE
[BUG] [RPC] getbalance <account> get the info from getreceivedbyaccount <account>

### ISSUE THREAD

**Issue by maikrolf** [PIVX-Project/PIVX#1642]
I got an balance error when i do getblance <account> here i get the getreceivedbyaccount <acount> amount

You can see the getblance <account> amount is also higher then the getblance (total wallet) amount of coins

this happend on every platform i try (ubuntu, windows, mac)

i added a screenshot to show more clear
![afbeelding](https://user-images.githubusercontent.com/40924921/82736164-c73a6600-9d27-11ea-8057-24a882071cc3.png)

I have this problem now in 5 different new pivx 4 wallets

**Comment by akshaynexus** [comment]
Looks like the same value ,not a error imo.Just that getreceivedbyaccount removed the extra 0's.

**Comment by maikrolf** [comment]
Yes that the problem it's the same! But that the balance of that user are only 5 coins and total wallet has 799.99 coins and it show actual balance of 1814 that are more coins then the total wallet coins

The getbalance (account) must give the actual balance right? And bot the receivedbyacccount (account) balance?

**Comment by Fuzzbawls** [comment]
The internal 'account' system has been deprecated since v4.0.1 (Jan 2020) and is being removed in v5.0 specifically because of it's inaccuracies and issues like this.
