### ISSUE TITLE
Can't run 4.1 GUI on Mac Mojave (10.14.6)

### ISSUE THREAD

**Issue by misternode** [PIVX-Project/PIVX#1648]
### Describe the issue
Can't run on Mac Mojave (10.14.6)

<img width="419" alt="Screen Shot 2020-05-26 at 3 19 43 PM" src="https://user-images.githubusercontent.com/41598501/82946989-ea058e00-9f64-11ea-89ac-4759d817d443.png">

#### If so, please list the steps to reproduce below:
1. install dmg (https://github.com/PIVX-Project/PIVX/releases/download/v4.1.0/pivx-4.1.0-osx.dmg)
2. try to run

### Expected behavior
Can run app

### Actual behavior
Can't run app

### Screenshots.
<img width="419" alt="Screen Shot 2020-05-26 at 3 19 43 PM" src="https://user-images.githubusercontent.com/41598501/82946989-ea058e00-9f64-11ea-89ac-4759d817d443.png">

### What version of PIVX Core are you using?
4.1

### Machine specs:
- OS: macos mojave 10.14.6
- CPU: intel i5 3Ghz
- RAM: 16 Ghz
- Disk size: 500 Gb
- Disk Type (HD/SDD): fusion

**Comment by random-zebra** [comment]
Duplicate of #1613 .

Temporary fix
```
xattr -d com.apple.quarantine /Applications/PIVX-Qt.app
```

**Comment by misternode** [comment]
Thanks. quick and easy. up and running 4.1.0
