### ISSUE TITLE
[BUG] [CLI] notify options don't work

### ISSUE THREAD

**Issue by maikrolf** [PIVX-Project/PIVX#1649]
al 3 types of notify functions are not executed

alertnotify=/bin/bash /root/alert.sh %s
walletnotify=/bin/bash /root/transaction.sh %s
blocknotify=/bin/bash /root/block.sh %s

when i run the same commanda on a pivx 2 or pivx 3 verion works great so its not on my wait of calling the script, someone an idear how to get this to work?

**Comment by Fuzzbawls** [comment]
these are working here locally, and also in our regression testing suite, so you'll need to review your own setup to see where things have gone wrong.

**Comment by furszy** [comment]
Closing this, can create a new issue if find something over the area.
