### ISSUE TITLE
[RFC] Bump minimum required Boost version to 1.57.0

### ISSUE THREAD

**Issue by Fuzzbawls** [PIVX-Project/PIVX#1682]
Currently, our minimum required Boost version is 1.47.0 in order to continue support primarily for Ubuntu Trusty, which reached the end of it's standard support April 2019.

In our upcoming sapling implementation, we rely on a `boost::optional` method that doesn't exist until Boost 1.57.0. This issue proposes to bump up our minimum required Boost version to 1.57.0 rather than create a workaround.

This will effectively end our support for the following distros **unless** compiling with the `depends` system:

| Distro and Version | Supplied Boost Version | Standard Support Ended Date | End of Life Date |
| --- | --- | --- | --- |
| Ubuntu Trusty 14.04 | 1.55.0 | April 2019 | April 2022 |
| Debian Jessie | 1.55.0 | June 2018 | June 2020 (LTS) |
| Fedora 21 | 1.55.0 | | Dec 2015 |
| CentOS 7* | 1.53.0 | | June 2024 |

\* This is probably the most controversial, as CentOS 7 is still in wide use; CentOS 8 was only released in Sept 2019.

**Comment by random-zebra** [comment]
ACK on bumping the minimum required boost version to 1.57

**Comment by furszy** [comment]
ACK on bumping the min version to 1.57 too.

Another good discussion would be the upgrade to c++17 to be able to use std::optional instead of boost::optional (as well as many others objects like the variant, visitor pattern, etc).

**Comment by furszy** [comment]
PR merged, closing issue
