### ISSUE TITLE
[GUI][Bug] Console output results are still movable

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1748]
Running a 4.2.0rc1 on mainnet, issue introduced in #1712 and fixed in PR #1741 is still not solved.

OS: Windows Server 2019

![bug1](https://user-images.githubusercontent.com/57232689/87485871-128f3780-c63a-11ea-8b6d-748a1447f8a9.jpg)

**Comment by Fuzzbawls** [comment]
#1741 isn't included in 4.2.0rc1 as it wasn't merged until after the branch-off and tag. it will be included in the final 4.2.0 release.

**Comment by NoobieDev12** [comment]
Oops, didn't notice, sorry. Closing.
