### ISSUE TITLE
pivxd (ARM) crashes after about 15 minutes on Pi4

### ISSUE THREAD

**Issue by go140point6** [PIVX-Project/PIVX#1778]
I'm running into an issue with pivx core 4.2.0 on the Pi (using the official ARM binary for pivxd from the release -> pivx-4.2.0-arm-linux-gnueabihf.tar.gz).  After about 15 minutes seemingly working as expected, the daemon crashes with the following:

```pivxd: net.cpp:1062: void AcceptConnection(const {anonymous}::ListenSocket&): Assertion `nMaxInbound > 0' failed.```

I switch back to 4.1.1 and it runs without issue.  I've duplicated this 3 times.

I'm using the following startup for both 4.1.1 and 4.2.0:

```pivxd -daemon -maxconnections=16 -onlynet=ipv4```

Machine specs:
- OS: Raspbian Buster (updated)
- Hardware: Pi 4b
- RAM: 4GB
- Disk: 128GB SSD via USB 3 port

**Comment by furszy** [comment]
Hi, thanks for reporting the issue. Please increase the `-maxconnections` to a number greater than 17 and it will work fine.

The issue was already reported, will be part of the next release

**Comment by go140point6** [comment]
Yeah, that seems to do it, stays running like normal... thanks.
