### ISSUE TITLE
QT won't work properly when compiled

### ISSUE THREAD

**Issue by andi448** [PIVX-Project/PIVX#1779]
### Describe the issue
I'm trying to compile the newest release v4.2.0 (but had this issue since v4.0) and it compiles without errors, but I can't use it, because if it opens a windowed dialogue, I get a black window instead and can't click anymore.

#### If so, please list the steps to reproduce below:
1. git clone https://github.com/PIVX-Project/PIVX.git
2. git checkout v4.2.0
3. ./autogen.sh
4. /configure --with-incompatible-bdb
5. make
6. sudo make install

### Expected behavior
The QT should work properly.

### Actual behavior
If I click something and get a windowed dialogue, but it's black (see screenshot) and I can't click anywhere, nor can I exit the program via the "x"-button. I have to stop it via terminate command.

### Screenshots.
This is what I get, if I want to unlock my wallet for staking:
![PIVX](https://user-images.githubusercontent.com/37498627/89041324-748fb280-d345-11ea-9e71-6374a019e1aa.png)

### What version of PIVX Core are you using?
v4.2.0 self compiled via the commands above.

### Machine specs:
- OS: Debian Buster 10.4 up-to-date
- CPU: Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
- RAM: 8GB
- Disk size: 500GB
- Disk Type (HD/SDD): HDD

**Comment by andi448** [comment]
The problem is persisting with v4.3.0.

**Comment by random-zebra** [comment]
Could possibly be the "upgrade wallet" pop-up showing off-screen?
Did you previously had two displays connected?
Have you tried bringing back off-screen windows (ALT+spacebar, ALT+F7 and move, etc...)

**Comment by andi448** [comment]
I don't think so, because if I'm starting the qt extracted of the released `pivx-4.3.0-x86_64-linux-gnu.tar.gz`, it just works fine.
No, I've just connected a monitor for initial installing the OS, after that I just login via xrdp without any monitor connected.
Tried the combinations, ALT+space opens a search bar and ALT+F7 doesn't seem to do anything.

I've also cleared the ~/.pivx folder and ~/.config/PIVX.
It seems that the buttons on the left side are also hidden until I click on one, so I think qt isn't compiled properly?

**Comment by andi448** [comment]
This also persists in v5.0.0.

**Comment by andi448** [comment]
This also persists in v5.0.1.

**Comment by Fuzzbawls** [comment]
spun up a fresh debian 10 VM, followed the required packages instructions in [doc/build-unix.md](doc/build-unix.md), configured with `--with-incompatible-dbd`, started the wallet (regtest mode, with `-legacywallet` initially, to ensure that a subsequent run would show the HD wallet upgrade notice). subsequent run showed the notice in both default and dark theme without issue.

![ScreenShot_20210117021419](https://user-images.githubusercontent.com/7393257/104837664-ee234a80-586a-11eb-82a5-7f527f107dc9.png)

**Comment by andi448** [comment]
Thanks for testing, you've led me to the idea that my desktop environment or language settings could be the problem, so I've also spun up a few virtual machines and came to the conclusion, that KDE somehow seems to cause the problem. If I use Gnome, it works fine (even without recompiling).

But now I don't know on whose side is the incompatibility? Is it qt to KDE? How can I determine that?

**Comment by furszy** [comment]
there hasn't been interaction here in an year long, can create another issue if needed, closing..
