### ISSUE TITLE
pivx-qt wallet automatically fully encrypted after send operation

### ISSUE THREAD

**Issue by KonstMisch** [PIVX-Project/PIVX#181]
This is a usability issue. The password should be required for the send operation only. The encryption state of the wallet should not change out of users perspective. 

1. Unlock the wallet with password for anonymization and staking only.
2. Verify wallet is stacking and unlocked for transactions by hovering over the lock sign in the bottom right corner and reading the text. 
3. Go to the send tab. Enter address and amount for the transfer.
4. Click send. 
5. Asked for "pass phrase". The check box for anonymization and staking only is checked. ( **it should NOT be checked because of the current intention to transfer pivx - Different issue** )
6. Uncheck the checkbox and enter password. 
7. Click yes and notice that the transaction has been successfully send. 
8. **Notice that the wallet is fully encrypted now. This is the unexpected behavior. The user needs to encrypt the wallet for staking again although he just entered the password.**   

Wallet Version: 2.2.1 Core
OS: Debian 8 ( QubesOS )

**Comment by Mrs-X** [comment]
I'll take care of this (next weekend...).

**Comment by PIVX-Project** [comment]
I am closing this issue, as it has been resolve.
