### ISSUE TITLE
Unhelpfull messages on wrong password when sendin pivx

### ISSUE THREAD

**Issue by KonstMisch** [PIVX-Project/PIVX#182]
When the user tries to transfer pivx and the wallet is locked for staking only, the user must first enter a password to transfer pivx. If the password is wrong, the user gets confronted with unintuitive and false error messages. 

1. Wallet is open encrypted for staking.
2. Go to send, enter send details and press send. 
3. On the password prompt for decrypting the wallet fully, enter a wrong passphrase. 
4. Read the misleading messages. 
   a. "Error: The wallet was unlocked only to anonymize coins" 
   b.   A fee 10000 times higher than 0.00010000 PIV per kB is considered an insanely high fee. 

The message should be. " Wrong passphrase. Try again. "

**Comment by Mrs-X** [comment]
I'll have a look.

**Comment by Mrs-X** [comment]
I can not reproduce this:

- started wallet
- `Settings -> Unlock Wallet...`: entered corrected password with `For anonymization and staking only` checked
- went to `Send` tab, entered address and amount, pressed `Send`, unchecked `For anonymization and staking only` and entered the wrong password

Result:
![pwd](https://cloud.githubusercontent.com/assets/22873440/26652007/be1661ba-464e-11e7-8eb7-8a572f8992b9.png)

a) Did you use the official (and latest) wallet from here https://github.com/PIVX-Project/PIVX/releases ?
b) which platform / operating system ?

**Comment by Fuzzbawls** [comment]
Closing this as a "stale" issue since there hasn't been any further response.

**Comment by Cedericm** [comment]
I have a solution for this..., website coming soon. So your coins are probably not lost!
