### ISSUE TITLE
[Feature Request] Set transaction fee to lowest possible instead of returning error message

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1836]
Instead of informing an user that Customized Fee is too low, feature request to implement the same logic as it is currently with Stake Split Threshold setting: Automatically set the lowest possible Custom Fee when user type in fee that is too low.

![feeTooLow1](https://user-images.githubusercontent.com/57232689/92309081-a62e1600-efa2-11ea-976f-94010415ee97.JPG)

**Comment by furszy** [comment]
covered in #2215.
