### ISSUE TITLE
[Bug] GUI isn't updating changes using the setstakesplitthreshold console command

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1838]
It can be a bug and feature request at the same time. As the title says, Stake split threshold isn't updated immediately if stake split threshold is set using the console command. It requires a wallet restart to show the latest saved option.

![stakeSplitBug01](https://user-images.githubusercontent.com/57232689/92395611-e5d03b80-f123-11ea-9536-630814d967bc.jpg)
![stakeSplitBug02](https://user-images.githubusercontent.com/57232689/92395615-e799ff00-f123-11ea-98c1-15b89ff41c31.jpg)

OS: Ubuntu 20.04

**Comment by random-zebra** [comment]
This is also fixed in #2293
