### ISSUE TITLE
Unable to build on FreeBSD

### ISSUE THREAD

**Issue by pigfrown** [PIVX-Project/PIVX#184]
I'm trying to build PIVX in a FreeBSD 10.3 jail but getting compilation errors. 

I can successfully build dash in the same environment. 
I use the following to build dash/pivx: https://gist.github.com/clinta/e9e300a33546b0a78489fb1052ffb9c0

I get the following errors : https://pastebin.com/quqYE006

**Comment by jonspock** [comment]
Seems like a difference in dependency order (exposing inherent issue). Which C++ compiler & version is that?

**Comment by pigfrown** [comment]
[pivx@pivx ~/PIVX]$ c++ --version
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: x86_64-unknown-freebsd10.3
Thread model: posix
[pivx@pivx ~/PIVX]$

**Comment by MrDefacto** [comment]
After configure just do gmake in PIVX directory. 
Following command should be enough:

`./autogen.sh
./configure --enable-debug --with-gui=no --disable-shared --with-pic --without-miniupnpc --disable-tests --enable-hardening
gmake`

Works for me on FreeBSD 11.1

**Comment by Fuzzbawls** [comment]
Closing for now, no further update(s) received from issuer.
