### ISSUE TITLE
WSL Compile error

### ISSUE THREAD

**Issue by risingstar2018** [PIVX-Project/PIVX#1846]
cp: cannot stat '../target/x86_64-pc-windows-gnu/release/rustzcash.lib': No such file or directory

**Comment by ifaist0s** [comment]
Same issue here while compiling PIVX v4.3.0 on WSL. Please note that I had no issues compiling previous versions, on the exact same development environment.

Running a search online, I found some info on how to compile rustzcash.lib at https://github.com/ip-gpu/KomodoOcean but I haven't tested that.

@risingstar2018 to avoid confusion I believe you should change the Issue title/content and mention the version you are trying to compile.

**Comment by risingstar2018** [comment]
> Same issue here while compiling PIVX v4.3.0 on WSL. Please note that I had no issues compiling previous versions, on the exact same development environment.
> 
> Running a search online, I found some info on how to compile rustzcash.lib at https://github.com/ip-gpu/KomodoOcean but I haven't tested that.
> 
> @risingstar2018 to avoid confusion I believe you should change the Issue title/content and mention the version you are trying to compile.

PIVX v4.3.0

> Same issue here while compiling PIVX v4.3.0 on WSL. Please note that I had no issues compiling previous versions, on the exact same development environment.
> 
> Running a search online, I found some info on how to compile rustzcash.lib at https://github.com/ip-gpu/KomodoOcean but I haven't tested that.
> 
> @risingstar2018 to avoid confusion I believe you should change the Issue title/content and mention the version you are trying to compile.

PIVX 4.3.0, I had no issue for previous PIVX version compile.

**Comment by an-anonymous-user-here** [comment]
I had also an error by compiling a Windows Wallet on Ubuntu

`--disable-online-rust` was solving it

so i used in configure:

`./configure --disable-online-rust  --prefix=/`

maybe it fix your problem

**Comment by ifaist0s** [comment]
I was able to compile PIVX Windows Wallet v4.3.0 using the proposed `--disable-online-rust` switch. Thank you @an-anonymous-user-here 👍 . Do you know what functionality will be disabled/not there using that switch?

**Comment by an-anonymous-user-here** [comment]
I think it downloads all required pakages by  `make HOST=x86_64-w64-ming32`
So it didnt download it two times.
