### ISSUE TITLE
Compile error on Ubuntu

### ISSUE THREAD

**Issue by risingstar2018** [PIVX-Project/PIVX#1849]
make[3]: Entering directory '/home/ubuntu/work/PIVX/src/secp256k1'
gcc -I. -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
gcc gen_context.o -o gen_context
./gen_context
  CC       src/libsecp256k1_la-secp256k1.lo
  CCLD     libsecp256k1.la
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
make[3]: Leaving directory '/home/ubuntu/work/PIVX/src/secp256k1'
RUSTC="" TERM=dumb  build --release   --manifest-path ../Cargo.toml
/bin/bash: build: command not found
Makefile:13140: recipe for target 'cargo-build' failed
make[2]: *** [cargo-build] Error 127
make[2]: Leaving directory '/home/ubuntu/work/PIVX/src'
Makefile:12614: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ubuntu/work/PIVX/src'
Makefile:778: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by furszy** [comment]
Next time, please write which branch were you compiling and the flag that you are using. 
As far as can see, you are most likely missing to install cargo. Please check the new dependencies in the specific .md of your system.

**Comment by Fuzzbawls** [comment]
as @furszy said, you're missing the `cargo` binary. you can install it with
```bash
sudo apt install cargo
```

**Comment by habibalejalil** [comment]
same issue

**Comment by habibalejalil** [comment]
> as @furszy said, you're missing the `cargo` binary. you can install it with
> 
> ```shell
> sudo apt install cargo
> ```

getting the bellow error:
Makefile:778: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
