### ISSUE TITLE
[Bug] getinfo returns wrong moneysupply amount

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1873]
Not sure why it's happening, both wallets are on the right chain, but `getinfo` command returns totally unrelated and completely wrong outputs for `moneysupply` amount.

4.2.1rc1:
![getinfoBug1](https://user-images.githubusercontent.com/57232689/94328375-55627980-ffb2-11ea-9972-2eae26e6e756.JPG)

4.3.0rc1:
![getinfoBug3](https://user-images.githubusercontent.com/57232689/94328453-010bc980-ffb3-11ea-910b-db458f05ded2.JPG)

**Comment by random-zebra** [comment]
Thanks. Can confirm this bug.

Restart with `--reindexmoneysupply` for a temporary workaround (it takes a while).
