### ISSUE TITLE
[Feature request] Allow the Masternode owners to vote with pre-defined number of masternodes only

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1893]
For example, if user have 10 masternodes, allow the user to vote with 7 masternodes only, while 3 masternodes can stay "neutral". It offers the ability to Masternode owner to vote for some proposals with more yes votes and on the other proposals with less yes votes, without downvoting any proposal. It allows the user to vote according to his/hers own priority list which proposals are worth more and which less.

**Comment by Fuzzbawls** [comment]
I think this is such an edge case that the solution would simply be to use the already existing "alias" option for `mnbudgetvote` to explicitly vote with specific MNs. Yes, it means re-running the command multiple times. That is preferable compared to adding more bloat/complication to the RPC command.

**Comment by NoobieDev12** [comment]
Agreed. Closing.
