### ISSUE TITLE
Updated Wallet to v4.3.0 But stuck at Block 1153936

### ISSUE THREAD

**Issue by faisalharianawalla** [PIVX-Project/PIVX#1896]
This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Discord](https://discord.pivx.org).

#### If so, please list the steps to reproduce below: 
1.Has been stuck for some time
2. Not sure if I can transfer my tokens in current state
3.

### Expected behavior
Tell us what should happen  Not sure if I can transfer to different wallet my tokens may be stuck in llimbo

### Actual behavior
Tell us what happens instead Have not tried for fear of losing tokens

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of PIVX Core are you using? 
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.
v 4.3.0
### Machine specs:
- OS: Windows 10
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by random-zebra** [comment]
Fear not, if you have your private keys (your wallet.dat) then you'll recover your coins (there's no such thing as "coins stuck in limbo").
If you cannot sync, it might be that you missed an update deadline and are now on a different chain.
In this case, you can just resync from scratch or use a snapshot.

Please join PIVX Discord server to get support.
