### ISSUE TITLE
[Bug][GUI] Upgrading coins database... is now on every wallet start loading screen

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1897]
After PR #1863 got merged, Qt wallet is now showing "Upgrading coins database..." on **every** startup on loading screen, although coins database upgrade has been completed with the first 4.3.0 wallet startup after updating the wallet from pre-4.3.0 wallet version.

**Comment by Liquid369** [comment]
Based on reviewing that PR, its just a movement of the message to if we are *not* reindexing the client it will always end up saying upgrading the coins database and then error if its not able to

Follow this block here,

https://github.com/random-zebra/PIVX/blob/979cb7495e9961cc7db8d0ec27bc332bab845376/src/init.cpp#L1494

Also as per #1801 random.zebra says it will always show but for a fraction of the startup as the function would return quickly.

Do you see it hanging in that portion or ?

No time to dive into a possible IsUpgradeNeeded() function or something similar, but as you see by above, its not necessarily a bug and we could solve that if thats the case by this

If its decided to go this way could submit something idk

**Comment by random-zebra** [comment]
Yes it's normal for the init message "Upgrading coins database..." to be displayed every time.
If the database is already upgraded, the message is quickly replaced by the following step ("Loading sporks...").
We can surely add some logic to outright prevent displaying "Upgrading coins database..." if is already upgraded, but I don't think it's really worth the effort.

**Comment by NoobieDev12** [comment]
Thanks for the comments. It's just GUI thing then, not a bug. Not worth the effort for a trivial GUI change that an average user won't even realize. Closing it.
