### ISSUE TITLE
PIVX-Qt.app is damaged

### ISSUE THREAD

**Issue by schlady** [PIVX-Project/PIVX#190]
### Describe the issue
The native PIVX app for MacOSX is not working/starting.
 
### Can you reliably reproduce the issue?
Yes.

#### If so, please list the steps to reproduce below:
1. Download the PIVX wallet installer from [github](https://github.com/PIVX-Project/PIVX/releases/download/v2.2.1/pivx-2.2.1-osx-unsigned.dmg)
2. Install it
3. Start it (/Applications/PIVX-Qt.app)

### Expected behavior
The PIVX wallet should start.

### Actual behavior
The PIVX wallet does not start, but a warning message appears, saying
`"PIVX-Qt.app" is damaged and can't be opened. You should move it to Trash.`

### Screenshots.
![image](https://cloud.githubusercontent.com/assets/873370/26378779/55118cd2-4016-11e7-99e1-7ad33c916403.png)

### What version of PIVX Core are you using?
v2.2.1 ( commit c23ceb4), official dmg installer

### Machine specs:
- OS: MacOS Sierra
- CPU: Intel Core i5
- RAM: 16 GB
- Disk size: 512 GB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
- Before I installed the new version of the PIVX wallet, I installed the latest MacOS Sierra update (v10.12.5).
- Old version (v2.2.0) of the app worked before the MacOS Sierre update.
- The binary pivx-qt from v2.2.1 tar package works without problems.

**Comment by Fuzzbawls** [comment]
try downloading again with a different browser. This is the first I have heard of this and there are others on OS X Sierra that are not having this problem.

**Comment by MarkShulgasser** [comment]
Similar problems. Downloaded from Github to MacOSX via Chrome, the wallet quits while Loading block index. Via Safari the download does not complete.

**Comment by Fuzzbawls** [comment]
@MarkShulgasser that isn't a similar issue at all mate.

Please read the original issue, if you aren't seeing the message stating that the app is damaged, then please file a new issue report.

**Comment by schlady** [comment]
@Fuzzbawls same problem with downloading from firefox.
I verified the checksum and they also match.  
:/

**Comment by Fuzzbawls** [comment]
@schlady Not sure what to tell you mate. I've checked, double checked, and triple checked with numerous other people running OS Sierra 10.12.5 and nobody can reproduce your issue.

**Comment by Fuzzbawls** [comment]
Closed for now due to this seemingly being a non-reproducible one-off issue.

**Comment by schlady** [comment]
@Fuzzbawls the problem is gone since I updated to v2.3.0
Thanks anyway!
