### ISSUE TITLE
[Bug] Different wallets showing different results for getbudgetinfo command

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1902]
Running a `getbudgetinfo` command for the same proposal on 2 different wallets is returning a different output.

![exist01](https://user-images.githubusercontent.com/57232689/95262332-3c688c80-082c-11eb-9e7f-329013bf5330.JPG)

![notExist01](https://user-images.githubusercontent.com/57232689/95262335-3e325000-082c-11eb-894b-5a87a43d978a.JPG)

OS: Windows 10 + Windows Server 2019

**Comment by furszy** [comment]
Isn't an issue, it could happen if the node isn't, tier two wise, synced and/or if none one of the connected peers have the proposal on their cache. Sooner or later, it will be gossiped across the network and all of the peers will see it.
