### ISSUE TITLE
PIVX daemon get killed when command is casted during the initial wallet loading phase

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1908]
I'm not sure if this is related to Linux only and cannot be prevented, but I'll post in case there's a solution for this on PIVX side.

**Describe the issue:**

pivxd gets killed when you cast a command during the initial loading block index phase, before the wallet loads up.

**Can you reliably reproduce the issue?**
Yes.

**If so, please list the steps to reproduce below:**
1. Start the pivxd with the `./pivxd` command (it will return `PIVX server starting`)
2. At the moment when `tail -f ~/.pivx/debug.log` command returns `init message: Loading block index...`, type any command, for example `./pivx-cli getbestblockhash`, return message will be `error: couldn't connect to server` and pivxd will be killed.
3. To confirm that pivxd got killed, `./pivx-cli stop` command returns `error: couldn't connect to server` instead of the `PIVX server stopping`.

**What version of PIVX Core are you using?**
4.3.0

**OS: Ubuntu Linux 20.04**

**Comment by JSKitty** [comment]
> I'm not sure if this is related to Linux only

I can confirm it does the same on Windows when the RPC is called during startup.
I have applications/scripts that call daemons frequently, and they always crash if it's called during the daemon's initialization.

In my cases it affects all PIVX versions I've tried (v4.0.0 to v4.3.0).

**Comment by random-zebra** [comment]
Thanks for the report. 
Fixed in #1909: during startup, now, commands throw an exception returning the exact init message ("Loading block index...", "Loading masternodes...", etc).
