### ISSUE TITLE
[GUI] Budget allocation is considered as a Masternode Reward

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1917]
Does it makes sense if a payment from the PIVX monthly budget be considered as a Masternode Reward?

![mnReward](https://user-images.githubusercontent.com/57232689/95979674-4a19a580-0e1c-11eb-87e8-7b8031552f41.JPG)

**Comment by random-zebra** [comment]
As it is the code now, budget payments replace masternode payouts during superblocks.  So, yeah, it kinda makes sense for the wallet to display it that way. This will change soonish with the updates planned for the tier2 network.

**Comment by furszy** [comment]
More and more development are coming 😄
