### ISSUE TITLE
[Bug] TX gets marked as conflicted - 2 scenarios outlined

### ISSUE THREAD

**Issue by mattL87** [PIVX-Project/PIVX#1923]
### Describe the issue
An issue with a TX being marked as Conflicted.

#### If so, please list the steps to reproduce below
Scenario 1:
1. Create a new TX.
2. Stake the next block.
3. TX is then conflicted.

Scenario 2:
1. Stake a block.
2. Wallet will attempt to stake the same input previously staked.

### Expected behavior
Should not attempt to stake recent/or previous input. 

### Actual behavior
After adding more log prints to the code to investigate what was going on, I found that the wallet is trying to stake the most recent input. So when a new TX is produced and you stake the next block, it's always marked as conflicted. What's happening is that it's trying to stake one of the inputs used in the previously generated TX. The same issue is seen while generating new stake. The wallet will attempt to stake several times the previous input that has already been staked.

### What version of PIVX Core are you using?
Linux 64 bit v4.3.0

### Machine specs:
Linux 18.04

**Comment by random-zebra** [comment]
Thanks for reporting this, @mattL87
