### ISSUE TITLE
[Bug] TX output size is validated with the wrong constant value.

### ISSUE THREAD

**Issue by mattL87** [PIVX-Project/PIVX#1929]
### Details:
The output size of a standard TX is validated with the following constant MAX_ZEROCOIN_TX_SIZE.
We should be checking it against MAX_STANDARD_TX_SIZE.

### Reference:
https://github.com/PIVX-Project/PIVX/blob/8a9b92c0ed5d66a6a83861b6134cedb149553d8b/src/consensus/tx_verify.cpp#L66

**Comment by random-zebra** [comment]
> We should be checking it against MAX_STANDARD_TX_SIZE.

No. 
A transaction with size exceeding `MAX_STANDARD_TX_SIZE`, is non-standard (meaning it's not accepted in the mempool), but is still valid inside a block.
The consensus limit here was initially the whole 1MB block space (`MAX_BLOCK_SIZE_LEGACY`), but it was lowered to `MAX_ZEROCOIN_TX_SIZE` (for all transactions) way back in 14588e825ee1b5bc2e1b1301860d89e30dddae86
