### ISSUE TITLE
socket send error Connection reset by peer

### ISSUE THREAD

**Issue by ScArFaCe2020** [PIVX-Project/PIVX#1957]
Hello,

I'm getting **Socket send error Connection reset by peer (104)** and **socket send error Broken pipe (32)** on my server.
I'm running current Ubuntu 18.04 (256GB RAM) with the latest PIVX wallet (4.3.0)

When this problem happened:

1. Only in Masternode wallets. (i'm running 39 wallets on this server)
2. After Masternode is enabled +-48 hrs.
3. Its random happened at all wallets.

**How i can solve this issue for next 48 hours:**
restart the wallet and enable the Masternode again in mine Windows Wallet.

Debug Log:

2020-11-01 23:58:33 socket send error Connection reset by peer (104)

2020-11-02 07:13:02 socket send error Broken pipe (32)

I have tested this also with Phantom nodes but there i don't have this issue.

**Comment by furszy** [comment]
The issue was solved in master. If you can, try self-compiling the code from the sources.
Remember that in master you will have to download the Sapling circuit params, script available in `/util/fetch-params.sh`.

**Comment by ScArFaCe2020** [comment]
Hello,

I i'm trying to run the fetch-params.sh but i'm getting some problem with it, can someone help me with this:

root@pivx:~/PIVX/util# ./fetch-params.sh "Ubuntu"
PIVX - fetch-params.sh

This script will fetch the PIVX zkSNARK parameters and verify their
integrity with sha256sum.

If they already exist locally, it will exit now and do nothing else.

Retrieving (wget): https://download.z.cash/downloads/sapling-spend.params.part.1
Ubuntu/sapling-spend.params.dl.part.1: No such file or directory

Retrieving (ipfs): /ipfs/QmXRHVGLQBiKwvNq7c2vPxAKz1zRVmMYbmt7G5TQss7tY7/sapling-spend.params.part.1
Error: merkledag: not found

Retrieving (curl): https://download.z.cash/downloads/sapling-spend.params.part.1
Warning: Failed to create the file Ubuntu/sapling-spend.params.dl.part.1: No
Warning: such file or directory

curl: (23) Failed writing body (0 != 936)

Failed to fetch the PIVX zkSNARK parameters!
Try installing one of the following programs and make sure you're online:

 * ipfs
 * wget
 * curl

root@pivx:~/PIVX/util#


ipfs is installed:

root@pivx:~/PIVX/util# ipfs version
ipfs version 0.7.0

root@pivx:~/PIVX/util# curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

root@pivx:~/PIVX/util# wget --version
GNU Wget 1.19.4 built on linux-gnu.

-cares +digest -gpgme +https +ipv6 +iri +large-file -metalink +nls
+ntlm +opie +psl +ssl/openssl

Wgetrc:
    /etc/wgetrc (system)
Locale:
    /usr/share/locale
Compile:
    gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC="/etc/wgetrc"
    -DLOCALEDIR="/usr/share/locale" -I. -I../../src -I../lib
    -I../../lib -Wdate-time -D_FORTIFY_SOURCE=2 -DHAVE_LIBSSL -DNDEBUG
    -g -O2 -fdebug-prefix-map=/build/wget-Xb5Z7Y/wget-1.19.4=.
    -fstack-protector-strong -Wformat -Werror=format-security
    -DNO_SSLv2 -D_FILE_OFFSET_BITS=64 -g -Wall
Link:
    gcc -DHAVE_LIBSSL -DNDEBUG -g -O2
    -fdebug-prefix-map=/build/wget-Xb5Z7Y/wget-1.19.4=.
    -fstack-protector-strong -Wformat -Werror=format-security
    -DNO_SSLv2 -D_FILE_OFFSET_BITS=64 -g -Wall -Wl,-Bsymbolic-functions
    -Wl,-z,relro -Wl,-z,now -lpcre -luuid -lidn2 -lssl -lcrypto -lpsl
    ftp-opie.o openssl.o http-ntlm.o ../lib/libgnu.a

Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later
<http://www.gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Originally written by Hrvoje Niksic <hniksic@xemacs.org>.
Please send bug reports and questions to <bug-wget@gnu.org>.
