### ISSUE TITLE
Unit caps

### ISSUE THREAD

**Issue by davidhedlund** [PIVX-Project/PIVX#197]
I need to finish https://en.bitcoin.it/wiki/Comparison_of_cryptocurrencies

* How many units are "hard-wired" in to the protocol?
* Is the rest of the information correct or should I change anything?
* Do you want to add something to the comment column?

**Comment by Fuzzbawls** [comment]
There is no cap on the number of coins that will ever be generated. The supply increase per year is now at ~2.6 million, which gives diminishing returns on inflation percentage.

**Comment by davidhedlund** [comment]
@Fuzzbawls I changed your Unit cap to **Unlimited**. Give me a short an concise text if you want to modify it and I'll add it.

**Comment by davidhedlund** [comment]
@Fuzzbawls What is the mining fee?

**Comment by davidhedlund** [comment]
Is PIVX the first cryptocurrency that implements the Quark algorithm?

**Comment by PIVX-Project** [comment]
PIVX is no longer mine-able, so there is no mining fee. The crypto-currency project 'Quark' was the first to implement the quark algo. We chose to use that particular algo during our mine-able period because of it's asic resistance and the fact that it could be mined fairly by all PC's

**Comment by davidhedlund** [comment]
@PIVX-Project Thank you. I updated the page again.

**Comment by Fuzzbawls** [comment]
Closing, questions answered. If you have more questions on this subject just comment again.
