### ISSUE TITLE
Compiling latest master problem

### ISSUE THREAD

**Issue by kopykatA** [PIVX-Project/PIVX#1992]
I was compiling all earlier versions by myself.
In latest version (4.3.0) i had problems with my masternodes getting stuck all the time. Tried to use suggested fix in chat put it was not permanent and after a while i had to restart the masternodes. In chat it was suggested that a fix is pushed in latest master and that it would be helpful to compile and run it. Now my problem starts.
Even though i have all dependencies described in build-unix file installed, i still get an error in "make".
The msg is the following:
make
Making all in src
make[1]: Entering directory '/root/PIVX/src'
make[2]: Entering directory '/root/PIVX/src'
make[3]: Entering directory '/root/PIVX'
make[3]: Leaving directory '/root/PIVX'
RUSTC="/root/.cargo/bin/rustc" TERM=dumb /root/.cargo/bin/cargo build --release   --manifest-path ../Cargo.toml
    Finished release [optimized] target(s) in 0.95s
  CXXLD    pivxd
libbitcoin_server.a(libbitcoin_server_a-init.o): In function `path<boost::filesystem::directory_entry>':
/usr/include/boost/filesystem/path.hpp:140: undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
libbitcoin_wallet.a(libbitcoin_wallet_a-walletdb.o): In function `path<boost::filesystem::directory_entry>':
/usr/include/boost/filesystem/path.hpp:140: undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `boost::program_options::detail::basic_config_file_iterator<char>::getline(std::string&)':
/usr/include/boost/program_options/detail/config_file.hpp:161: undefined reference to `boost::program_options::to_internal(std::string const&)'
libbitcoin_util.a(libbitcoin_util_a-util.o): In function `boost::program_options::detail::basic_config_file_iterator<char>::basic_config_file_iterator(std::istream&, std::set<std::string, std::less<std::string>, std::allocator<std::string> > const&, bool)':
/usr/include/boost/program_options/detail/config_file.hpp:145: undefined reference to `boost::program_options::detail::common_config_file_iterator::common_config_file_iterator(std::set<std::string, std::less<std::string>, std::allocator<std::string> > const&, bool)'
collect2: error: ld returned 1 exit status
Makefile:4993: recipe for target 'pivxd' failed
make[2]: *** [pivxd] Error 1
make[2]: Leaving directory '/root/PIVX/src'
Makefile:13096: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/PIVX/src'
Makefile:778: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

#### If so, please list the steps to reproduce below:
1. I reinstalled the dependencies o make sure
2. Run ./autogen.sh, then ./configure  (they worked ok)
3. Then run make

### Expected behavior
Finish compile and use the bin.

### Actual behavior
The above error appeared.

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of PIVX Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.
latest master
### Machine specs:
- OS: ubuntu 16.04
- CPU: 4 x 2.4 GHz
- RAM:16gb
- Disk size: 160gb
- Disk Type (HD/SDD):HD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by Fuzzbawls** [comment]
looks like you're missing the `-dev` boost packages. try the following:
```bash
sudo apt-get install --reinstall libboost-all-dev
```
