### ISSUE TITLE
Stuck a block but still showing active in controller

### ISSUE THREAD

**Issue by borris345** [PIVX-Project/PIVX#202]
Real problems with stuck wallets/masternodes.

In the controller wallet it shows its active but when check the debug file of the masternode it is stuck. Filled with:

2017-06-12 13:34:56 getblocks 661368 to eabaeacf9c731ed24736a2df66931b1ffd8c7673cfc6d35223c9923ac281058a limit 500 from peer=2869

**Comment by rejectedpromise** [comment]
still relevant?

**Comment by Mrs-X** [comment]
This (stuck at a block) was fixed with Zerocoin release last year, so I'll close this one.

If it should happen again please open a new issue.
