### ISSUE TITLE
Can't open Core Wallet on MacOSX

### ISSUE THREAD

**Issue by MarkShulgasser** [PIVX-Project/PIVX#203]
### Describe the issue

Downloaded from Github to MacOSX via Chrome, the wallet quits while 'Loading block index'. Via Safari the download does not complete.

#### If so, please list the steps to reproduce below:
1. Download
2. Open Core Wallet
3. First page displays with "Loading block index..." then quits.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of PIVX Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.
2.2.1 dmg from Github

### Machine specs:
- OS: x.12.2
Model Name:	Mac mini
  Model Identifier:	Macmini4,1
  Processor Name:	Intel Core 2 Duo
  Processor Speed:	2.4 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache:	3 MB
  Memory:	4 GB
  Bus Speed:	1.07 GHz
  Boot ROM Version:	MM41.0042.B03
  SMC Version (system):	1.65f2
  Serial Number (system):	C07D32GRDD6H
  Hardware UUID:	088758E6-DB1F-5EC9-9E33-0402BCEA8499

- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

There are two wallet files in the User/Library, a .log whch indicates the beginning of activity on June 10, and a .db which lacks an application to open it with. When the page quits there's a long report to send to Apple, but I can't copy it -- it would require several screen shots. Which I can do if it would help. Thanks.

**Comment by Fuzzbawls** [comment]
yes, need screenshots (or copy/paste the text from the report window), also any contents from `debug.log` and `db.log` (both can be opened with any plain text editor like the TextEdit app.

**Comment by Fuzzbawls** [comment]
closing, haven't received any further information
