### ISSUE TITLE
[Documentation] v5 release new capabilities and changes

### ISSUE THREAD

**Issue by furszy** [PIVX-Project/PIVX#2057]
This issue is merely to track the progress over the different areas that require documentation for v5.

Upcoming release is really huge, we need to start sooner rather than later preparing the release notes and pulling the information from all of the created PR/commits. New wallet and node capabilities introduced, new RPC commands and visual workflows, functional changes over pre-existent workflows, new unit and functional tests etc.

Essentially, we need to "land down" +1100 commits (180 PRs) into a proper release notes doc so when testnet phase finishes, we can go straight to mainnet.

**Comment by random-zebra** [comment]
Closed with #2114
