### ISSUE TITLE
Initial sync takes too long on a NAS (old school harddrive)

### ISSUE THREAD

**Issue by rennne** [PIVX-Project/PIVX#209]
Initial "sync with the network" takes more than a week, when the pivx-folder is set to a NAS-drive with an old-school Harddrive via Gbit-LAN

PIVX v2.2.1 64bit
Windows 7 Sp1 64bit 8GB sdd 

Later, I changed that folder to my internal SSD an it is much faster, but still takes 11 hours and pivx-qt.exe is running on one cpu-core at maximum(100%) all the time. Maybe that is supposed to be that way. 

In comparison may dash-wallet took about 3 hours for the same process.

**Comment by sabhiram** [comment]
The full sync of the chain certainly takes a bit of time. You can always try using one of the supported bootstrap files if you are in a rush :)

**Comment by rennne** [comment]
I am not in a rush, and my local SSD solved it anyway. But this behavior indicates a flaw in the software, therefore I reported it.

**Comment by Mrs-X** [comment]
Syncing speed mainly depends on 3 factors:
a) network speed
b) number of transactions which belong to the addresses/keys of your wallet.dat
c) disk (seeking-) speed

a) is (almost) linear, if your internet connection is twice as fast the sync time (almost) halves.
b) doesn't matter until you reach some 5 digit numbers of transaction. But then it _really_ gets slow.
Best workaround is to move that wallet.dat somewhere else, sync (which creates a new wallet.dat), and than copy your original back. Don't forget to stop the wallet before doing this!
c) SSDs are the solution here.

**Comment by Fuzzbawls** [comment]
Closing, this is more of a hardware/network/environment issue rather than a software issue.
