### ISSUE TITLE
[Trivia] GitHub's main repo still describes zPIV

### ISSUE THREAD

**Issue by kyeno** [PIVX-Project/PIVX#2099]
Just a trivial copy issue that I wanted to mention here in order it won't get lost in the lines.
https://github.com/PIVX-Project/PIVX/blob/master/README.md

This is likely also used by various people to determine what the coin is, especially as link to it is referred in SERP.

**Comment by random-zebra** [comment]
#2095 was opened just few hours ago :)

**Comment by furszy** [comment]
PR merged, closing
