### ISSUE TITLE
PIVX Core Client is not Syncing

### ISSUE THREAD

**Issue by jjmr007** [PIVX-Project/PIVX#210]
Client Version V2.2.1
Windows 7 Ultimate
CPU: Intel Celeron G1610
RAM: 8 GB
Disk Size: 2 TB
Disk Type: HDD

Issue:
Wallet got stuck in block# 709048 in mainnet (16 peers)
Wallet got stuck in block# 144825 in testnet (1 peer)

How to reproduce the issue: I just ran pivx_qt.exe in mainnet and in testnet (--testnet)

Expected behavior: I always got the wallet syncronized in few minutes. Now my client is permanently stuck.

Mainnet Client:
![mainnet](https://user-images.githubusercontent.com/17028457/27815986-8e11440e-6056-11e7-9d93-2be5e0f620f9.PNG)

Testnet Client:
![testnet](https://user-images.githubusercontent.com/17028457/27816495-eb484958-6059-11e7-9cc1-3482b3b000b5.PNG)

debug.log file for mainnet, with extension changed to "txt":
[debug.txt](https://github.com/PIVX-Project/PIVX/files/1121047/debug.txt)

debug.log file for testnet, with extension changed to "txt":
[debug.txt](https://github.com/PIVX-Project/PIVX/files/1121052/debug.txt)

**Comment by Fuzzbawls** [comment]
no errors here, though i do see you starting/stopping your client a number of times in quick succession.

Testnet will be for the most part unavailable right now as we're doing tests on a higher protocol version at the moment in preparation for the next major release.

**Comment by jjmr007** [comment]
Should I wait or restart the PC to re-initiate the client?
Thanks for the testnet info. 

(Btw: Is there any way to get some testnet pivx coins?) Regards

**Comment by rejectedpromise** [comment]
still relevant?
