### ISSUE TITLE
Masternodes with offline (paper) wallets

### ISSUE THREAD

**Issue by cryptoclm** [PIVX-Project/PIVX#2106]
Can masternodes be run with offline paper wallets? 
if it is possible to do this, how to manually sign the masternode ?

**Comment by furszy** [comment]
Masternodes are 24/7 online nodes storing the complete blockchain, periodically signaling the network to indicate its normal operation (heartbeat).

You can store the collateral private key on a paper wallet, but you will initially need a controller wallet crafting and broadcasting the masternode start message and the 24/7 server running the masternode.

**Comment by cryptoclm** [comment]
> Masternodes are 24/7 online nodes storing the complete blockchain, periodically signaling the network to indicate its normal operation (heartbeat).
> 
> You can store the collateral private key on a paper wallet, but you will initially need a controller wallet crafting and broadcasting the masternode start message and the 24/7 server running the masternode.

is it possible to do the masternode start message using bitcoinjs?
