### ISSUE TITLE
host dependency in depends directory

### ISSUE THREAD

**Issue by techy2** [PIVX-Project/PIVX#2127]
### Describe the issue

building the depends directory on ubuntu goes smoothly
when attempting to build an link the binaries an error is encountered <- below ->

RUSTC="/master/gitrepo/PIVX/depends/x86_64-pc-linux-gnu/share/../native/bin/rustc" TERM=dumb /master/gitrepo/PIVX/depends/x86_64-pc-linux-gnu/share/../native/bin/cargo build --release   --manifest-path ../Cargo.toml
/master/gitrepo/PIVX/depends/x86_64-pc-linux-gnu/share/../native/bin/cargo: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /master/gitrepo/PIVX/depends/x86_64-pc-linux-gnu/share/../native/bin/cargo)
/master/gitrepo/PIVX/depends/x86_64-pc-linux-gnu/share/../native/bin/cargo: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by /master/gitrepo/PIVX/depends/x86_64-pc-linux-gnu/share/../native/bin/cargo)
Makefile:12908: recipe for target 'cargo-build' failed
make[2]: *** [cargo-build] Error 1

This is error is caused by a pre-compiled binary "cargo" embedded in downloaded package from
depends.pivx.org --- rust-1.42.0

The binary "cargo" includes code built AFTER the release of 1.42.0 which requires the openssl-1.1.1 library
At the time of 1.42.0 release, openssl-1.0.2 was required.

exact rust package downloaded from depends.pivx.org
rust-1.42.0-x86_64-unknown-linux-gnu.tar.gz

The system used for the build does not have openssl-1.0.2 or 1.1.1, it has 1.1.0
The requirement for the host system to have a particular version of openssl breaks the "depends" system

### Can you reliably reproduce the issue?
YES
#### If so, please list the steps to reproduce below:
pre-condition, underlying OS must not have openssl 1.1.1

1. git clone ..... PIVX...
2. cd depends
3. make
4. cd ../
5.  ./autogen.sh
6. ./configure --prefix=blah blah
7. make

### Expected behavior
no error

Tell us what should happen
error as shown above

### What version of PIVX Core are you using?

latest git clone as of this date
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

### Machine specs:
- OS: ubuntu 18.04
- CPU: dual Xeon X5570
- RAM: 128 GB
- Disk size: 1.5T
- Disk Type Fully ram buffered with smart controller HP proliant series server

### Any extra information that might be useful in the debugging process.
dump of the downloaded rust-1.42.0-x86_64-unknown-linux-gnu.tar.gz
package shows binary file ./cargo/bin/cargo

running this file produces the error
 ./cargo
./cargo: /usr/lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by ./cargo)
./cargo: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by ./cargo)

This BREAKS the depends library completely

**Comment by NoobieDev12** [comment]
@techy2 you're missing a cargo lib. Run this command and try to compile again:

`sudo apt-get install libssl-dev libgmp-dev libevent-dev libboost-all-dev libsodium-dev cargo`

**Comment by techy2** [comment]
The whole point of the depends system is to avoid having to clutter up the system with extra libraries that many times create compatibility issues. I could simply install openssl-1.1.1 and the error would go away. I do not wish to do that because I am fairly sure it will break running programs on this SERVER

There should be no dependencies within a depends library system other then basic compilers required for the build. 
The depends requested SOURCE file rust-1.42.0-x86_64-unknown-linux-gnu.tar.gz  includes a binary that has local host dependencies. This is fundmentally flawed. If that source file needs openssl-1.1.1, then it should be in the depends tree and the "binary" should be built for source so the entire system is portable.
This is a bug, it would be nice if it were fixed by whoever decided "rust" was needed in the first place. Previous versions of PIVX were free of yet another layer of language requirements. If they must be used then they need to be portable, not system dependent.

**Comment by furszy** [comment]
give it another try now, #2280 got recently merged.
