### ISSUE TITLE
Keyboard not working in GUI

### ISSUE THREAD

**Issue by a2457** [PIVX-Project/PIVX#2140]
### Describe the issue
Used snap store to install 5.01 , when going to the debug console, keyboard does not respond. can't type in there. or in any other field. (the keyboard works in linux.)

### Expected behavior
i should be able to type.

### Actual behavior
i can not type

### What version of PIVX Core are you using?
v5.01, problem was present in v5.0
### Machine specs:
- OS:ubuntu 18
- CPU: e350 amd
- RAM: 4 gigs
- Disk size: 120 gigs
- Disk Type (HD/SDD):
sdd

**Comment by Fuzzbawls** [comment]
just pushed a new revision to the stable branch that should fix the issue. the snap store should see that there is an update available shortly, otherwise you can run `snap refresh pivx-core` from the terminal

**Comment by Fuzzbawls** [comment]
@a2457 please update here if the issue has been resolved with the latest snap version or not

**Comment by a2457** [comment]
Yess, issue fixed with upgrade, thank you for the fast response
