### ISSUE TITLE
"getbalance" with arguments broken in latest versions

### ISSUE THREAD

**Issue by SharkWipf** [PIVX-Project/PIVX#2149]
### Describe the issue
A recent update changed the `getbalance` syntax, but now neither the new or old syntax work anymore.
Without arguments, `getbalance` works fine, but with any arguments in any order, it will throw an error.
Also, the documentation is only half-updated, and lists the old syntax in the examples.

#### If so, please list the steps to reproduce below:
```bash
# No arguments, works
$ pivx-cli getbalance
22.29595636

# Old syntax, broken
$ pivx-cli getbalance "*" 25
error: {"code":-1,"message":"JSON value is not an integer as expected"}

# New syntax, broken
$ pivx-cli getbalance 25
error: {"code":-1,"message":"JSON value is not an integer as expected"}
```
### Expected behavior
The wallet should return the balance with the filters from the arguments applied.

### Actual behavior
The call exits with an error.

### What version of PIVX Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.
Pivx Core Daemon version v5.0.1, official package

### Machine specs:
- OS: Ubuntu 16.04

**Comment by random-zebra** [comment]
Fixed in #2141 and #2147
