### ISSUE TITLE
database/chain corruption on power loss

### ISSUE THREAD

**Issue by rnewsham** [PIVX-Project/PIVX#215]
This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Slack](http://pivx.slack.com).

### Can you reliably reproduce the issue?
yes

#### If so, please list the steps to reproduce below:
1. lose power (power loss, or toddler finds the 'reset' button)
2. chain is broken (assertion fails)
3. need to manually delete chain and resync

### Expected behavior
Surely you are capable of writing some recovery routine on start-up that throws away corrupt blocks and resumes from some reasonable point, and does so automatically, and doesn't require a full resync.

### Actual behavior
wasted time, and masternode connection lost

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of PIVX Core are you using?
$ ./pivx-cli --version
Pivx Core RPC client version v2.2.0
$ ./pivxd --version
Pivx Core Daemon version v2.2.0

### Machine specs:
- OS: ubuntu 16.04
- CPU: lots
- RAM: lots
- Disk size: lots
- Disk Type (HD/SDD): hd

**Comment by rnewsham** [comment]
pivxd: main.cpp:2300: bool ConnectBlock(const CBlock&, CValidationState&, CBlockIndex*, CCoinsViewCache&, bool): Assertion `hashPrevBlock == view.GetBestBlock()' failed.

**Comment by Fuzzbawls** [comment]
upgrade to v2.2.1

**Comment by rnewsham** [comment]
ok. upgrading. 

can close this ticket.

thanks!
