### ISSUE TITLE
pivx-cli/pivx-tx do not compile on macOS 11 when using CMake

### ISSUE THREAD

**Issue by VisionBao** [PIVX-Project/PIVX#2151]
### Describe the issue
I can't build  pivx-cli.
I had compiled the code correctly before 5.0.0. However, an error will be reported after the update.

#### If so, please list the steps to reproduce below:
1.Update the code to tag 5.0.1
2.Clean & Run.

### Actual behavior
...
[ 46%] Building CXX object CMakeFiles/pivx-cli.dir/src/pivx-cli.cpp.o
[ 46%] Building CXX object CMakeFiles/COMMON_A.dir/src/keystore.cpp.o
[ 46%] Linking CXX executable pivx-cli
Undefined symbols for architecture x86_64:
  "_CFBundleCopyBundleURL", referenced from:
      initZKSNARKS() in libUTIL_A.a(util.cpp.o)
  "_CFBundleGetMainBundle", referenced from:
      initZKSNARKS() in libUTIL_A.a(util.cpp.o)
  "_CFRelease", referenced from:
      initZKSNARKS() in libUTIL_A.a(util.cpp.o)
  "_CFStringGetCStringPtr", referenced from:
      initZKSNARKS() in libUTIL_A.a(util.cpp.o)
  "_CFStringGetSystemEncoding", referenced from:
      initZKSNARKS() in libUTIL_A.a(util.cpp.o)
  "_CFURLCopyFileSystemPath", referenced from:
      initZKSNARKS() in libUTIL_A.a(util.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [pivx-cli] Error 1
make[1]: *** [CMakeFiles/pivx-cli.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 46%] Building CXX object CMakeFiles/SERVER_A.dir/src/net_processing.cpp.o
[ 46%] Built target qt_stuff_autogen
...

### Screenshots.
<img width="677" alt="Screenshots" src="https://user-images.githubusercontent.com/10562694/105441803-48c20980-5ca4-11eb-809f-7df0f0627b47.png">
### What version of PIVX Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

### Machine specs:
- OS:macOS 11.1
- CPU:Intel Core i7
- RAM: 16GB
- Disk size:500G
- Disk Type (HD/SDD):SSD

I can't find and solve the problem from the log, so where should the problem be?

**Comment by Fuzzbawls** [comment]
The problem is due to a change in Apple's linker policy with Big Sur that no longer allows linking against a core libraries' file on disk directly.

See #2152 for a fix.

Note: CMake is not the only build system we support, and it is considered a "secondary" build system for us, with the much more mature Autotools build system being our "primary" build system. I tested Autotools on Big Sur and it works as-is, so this issue is specific to CMake.

**Comment by VisionBao** [comment]
thx for your tip. @Fuzzbawls .

I checked the CMakeList.txt file and found that the cocoa library was not connected when compiling pivx-cli. In the latest update, the content of the cocoa library is used in util.cpp, so I can't compile. 

Just add `target_link_libraries(pivx-cli "-framework Cocoa")`

By the way, what IDE do you recommend under macOS?

**Comment by Fuzzbawls** [comment]
> Just add `target_link_libraries(pivx-cli "-framework Cocoa")`

Yes, that is what #2152 does.


> By the way, what IDE do you recommend under macOS?

I use CLion. I'm not on Big Sur though, hence why this issue was not caught sooner

**Comment by Alonewolf-123** [comment]
I can't build pivx-qt on macOS Big Sur.

I think it needs c++14 or c++17. Can you help me please?
