### ISSUE TITLE
[Bug] Cold Staked UTXOs After Fee is not calculated properly

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#2156]
Steps to reproduce the issue:
1. Running the 5.0.1 on mainnet with wallet locked.
2. Set the custom fee to 0.0001 PIV/kb (not sure if that plays the role too, but issue can be reproduced with it for sure). 
3. On a single transparent address there are multiple UTXOs, all of them Cold Staked (delegated to the same cold staking address, make sure there are at least 10-15 UTXOs).
4. Open Coin Control, select all UTXOs from the address, copy-paste the After Fee amount into the Amount field and try to send them to the outside PIVX address.
5. The following error with appear:
![cold staking fees bug1](https://user-images.githubusercontent.com/57232689/105740810-d8341a80-5f39-11eb-85ec-9fa00d1a8023.jpg)

**Comment by NoobieDev12** [comment]
It's kind of weird situation that "After Fee" still doesn't work and returns "Insufficient funds..." error, while at the same time when you copy-paste the Amount and use the "subtract fee from Amount" function it **does work**, while these functions are the same actually.

**Comment by random-zebra** [comment]
The functions are completely different. The fee displayed in coin control, as well as "After Fee", involves some guess-work as it must be available *before* creating the transaction. "Subtract-fee-from-amount", instead, does the calculation *during* the transaction creation process.

**Comment by random-zebra** [comment]
@NoobieDev12 try #2568 when you can.

Btw, as stated before, keep in mind that this is different than "subtract fee from amount".
Copying "After fee" **always** results in paying a slightly higher fee than you would pay with SFFA.

For example, for the computation of the fee in coin control, it is assumed an additional output for the change.
But, when you copy "after fee", you don't need a change output. The difference is so small that is added to the fee anyway.

You can try sending one single coin (with default fee rate): with SFFA you pay ~0.00000192, while with "after fee" you pay ~0.00000227.
