### ISSUE TITLE
[Request] Daily version check within software

### ISSUE THREAD

**Issue by Elliander** [PIVX-Project/PIVX#2158]
### Describe the issue

This is more of a feature request combined with feedback than a bug report, although the way it works right now does feel very buggy.

When a mandatory release comes out it results in all staking going inactive, however, there is NOTHING to indicate that this has happened. In fact, it even showed that it was synchronized, whereas after updating it was actually unsynchronized for 2 days showing that not only does the user not get the information they need, it also gives them wrong information. 

This isn't my first time encountering an issue like this, so I have gotten used to checking to see if staking is active if I haven't recieved any stakes in a few days at which point I look it up to see if there are new updates. In this case, I missed a few mandatory updates since my last update a few weeks ago.

My first time encountering this issue though I had no idea that it wasn't staking and I had the software running for _several months_ without anything being staked because I didn't know it would do this. I get that important bugs will need to be fixed with actively maintained software, but not informing the users of it through the software is a major barrier to entry.

### Expected behavior

When an update is available the software should be capable of checking for it and notifying users of it. This shoudln't occur just on startup though because most people (like myself) have it staking in the background while doing other things, running for days or weeks at a time between restarts. It should at least have the option of doing a daily check for any update and notifying the user in the event of a mandatory update being available.

If it worked as expected I could recommend this to my less than technically minded friends, but with these issues I just know that within the first week they'll stop staking and never stake again.

### Actual behavior

The software never tells a user that staking is no longer active or why. It also never tells the user if any updates are available. It usually tells the user that it's synchronized when it's not though.

Additionally, now that I have updated, it's stuck on "scanning block 2685133". Which makes sense, since the only connections are 16 outgoing connections. No incoming data on 5.0.1. Getting up to date after it's been out of synch for a while is always a painful process that could be avoided if the user could always know when an update is available to not fall out of sync. I am really tired of having to download snapshots every few weeks. That should not be the normal procedure across every release, but it is, and it really needs to be fixed

**Comment by Elliander** [comment]
To add to the above, there was a very serious problem that resulted from the way things currently work: My client forked before updating!

I had 22 more PIVX through staking before I updated than after I update. It turns out that in 4.3 it continued to stake after the first mandatory update was released, just on a new fork it seems, and the reason why I couldn't synchronize without downloading a snapshot is because of this fact.

In other words, I can't even trust that when the client says it's staking it really is staking anymore! Because the last true stake I earned was on 1-11-21 whereas the last staking I saw before noticing the client was out of date was 1-21-21 with most of the stakes being on 1-18-21 for whatever reason. 

By not checking for updates and informing people that they are available it causes people who just want to run the client as a background process completely avoidable heachaches. Often I see threads on forums on how to get more people to use PIVX, well, this is it. Make it accessible to the average person by not making them fork every few weeks.

**Comment by Fuzzbawls** [comment]
The reason that the core wallet **DOESN'T** include such a feature is that it would either require an external network request (something that exposes PIVX nodes to 3rd party services), or an overly convoluted internal network version tracking system that could not be 100% guaranteed accurate.

Client versioning, and client version message values, are not strictly enforced on the network, and therefore cannot be used to determine if a new version is available or not. Likewise, protocol versioning, which IS strictly enforced, could span multiple client versions.

A much simpler "solution" to an end user being notified about a new version, would be to simply subscribe/watch to this github repo...**AND** to double check the pivx.org website/discord/twitter/telegram/FB/etc to verify (just in case the rare event that this repository is compromised)
