### ISSUE TITLE
[GUI][BUG] Wallet Crash al click to address

### ISSUE THREAD

**Issue by Kingston-kms** [PIVX-Project/PIVX#2160]
### Describe the issue
Wallet Crash

#### If so, please list the steps to reproduce below:
1. Select SEND dialog
2. Open dropdown with addresses
3. Click to btn Clear all
4. Select any addresses in dropdown list

**Comment by furszy** [comment]
thanks for reporting it, solved in #2161.

**Comment by furszy** [comment]
#2161 got merged, issue solved.
