### ISSUE TITLE
[Bug] PIVX Core wallet doesn't recognize default folder properly if non-english letters are being used for user name

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#2163]
If the user on Windows has their default user name set as for example `Norris Huć` (or any other non-english letter), when running the PIVX Core wallet for the first time, PIVX Core wallet will offer the following default data directory:
`C:\Users\Norris Huc\AppData\Roaming\PIVX`

Issue is that PIVX Core wallet will recognize the default folder incorrectly by dropping the non-english letter and replacing it with english letter (`ć` -> `c`). So, of course, there will be an issue and impossible to start the wallet by going further without manually changing the `c` to `ć`, because there is no folder nor user in Users called `Norris Huc`.

OS: Windows 10

**Comment by random-zebra** [comment]
related to https://github.com/PIVX-Project/PIVX/issues/940

**Comment by furszy** [comment]
Try #2449 and let us know how it goes.

**Comment by furszy** [comment]
Solved, closing.
