### ISSUE TITLE
Sub-title text in Staking Rewards section of Home screen needs clarification.

### ISSUE THREAD

**Issue by EricStanek** [PIVX-Project/PIVX#2199]
__Currently, the section has the following Title and Sub-Title:__

Staking Rewards
Amount of PIV and zPIV staked.

__Issue:__

Some users are incorrectly interpreting the sub-title to mean this section shows how many coins are being staked, as opposed to the rewards that they have earned while staking. This seems to happen only when they have not yet received any rewards at all. As soon as a bar chart is displayed, the intent becomes obvious. We also have the issue of the sub-title stating 'zPIV' which is obsolete. I understand that it is being left there as a placeholder until we have private staking again, but perhaps the following suggested sub-title works for resolving this current issue and the future.

__Title and suggestion for Sub-Title:__

Staking Rewards
Amount of rewards received.

**Comment by furszy** [comment]
Closed on #2200
