### ISSUE TITLE
Need bitcoin-config.h to create my own currency.

### ISSUE THREAD

**Issue by kuldeepsinghsaini108** [PIVX-Project/PIVX#221]
I am building my own currency. I need bitcoin-config.h. It is in gitignore file. I am not able to find out its copy by forking your git.

Please help me out.

Thanks

**Comment by Fuzzbawls** [comment]
the filename is `pivx-config.h` and it is generated by the build system automatically

**Comment by kuldeepsinghsaini108** [comment]
I want to create my own coin  by forking your Pivx. Can I get its copy? How and where I can config name and other setting for my own coin?

**Comment by jonspock** [comment]
We are busy developing and don't have time to help beginners clone our coin. Try google.

**Comment by EricStanek** [comment]
Not to be mean or anything, but your questions are so incredibly basic, there is no way you will be able to make the code changes you are suggesting. You need to start with a very simple project.
