### ISSUE TITLE
FAQ cleanup : Remove SwiftX reference and FreshDesk support link.

### ISSUE THREAD

**Issue by EricStanek** [PIVX-Project/PIVX#2217]
The wallet FAQ needs updates in Questions 4 and 5.

In Q4: "Where should I go if I need support?" we should not reference FreshDesk. It is FULL of obsolete guides and is not maintained at all. I suggest the answer simply be; "We have support in most of our official social channels, but the most popular is our Discord. Invites are available at https://Discord.PIVX.org."

In Q5: "What is a Masternode?" we should remove the first bullet which states Masternodes provide 'Instant transactions (SwiftX).

**Comment by random-zebra** [comment]
Closed in #2219
