### ISSUE TITLE
[Feature Request] Set custom transaction fee to highest possible when input is too high

### ISSUE THREAD

**Issue by dnchk** [PIVX-Project/PIVX#2234]
Feature request to automatically set the highest possible Custom Fee when user typed fee is higher than allowed. Related to https://github.com/PIVX-Project/PIVX/issues/1836

1. Open custom fee dialog.
2. Try to set >=1 to custom fee.

**Expected behavior**
Information message appears, typed value is changed to 0.9999.

**Actual behavior**
Information message appears, typed value is unchanged.

**Screenshot**
![1](https://user-images.githubusercontent.com/22178604/110342942-a3d17500-8034-11eb-86ed-0e93b427273b.png)

**Comment by random-zebra** [comment]
Closed in #2237
