### ISSUE TITLE
[Feature Request][GUI] Icon for a received transaction to be colored differently if there is an encrypted memo in it

### ISSUE THREAD

**Issue by ambassador000** [PIVX-Project/PIVX#2242]
Self-explanatory title. Make clear visual difference between transactions that have encrypted memo attached and those that don't.

Additional feature: In HOME tab in Transactions filter, add another sortable option -> Encrypted Memo.

**Comment by furszy** [comment]
Will need new vectorized icons that defines a transaction record with a memo (possibly a letter or a mail) to be used as a badge at the right bottom corner (code wise, on top of the view) of the current tx record row icon.
If we get a good set of icons following the wallet design for both themes (12x12 and 16x16). i can implement it quite fast.

tip for the icon builder: check the dashboard txes row current icons in `qt/pivx/res/img/ic-transaction-xxx` to see how they were built and what is specifically needed.

**Comment by panleone** [comment]
Solved by #2865
