### ISSUE TITLE
High resolution with % scaling of text,etc

### ISSUE THREAD

**Issue by pivxslimjim** [PIVX-Project/PIVX#228]
### Describe the issue
Support ticket 54

When on a high resolution, raising the scale of windows stuff makes the text tiny and difficult to work with

### What version of PIVX Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.
Official 2.2.1 Windows64

**Comment by Fuzzbawls** [comment]
should be fixed in #233

please comment again if it isn't.
