### ISSUE TITLE
direct hyperlink for my address

### ISSUE THREAD

**Issue by gvian** [PIVX-Project/PIVX#2287]
for example, [my bitcoin address](https://btc.com/3K7Ba2DFyyuGTukNqXEmogG4VgYp2RWnZV)

for my pivx, how?

**Comment by JSKitty** [comment]
That URL is simply an explorer service for Bitcoin, PIVX has many of these, just be aware these are 3rd-parties and thus you have to apply a level of trust into the data displayed (in the case of: them being forked, or them purposefully manipulating data).

An example:
[Random PIVX address](https://chainz.cryptoid.info/pivx/address.dws?DDooQKsYnQzGdM926BBspmjLGADWadcjbd.htm)
[Another explorer, same address!](https://explorer.pivx.link/address/DDooQKsYnQzGdM926BBspmjLGADWadcjbd)

I would recommend closing this issue now, as this isn't an actual issue and it also doesn't relate to PIVX Core.

**Comment by random-zebra** [comment]
Yup. Closing.
