### ISSUE TITLE
Getting error while installation new wallet

### ISSUE THREAD

**Issue by kavya14032019** [PIVX-Project/PIVX#2316]
This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Discord](https://discord.pivx.org).

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of PIVX Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by kavya14032019** [comment]
![Capture pivx](https://user-images.githubusercontent.com/82597338/114888741-236a1500-9e27-11eb-8fd4-2084017bcba0.JPG)

**Comment by furszy** [comment]
Please read the release-notes, section "How to Upgrade".
https://github.com/PIVX-Project/PIVX/releases/tag/v5.0.0

**Comment by kavya14032019** [comment]
![pivx error](https://user-images.githubusercontent.com/82597338/114900482-86f94000-9e31-11eb-88d2-0162e3724bec.jpg)

**Comment by furszy** [comment]
Please share the `debug.log` last 250 lines.

**Comment by kavya14032019** [comment]
not understand what you want exactly
![pivx error](https://user-images.githubusercontent.com/82597338/114902569-937e9800-9e33-11eb-9d26-2ad1b0ff8432.jpg)

**Comment by sieb** [comment]
kavya14032019 create a folder named ".pivx-params" in your home folder;
Copy and paste the two files ( sampling-output.params and sampling-spend.params );
Run pivx-qt (pivx-5.0.1).
Thats it!

**Comment by random-zebra** [comment]
> support requests are best directed to the [PIVX Discord](https://discord.pivx.org)

**Comment by EricStanek** [comment]
The initial error message references sapling-fetch-params and fetch-params.sh, but doesn't mention /params/install-params.sh for Linux users, which seems to be the source of this confusion. I empathize with the user, because it trips me up too.
