### ISSUE TITLE
Does the repo have to be a Dash fork?

### ISSUE THREAD

**Issue by givanse** [PIVX-Project/PIVX#237]
The issue I see is that the repo is not searchable through the Github UI because it is a fork. This problematic when:
 - trying to search the code for the source of error messages
 - trying to find out more about CLI commands and options

Wouldn't make sense to detach the fork and make it a project of its own now?

> To detach the fork and turn it into a standalone repository on GitHub, contact GitHub Support. If the fork has forks of its own, let support know if the forks should move with your repository into a new network or remain in the current network. For more information, see "About forks."
> https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork

**Comment by jonspock** [comment]
You can search through Github UI by using "fork:true"

**Comment by givanse** [comment]
`fork:true` is used to find repos only

> You will not be able to search the code in a fork that has less stars than its parent.
> https://help.github.com/articles/searching-in-forks/

**Comment by jonspock** [comment]
I don't have a problem with detaching the fork, but I don't think it's really an issue as there are other ways to search through the code

**Comment by givanse** [comment]
The only other way I know is to get a clone of the repo and grep/ack through it. I think that being able to search the repo directly in Github reduces the friction for new comers.

Very subjectively speaking, I'm lazy and I don't want to clone the two or three things that I've been playing with for the last couple of days; and, that I might not touch again in a while.

**Comment by givanse** [comment]
I do understand that there might be other reasons for keeping it attached as a fork.
