### ISSUE TITLE
WSL2 Cross Compile for Windows not possible

### ISSUE THREAD

**Issue by swtrse** [PIVX-Project/PIVX#2415]
### Describe the issue
Cross Compile Build on WSL2 for Windows fails.

### Can you reliably reproduce the issue?
Every time I build.

#### If so, please list the steps to reproduce below:
1. I use this script located in the project root folder
```
#!/bin/bash
PATH_SAVE=$(echo  "$PATH") # save original Path
PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g') # strip out problematic Windows %PATH% imported var
sudo bash -c "echo 0 > /proc/sys/fs/binfmt_misc/status" # Disable WSL support for Win32 applications.
cd depends
make HOST=x86_64-w64-mingw32
cd ..
./autogen.sh # not required when building from tarball
CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/ --disable-online-rust --with-incompatible-bdb
make
sudo bash -c "echo 1 > /proc/sys/fs/binfmt_misc/status" # Enable WSL support for Win32 applications.
PATH=$(echo  "$PATH_SAVE") # restore original Path
```
2. Output is in
[log.txt](https://github.com/PIVX-Project/PIVX/files/6630130/log.txt)

### Expected behavior
Build should finish without failure.

### Actual behavior
build stops with error

### What version of PIVX Core are you using?
Current sources from github

### Machine specs:
- OS: WSL  Ubuntu TLS 20.04 (Windows 10 x64)
- CPU: AMD
- RAM: 64 GB
- Disk size: 2 TB
- Disk Type (HD/SDD): SSD

**Comment by Hser2bio** [comment]
hi there swtrse 

try the following: (in coin folder..)

sudo make clean && sudo ./autogen.sh  && sudo ./configure --disable-online-rust --prefix=`pwd`/depends/x86_64-w64-mingw32 && sudo make -j15 

cheers

**Comment by cryptonana** [comment]
> 
> 
> hi there swtrse
> 
> try the following: (in coin folder..)
> 
> `sudo make clean && sudo ./autogen.sh && sudo ./configure --disable-online-rust --prefix=`pwd`/depends/x86_64-w64-mingw32 && sudo make -j15`
> 
> cheers

configure: error: expected an absolute directory name for --prefix: pwd/depends/x86_64-w64-mingw32

This error show and one more thing when run this command 

cd depends
make HOST=x86_64-w64-mingw32

i see this error

![Untitled-3](https://user-images.githubusercontent.com/40866572/121768962-738cfb80-cb7a-11eb-8ecb-2c7b5707f52d.png)

**Comment by furszy** [comment]
Just answered the screenshot in https://github.com/PIVX-Project/PIVX/issues/2416#issuecomment-860059137. 
Please try to not make the same comment twice.

**Comment by swtrse** [comment]
After playing around some time. It all started to work. I can not tell what is different now but after the x-th time running make clean, autogen and configure it started to work. I already tested the build client on my windows machine.

Thanks for the help.
