### ISSUE TITLE
make HOST=x86_64-w64-mingw32 error show

### ISSUE THREAD

**Issue by cryptonana** [PIVX-Project/PIVX#2416]
when i run this command
cd depends
make HOST=x86_64-w64-mingw32

i see this error

![Untitled-3](https://user-images.githubusercontent.com/40866572/121770343-36c50280-cb82-11eb-888b-f652f4558efa.png)

what i do now

**Comment by furszy** [comment]
You aren't running master, was solved two months ago in #2384.
