### ISSUE TITLE
Error when compiling on macOS Big Sur

### ISSUE THREAD

**Issue by swtrse** [PIVX-Project/PIVX#2424]
#### If so, please list the steps to reproduce below:
1.  Clone pivx repository
2. install homebrew with arm64 architecture (/opt/homebrew)
3. brew install -s autoconf automake berkeley-db4 libtool boost miniupnpc pkg-config python3 qt5 zmq libevent qrencode gmp libsodium rust
I used -s just to be sure. I had problems with gmp when not doing it.

4. Update .zshrc so that it cointains
```
if [ "$(arch)" = "arm64" ]; then
  eval $(/opt/homebrew/bin/brew shellenv);
  export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH"
  export LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib -L/opt/homebrew/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/openssl@1.1/include -I/opt/homebrew/include"
  export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@1.1/lib/pkgconfig"
else
  eval $(/usr/local/bin/brew shellenv);
  export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
fi
```
I had to add -L/opt/homebrew/lib and -I/opt/homebrew/include in addition to the build description for mac so that configure runs without an error. Otherwise ./configure would not find gmp.h
brew is installed for arm64 and x86_64. depending if running with rosetta the right version will be used...
5. Restart terminal
6. go to pivx folder
7. Run "git checkout 5.1"
8. Run "git pull"
9. Run "./autogen.sh"
10. Run "./configure --with-qrencode --with-zmq --with-gui"

### Expected behavior
Run ./configure without error

### Actual behavior
Got Error
```
checking whether to build PIVX Core GUI... yes (Qt5)
checking for boostlib >= 1.57.0... yes
checking whether the Boost::System library is available... yes
configure: error: Could not find a version of the boost_system library!
```

I suspect there is some mismatch with paths regarding arm64 libraries.
If for some tests I install the homebrew packages for x86_64 in an terminal running rosetta.
./configure will run fine in both terminals
however after installing the packages and try to build for arm64 there is a build error (most likely with the boost libraries) stating that there is no library for arm64 present.

**Comment by swtrse** [comment]
I could go past the ./configure error when running
"./configure --with-qrencode --with-zmq --with-gui --with-boost-libdir=/opt/homebrew/lib"
however it is strange that boostlib and Boost:System was found even without this option and only the next step fails.

However even with that option the build error running make remains

```
  AR       libsapling.a
RUSTC="/opt/homebrew/bin/rustc" TERM=dumb /opt/homebrew/bin/cargo build --release   --manifest-path ../Cargo.toml
    Finished release [optimized] target(s) in 0.07s
  CXXLD    pivxd
Undefined symbols for architecture arm64:
  "_getauxval", referenced from:
      crc32c::Extend(unsigned int, unsigned char const*, unsigned long) in libcrc32c.a(libcrc32c_a-crc32c.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [pivxd] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

```

**Comment by swtrse** [comment]
I looked in the build error and found this in the bitcoin repository 
https://github.com/bitcoin/bitcoin/issues/20371
however after adding these lines seems to do nothing for pivx

**Comment by Fuzzbawls** [comment]
I don't think any of us have M1 based macs to do any native testing for this, but I have at least backported the `crc32c` subtree update in #2426, which should fix the `_getauxval` issue. Still plenty more to do though before M1 chips would be considered "supported"

**Comment by swtrse** [comment]
I added your changes to my fork and building finished without a flaw.
make check however have many test disabled and stops with an error
```
test/librust/sapling_key_tests.cpp:17: Test suite "sapling_key_tests" is skipped because disabled
test/librust/pedersen_hash_tests.cpp:15: Test suite "pedersen_hash_tests" is skipped because disabled
test/librust/noteencryption_tests.cpp:22: Test suite "noteencryption_tests" is skipped because disabled
test/librust/sapling_note_tests.cpp:20: Test suite "sapling_note_tests" is skipped because disabled
test/librust/sapling_keystore_tests.cpp:20: Test suite "sapling_keystore_tests" is skipped because disabled
test/librust/zip32_tests.cpp:13: Test suite "zip32_tests" is skipped because disabled
test/librust/wallet_zkeys_tests.cpp:23: Entering test suite "wallet_zkeys_tests"
test/librust/wallet_zkeys_tests.cpp:32: Entering test case "StoreAndLoadSaplingZkeys"
unknown location:0: fatal error: in "wallet_zkeys_tests/StoreAndLoadSaplingZkeys": std::runtime_error: Sapling params don't exist
test/test_pivx.cpp:105: last checkpoint
test/librust/wallet_zkeys_tests.cpp:32: Leaving test case "StoreAndLoadSaplingZkeys"; testing time: 16511us
test/librust/wallet_zkeys_tests.cpp:135: Entering test case "WriteCryptedSaplingZkeyDirectToDb"
make[3]: *** [test/librust/wallet_zkeys_tests.cpp.test] Error 1
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
```

make deploy
does generate an dmg package. However I can not start the application. It is giving me a signature error.
I thought building directly on Mac does prevent this?

Any advices for this problems too?
Thanks

**Comment by Fuzzbawls** [comment]
You should be able to run `src/qt/pivx-qt` from the terminal after compiling.

Apple has become increasingly more restrictive in requiring code signatures for app bundles and the methods for circumventing those restrictions have changed with pretty much every new OS version since Mojave. Double check the 'Security & Privacy' section of System Preferences to see if the PIVX-Qt.app is needing manual user authorization to run or not (that was needed on first run for Catalina at least)
