### ISSUE TITLE
master node with onion address no longer works (with or without controller)

### ISSUE THREAD

**Issue by eval9** [PIVX-Project/PIVX#2454]
This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Discord](https://discord.pivx.org).

### Describe the issue

unable to setup master node with onion address and use it with (or without) UIX controller

#### If so, please list the steps to reproduce below:

1. created tor enabled PIVX node , obtained node onion address proceeded to activate in step 2 

2. UIX master controller throws invalid IP address when input is of format foo.onion (foo is onion address of a masternode)

3. on the node itself in the log following message is thrown 

2021-06-25 17:21:12 ManageStatus - Checking inbound connection for masternode to 'foo.onion:51472'
2021-06-25 17:21:12 ConnectNode: cannot connect to local node
2021-06-25 17:21:12 ManageStatus - not capable: Masternode address:port connection availability test failed, could not open a connection to the public masternode address (foo.onion:51472)

4. trying to do local mn activation fails also with the following message 

pivx1 startmasternode local false

Not capable masternode: Masternode address:port connection availability test failed, could not open a connection to the public masternode address (foo.onion:51472)

Not capable masternode: Masternode address:port connection availability test failed, could not open a connection to the public masternode address (foo.onion:51472)

### Expected behavior

PIVX software including controller should recognize and activate valid onion address for master node

### Actual behavior

software is unable to recognize onion address in master node activation process

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of PIVX Core are you using?
v5.2.0rc1 (binaries) , note that prior versions (cant recall which precise could have been 4.1.x) was able to recognize and activate master node onion addresses  (both core and UIX)

### Machine specs:
- OS: unix

**Comment by furszy** [comment]
The `Not capable masternode: address:port connection availability test failed, could not open a connection to the public masternode address` logging is merely a warning, could be related to different causes. it's not blocking the MN startup.

You most likely have a setup issue there. Using the GUI, i just have setup and enabled, on top of v5.2, a masternode in testnet over Tor.

Some advices:
1) Do not use an all-in-one Masternode-Controller node (It's not supported in v5.2 nor v5.1). Divide the controller and the Masternode in different instances.
2) Verify the masternode data, need to be the same in the masternode and the controller.
3) Use the RPC command `getmasternodestatus` to verify that your Masternode received the mnb start message after the broadcast (you will see a "Masternode successfully started" if it was started correctly).
4) If you are still having issues, probably you have stale data there, and you have two options: (1) remove the `mncache.dat` (from the Masternode side) and send another start message from the controller, or (2) self-compile v5.2 and include #2402, then re-broadcast the start message and reset the nodes.

Side from that, if you are still unlucky, come to our discord server, there are cool people there that will surely support you on the setup process.

**Comment by eval9** [comment]
> Some advices:
> 
> 1. Do not use an all-in-one Masternode-Controller node (It's not supported in v5.2 nor v5.1). Divide the controller and the Masternode in different instances.

Ans: it is not all in one setup: controller with coins (collateral) is on one machine , master node on another (different IP different wallet.dat)

> 2. Verify the masternode data, need to be the same in the masternode and the controller.

Ans: dont follow this, what data has to be common under .pivx on these two machines ?

> 3. Use the RPC command `getmasternodestatus` to verify that your Masternode received the mnb start message after the broadcast (you will see a "Masternode successfully started" if it was started correctly).

Ans: never got to this point 

on the machine (not the controller) seeing "ERROR: ProcessBlock: Active Masternode not initialized." (and the message prior: "The Not capable masternode: address:port connection availability test failed, could not open a connection....")

then using GUI , under "Create Master Controller" tab and "Enter IP Address" as soon as I put IP: foo.onion and enter I get "Invalid IP" 

> 4. If you are still having issues, probably you have stale data there, and you have two options: (1) remove the `mncache.dat` (from the Masternode side) and send another start message from the controller, or (2) self-compile v5.2 and include [Fix MN activation when the node received the mnb before initialize the MN. #2402](https://github.com/PIVX-Project/PIVX/pull/2402), then re-broadcast the start message and reset the nodes.

appreciate this! 

looks like UIX does not validate foo.onion in the IP field , but you have mentioned you activated a master node with such address format (onion format for tor network), UIX returns fast with "Invalid IP" as if format is invalid or something (using standard tor v2 format , similar to this

x3f4prt23499avrn.onion 

port is standard 51472

**Comment by eval9** [comment]
I think it could be all on me, machine on which controller runs has to have this I think (in the pivx.conf) : proxy=127.0.0.1:9050

according to this documentation

https://github.com/PIVX-Project/PIVX/blob/master/doc/tor.md

its what probably make onion IP address invalid during activation (from the controller)

(masternode on the second machine has these in the pivx.conf)

proxy=127.0.0.1:9050
onion=127.0.0.1:9150
torcontrol=127.0.0.1:9051
externalip=foo.onion
masternodeaddr=foo.onion:51472

so just the controller, hopefully we can close this as a non issue (but its good to know that a defect in regards to some aspect of activation is in master)

**Comment by eval9** [comment]
working as designed
