### ISSUE TITLE
I can't build pivx-qt on MacOS Big Sur

### ISSUE THREAD

**Issue by Alonewolf-123** [PIVX-Project/PIVX#2456]
In file included from /usr/local/Cellar/qt@5/5.15.2/lib/QtWidgets.framework/Headers/QMainWindow:1:
In file included from /usr/local/Cellar/qt@5/5.15.2/lib/QtWidgets.framework/Headers/qmainwindow.h:43:
In file included from /usr/local/include/QtWidgets/qtwidgetsglobal.h:43:
In file included from /usr/local/include/QtGui/qtguiglobal.h:43:
/usr/local/include/QtCore/qglobal.h:387:11: warning: inline variables are a C++17 extension [-Wc++17-extensions]
constexpr inline Deprecated_t Deprecated = {};
          ^
/usr/local/include/QtCore/qglobal.h:675:26: error: no template named 'enable_if_t' in namespace 'std'; did you mean 'enable_if'?
         typename = std::enable_if_t<std::is_arithmetic_v<T> && std::is_arithmetic_v<U> &&
                    ~~~~~^~~~~~~~~~~
                         enable_if
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:538:63: note: 'enable_if' declared here
template <bool, class _Tp = void> struct _LIBCPP_TEMPLATE_VIS enable_if {};

### Machine specs:
- OS: macOS Big Sur
- CPU: Intel Core i 5
- RAM: 8GB
- Disk size: 500GB
- Disk Type (HD/SDD): SDD

**Comment by Fuzzbawls** [comment]
How are you trying to compile the wallet? following the steps in [doc/build-osx.md](https://github.com/PIVX-Project/PIVX/blob/master/doc/build-osx.md) on a fresh macOS Big Sur (Intel CPU) VM compiled and launched without any issues other than some deprecation warnings.

**Comment by Alonewolf-123** [comment]
I did that. But above errors.

In file included from /usr/local/include/QtGui/qtguiglobal.h:43:
/usr/local/include/QtCore/qglobal.h:675:87: error: expected '>'
         typename = std::enable_if_t<std::is_arithmetic_v<T> && std::is_arithmetic_v<U> &&
                                                                                      ^
/usr/local/include/QtCore/qglobal.h:675:37: note: to match this '<'
         typename = std::enable_if_t<std::is_arithmetic_v<T> && std::is_arithmetic_v<U> &&
                                    ^
/usr/local/include/QtCore/qglobal.h:675:65: error: expected ',' or '>' in template-parameter-list
         typename = std::enable_if_t<std::is_arithmetic_v<T> && std::is_arithmetic_v<U> &&
                                                                ^
/usr/local/include/QtCore/qglobal.h:676:66: error: expected unqualified-id
                                     std::is_floating_point_v<T> == std::is_floating_point_v<U> &&
                                                                 ^
/usr/local/include/QtCore/qglobal.h:687:35: error: no type named 'Promoted' in namespace 'QTypeTraits::detail'
using Promoted = typename detail::Promoted<T, U>::type;
                 ~~~~~~~~~~~~~~~~~^~~~~~~~
/usr/local/include/QtCore/qglobal.h:687:43: error: expected ';' after alias declaration
using Promoted = typename detail::Promoted<T, U>::type;
                                          ^
                                          ;
/usr/local/include/QtCore/qglobal.h:699:31: error: no template named 'Promoted' in namespace 'QTypeTraits'
constexpr inline QTypeTraits::Promoted<T, U> qMin(const T &a, const U &b)
                 ~~~~~~~~~~~~~^
/usr/local/include/QtCore/qglobal.h:701:28: error: no template named 'Promoted' in namespace 'QTypeTraits'
    using P = QTypeTraits::Promoted<T, U>;
              ~~~~~~~~~~~~~^
/usr/local/include/QtCore/qglobal.h:702:5: error: unknown type name 'P'
    P _a = a;
    ^
/usr/local/include/QtCore/qglobal.h:703:5: error: unknown type name 'P'
    P _b = b;
    ^
/usr/local/include/QtCore/qglobal.h:707:31: error: no template named 'Promoted' in namespace 'QTypeTraits'
constexpr inline QTypeTraits::Promoted<T, U> qMax(const T &a, const U &b)

**Comment by Fuzzbawls** [comment]
try uninstalling and re-installing qt, or even completely removing and re-installing homebrew and all dependencies. Your problems seem to be due to an environment issue and not anything related to the pivx-core codebase itself.

**Comment by Alonewolf-123** [comment]
I think this issue is c++ version.
Mac SDK c++ version is 14.

**Comment by Alonewolf-123** [comment]
I tried to re-install qt and homebrew. But same issue.

**Comment by Fuzzbawls** [comment]
The PIVX Core repo already uses (and requires) c++14 standard, so that isn't the issue.

You could also try building via the [depends](https://github.com/PIVX-Project/PIVX/blob/master/depends/README.md) system, which builds all dependencies in it's own environment separate from the system environment.

**Comment by Alonewolf-123** [comment]
How can I build it by depends?

**Comment by Fuzzbawls** [comment]
The readme i linked above includes instructions

**Comment by Alonewolf-123** [comment]
I followed it already.

**Comment by Fuzzbawls** [comment]
https://github.com/PIVX-Project/PIVX/blob/master/depends/README.md

^^ that readme. building the depends system typically takes, on average, at least 30 minutes to an hour on it's own.

**Comment by Alonewolf-123** [comment]
I got this error when I run "make" in the "depends" folder.

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -x c++ -O3 -std=c++11 -O3 -s -DNDEBUG builtins.cpp class.cpp command.cpp compile.cpp constants.cpp cwd.cpp debug.cpp debugger.cpp execcmd.cpp filesys.cpp frames.cpp function.cpp glob.cpp hash.cpp hcache.cpp hdrmacro.cpp headers.cpp jam.cpp jambase.cpp jamgram.cpp lists.cpp make.cpp make1.cpp md5.cpp mem.cpp modules.cpp native.cpp object.cpp option.cpp output.cpp parse.cpp pathsys.cpp regexp.cpp rules.cpp scan.cpp search.cpp strings.cpp subst.cpp sysinfo.cpp timestamp.cpp variable.cpp w32_getreg.cpp modules/order.cpp modules/path.cpp modules/property-set.cpp modules/regex.cpp modules/sequence.cpp modules/set.cpp execunix.cpp fileunix.cpp pathunix.cpp -o b2
In file included from builtins.cpp:7:
./jam.h:336:10: fatal error: 'sys/types.h' file not found
#include <sys/types.h>
         ^~~~~~~~~~~~~
1 error generated.
In file included from class.cpp:15:
In file included from ./rules.h:35:
./timestamp.h:21:10: fatal error: 'time.h' file not found
#include <time.h>
         ^~~~~~~~
1 error generated.
In file included from command.cpp:17:
./jam.h:336:10: fatal error: 'sys/types.h' file not found
#include <sys/types.h>
         ^~~~~~~~~~~~~
1 error generated.
In file included from compile.cpp:23:
./jam.h:336:10: fatal error: 'sys/types.h' file not found
#include <sys/types.h>
         ^~~~~~~~~~~~~
1 error generated.
In file included from cwd.cpp:11:
./jam.h:336:10: fatal error: 'sys/types.h' file not found
#include <sys/types.h>
         ^~~~~~~~~~~~~
1 error generated.
In file included from debug.cpp:8:
./jam.h:336:10: fatal error: 'sys/types.h' file not found

**Comment by furszy** [comment]
Give a look to #2465, pushed the fixes for depends building on macOS Big Sur and Catalina there. System libs deployment works fine here, only had issues using depends.

**Comment by Alonewolf-123** [comment]
Thank you so much! Fixed perfectly!
