### ISSUE TITLE
Masternode will not activate after update to 5.2.0

### ISSUE THREAD

**Issue by krilson** [PIVX-Project/PIVX#2458]
This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Discord](https://discord.pivx.org).

### Describe the issue
Masternode worked normally for the last 4 months.

Update to 5.2.0 was preformed in the following way:
1. pivx-cli stop
2. replace pivxd and pivx-cli binary with version 5.2.0
3. pivxd

After update to 5.2.0 masternode will not come online. 
pivx-cli getmasternodestatus
error: {"code":-1,"message":"Active Masternode not initialized."}

Errors in .pivx/debug.log:
ERROR: ProcessBlock: Active Masternode not initialized.
and
ManageStatus - Checking inbound connection for masternode to 'IPADDRESS:51472'
ConnectNode: cannot connect to local node
ManageStatus - not capable: Masternode address:port connection availability test failed, could not open a connection to the public masternode address (IPADDRESS:51472)

Connection from masternode tested with nmap and telnet to port 51472. Both work without a problem from the same user that is running pivxd. Connection also works from outside (other public addresses as well as from the controller wallet). Connection should not be an issue?

Attempted to delete mncache.dat and issue another "pivx-cli startmasternode alias lockwallet mn1" from the controller wallet - with successful result returned:
{
  "alias": "mn1",
  "result": "success",
  "error": ""
}

It did not solve this issue.

#### If so, please list the steps to reproduce below:
No.

### Expected behavior
Usually masternodes keep working after an update. Usually without the need of reactivation.

### Actual behavior
Masternode does not come online. It is "activating?" forever. No other useful information on what is the problem.

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of PIVX Core are you using?
5.2.0 release - pivx-5.2.0-x86_64-linux-gnu.tar.gz

### Machine specs:
- OS: Ubuntu 18.04 LTS
- CPU: 2
- RAM: 8GB
- Disk size: 200GB
- Disk Type (HD/SDD): HDD

### Any extra information that might be useful in the debugging process.
Masternode worked fine for the last 4 months. I have other masternodes (not pivx, other coins) that run without issues on this same server. No other masternode is having issues with connection or anything else.

**Comment by NoobieDev12** [comment]
Check the release notes:
https://github.com/PIVX-Project/PIVX/releases/tag/v5.2.0

Quoting:
> Masternodes will need to be restarted once both the masternode daemon and the controller wallet have been upgraded.

**Comment by krilson** [comment]
> Check the release notes:
> https://github.com/PIVX-Project/PIVX/releases/tag/v5.2.0
> 
> Quoting:
> 
> > Masternodes will need to be restarted once both the masternode daemon and the controller wallet have been upgraded.

Restarted meaning to re-do "startmasternode"? If this is the case than that did not solve it. Still getting "ERROR: ProcessBlock: Active Masternode not initialized."

I also tried "pivx-cli initmasternode" and it also makes no difference.

What would be the next step here? Resync? Transfer collateral and make new masternode?

**Comment by furszy** [comment]
have you updated to v5.2 both sides or only the controller wallet?

**Comment by krilson** [comment]
> have you updated to v5.2 both sides or only the controller wallet?

I updated both sides. I am resyncing the masternode side now. Its taking quite a long time.

**Comment by krilson** [comment]
I resynced both nodes (masternode and controller). I kept only wallet.dat and pivx.conf and masternode.conf

Masternode now activated ok :)

This issue can be closed.

**Comment by furszy** [comment]
Good, closing.
