### ISSUE TITLE
[Feature Request][GUI] Add Coin Control functionality to Masternode Creation Wizard

### ISSUE THREAD

**Issue by ambassador000** [PIVX-Project/PIVX#2498]
I've played around with this and currently if wallet is having a lot of small UTXOs, in most cases wallet will automatically try to create a Masternode by selecting a lot of these small UTXOs instead of the big one (let's say 20000 PIV UTXO). This results with the user being unable to create the new Masternode through the Masternode Creation Wizard GUI. Adding the Coin Control functionality would fix this issue to large extent, unless wallet can somehow automatically pick the bigger (biggest) available UTXOs for masternode creation.

Coin Control could be added here:
![check](https://user-images.githubusercontent.com/57232689/128646408-8a677ce9-fa84-4472-ae4c-0f1b2f0b5d04.JPG)

**Comment by panleone** [comment]
Solved by #2862
