### ISSUE TITLE
[Feature Request][GUI] Add search functionality to Cold Staking addresses list

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#2499]
Same as the search functionality in RECEIVE tab, it would be great to have the search functionality in COLD STAKING tab as well:

![check02](https://user-images.githubusercontent.com/57232689/128646594-dbfc0ea2-7b25-4df2-b961-6f014dbb7639.JPG)

![check01](https://user-images.githubusercontent.com/57232689/128646605-2202c434-7df6-442a-a1e5-f56daa148933.JPG)

**Comment by Gordis890** [comment]
I agrongly agree

**Comment by Gordis890** [comment]
> Same as the search functionality in RECEIVE tab, it would be great to have the search functionality in COLD STAKING tab as well:
> 
> ![check02](https://user-images.githubusercontent.com/57232689/128646594-dbfc0ea2-7b25-4df2-b961-6f014dbb7639.JPG)
> 
> ![check01](https://user-images.githubusercontent.com/57232689/128646605-2202c434-7df6-442a-a1e5-f56daa148933.JPG)

Agree
