### ISSUE TITLE
error message "Pivx core quit unexpectedly"

### ISSUE THREAD

**Issue by lollipopsunshine** [PIVX-Project/PIVX#2509]
### Describe the issue
After recently deleting pivx wallet then downloading pivx wallet, to un fork and re sync inline with the latest update. Once the sync was complete my wallet now quits after moments of opening. Error message 'pivx core quite unexpectedly'

#### If so, please list the steps to reproduce below:
1.no
2.
3.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of PIVX Core are you using?
List the version number/commit ID, V.5.2.0.1
### Machine specs:
- OS: Big Sur
- CPU: Apple M1
- RAM: 16G
- Disk size: 2T
- Disk Type (HD/SDD): SDD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by G-i-o** [comment]
It was never necessary to delete previous version to install newer ones. It might be that some files have been deleted but some not, having the newer client crashing on that conflict.

Could you please attach the log file? (Debug.log)

While waiting, I would make a copy of the blockchain (see[ here](https://forum.pivx.org/threads/how-to-create-your-own-blockchain-snapshot.715/)) and make sure you have your own safe copy of the "_wallet.dat_".

Then I would delete everything, making sure that absolutely all PIVX related files and folders are deleted. Then, re-read the last release notes, re-download the latest client and re-install.

See if it runs. If it does, exit (even if not synced to date) and copy the previously backed up blockchain over. See again if it runs. Finally, copy over your "_wallet.dat_"

If it doesn't run after having copied the blockchain, there are issues with that and you'll need to re-sync from scratch.

**Comment by lollipopsunshine** [comment]
hey Gio, Thank you for your reply. Is this information found in my wallet? Because it won't stay open long enough to do anything.

**Comment by lollipopsunshine** [comment]
[debug.log](https://github.com/PIVX-Project/PIVX/files/7024458/debug.log)

**Comment by G-i-o** [comment]
:arrow_up: Issue solved. User was assisted in wiping and re-installing the Core client.
