### ISSUE TITLE
Core v5.3.0 Sync Issues

### ISSUE THREAD

**Issue by G-i-o** [PIVX-Project/PIVX#2536]
Just updated from v5.2.0 to v5.3 on Linux.
The previous version was running fine. The blockchain was 1day behind as I don't keep it running 24/7.
When I updated to v5.3, it seems to load fine but it does not sync. It did advanced few blocks after rebooting but now is stuck to block 2995256 and even rebooting does not make it move.

It has 14 to 16 connections, all to 5.2.0 - 5.2.0.1 and 5.3.0 clients.

### Machine specs:
- OS: Linux Kernel 5.12
- CPU: Intel Core I7
- RAM: 16Gb
- Disk size: Plenty of free space
- Disk Type (HD/SDD): HD

**Comment by Fuzzbawls** [comment]
Try starting the node with `-maxtipage=1000`, ie
```bash
./pivxd -maxtipage=1000
```
or add a line to your `pivx.conf` file that reads
```
maxtipage=1000
```

**Comment by G-i-o** [comment]
Thanks a lot @Fuzzbawls . It did work.
