### ISSUE TITLE
failed in compiling

### ISSUE THREAD

**Issue by habibalejalil** [PIVX-Project/PIVX#2542]
Hello, I'm getting the bellow errors while I'm compiling the source code by following the https://github.com/PIVX-Project/PIVX/blob/master/doc/build-windows.md, how I can fix that?

> Makefile:12940: recipe for target 'pivxd-pivxd.o' failed
> make[2]: *** [pivxd-pivxd.o] Error 1
> make[2]: Leaving directory '/root/test/pivx/src'
> Makefile:15116: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/root/test/pivx/src'
> Makefile:770: recipe for target 'all-recursive' failed
> make: *** [all-recursive] Error 1

<img width="1359" alt="Screen Shot 2021-09-06 at 4 45 02 AM" src="https://user-images.githubusercontent.com/16974436/132149159-266093b5-0f19-4819-8b7d-536566381a28.png">

Ubuntu 18.04
PIVX latest version.

**Comment by habibalejalil** [comment]
Still not fixed!!!!!

**Comment by random-zebra** [comment]
> Still not fixed!!!!!

Given the few relevant log lines shown in the screenshot, I think this is a duplicate of #1019.
I.e. you need to set the default mingw32 g++ compiler option to posix (as documented also in the guide you linked):
```
sudo update-alternatives --config x86_64-w64-mingw32-g++
```

**Comment by habibalejalil** [comment]
> > Still not fixed!!!!!
> 
> Given the few relevant log lines shown in the screenshot, I think this is a duplicate of #1019.
> I.e. you need to set the default mingw32 g++ compiler option to posix (as documented also in the guide you linked):
> 
> ```
> sudo update-alternatives --config x86_64-w64-mingw32-g++
> ```

not work.

**Comment by furszy** [comment]
please come to the main PIVX discord, #support channel so someone there can help you in a more fluid way.
