### ISSUE TITLE
[GUI][Bug] Welcome screen GUI bug

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#2570]
(1) `Welcome to %1 wallet ` -> `Welcome to PIVX Wallet`
And maybe it would look better if it is in single line.

![bug in the welcome screen](https://user-images.githubusercontent.com/57232689/134736249-0cc47788-fc52-496f-8134-ad86441e11e1.JPG)

-------
(2) Shouldn't it tell users it will store **at least** 25GB of data? It's the current PIVX's blockchain size.
Also, `PIVX block chain` -> `PIVX blockchain` to be consistent with the next screen (2 - Welcome).

![PR](https://user-images.githubusercontent.com/57232689/134735988-34fa23ef-500d-4d33-a82f-dcb00408ae48.JPG)

**PIVX v5.3.1**
**OS: Windows 10 Pro**

**Comment by random-zebra** [comment]
Can confirm this on linux. 
Some additional info: the "welcome" tab (2) shows correctly with *default* language, but shows the issue if any language is selected in the "language" (1) tab. Further, going back from (2) to (1) and changing the language back to *default* does not fix the issue (title remains "welcome to % wallet").

**Comment by furszy** [comment]
The issue with the "Welcome to %1" it's because since #2491, the "PIVX Core" label is not translated anymore and no ts language file has it.. all of the translations files still have "Welcome to PIVX Core".
Seems that need admin access in transifex to push/pull the updates.
