### ISSUE TITLE
[Build] GA macOS CMake Builds failing

### ISSUE THREAD

**Issue by Fuzzbawls** [PIVX-Project/PIVX#2571]
A recent GA OS Image update for macOS 10.15 has introduced build errors in the CI job due to a stricter environment configuration, which is more in-line with the macOS 11 image's environment.

As such, our macOS CMake jobs will currently fail until the underlaying cause (improper detection of GMP header/library; fixed in https://github.com/PIVX-Project/bls-signatures/pull/9) is merged into the external library and the subtree is updated here.

A test GA run showing the fix result can be seen at https://github.com/Fuzzbawls/PIVX/runs/3707380747

**Comment by random-zebra** [comment]
#2572 is ready
