### ISSUE TITLE
[BUG/RPC] After fresh sync "getinfo" returns "transparentsupply" value of 0

### ISSUE THREAD

**Issue by kyeno** [PIVX-Project/PIVX#2573]
When you sync fresh (running `pivxd` in background), the `getinfo` CLI/RPC command will return `transparentsupply` value of 0.

```
$ pivx-cli getinfo
{
  "version": 5030100,
  "protocolversion": 70923,
  "services": "NETWORK/BLOOM/",
  "walletversion": 170000,
  "balance": 0.00000000,
  "staking status": "Staking Not Active",
  "blocks": 3037307,
  "timeoffset": 0,
  "connections": 20,
  "proxy": "",
  "difficulty": 11017.5688966531,
  "testnet": false,
  "moneysupply": 755635.04993567,
  "transparentsupply": 0.00000000,
  "shieldsupply": 755635.04993567,
  "keypoololdest": 1610750908,
  "keypoolsize": 100,
  "paytxfee": 0.00000000,
  "relayfee": 0.00010000,
  "errors": ""
}
```

This remains true no matter how long you wait after full resync (I waited 2 hours).
Only after killing and restarting the `pivxd`, `transparentsupply` will render a correct value.

```
# systemctl restart pivx
$ pivx-cli getinfo
{
  "version": 5030100,
  "protocolversion": 70923,
  "services": "NETWORK/BLOOM/",
  "walletversion": 170000,
  "balance": 0.00000000,
  "staking status": "Staking Not Active",
  "blocks": 3037313,
  "timeoffset": 0,
  "connections": 7,
  "proxy": "",
  "difficulty": 10758.39464547837,
  "testnet": false,
  "moneysupply": 67160981.73052198,
  "transparentsupply": 66405346.68058631,
  "shieldsupply": 755635.04993567,
  "keypoololdest": 1610750908,
  "keypoolsize": 100,
  "paytxfee": 0.00000000,
  "relayfee": 0.00010000,
  "errors": ""
}
```

**Comment by random-zebra** [comment]
The transparent supply (as returned by `getinfo`) is updated when the chainstate is flushed to disk (you can use `getsupplyinfo` to see at which height this happened). To force the update and recalculation of supply on demand use `getsupplyinfo true`.

**Comment by kyeno** [comment]
Thanks RZ!
Furszy told me something similar before, yet I didn't entirely grasp it. I guess I'll need to redo the stats fetching+calculation scripts for the web, or at least add some failsafes there.

**Comment by kyeno** [comment]
Maybe this thread actually could be moved to "feature request" then, where I'd suggest:

When the wallet figures out it has fully synced AND it's `transparentsupply` returns `0`, it performs on-demand (cache-less) recalculation itself automagically.

What you think?

**Comment by furszy** [comment]
> Furszy told me something similar before, yet I didn't entirely grasp it
Not sure what you did not understand it but feel free to ask, i told you exactly the same actually. The `getsupplyinfo` is really simple. It's a command with a boolean argument to force a flush or not, nothing else. Please read the command description.

As per the `getinfo` command description:
 >`getinfo` exists for backwards-compatibility only. It combines information from wildly different sources in the program, which is a mess, and is thus planned to be deprecated eventually. 
> Based on the source of the information, new information should be added to:
> - `getblockchaininfo`,
> - `getnetworkinfo` or
> - `getwalletinfo`
> 
>  Or alternatively, create a specific query method for the information.

We will end up deprecating `getinfo` in +v8 probably. Based on the current priorities, it has low to null priority.
Better if you start using `getsupplyinfo` command sooner rather than later.
