### ISSUE TITLE
[Bug][GUI] Masternode status is invisible if entered masternode name is too long

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#2602]
If Masternode 1 has too long name, status won't be visible both for Masternode 1 and Masternode 2.

![check67](https://user-images.githubusercontent.com/57232689/137530285-a78d30c5-4798-42cb-8607-b80091f81d83.JPG)

**Comment by furszy** [comment]
already restricted in #2406.
