### ISSUE TITLE
Cannot invalidateblock

### ISSUE THREAD

**Issue by njd5475** [PIVX-Project/PIVX#2605]
### Describe the issue

Whenever I try to run `pivx-cli invalidateblock <invalidblockhash>` I get the following error 

`pivxd: sapling/saplingscriptpubkeyman.cpp:308: void SaplingScriptPubKeyMan::DecrementNoteWitnesses(int): Assertion nWitnessCacheSize > 0' failed.`

#### If so, please list the steps to reproduce below:
1. Load pivxd with broken chain
2. Attempt to invalidate the first badblock `pivx-cli invalidateblock <firstbadblockhash>`

### Expected behavior
Best block should be thechain block before the invalidblock

### Actual behavior
Error pivxd crashes with following error
`pivxd: sapling/saplingscriptpubkeyman.cpp:308: void SaplingScriptPubKeyMan::DecrementNoteWitnesses(int): Assertion `nWitnessCacheSize > 0' failed.
`

### What version of PIVX Core are you using?
`PIVX Core Daemon version v5.3.2`

**Comment by furszy** [comment]
Thanks for creating an issue for this. It has been on my to do list for some time. #2539 is the first step heading into the solution direction.
This essentially happens when you invalidate a block that is +100 blocks deep on the chain. The Sapling witness cache needs to be recreated.

**Comment by walkjivefly** [comment]
Reproduces with 5.3.3 as well. Now I gotta resync from scratch :-(
