### ISSUE TITLE
[GUI] Wrong blockchain size number is displayed

### ISSUE THREAD

**Issue by ambassador000** [PIVX-Project/PIVX#2618]
Shouldn't it tell users that the Core wallet will store at least **25GB** of data instead of current 1GB?

Also, PIVX **block chain** -> PIVX **blockchain** to be consistent with the next screen (2 - Welcome).

![blockchain size](https://user-images.githubusercontent.com/57232689/139443377-d57e868c-9c8f-4ef0-9452-28f244976f45.jpg)

**Comment by Fuzzbawls** [comment]
#2621 fixes the displayed size issue on a per-network basis. I intentionally didn't do the `block chain` -> `blockchain` change though, as doing so would invalidate all existing translations of that string. would be better to do that **after** a major release so as to give translators time to submit new translations without a rush.
