### ISSUE TITLE
RPC Call 'getbalance' is partially broken

### ISSUE THREAD

**Issue by PIVX-Project** [PIVX-Project/PIVX#262]
When calling 'getbalance *' from the console the output is correct and as expected.

When calling 'getbalance (account name)' The output is broken

Also, would be good to add a way to obtain the balance of an address directly instead of using the account name.

**Comment by mkgin** [comment]
'getbalance' operates on accounts not addresses. This goes back to the deprecated bitcoin accounts system. Probably best that accounts are left as is.

Results from:
> getbalance "accountname"
appear normal to me.

Balance for an address can be calculated by summing unspent transactions to an address using 'listunspent'

> pivx-cli listunspent 6 9999999 "[\"ADDRESS_HERE\"]" |grep amount

**Comment by Fuzzbawls** [comment]
yeah the internal accounting system isn't something that we're intending to "fix" in this regard...at least not right now. Just have the issue here for posterity.

**Comment by rejectedpromise** [comment]
Still relevant?

**Comment by Fuzzbawls** [comment]
not really. the internal accounting mechanism is known to be inaccurate, depreciated, and even removed upstream.

if anything, this just serves as a reminder that relying on internal accounting shouldn't be done, and that the internal accounting system may be removed here as it has been upstream.

**Comment by Fuzzbawls** [comment]
going to close this for now. There is no intent to 'fix' the wallet's internal accounting system at this time. If such intent surfaces down the road then this can be reopened.
