### ISSUE TITLE
Can't peer with nodes

### ISSUE THREAD

**Issue by hardcore-sushi** [PIVX-Project/PIVX#2637]
### Describe the issue
pivx-qt can't connect to other nodes. I tried with pivxd to get more informations and it shows:
```
asking peer for sporks
timeOffset (75 seconds) too large. Disconnecting node <node ip>
```
for every nodes it tries to connect to. My machine is set to the correct time in the UTC timezone.

### Can you reliably reproduce the issue?
Yes, everytime I launche either pivx-qt or pivxd.

### What version of PIVX Core are you using?
PIVX 5.3.3 from GitHub releases.

### Machine specs:
- OS: Linux 5.14.0-2-amd64 Debian 5.14.9-2 (2021-10-03) x86_64 GNU/Linux
- Disk size: more than 100 GB available
- Disk Type (HD/SDD): SSD

**Comment by EricStanek** [comment]
Time setting needs to be accurate to within 15 secs I believe. So, the error message makes sense.

It is common for Windows OS to not be able to tell time accurately, but I have not seen this with a Linux OS. Is it possible you have the toggle for 'Network time' turned off and set to 'Manual' time?

**Comment by hardcore-sushi** [comment]
My NTP service was disabled, I was a few seconds behind. I enabled it and now it works fine.
Thanks!
