### ISSUE TITLE
When it will be possible to check the balance of any address via RPC getaddressbalance?

### ISSUE THREAD

**Issue by berkutx** [PIVX-Project/PIVX#2640]
Many coins(wallets) have a "-adrressindex=1" argument that can track "external" balances. See dash for details: https://dashcore.readme.io/docs/core-api-ref-remote-procedure-calls-address-index.
Also check the patch: https://github.com/bitcoin/bitcoin/pull/10370/files

At the moment I am using a third-party explorer, which is paid and has limits. 
**Are there any plans to add this feature?**

**Comment by furszy** [comment]
So far, no plans for it. For few reasons:

1) Same rationale as Bitcoin when they closed that PR (and every other attempt), check the last comment on the PR: https://github.com/bitcoin/bitcoin/pull/10370#issuecomment-323211049.

   Most of the attempts to add an addresses indexer were polluting the consensus, validation and mempool code which is not acceptable for a non-core functionality.

2) There are pretty simple external addresses indexer softwares that can be used like electrumx or blockbook. Both have support for our network.

Saying that, there might be a good way of implementing new indexes in the future. Only based on signals without polluting the consensus related code but would still need a good number of updates from upstream (starting with the tx index updates).
Best, and quickest, advice that can give you is to use one of the external softwares that were specifically built to provide this functionality, which are meant to be much more performant than any all-in-one PIVX-core indexer integration.
