### ISSUE TITLE
[Bug] Wallet crashes if Amount entered in the field starts with 0

### ISSUE THREAD

**Issue by ambassador000** [PIVX-Project/PIVX#2666]
Tried on testnet with compiled wallet version of master + PR 2659, 2662, 2664 and 2665.

OS: Ubuntu 20.04

While creating a proposal using the new Governance GUI, by entering `099` in the Amount field, wallet will accept it and proceed to the next step and recognize it as 99 PIV proposal, but then the wallet crashes and the following output appears in the terminal:

```
EXCEPTION: NSt8ios_base7failureB5cxx11E
String length limit exceeded: iostream error
pivx in Runaway exception

terminate called after throwing an instance of 'std::ios_base::failure[abi:cxx11]'
  what():  String length limit exceeded: iostream error
```
  

 After trying to restart the wallet, Runaway exception appears again and wallet cannot be started, while another output shows in the terminal:
 
```
EXCEPTION: 19QUnhandledException
std::exception
pivx in Runaway exception

pivx-qt: /usr/include/boost/signals2/detail/lwm_pthreads.hpp:60: void boost::signals2::mutex::lock(): Assertion `pthread_mutexlock(&m) == 0' failed.
```

**Comment by furszy** [comment]
Great, thanks for the report 👍 .

To recover the wallet, start it with the `-zapwallettxes=2` argument.

**Comment by furszy** [comment]
Done. @ambassador000, try this branch: https://github.com/furszy/PIVX/tree/2021_gui_fix_governance_entry

**Comment by ambassador000** [comment]
@furszy some feedback:

1) Box is not red when more than 19 characters are entered (for example, box is properly red when too many characters are entered in the URL field below):
![name1](https://user-images.githubusercontent.com/57232689/145318042-c6192e15-9643-4dda-98da-5321adf0f47e.JPG)

**EXTRA NOTE:** To keep things consistent, error should start with the capital letter: `invalid` -> `Invalid`, and comma (`,`) replaced with the colon (`:`)

------------------------

2) Proposal name box allows you to enter 20 characters in total, while it can only go to the next step if up to 19 characters are entered. Why not limit the user in the first place to be able to type up to 19 characters, so that the error never shows up? 

------------------------

3) Same as the proposal name, why not limit the amount of characters that user can enter in the URL field to 63, so that the `Invalid URL` error never shows up?
![limit1](https://user-images.githubusercontent.com/57232689/145318851-2beac25c-2a5a-4ccb-a054-8ade61ce7f4c.JPG)

**Comment by furszy** [comment]
you shouldn't be able to input more than 20 characters for the name and 64 for the URL. There is a size limit being set for it. Which is working properly in OSX. So.. need to check it in linux now.

**Comment by ambassador000** [comment]
It's working, explained in DM 👍 :
