### ISSUE TITLE
[Bug][GUI] Budget rewards not showing in staking graph

### ISSUE THREAD

**Issue by FlorentG74** [PIVX-Project/PIVX#2667]
#### If so, please list the steps to reproduce below:
1. Upgrade a wallet that received both staking rewards and budget rewards to PIVX Core Wallet to 5.4.RC1 version
2. Open the wallet and look at the staking graph

### Expected behavior
1. Staking rewards should display in the graph in dark purple
2. Masternode/Budget rewards should display in the graph in light purple

### Actual behavior
Only Staking rewards show in the graph. Budget rewards are not displayed

### Screenshots.
![Capture d’écran 2021-12-06 à 21 26 25](https://user-images.githubusercontent.com/84814284/144917693-2a550d58-e2cc-44a5-8b42-488ee5b2a93f.png)

### What version of PIVX Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

### Machine specs:
- OS: Debian
- CPU: ARM (Raspberry PI)
- RAM:2Go
- Disk Type (HD/SDD): SSD

**Comment by furszy** [comment]
Masternode rewards are not the same as budget proposals payments. Only stakes and Masternode rewards and being presented in the chart.

**Comment by FlorentG74** [comment]
Thanks @furszy for the prompt feedback - the amount i have on top (ending in 684), plus the scaling for the chart, relates to budget proposal payments (1421 PIV on the right hand side is the amount paid as part of the proposal I submitted), so I suspect there's still an inconsistency here (as the staking bars are very small due to that)

**Comment by furszy** [comment]
Ok great, thanks for the report, really appreciated 👌 .
Inconsistency found, it's due how the coinstake transaction is being parsed in the GUI side.

**Comment by FlorentG74** [comment]
Cool thanks Furszy
