### ISSUE TITLE
Boot failed with assertion failure for `GetSaplingAnchorAt`

### ISSUE THREAD

**Issue by omochi** [PIVX-Project/PIVX#2692]
### Describe the issue

I tried to boot `eXperiencePoints-Qt.exe` version 5.2.0.3.
And it failed with assertion failure dialog.

### Screenshots.

![スクリーンショット 2021-12-19 221146](https://user-images.githubusercontent.com/312792/146676114-33b77566-aba8-42be-846b-773385488c23.png)

I can boot the version 3.4.0.4.
I stacked with migration.

**Comment by furszy** [comment]
`eXperiencePoints-Qt.exe` is not PIVX. Ask on their repository.
