### ISSUE TITLE
Votes missing in DAO screen while proposal not established.

### ISSUE THREAD

**Issue by EricStanek** [PIVX-Project/PIVX#2708]
It has been less than 24 hrs since my proposal was submitted to the network. As such, it is not yet 'Established'. However, there are votes that have already been made. Both these points are shown in the screen shot below of the console output. The DAO screen shown below incorrectly shows there are no votes. I strongly suspect that this is simply because the proposal is not established yet.

**The new DAO screen should show the actual vote counts, even if the proposal is not yet established.** Otherwise, anyone who votes during the first 24 hrs while the proposal is being established, will think something has gone wrong and their vote failed. Sure - they could check in the console, but that undermines the entire purpose of the DAO screen, which is to make things extremely user friendly.

![_votes_missing](https://user-images.githubusercontent.com/24375948/148253740-5a187fb3-d301-4952-8de1-2965f586eb7e.png)

![_is_established](https://user-images.githubusercontent.com/24375948/148253764-9cd147d6-4652-4e03-afe8-cb72610a4918.png)

**Comment by random-zebra** [comment]
> The DAO screen shown below incorrectly shows there are no votes

It shows that there are no *No* votes.
All votes are positive so the widget shows "Yes 100%".
You can use the contextual menu of the proposal card, select "More info" to see the actual vote count (bottom of the dialog)

<img src="https://user-images.githubusercontent.com/18186894/148261191-a397ef20-1fa5-4c1e-9c7b-7b7fa88e79f2.png" alt="more-info-dialog" width="400"/>

**Comment by EricStanek** [comment]
Ah! My bad. To be honest, the dark mode is difficult for me to see with my poor eyesight.
Thanks for the quick response. Sorry for the interruption.
