### ISSUE TITLE
Masternode won't start after upgrade to 3.0.0

### ISSUE THREAD

**Issue by schwitin** [PIVX-Project/PIVX#274]
### Describe the issue
After  sync or resync with v3.0.0 I get the following error while starting the masternode:
"Not capable masternode: Hot node, waiting for remote activation."

The following suggestion doesn't work for me:

https://forum.pivx.org/t/uploaded-3-0-0-wont-sync-past-the-last-6-weeks/2309 

### Can you reliably reproduce the issue?
yes

1. stop older version with pivx-cli stop
2. unzip the new one:  https://github.com/PIVX-Project/PIVX/releases/download/v3.0.0/pivx-3.0.0-x86_64-linux-gnu.tar.gz
3. delete  all files and directories below ~/.pivx except of wallet.dat, masternode.conf and pivx.conf 

4. download and unzip suggested blocks and chainstate dirs to ~/.pivx to get the blockchain synced quickly: https://forum.pivx.org/t/uploaded-3-0-0-wont-sync-past-the-last-6-weeks/2309

5. start new version with pivxd -daemon and wait until sync is done

6. check sync status with  pivx-cli mnsync status, which shows after a while:
{
    "IsBlockchainSynced" : true,
...
}

6. start configured masternode with pivx-cli masternode start masternode1

=> Not capable masternode: Hot node, waiting for remote activation.

### Expected behavior
pivx-cli masternode status
should show something like "masternode started successfully"

### Actual behavior
"Not capable masternode: Hot node, waiting for remote activation."

### Machine specs:
- OS: 
Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07)

- CPU:
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU E5-2650L v4 @ 1.70GHz
stepping	: 1
microcode	: 0xb00001e
cpu MHz		: 1699.999
cache size	: 35840 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 20
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts nopl xtopol
ogy tsc_reliable nonstop_tsc aperfmperf pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx hypervisor lahf_lm 3dnowprefetch ida arat epb pln pts dtherm
bogomips	: 3399.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

- RAM:
free
             total       used       free     shared    buffers     cached
Mem:       1024404     955180      69224       5568       2616      46988
-/+ buffers/cache:     905576     118828
Swap:      1949692     956256     993436

- Disk size:
/dev/dm-0        18G  4.3G   13G  26% /
udev             10M     0   10M   0% /dev
tmpfs           201M   25M  176M  13% /run
tmpfs           501M     0  501M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           501M     0  501M   0% /sys/fs/cgroup
/dev/sda1       461M   33M  405M   8% /boot

- Disk Type (HD/SDD):
?? (VM)

**Comment by Fuzzbawls** [comment]
You have to start the masternode from the controller wallet

**Comment by schwitin** [comment]
I tried to start the masternode from the local installed pivx wallet (for the first time in my young live)

I got the following error dialog:
======================
Alias: masternode1
Failed to start masternode.
Error: Invalid IP address 94.177.230.233, masternode=<very long random string>
======================

While I can ssh to my masternode host using 94.177.230.233

**Comment by Mrs-X** [comment]
You have to configure the masternode in the local wallet's `masternode.conf`. You can do this either by hand (it's located in the same folder as the `pivx.conf file`) or from within the wallet (menu 'Tools'->'Open Masternode Configuration File').
See here https://pivx.freshdesk.com/support/solutions/articles/30000019701-masternode-vps-tutorial-linux- how the configuration entry should looks like.

**Please note that:**
a) you have to restart the wallet after you've changed the configuration file
b) the syntax of the command has changed: **old:** `masternode start-alias <alias>` **new:** `startmasternode alias 0 <alias>` 
(the docu needs to be updated, yes).

> Why is the cli command "pivx-cli masternode start/start-alias" still provided?

Because you could also use a running (local) PIVX daemon (pivxd) to start your masternode(s).

**Comment by schwitin** [comment]
I could start my masternode from local unlocked wallet with `sartmasternode all 0`.
