### ISSUE TITLE
PC Wallet Installation - PIVXParams Forced on C Drive By Default

### ISSUE THREAD

**Issue by Lulzzzz** [PIVX-Project/PIVX#2775]
### Describe the issue
During the PIVX wallet installation, user cannot fully select a true install location in a separate partition, such as **D** drive for example. PIVX defaults the PIVXParams folder to **C:\Users\myPC\AppData\Roaming\PIVXParams** forcing necessary files on the C drive rather than everything on D drive. 

#### If so, please list the steps to reproduce below:
1. Install PIVX wallet
2. Select another drive for installation other then C drive.
3. PIVX will still place **PIVXParams** folder on the C drive.

### Expected behavior
Installing Monero, DOGE, FIRO wallets for example, a user can fully install these wallets on a different partition without any dependencies on the default C drive. PIVX should be able to be installed fully on a separate partition using the default GUI wallet installation without having dependencies forced to be installed on the C drive.

### Actual behavior
You can direct the PIVX installation at a different partition but it still installs the **PIVXParams** folder to the C drive. **C:\Users\myPC\AppData\Roaming\PIVXParams**

### Machine specs:
- OS: Windows 10

**Comment by Fuzzbawls** [comment]
Installing static application support data in the %APPDATA% path (in your case `C:\Users\myPC\AppData\Roaming\`) is the intended, expected, and proper place to do so for ANY windows application, even when choosing to install the runtime files elsewhere.

No windows application that utilizes setting storage can be completely isolated from using the system drive. Monero, DOGE, FIRO, etc all utilize the windows registry to store basic GUI application setting data, and the windows registry is on your C drive.

**Comment by Lulzzzz** [comment]
Windows only creates shortcuts to a D drive install of DOGE, FIRO etc. on the C drive. You can delete every remnant instance on the C drive of those wallets if completely installed on another partition. Meaning, Windows will create shortcuts again in the registry and in C:\Users\myPC\AppData\Roaming\ when you open the wallets in another partition.

The whole idea here is to fully install the PIVX wallet on a separate partition and have them completely survive a C drive wipe. This can be done with DOGE, Monero, FIRO wallets. PIVX on the other hand creates a complete dependency on the C drive by not allowing a complete install on another partition.

**Comment by Fuzzbawls** [comment]
You've gotten your answer. the current behavior is the correct and proper behavior and we will not be changing such behavior.

**Comment by Lulzzzz** [comment]
Its more of a feature than expected behavior.
