### ISSUE TITLE
[Feature Request]Need to change the reward address for the masternode to another address for collecting rewards.

### ISSUE THREAD

**Issue by SkynetResearchProject** [PIVX-Project/PIVX#2777]
I have an idea how to increase the safety of collateral (C) storage . Now masternode rewards are going to (C). MN on vps signs transactions with his key on behalf of the owner of the collateral. The public key of the collateral is not known until the wallet collects inputs or until the user performs an outgoing transaction from (C) address. You need to enter 1 more input index from the transaction in the config line for MH, for example, the change exit index, and use the change address to collect rewards.

Added later.
The collateral can be stored on a cold wallet and the rewards can be sent to a desktop or mobile wallet (The public key is published on the blockchain during the collection of rewards in one amount).
In case of losing the phone, the user will only lose some of the rewards until the masternode is re-mortgaged.

Adding this capability requires a high level of skill and code knowledge.
The masternode address is retrieved by index during the processing of the masternode.conf file and the masternode manager adds it to the database. When a new block is created (MN active), a reward is added for the winning masternode. The masternode manager retrieves the masternode address from the database.
To pay to a custom address, you must correctly add the new address along with the masternode address to ensure compatibility with the previous version of the wallet and blockchain. This is one new field in 1-2 .dat files and several weeks to test work on the testnet.

masternode-payments.cpp
void CMasternodePayments::FillBlockPayee(CMutableTransaction& txNew, const CBlockIndex* pindexPrev, bool fProofOfStake)
masternode-payments.cpp (1 hits)
	 CMasternode* winningNode = mnodeman.GetCurrentMasterNode(1);
masternodeman.cpp (1 hits)
	 CMasternode* CMasternodeMan::GetCurrentMasterNode(int mod, int64_t nBlockHeight, int minProtocol)
masternodeman.h (1 hits)
         CMasternode* GetCurrentMasterNode(int mod = 1, int64_t nBlockHeight = 0, int minProtocol = 0);

**Comment by Fuzzbawls** [comment]
This functionality is included in the intended 6.0 DMN set of features. no sense in modifying the current system at this point.
