### ISSUE TITLE
Need Clipboard Copy button for 'Recipient' address in Proposal Info screen.

### ISSUE THREAD

**Issue by EricStanek** [PIVX-Project/PIVX#2792]
### Describe the issue

Unable to copy the Recipient address from the 'Proposal Information' window in the DAO screen.

#### If so, please list the steps to reproduce below:
1. In the Core Wallet - go to the DAO screen and select 'More Info' using the '3 dots' menu for any proposal.
2. Note that the Recipient address is not selectable to 'copy and paste'. It can't be highlighted to select and there is no 'Clipboard Copy' button.

### Expected behavior
User should be able to copy the address to the clipboard with a button.

### Actual behavior
User must manually type the address into an explorer. Very tedious and error prone. Bad UX.

### Screenshots.

![_need_clipboard_copy](https://user-images.githubusercontent.com/24375948/213935726-13c8154b-bdc1-463f-ba07-3661843c1e24.png)

### What version of PIVX Core are you using?
v5.5

**Comment by panleone** [comment]
Issue has been solved
