### ISSUE TITLE
All zpiv transactions conflicted

### ISSUE THREAD

**Issue by joae1975** [PIVX-Project/PIVX#281]
This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Slack](http://pivx.slack.com).

### Describe the issue
I'm not a developer and don't know how to technically report this but all my autominted zpiv coins are conflicted. 

### Can you reliably reproduce the issue?
yes
#### If so, please list the steps to reproduce below:
1. paste destination address in "pay to" field under privacy tab
2. entered 1 zpiv
3. pressed spend zerocoin

### Expected behavior
Coin should send in seconds

### Actual behavior
I have a mac and received the rainbow wheel of death for a few minutes then it gave me this error message:
"Error"  The transaction was rejected!  This might happen if some of the coins in your wallet were already spent, such as if you used a copy of wallet.dat and coins were spent in the copy but not marked as spent here."  I received 10 zpiv from an accumulator transaction and after I tried to send that 1 zpiv, the amount change to 9 in my transactions details.  None of my accumulator transactions have been broadcasted yet. 

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of PIVX Core are you using?
3.0, the latest version
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

### Machine specs:
- OS: OSX 10.12.6 (16G29)
- CPU: Intel Core i3
- RAM: 16Gb
- Disk size: 1Tb
- Disk Type (HD/SDD): HD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by Fuzzbawls** [comment]
See #280 for the proposed fix

**Comment by Fuzzbawls** [comment]
Closing now that #280 has been merged
