### ISSUE TITLE
verion 5.6.1 masternode doesn't pay out rewards

### ISSUE THREAD

**Issue by skironDotNet** [PIVX-Project/PIVX#2910]
Is it possible? I ran MN over 48h and nothing I think in 5.5 withing 48h was paying out

**Comment by Liquid369** [comment]
It is indeed possible! I started mine on 5.6.1 and it took around 82 hours for me. Considering around the update we were at about 1800 Masternodes. With a 3x wait that would be about 3-4 days. 1440 blocks per day, so 1440 can be paid, 1800 MN is 1440 + 360 which is about a day and 6 hours. 30 x 3 = 90 hours wait time with this current masternode count. It could be less or more if there was any node issues.

**Comment by skironDotNet** [comment]
I got the payout, it makes sense. Also https://zkbitcoin.com/charts/masternode shows the drop in MNs probably as ppl update to new version before 29th.
Thanks for additional details on how things are distributed.
