### ISSUE TITLE
Website links download wallet gives 404 page

### ISSUE THREAD

**Issue by AndyBrooks** [PIVX-Project/PIVX#295]
This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Slack](http://pivx.slack.com).

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of PIVX Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by jonspock** [comment]
Thanks but not the best place for this type of issue since this is only for PIVX-Core wallet. Whole other team is involved that don't probably look here, so closing this off
