### ISSUE TITLE
Issue with spending zPIV on RC2

### ISSUE THREAD

**Issue by geni4** [PIVX-Project/PIVX#303]
following situation:

- RC2 wallet, synced this night
- zPIV amount of 10x 100, and 10x10 all confirmed over 8000 times 

now i want to convert zPIV into PIV. therefore I want to spend 700 zPIV (as max is 7 different denominations) but it did not went through and i got instead of that the attached error message

if i try in a 2nd step to choose only the denominations with the size of 100 and check the box of the denominations of 100 in the zPIV control, i get the same error message.

<img width="447" alt="bildschirmfoto 2017-10-23 um 13 24 09" src="https://user-images.githubusercontent.com/24824934/31900974-68a75b5a-b820-11e7-9667-6b267984cf8f.png">

**Comment by jonspock** [comment]
Thanks. These types of spends are not possible due to limitations of spends/transaction. However, the GUI should notify you in advance instead of just giving an error
