### ISSUE TITLE
New error when opening wallet

### ISSUE THREAD

**Issue by satoshinakajeff** [PIVX-Project/PIVX#305]
main.cpp:5322: void ProcessGetData(CNode*): Assertion `!"cannot load block from disk"'

This is the error the client gets.

### What version of PIVX Core are you using?
3.0.4 RC2

**Comment by PIVX-Project** [comment]
is this done using the Clean chain posted in Slack?

Have you tested this issue by doing a resync from scratch (By deleting the blocks, chainstate, sporks and zerocoin folders?)

**Comment by Mrs-X** [comment]
This issue is most probably just a corrupt blockchain file, however while investigating this I found a possible issue which could also trigger this error message.
I'll open a PR soon.

**Comment by Fuzzbawls** [comment]
closing now that #306 has been merged
