### ISSUE TITLE
"pivxd --help" stopped working after commit 765af89595399f3131547b09574af650cceb3531

### ISSUE THREAD

**Issue by mkgin** [PIVX-Project/PIVX#311]
### Describe the issue

$ ./pivxd --help 
pivxd: chainparams.cpp:389: const CChainParams& Params(): Assertion `pCurrentParams' failed.
Aborted

Perhaps help could be added to the tests...

### Any extra information that might be useful in the debugging process.

I have narrowed down to one line, problem disappears after commenting this line.  
Will reference it with a comment to the commit in a moment.

**Comment by jonspock** [comment]
OK, thanks. It should be fixed in this branch
https://github.com/PIVX-Project/PIVX/tree/init_fix
Will be merged to master soon hopefully

**Comment by Fuzzbawls** [comment]
closing now that #314 has been merged

**Comment by mkgin** [comment]
:vulcan_salute:  zPiv long and prosper. :-)
