### ISSUE TITLE
Pivx Source Build Wrong Version

### ISSUE THREAD

**Issue by JSponaugle** [PIVX-Project/PIVX#313]
### Describe the issue
Building From source is producing
"version" : 3009900

#### If so, please list the steps to reproduce below:
1. Clone Git
2. Build Unix
3. pivx-cli getinfo

### Expected behavior
Everyone says the version is wrong

### Actual behavior
Should it be something else?

### What version of PIVX Core are you using?
Version: 3009900
commit ID: dbd801d
Self Compiled

**Comment by presstab** [comment]
Master branch is versioned with .99, which is in line with how bitcoin treats their versioning/banching. Building from the specific version tag will give you a different version number.
