### ISSUE TITLE
stuck on sync wit nodes on block 863726 

### ISSUE THREAD

**Issue by kiwseb** [PIVX-Project/PIVX#315]
1. stop sync with net on block 863726
2. reindex not help
3. repair opt not help

- OS: win10
- CPU: i7 7700
- RAM: 8
- Disk size: 3 tb
- Disk Type (HD/SDD): hd

**Comment by madayar** [comment]
exact same thing with me. stop sync with net on block 863726

OS: macOS Sierra
CPU: i7

**Comment by presstab** [comment]
What version of the wallet?

**Comment by kiwseb** [comment]
last available 
last wallet have also no opt to disable zerocin -too bad not all want to be anonymously :)

**Comment by PIVX-Project** [comment]
every wallet has the option to disable automint. add: enablezeromint=0 to your pivx.conf file

**Comment by PIVX-Project** [comment]
Are you sure your wallet has stopped syncing? If you are stuck at a block approx 2 weeks ago, then these blocks have over 1k transactions so they will take awhile to process.

**Comment by presstab** [comment]
Any relevant information in the debug.log?

**Comment by arb0iten** [comment]
Hello friends! There was a similar problem, it hung for two days and was not synchronized. First, make copies just in case. The solution is to clean everything in folders (blocks, chainstate, sporks, zerocoin) and run the program all! bingo!!!! Good luck! ;-)

**Comment by Fuzzbawls** [comment]
@presstab update on this one? is more information needed or has this been addressed already?

**Comment by Warrows** [comment]
Looking at the dates, this has probably been fixed after 3.0.4. Should be closed IMO.

**Comment by Mrs-X** [comment]
This is most probably addressed with several sync/block-verification related updates since this issue was opened.
If there's still a problem (or a new one) please open a new issue.

Thanks.
