### ISSUE TITLE
1/10th of my masternode went to zPiv accumulator automatically. My zPiv balance is still 0 even though it has 2000 confirms. How do I restore my wallet balance back to 10,000 and how to I prevent auto conversions?

### ISSUE THREAD

**Issue by henryshale** [PIVX-Project/PIVX#318]
Mac High Sierra PIVX Core version v3.0.3.2-1c203d578-dirty (64-bit)

**Comment by jonspock** [comment]
Hi @henryshale can you try our slack support. This is not really geared for interactive support. Disable auto conversions by putting enablezeromint=0 in your pivx.conf file

**Comment by jonspock** [comment]
Can you also please re-download the High Sierra DMG. That one was a debug build which will be very slow. Thanks

**Comment by henryshale** [comment]
Hello, thanks for your reply. The slack channel is full and not accepting new members. The enablezeromint=0 solves the problem of stopping it from auto minting, but I'm still missing 1000 PIVX and have 0 zPiv to show for it. I've tried these commands:
getarchivedzerocoin
reconsiderzerocoin
resetspentzerocoin
resetmintzerocoin true

**Comment by jonspock** [comment]
https://discord.gg/3X7hwr Try Discord

**Comment by jonspock** [comment]
https://join.slack.com/t/pivx/shared_invite/enQtMjU4MDMxODIyOTE5LTEzYmMwZGFkMjcxYjgwNTNmMzIwMGFlZjhkMjc1MWQxY2M0ZWJhZDcxMGU3OGM1YWFmOWI0ODFkMWY4MGJiMDQ

that will get you into slack I think if you are the first to use it

**Comment by jonspock** [comment]
Also in the Privacy tab open zPIV control to see if the coins show up there with a message

**Comment by jonspock** [comment]
I think this was resolved in Slack or Discord, closing
