### ISSUE TITLE
[Suggestion] Error messages changed to be understood by user

### ISSUE THREAD

**Issue by Sieres** [PIVX-Project/PIVX#319]
#### If so, please list the steps to reproduce below:
example 1.
1. zPIV transaction with more than 8 denominations
2. Get an error that does not tell the user that you cannot have more than 7 denominations

example 2.
1. Spend zPIV with having enough denominations in the mixing pool
2. Get an error that does not describe that is what occured

### What version of PIVX Core are you using?
3.0.4rc3

### Any extra information that might be useful in the debugging process.
The support team will be happy to assist in translating the text if needed.

**Comment by Fuzzbawls** [comment]
See #309 that addresses this exact concern. It has since been merged but didn't make it in time for 3.0.4rc3
