### ISSUE TITLE
3.0.4RC3: Fatal error. Error 22, can't open database

### ISSUE THREAD

**Issue by relramackers** [PIVX-Project/PIVX#321]
On Windows 64-bit, after I click the ReScan button under the Privacy tab:

![image](https://user-images.githubusercontent.com/32817490/32065616-88c9a582-ba7d-11e7-9c98-655751d9c895.png)

**Comment by relramackers** [comment]
Now my wallet is corrupt, salvage failt. 

IF I would have enabled the minting and accumulated coins today these coins of today would now be lost.

**Comment by presstab** [comment]
So you pressed the rescan button without any zPiv actually existing in your wallet?

**Comment by relramackers** [comment]
No, I clicked the Rescan button to get my zPIV back that were lost. Obviously with this fatal error they did not return. The zPIV that still existed in the wallet could only be returned with a backup wallet, after the fatal error corrupted the wallet.

**Comment by PIVX-Project** [comment]
why are you using an outdated wallet to try and recover your PIV??

**Comment by rejectedpromise** [comment]
still relevant?

**Comment by relramackers** [comment]
Nope, you can close the ticket.

Verstuurd vanaf mijn iPad4
