### ISSUE TITLE
Display zPiv waiting for additional mints more prominently 

### ISSUE THREAD

**Issue by derekhansen** [PIVX-Project/PIVX#330]
After upgrading the wallet many users are confused when they see an incorrect balance on the Overview tab of the qt gui. The Combined balances (including immature coins) section does not show zPiv that require additional mints in order to be spent. Since the release this has frequently come up in the slack support channel.

Users must go to the Privacy -> zPiv control -> drop down arrows to the left, and check the rightmost column in order to discover what the status of their coins are.

I would suggest that on the overview tab under Combined balances (including immature coins) the zPivs that require additional mints are displayed in the total. This way, at the very least users won't be as concerned that they have missing coins.

Thoughts?

**Comment by presstab** [comment]
Added in #323 will be in release.
