### ISSUE TITLE
zPIV spend transaction disappears from record after restart 

### ISSUE THREAD

**Issue by jonspock** [PIVX-Project/PIVX#334]
On Mac.
A zPIV spend which went through and is verified on block explorer and was initially visible in the wallet, is no longer visible upon a restart. There were a few spends over a period of time and just 1 or 2 is unaccounted for. No zPIV or PIV lost, just the transaction record

**Comment by presstab** [comment]
Are you sure that it is lost, or is it possible that the date of the transaction was recorded improperly on that record?

**Comment by rejectedpromise** [comment]
still relevant?

**Comment by Fuzzbawls** [comment]
closing...no further information provided.
