### ISSUE TITLE
[Feature Request] pivx-cli loading messages

### ISSUE THREAD

**Issue by jk9694** [PIVX-Project/PIVX#335]
**Feature Request**

Add chain loading % and block verification % to the pivx-cli response when the wallet it starting.

**Comment by rejectedpromise** [comment]
moving to project -> https://github.com/PIVX-Project/PIVX/projects/23

**Comment by Fuzzbawls** [comment]
Reopening this to see if there is any further consensus as to it's viability and/or if anyone wants to pick it up for submitting a PR.

**Comment by mrmetech** [comment]
I mean if am paid for my time, I could probably do this.

**Comment by Fuzzbawls** [comment]
Status/step updates for when the wallet is still loading were added in #1909. Closing this.
