### ISSUE TITLE
Version 3.0.4 High Sierra is not working

### ISSUE THREAD

**Issue by gfnord** [PIVX-Project/PIVX#336]
I just upgraded my wallet to 3.0.4 using High Sierra version and it not work here, it crash after a few seconds. 

One thing I noticed every time I try to run the wallet I got the message from system asking to allow Pivx-QT to listen to a port. In the older version that happened only once after the installation of a new version.

**Comment by Fuzzbawls** [comment]
you'll need to provide more details, such as the text box from the report window, or screenshots, something.

**Comment by gfnord** [comment]
Hi Fuzzbawls, there is no more details than the follow:

gustavo@Macnord ~ % /Applications/PIVX-Qt.app/Contents/MacOS/PIVX-Qt
Assertion failed: (hashPrevBlock == view.GetBestBlock()), function ConnectBlock, file /Users/spock/spock_PIVX/src/main.cpp, line 2855.
[1]    1825 abort      /Applications/PIVX-Qt.app/Contents/MacOS/PIVX-Qt
/Applications/PIVX-Qt.app/Contents/MacOS/PIVX-Qt  19.03s user 0.67s system 96% cpu 20.363 total

When I click on Report button from the system error message, nothing appears.

**Comment by gfnord** [comment]
What's unusual too.

**Comment by Fuzzbawls** [comment]
you can try the `-forcestart` option (Open your terminal app and type `/Applications/PIVX-Qt.app/Contents/MacOS/PIVX-Qt -forcestart`) or you can follow the steps outlined on https://pivx.freshdesk.com/solution/articles/30000004661-wallet-crashes-or-has-crashed-and-now-won-t-launch-fails-every-time-what-do-i-do-

**Comment by jonspock** [comment]
@gfnord, can we close this now? Did -forcestart work?

**Comment by presstab** [comment]
This error is not specific to High Sierra, it is a corrupted database that you can force your way past by using `-forcestart`. By using forcestart you are continuing past the corruption error and letting your wallet run until it hits that corrupted data again, at which point a reindex will be needed.
