### ISSUE TITLE
Send tab says SwiftTX, but should be SwiftX.

### ISSUE THREAD

**Issue by EricStanek** [PIVX-Project/PIVX#338]
### Describe the issue

Send tab says SwiftTX, but should be SwiftX. Trivial - I know. Sorry. But therefore easy to fix too!

### Can you reliably reproduce the issue?

Yes

#### If so, please list the steps to reproduce below:
1. Open wallet.
2. Go to Send tab.
3. Look in lower right.

### Expected behavior

Label should be SwiftX.

### Actual behavior

Label is SwiftTX.

### What version of PIVX Core are you using?

PIVX Core version v3.0.4 (64-bit)

**Comment by Mrs-X** [comment]
Hmh, here (https://pivx.org/what-is-pivx/features/) it says 'SwiftTX'.
@s3v3nh4cks what's the official term?
