### ISSUE TITLE
Crash after corrupted block database

### ISSUE THREAD

**Issue by spiralus** [PIVX-Project/PIVX#34]
When App is opened with a corrupted block index, App asserts in Boost's recursive_mutex.hpp lock function
Assertion failed: (!pthread_mutex_unlock(&m)), function unlock, file /usr/local/include/boost/thread/pthread/recursive_mutex.hpp, line 118.
       void lock()
        {
            BOOST_VERIFY(!pthread_mutex_lock(&m));
        }

Later it asserts at the same place without even notifying about corrupted block database

**Comment by jonspock** [comment]
Fixed in commit e0037bbd688b9139f9bb375a46e901d7b0747e9f
