### ISSUE TITLE
Rescan doesn't always work

### ISSUE THREAD

**Issue by jonspock** [PIVX-Project/PIVX#341]
### Describe the issue
I had different backup wallet.dat files. I swapped out 3 different ones. When I replaced it the 3rd time, the wallet didn't rescan fully (or at all) and I was left with very large balance but unable to spend 1 PIV.  This was on Testnet
Error message was `The transaction was rejected! This might happen if some of the coins in your wallet were already spent, such as if you used a copy of wallet.dat and coins were spent in the copy but not marked as spent here.`

### Can you reliably reproduce the issue?
I quit the wallet and restarted but problem persisted

### Expected behavior
Wallet should rescan and give correct balance

### Actual behavior
Wrong balance

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of PIVX Core are you using?
3.0.4

### Machine specs:
- OS: MacOS

**Comment by mkgin** [comment]
Me too, but comand line, .. Issues with main net wallet... tag 3.0.4 and master.

I hope that result I get from:

`pivx-cli exportzerocoins false  |grep -e \"d\" |sort |uniq -c`

reflects the situation more accurately than.

`pivx-cli listzerocoinamounts`

**Comment by presstab** [comment]
@jonspock when you say that rescan didn't work, which scan did you use? Was it `Recover Transactions 1` from the GUI?

**Comment by jonspock** [comment]
I thought the rescan was automatic. At least it was the 1st time I replaced wallet.dat

**Comment by Fuzzbawls** [comment]
@jonspock did you ever run this against a forced `-rescan` ???
