### ISSUE TITLE
When minting zPIV notification amount is wrong

### ISSUE THREAD

**Issue by jonspock** [PIVX-Project/PIVX#342]
If I mint 4 zPIV, I just get the popup notice for the last mint rather than the total

**Comment by Mrs-X** [comment]
I'll take care of this.

**Comment by Fuzzbawls** [comment]
@Mrs-X still open?

**Comment by Mrs-X** [comment]
We don't have a popup anymore, all information is the status field on the Privacy tab now.

Just minted 4 zPIV, and as expected:
```
Successfully minted 4 zPIV in 0.574 sec. Used denominations:
1 1 1 1 
```
Closing...

**Comment by Sieres** [comment]
ACK
