### ISSUE TITLE
Missing german translation in Wallet 

### ISSUE THREAD

**Issue by Harry-Hirsch** [PIVX-Project/PIVX#343]
In the german wallet version at the Privacy tab it shows the english lines "Denom with value: xxxx"
instead of the german translation of these lines.
(The Tooltip shows the translated lines.)
In Transifex these lines are already translated since about 1 month

![missingtranslation](https://user-images.githubusercontent.com/33361891/32399561-421aa3ae-c0f7-11e7-9275-e2806610a5cf.PNG)
.

**Comment by Fuzzbawls** [comment]
Closing this as all available strings are currently passed to transifex for translation.

Anything that shows an untranslated string is due to no available translation for the particular release.
