### ISSUE TITLE
Incorrect output index displayed in transaction details dialog box

### ISSUE THREAD

**Issue by cryptoj-pivx** [PIVX-Project/PIVX#344]
### Issue
Transactions details dialog box keeps displaying _Output index: 0_ for transactions with non-zero output index values

### Can you reliably reproduce the issue?
Yes

#### If so, please list the steps to reproduce below:
1. Create a transaction with non-zero output index
2. Open transaction dialog box

### Expected behavior
_Output index:_ should display correct output index

### Actual behavior
_Output index: 0_ 

### What version of PIVX Core are you using?
Official PIVX Core Qt version v3.0.4 (64-bit) Linux binary

**Comment by DICKWJC** [comment]
[Electrum Pivx](https://www.electrumpivx.org)
[Electrum Pivx Wallet](https://www.electrumpivx.org)
[Electrum Wallet Pivx](https://www.electrumpivx.org)
[Pivx Electrum](https://www.electrumpivx.org)
[Pivx Electrum Wallet](https://www.electrumpivx.org)
[Pivx Wallet Electrum](https://www.electrumpivx.org)

**Comment by random-zebra** [comment]
old GUI
