### ISSUE TITLE
Missing zPIV. RPi3 crashed  and all backups from zerocoin time have been lost.

### ISSUE THREAD

**Issue by Avatar1964** [PIVX-Project/PIVX#345]
piter - PIVXSports Instagram moderator, long-term community member, PIVX Polska group moderator, KKS Rawa Katowice sponsored by PIVX manager.

I really had a bad luck, because my Raspberry Pi 3 crashed and all the files there have been lost. I ve tried to recover the backups in so many ways but even professional IT guy couldn't recover them. I only have the older wallet.dat file that is not able to recover lost zPIVs (more than 2600 PIVs converted to zPIV while using versions between 3.0.0 and 3.0.4)

However, the transactions showing PIVs being converted to zPIVs are still in the Transaction Tab in my wallet. The final balance then (zPIVs+PIVs) in overview is not equal to the transaction history sum, while it should be.
I am asking for a help and for a fix, that will be able to recover/generate zPIVs when final balance is not equal to Tx sum in the wallet, so there will be everything fine.

I am asking for a help, I have been here for so long time, I love this project, devs and community and I strongly believe there could be a fix found for cases like mine.

Regards
piter

**Comment by PIVX-Project** [comment]
This is not the same story we were told before, previously you stated that you had deleted the backups by mistake (even thought you had to enter a hidden directory to do so). If you can't recover your data, there isn't anything that can be done.

Never delete your wallet.dat files..

**Comment by mkgin** [comment]
`pivx-cli exportzerocoins false |grep \"d\"`
 
And you can count the amounts of your zero coins...
I have noticed a discrepancy with what is there and calculated by the client

`pivx-cli listzerocoinamounts`

**Comment by Avatar1964** [comment]
Accidentally deleting is not equal to crash? Sorry if you undersood me wrong, i am not the native speaker and i have never been to english-speaking country. Please forgive me

**Comment by Avatar1964** [comment]
In polish crash is equal to accident so maybe that is why :/
