### ISSUE TITLE
zPiv Staking

### ISSUE THREAD

**Issue by presstab** [PIVX-Project/PIVX#346]
Description: Add the ability to stake zerocoins.
Status: Not compilable, not integrated into testnet or mainnet.
Feature development branch: https://github.com/presstab/pivx/tree/zpiv_stake

**Comment by borris345** [comment]
Nice. Did I see it was ready for testnet?

**Comment by presstab** [comment]
Feature development branch: https://github.com/presstab/pivx/tree/zpiv_stake
