### ISSUE TITLE
[UI] Redesign

### ISSUE THREAD

**Issue by Mrs-X** [PIVX-Project/PIVX#348]
Complete re-design of the Qt-wallet.
Issue opened for waffle.io tracking

**Comment by turnkit** [comment]
In this update, please make the "unlocked" icon more obviously unlocked.  Not sure where the correct site is for this comment so apologies if it doesn't go here.

**Comment by turnkit** [comment]
Also please create the new UI so that a newb could understand and send private coin transactions!  Thanks.

**Comment by Sieres** [comment]
Can we consider making the SwiftX button larger / more obvious. When it's available again, it would be a very highly used feature.

**Comment by Sieres** [comment]
ACK
