### ISSUE TITLE
Trust-less setup for Zerocoin Params

### ISSUE THREAD

**Issue by PIVX-Project** [PIVX-Project/PIVX#352]

**Comment by rejectedpromise** [comment]
moving to project -> https://github.com/PIVX-Project/PIVX/projects/23

**Comment by DICKWJC** [comment]
[Electrum Pivx](https://www.electrumpivx.org)
[Electrum Pivx Wallet](https://www.electrumpivx.org)
[Electrum Wallet Pivx](https://www.electrumpivx.org)
[Pivx Electrum](https://www.electrumpivx.org)
[Pivx Electrum Wallet](https://www.electrumpivx.org)
[Pivx Wallet Electrum](https://www.electrumpivx.org)
