### ISSUE TITLE
In-Wallet U2F Integration

### ISSUE THREAD

**Issue by PIVX-Project** [PIVX-Project/PIVX#354]
Yubico has the C Modules for this and instructions for implementing this.

**Comment by Mrs-X** [comment]
Feature request moved to new project https://github.com/PIVX-Project/PIVX/projects/17

**Comment by Fuzzbawls** [comment]
Closing this after discussions with @blondfrogs 

For the time being, there just isn't any real security benefit to U2F in a client-only scenario.
