### ISSUE TITLE
Application locked when switching from 'Masternodes' to 'Overview' tab.

### ISSUE THREAD

**Issue by EricStanek** [PIVX-Project/PIVX#36]
The application locked when switching from 'Masternodes' to 'Overview' tab.

Version: PIVX Core version v2.1.4.0-9efddca (64-bit)
OS: Fedora 25

This happened the first time I ran this specific new version of the wallet, and before I set the theme to the default. I will update here if I am able to reproduce the issue. The debug.log file had no errors at all. Just this seemingly unrelated warning.

    "GUI: libpng warning: iCCP: known incorrect sRGB profile."

In the attached image you can see the 'Overview' button shows as selected, but it locked up and didn't switch. I had to 'Force Quit' (In Linux) and that meant replacing the chain too for the next time I started it.

![locked](https://cloud.githubusercontent.com/assets/24375948/22179842/9bc1a6f2-e02c-11e6-9b77-84f0bc6aeba0.png)

**Comment by Fuzzbawls** [comment]
Is this still a reproducible issue in v2.1.5?

**Comment by EricStanek** [comment]
Thanks for the follow up. I was able to reproduce the issue easily when it occurred, but after a reboot, I was not able to, and have not since. I'm going to assume it was an issue unrelated to PIVX code and close this one.
