### ISSUE TITLE
In-Wallet Proposal Creation Tab

### ISSUE THREAD

**Issue by PIVX-Project** [PIVX-Project/PIVX#361]

**Comment by rejectedpromise** [comment]
moving to project -> https://github.com/PIVX-Project/PIVX/projects/23

**Comment by DICKWJC** [comment]
[Electrum Pivx](https://www.electrumpivx.org)
[Electrum Pivx Wallet](https://www.electrumpivx.org)
[Electrum Wallet Pivx](https://www.electrumpivx.org)
[Pivx Electrum](https://www.electrumpivx.org)
[Pivx Electrum Wallet](https://www.electrumpivx.org)
[Pivx Wallet Electrum](https://www.electrumpivx.org)

**Comment by akshaynexus** [comment]
Phone has done something similar to what is to be done as per the issue, might be a good reference

**Comment by random-zebra** [comment]
Closed in #2406
