### ISSUE TITLE
Create Buttons for any  function the user may need to access the Data Directory for

### ISSUE THREAD

**Issue by PIVX-Project** [PIVX-Project/PIVX#376]
Would be good to add more functionality to the repair wallet section;

- Delete Peers file
- Export Log files
i will think of others

**Comment by Mrs-X** [comment]
Some random thoughts:
- you know that deleting `peers.dat` would also need a wallet restart?
- what do you mean with "Export"? I could open a file explorer in the folder where `debug.log` is located to allow him/her easy access and copying it somewhere else.

**Comment by rejectedpromise** [comment]
moving to project -> https://github.com/PIVX-Project/PIVX/projects/23

**Comment by Fuzzbawls** [comment]
Think this can be closed as "stale" now. The two examples given are rather irrelevant now: `peers.dat` no longer holds ban information, which was the number 1 reason to ever delete the file prior to the multiple peer banning PRs, and "exporting" the log file is a bit out of scope.

**Comment by Mrs-X** [comment]
Agreed, closing it.
