### ISSUE TITLE
Add BIP39/44 functionality 

### ISSUE THREAD

**Issue by PIVX-Project** [PIVX-Project/PIVX#378]
Self Explanatory.. :)

**Comment by vampyren** [comment]
Sorry i dont think this is very "Self Explanatory"
So i found this info:
BIP-0039:
This BIP describes the implementation of a mnemonic code or mnemonic sentence -- a group of easy to remember words -- for the generation of deterministic wallets.

BIP-0044:
This BIP defines a logical hierarchy for deterministic wallets based on an algorithm described in BIP-0032 (BIP32 from now on) and purpose scheme described in BIP-0043 (BIP43 from now on).

**Comment by Warrows** [comment]
See #956

**Comment by random-zebra** [comment]
Bip44 implemented in #1327 
Bip39 will not be implemented in its current form.
