### ISSUE TITLE
zDEX Compatibility

### ISSUE THREAD

**Issue by PIVX-Project** [PIVX-Project/PIVX#383]
We will be integrating our own zDEX into the PIVX wallet, so users can purchase zPIV more privately and in a decentralized manner..

**Comment by rkilchmn** [comment]
Will it use atomic swaps once trading partners have agreed?

**Comment by Mrs-X** [comment]
Feature request moved to new project https://github.com/PIVX-Project/PIVX/projects/22

**Comment by tofutim** [comment]
i'm curious what the status is of zdex

**Comment by Fuzzbawls** [comment]
its being developed in a private repository

**Comment by Fuzzbawls** [comment]
Compatibility with zDEX was introduced in #705, closing
