### ISSUE TITLE
pivxd fails to load

### ISSUE THREAD

**Issue by silverbucket** [PIVX-Project/PIVX#391]
It used to work fine, but now whenever I start `pivxd` it dies after a minute or two, never successfully loading.

#### If so, please list the steps to reproduce below:
1. run pivxd

### Expected behavior
eventually, I should be able to `pivx-cli getinfo`

### Actual behavior
after 1-2 minutes, the daemon is dead.

### What version of PIVX Core are you using?
`3.0.99` and `3.0.5` .. started happening at about 4am this morning UTC

### Machine specs:
- OS: Ubuntu x86_64
- CPU: 
- RAM: 1GB
- Disk size: 20G
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
I successfully upgraded from `3.0.4` to `3.0.99` yesterday, and everything was running fine. Today though, the daemon was stopped. I checked the releases page and say `3.0.5` was released, so figured it might be due to that. I downloaded and ran `3.0.5` but am getting the same behavior.

I also tried `reindex=1` but that doesn't seem to help.

**Comment by Fuzzbawls** [comment]
Check both the debug.log file and your system log. You may well be running out of memory and the process is getting killed

**Comment by silverbucket** [comment]
Of course, another service started up that was supposed to be off. I should have checked first thing. Thanks @Fuzzbawls
