### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by parizona** [PIVX-Project/PIVX#394]
After installing "pivx-3.0.5-win64-setup-unsigned.exe" to replace my old PIVX wallet, the new wallet was not able to synchronize. So I restarted my computer, and now whenever I try to open the new PIVX wallet I get the following error:

![runtime error message](https://user-images.githubusercontent.com/33735276/32917207-b1df25be-cadb-11e7-9112-99934b3700b8.JPG)

I am using Windows 8.1 Pro with a 2.4 GHz processor and 32 GB RAM.

I will be very grateful for any help solving this problem!

**Comment by mkgin** [comment]
This make be connected. 

Perhaps something to do with log message formats?
https://github.com/bitcoin/bitcoin/issues/9423

debug log from pivxd 3.0.5 ( self compliled  Debian 9.1 amd64 )

On restart....

2017-11-18 20:15:16 RecalculatePIVSupply : block 907000...
2017-11-18 20:15:16 RecalculatePIVSupply : block 908000...


************************
EXCEPTION: St13runtime_error       
tinyformat: Too many conversion specifiers in format string       
pivx in AppInit()       

2017-11-18 20:15:17 

************************
EXCEPTION: St13runtime_error       
tinyformat: Too many conversion specifiers in format string       
pivx in AppInit()       

2017-11-18 20:15:17 PrepareShutdown: In progress...
2017-11-18 20:15:17 RPCAcceptHandler: Error: Operation canceled
2017-11-18 20:15:17 StopNode()
2017-11-18 20:15:17 Shutdown: done

**Comment by presstab** [comment]
Please see v3.0.5.1 if you are experiencing this runtime error.
