### ISSUE TITLE
Crash when trying to send PIV

### ISSUE THREAD

**Issue by pferdob** [PIVX-Project/PIVX#396]
Sending PIV does not work for me.

1. Open up wallet, let it sync with the network
2. Try to send PIV, enter address, note, amount and wallet password
3. Wallet crashed without any message. On the  shell one can read: "pivx-qt: crypter.cpp:251: bool CCryptoKeyStore::Unlock(const CKeyingMaterial&): Assertion `false' failed." 

Wallet Version: 3.0.5 official, both 32 bit and 64 bit show the same behaviour.
System: Fedora 27 x86-64, intel i5 6600, 32GB RAM, 240 GB SSD

**Comment by pferdob** [comment]
Issue persists with version 3.5.0.1 (same error message)

**Comment by Fuzzbawls** [comment]
Sounds like the wallet can't be unlocked for whatever reason. Try unlocking the wallet from the menu prior to sending. Also check your debug.log and db.log files for more information.

Would also be a good idea to try some backup `wallet.dat` files in case the cause is file corruption.

**Comment by pferdob** [comment]
Corrupted wallet file. Don't know why (never crashed nor touched). Sorry for occupying your time.
