### ISSUE TITLE
Unclear warning dialog sending funds.

### ISSUE THREAD

**Issue by VTHokiEE** [PIVX-Project/PIVX#404]
### Describe the issue
When sending funds from the GUI a popup dialog states that sending from "any available funds" is not recommended. This is vague and doesn't detail why it is not recommended or what would be the recommended method for sending funds.

### Expected behavior
Rewording to explain why this is not recommended (if it truly isn't) and what and alternative approach would be.

**Comment by danielelis** [comment]
How about changing (not recommended) to: 
“(not private), Spend Zerocoin in the Privacy tab is private.”

**Comment by Fuzzbawls** [comment]
This was actually resolved in #499, closing.
