### ISSUE TITLE
Encryptwallet missing from Help

### ISSUE THREAD

**Issue by VTHokiEE** [PIVX-Project/PIVX#410]
### Describe the issue
There is no help for the encryptwallet command

If I run: 
pivx-3.0.5/bin/pivx-cli encryptwallet
error: {"code":-15,"message":"Error: running with an encrypted wallet, but encryptwallet was called."}
Which leads me to believe the command is valid however:

pivx-3.0.5/bin/pivx-cli help encryptwallet
help: unknown command: encryptwallet

The command is also missing if I simply type `help`

### Expected behavior
./pivx-cli help encryptwallet should describe the command and show example usage.

### What version of PIVX Core?
Official binary for 3.0.5.1

**Comment by jonspock** [comment]
I believe you can't get help if the wallet is already encrypted. Please look up the topic in bitcoin wiki/help

**Comment by jonspock** [comment]
See here: https://bitcoin.stackexchange.com/questions/24799/how-to-enable-wallet-encryption-from-the-command-line

**Comment by VTHokiEE** [comment]
Oh interesting, good to know. I’ll close this.
