### ISSUE TITLE
[Feature Request] Version number in overview tab

### ISSUE THREAD

**Issue by Sieres** [PIVX-Project/PIVX#414]
### Describe the issue
To assist the support team, have a small print of the wallet version number somewhere on the overview tab. perhaps in the bottom bar? It'll allow for quick references to the wallet version when interacting with the support staff.

**Comment by Fuzzbawls** [comment]
I personally am against this. The version number is already displayed in abundance and adding it to the overview tab just adds clutter.

**Comment by rejectedpromise** [comment]
moving to project -> https://github.com/PIVX-Project/PIVX/projects/23
