### ISSUE TITLE
PIVX stuck at block 907999

### ISSUE THREAD

**Issue by jetsnation** [PIVX-Project/PIVX#415]
Hello . I have seen other users also stuck on block 907999.  I have followed those instructions but with no luck. I think the issue still remains with users of Mac High Sierra. Here is what I have tried so far....

1)  Copy and backup wallet.dat  file  and Pivx.conf file
2) Get up to date index of chain up until todays date and replace them in ~/Library/Application\ Support/PIVX
3) Delete all other PIVX files
4) Download new Pivx 3.0.5.1 files for Mac High Sierra

Start app.  Loads to block 907999 and for some reason it finds my wallet.dat file even though the only copies should be on a USB

Therefore I went looking for any hidden files that might be lurking.  The PIVX High Sierra version is supposed to store its files on the mac supposedly at :

~.PIVX\    

   instead  of  

  ~/Library/Application\ Support/PIVX

However I cannot find any PIVX files anywhere . What Is the  ~ supposed to represent. Am I missing something ? 

Thanks

**Comment by hussaino3** [comment]
Same problem, downloaded the app on many Windows and Mac computers, all of them stuck at 907999. Have you found a solution atm?

**Comment by VTHokiEE** [comment]
In the terminal if you type ~/.pivx, it would bring you to your data directory on High Sierra, this exact location should be /Users/<user name>/.pivx, remember .pivx is a hidden directory so you need to press "command + shift + ." to show them if you try to navigate there on finder. I believe this issue is being resolved in 3.0.6.

**Comment by jetsnation** [comment]
I finally found the files the other day and swapped an up to date blockchain which remedied the situation. My coins are all there.  However despite all attempts at staking I cant seem to stake any coins.  The arrow is green and everything is "true" in the debug console.  It just doesn't stake its been a few days and nothing. I have lots of PIVX so its not the problem. I'm just about ready to sell all y PiVX and throw in the towel.

**Comment by VTHokiEE** [comment]
GitHub is probably not the right place to discuss staking, you should join the discord for better support: https://discord.gg/pbsV4FQ
However, staking is not something that occurs at set intervals, the payouts are randomly generated and average out over a long period of time. Beyond that depending on how you have your UTXOs configured you may see stakes in bunches (where you see a lot in a very close period of time and then nothing for a while again) or they could be configured to have a better chance at them trickling in. Also, more people are starting to stake with increases the time between stakes for everyone as well.

**Comment by jetsnation** [comment]
Thanks.

**Comment by jonspock** [comment]
This should be fixed with the 3.0.6 release. If you can confirm please close the issue. Thanks
