### ISSUE TITLE
c++11 boost compilation errors

### ISSUE THREAD

**Issue by presstab** [PIVX-Project/PIVX#42]
Boost gets compilation errors when compiling on c++11

``libbitcoin_server.a(libbitcoin_server_a-init.o): In function `copy_file':
/usr/include/boost/filesystem/operations.hpp:384: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'
libbitcoin_wallet.a(libbitcoin_wallet_a-walletdb.o): In function `copy_file':
/usr/include/boost/filesystem/operations.hpp:381: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
make[1]: *** [pivxd] Error 1``

**Comment by jonspock** [comment]
Which boost version and which os, please?
