### ISSUE TITLE
[Feature Request] setstakesplitthreshold value set in Qt GUI

### ISSUE THREAD

**Issue by Sieres** [PIVX-Project/PIVX#424]
### Describe the issue
With the stakeweights now getting bigger, the default setstakesplitthreshold of 2000 is getting less relevant. Could we get a text box in the Qt options or Coin control where we can set the value of setstakesplitthreshold

**Comment by Fuzzbawls** [comment]
Probably a decent feature request, especially considering that the value doesn't require a client restart.

**Comment by Fuzzbawls** [comment]
closed, addressed in #464

**Comment by Sieres** [comment]
ACK
