### ISSUE TITLE
Incorrect port example in masternode.conf 

### ISSUE THREAD

**Issue by Fuzzbawls** [PIVX-Project/PIVX#425]
### Describe the issue
The example created in a fresh `masternode.conf` file references the port `51474`, which is the testnet P2P Port and not the mainnet P2P Port.

#### If so, please list the steps to reproduce below:
1. Start the wallet fresh
2. A `masternode.conf` file is created automatically with an example

### Expected behavior
Example should be using the proper mainnet port of `41472`

### Actual behavior
Example uses the testnet port

### What version of PIVX Core are you using?
v3.0.6 Release

**Comment by Sieres** [comment]
ACK
