### ISSUE TITLE
getstakingstatus all "true" except for stakingstatus field which is false in QT Desktop Client

### ISSUE THREAD

**Issue by Rock-N-Troll** [PIVX-Project/PIVX#427]
Currently there is an issue when trying to stake where all fields in the return of the rpc "getstakingstatus" are true, but the final field of "statingstatus" is false and stays false. 

The QT desktop client is not staking and never displays the staking icon in the bottom right corner of the client. Currently the only solution that reliably works is restarting the client which is a simple fix, but otherwise should not have been an issue in the first place.

This issue has occurred across multiple OS and in particular my own on Raspberry Pi 3 using Raspbian. I only know that this issue occurs on the QT desktop client and I am unsure if it occurs in Command Line Wallet.

Some potential reasons for this issue based on speculation and my own observations:
1. Trying to unlock wallet for staking while still synchronizing with the network
2. Trying to unlock wallet for staking while rebuilding block database

When closing client, the following error message appears in the debug.log file which might be helpful:

...
2017-12-07 14:22:14 ThreadStakeMinter() error
2017-12-07 14:22:14 ThreadStakeMinter exiting
2017-12-07 14:22:14 stakemint thread exit
2017-12-07 14:22:14 PrepareShutdown: In progress...

**Comment by blondfrogs** [comment]
Is this still a problem?

**Comment by rejectedpromise** [comment]
I have run into this issue before, and simply restarting the wallet has resolved it in my cases. I know this is a _work around_ but I think this issue should stay open until a solution is found, and resolves this minor (but annoying) bug

**Comment by presstab** [comment]
Fixed with 2b896d18360ce917c61a36e9f90e67eb3f6d36a4
