### ISSUE TITLE
X not visibles

### ISSUE THREAD

**Issue by purpelado** [PIVX-Project/PIVX#431]
The transactions are not shown, they do not appear ... but they are subtracted from the central balance (they do not appear in Dashboard or in transaction history). Other times, they appear with the icon on the left of "sent" or "X confirmed transactions" ... with a blank icon, if you say nothing ... While this remains, it is also not confirmed in the explorer (although the amount sent is subtracted from the central balance)

For several minutes (about 10 in the worst case) it seems that you have run out of the coins sent and it is lousy.

**Comment by purpelado** [comment]
TX not visibles, sorry

**Comment by Fuzzbawls** [comment]
screenshots would help here

**Comment by Fuzzbawls** [comment]
closing, no further information provided
