### ISSUE TITLE
[Feature Request] Add One Click staking icon to PIVX Core Wallet Overview page

### ISSUE THREAD

**Issue by wholewheatbiscuits** [PIVX-Project/PIVX#432]
### Describe the issue

Tech illiterate person doesn't know he has to un-encrypt the wallet for staking. Tech illiterate person accidentally forgot to check the checkbox for Unlock for anonymization and staking only when unlocking the wallet for staking, and someone with access to his computer steals his funds.

The following feature will help Tech illiterate person secure the network and be less likely to accidentally unlock for Spending when he only wanted to unlock for Staking.

One-click staking icon in Overview tab.

Click the staking icon (when staking is not active and also not unlocked for staking yet, users can be informed with a text bubble above the icon saying staking not active), it asks for password, you type it in, click OK or hit Enter on keyboard, and it will unencrypt for anonymization and staking ONLY.

If want to make it 1 click+password entry staking, then after each keystroke, the wallet will attempt to see if currently typed password unlocks the wallet, but doesn’t warn users about incorrect password each time it attempts to use the currently-typed-in data as the password. But once the full password is typed in, the wallet will succeed in its attempt to use the currently-typed-in data to unlock the wallet for staking/anonymization WITHOUT the user clicking OK, and it can go straight to staking.

And if not too hard, a questionnaire that asks questions required for setting up masternode, and auto-add the correct pivx.conf and masternode.conf lines, settings within wallet, and in-wallet masternode setup guide for the currently-used OS plus VPS, to facilitate masternode setup all in-wallet and hopefully not require any googling or asking for support.

**Comment by Fuzzbawls** [comment]
Please keep issues as narrowly focused as possible (ie, don't try to cover multiple suggestions in a single issue).

In regards to the title of the issue: Better education outside the wallet client would probably be the more elegant solution vs adding a dedicated unlock button/menu just for staking, which (IMHO) just adds clutter and risks further confusion by offering too many options that cover basically the same thing.

**Comment by wholewheatbiscuits** [comment]
"In regards to the title of the issue: Better education outside the wallet client would probably be the more elegant solution vs adding a dedicated unlock button/menu just for staking"

In the overview tab, the Circle with Up arrow icon for "Staking/Multisend" at the bottom right, can be used as the button itself for unlocking staking. There is no need for a dedicated menu just for staking. By reusing this icon as a button for staking, there will not be much additional space taken up. The only additional space I am proposing would be to make use of a little bit of the vast empty space curently above this icon, to provide a few words' worth of text to inform users that this button can be used to unlock the wallet for staking.

"which (IMHO) just adds clutter and risks further confusion by offering too many options that cover basically the same thing."

When staking is not active AND the wallet has not yet been unencrypted for staking, this icon which already exists, should have a small bubble box above it, pointing down towards it, stating something to the effect of: "Click here to unlock wallet for staking.", "here" referring to area of the icon and the bubble box, since the icon itself may be inconveniently small for clicking regularly.

There should be no small bubble box above the icon IF the wallet has already been unencrypted for staking, even if staking is not active, so that the wallet does not accidentally try to inform the user to unencrypt the wallet for staking when it has already been unencrypted for staking, simply because the wallet is not currently staking (this can happen when the wallet is still syncing, or when the available balance becomes 0, such as if the user has all of his balance in a single UXTO, and wins a staking reward).

**Comment by rejectedpromise** [comment]
moving to project -> https://github.com/PIVX-Project/PIVX/projects/23
