### ISSUE TITLE
[Feature Request] Explanation of zPIV autominting at first-time PIVX wallet startup OR new wallet creation (only one or the other)

### ISSUE THREAD

**Issue by wholewheatbiscuits** [PIVX-Project/PIVX#433]
At first-time PIVX wallet startup OR new wallet creation (only one or the other), explanation of zPIV autominting, detailing what it does and reasons to keep it on, and how they should never delete their wallet.dat until HD zPIV wallets arrive. It may or may not also include a button to disable it, but preferably, it should also include instructions on how to disable it, if the user so chooses. But I reiterate, this pop-up should inform people about WHY they should not disable it, and it no longer needs to be popped up anymore after.

Of PIVX's features, I feel zPIV autominting is the one that most requires an explanation, in order to minimize the possibility of people being confused or worried about what is going on.

Below is an example of how we could try to effectively inform people about zPIV autominting, the importance of not disabling it, and brief instructions and explanation about not deleting any wallet.dat files:

**Why does PIVX Core Wallet automint zPIV and charge me for it?**

PIVX's Zerocoin Protocol works by automatically "mixing" zPIV of the same denomination together, making zPIV transactions virtually impossible to trace. The PIVX Core Wallet automatically mints 10% of users' unlocked PIVX balances into zPIV, which ensures there are enough zPIV denominations available to mix and make Zerocoin Protocol effective regardless of manual zPIV minting volume.

To ensure the PIVX network cannot be easily attacked, a 0.01 PIV fee is incurred whenever a zPIV denomination is minted, and from 1 to up to 10 or so denominations may be minted whenever zPIV is auto-minted. All such minting fees are "burned", or removed from the coin supply, so that the loss of value due to zPIV autominting is offset by the gain in value caused by deflation. It is intended that all wallets of the PIVX network should automint with the exception of exchanges.

**Do not delete any wallet.dat files.**

Currently, any wallet.dat files where zPIV minting occurred must be retained, or you may lose your zPIV. Hierarchical-Deterministic zPIV wallets are coming soon, after which the loss of wallet.dat files where zPIV minting ocurred will not result in loss of zPIV.

**Comment by Fuzzbawls** [comment]
I am generally against adding in one-time popups to explain behavior changes, That is precisely what the Release Notes are for, which are accessible outside the program for anyone and everyone to see.

I don't want to set a precedence of one-time popups as then it becomes expected in the future, which would add a sizable amount of bloat to the client over time, not to mention the very off-putting "chain" of popups for new users.

**Comment by wholewheatbiscuits** [comment]
"I am generally against adding in one-time popups to explain behavior changes, That is precisely what the Release Notes are for, which are accessible outside the program for anyone and everyone to see."

Where are the release notes for the zPIV autominting now? I think it is too difficult to obtain the release notes of prior releases, and I believe it is also an unreasonable expectation for people to obtain the release notes of prior releases and do full due diligence by reading through every single one of them.

Additionally, I would like to point out that my one page description of zPIV autominting, and the importance of not deleting wallet.dat files (I learned after I wrote this Feature Request that Presstab has demoed on YouTube zPIV HD wallets and I am guessing it will arrive soon. Of course this note to users can be left out as soon as zPIV HD wallets arrive), are far more detailed than the very limited information that was found within the release notes when zPIV was rolled out. If I recall correctly, the release notes did not mention the importance of not deleting wallet.dat, since zPIV HD wallets was (and is still not) implemented yet.

"I don't want to set a precedence of one-time popups as then it becomes expected in the future"

I believe hundreds of hours of combined work by the PIVX dev and support team may have been avoided if a one-time popup existed and was used as I described at the time of zPIV rollout. I recall a single support person claiming to have helped over a hundred people recover funds they thought they lost due to zPIV rollout. Does that not speak to you of how INADEQUATE the documentation/informing of users of what they need to know to avoid easily avoidable issues?

I recall you yourself saying you had to guide someone through the release notes page via TeamViewer, in order for them to finally see what was in it. I'm sorry, but the fact is, most people aren't going to do due diligence to such a degree, and most people aren't that smart we can make sense of release notes enough that we will add 2+2 together and realize the implications of zPIV autominting (fees being incurred, inaccessibility of funds until adequate number of more mints have occurred after our automints occured, etc). I include myself in that group of people who most of the time won't be able to figure it out by reading a release note, the only reason I realized it was a stroke of unusual logic for me when watching a zPIV demo by Spock, and deciding to ask PIVX channel if fees would be automatically incurred without my express acknowledgement, even though I felt that would be very odd if so.

"which would add a sizable amount of bloat to the client over time"

When zPIV autominting is disabled (which is the plan after zPIV staking rewards exist and will serve as adequate incentive for people to mint and hold zPIV), you can remove the entirety of the mention of zPIV autominting.

When zPIV HD wallets are implemented, you can remove the entirety of the mention of the warning not to delete any wallet.dat files.

"not to mention the very off-putting "chain" of popups for new users."

The pop-up can occur ONLY if a new wallet is created or IF it is a pop-up about prior releases' changes which current users most likely know about.

IF a new wallet is not being created and IF it is a pop-up about prior releases' changes which current users most likely know about, then you can AVOID the pop-up.

IF it is a pop-up about the current/very recent releases' changes which current users most likely MIGHT NOT know about, then regardless of whether or not a new wallet is being created, the pop-up should occur.

And as I said before, as soon as pop-up information is no longer relevant, it should be removed. The purpose of the pop-up is SOLELY to inform people of vitally important things for them to know, which they cannot be reasonably expected to be aware of without such pop-ups. For example, everyone knows not to share their passwords or private keys. Everyone knows not to send funds to random addresses. Everyone knows not to delete ALL of their wallet.dat (keep at least one copy, and you should be fine with HD wallets). Everyone knows not to add lots of zeroes to PIV amount whens ending.

But you have to have been told, or done a lot of research, or be a downright genius, or be telepathic, to know that as soon as you have available balance and unlock your wallet for staking, you will suddenly be bombarded with zPIV Accumulator transactions, telling you you are having funds deducted while you panic. Then when you realize the wallet has done these transactions without your express permission, you feel more relieved, but then you realize you were charged 0.01 PIV for each of these automints, without your express permission. Then you get annoyed, and try to send your funds back, but then soon after, it gets auto-minted back into zPIV because you didn't know about zPIV autominting settings or how to disable it. Then you Google it or complain on PIVX channels, find the answer, and be bewildered about why a cryptocurrency can do such a thing as zPIV autominting without adequately informing you, and why you had to look outside the wallet to be able to find out how to disable such a feature and then navigate through folders to disable the feature (add enablezeromint=0 to pivx.conf).

So I feel we should make use of a pop-up like I described, and hopefully greatly reduce something like the above happening.

**Comment by Fuzzbawls** [comment]
Release notes for past releases are available at https://github.com/PIVX-Project/PIVX/releases and periodically updated in-tree at https://github.com/PIVX-Project/PIVX/tree/master/doc/release-notes.

I firmly believe that the target audience for this suggestion is the very same audience that will blindly click through any popups without reading them. The time investment on the dev side to code and maintain such pop-ups, and the translator's time to translate them is not likely to provide any measurable benefit nor alleviate any meaningful number of support requests.

It does not take a lot of time, nor does it require someone to be a genius or telepathic to spend a couple minutes reading the notable changes section of the release notes.


I can't speak for the rest of the Dev team, but conceptually I have to NACK the idea. If you'd like to submit a pull request that implements your idea it can be reviewed there as well though.

**Comment by turtleflax** [comment]
I very much support this request.  The automint is unique to PIVX and whether you think it is reasonable or not, there is an expectation that crypto software would not do something like this.  When unexpected things happen in software, especially when it deals with your money, it is a bad user experience.  As someone on support answering all the users caught off guard by this, I promise you it would be a significant improvement to the user experience if they were alerted.

You've said you want the user to read the release notes, and while I very much relate to the notion of user responsibility, the fact remains that they don't read the notes.  This again seems to be a unique expectation with the PIVX software that they are not used to with other software.  Perhaps this is a matter of goals for PIVX.  Is the target market limited to the narrow group of people who read github release notes or is it meant for everyone?

As for the autopilot users who click through popups, of course they do exist but the popup would reach more people than github notes.  Additionally, if any users skip it and complain it is far better to be able to refer them to popups in the software they ignored than an expectation to read github release history for several versions.

I understand the objection to bloat, but don't believe this is a slippery slope situation unless you're planning on more automint type features.  In fact, I see it as a marketing opportunity.  You guys work hard on these features and releases, don't you want to show people what you've built?  It's pretty standard in software to have a FirstRun new release message about new features.  For this reason I would support the FirstRun popup and also a mention of automint in places like "Unlock for Staking, anonymization, and automint only"

While I know it would be more work and you'd rather work on cooler features, I would counter that this is a major pain point for PIVX and perhaps holding down the value much lower than it could be.  If this value increased, dev budget could go up to pay you more and also hire more devs so you could focus on what you want to build.

Given the strong opinions on this topic and the fact that PIVX is a community coin, I would encourage that we ask the community.  Both sides could be presented and sentiment could be measured in Discord and other platforms

**Comment by Newar417** [comment]
New to PIVX, but not new to crypto, I would have appreciated some info about this particular feature. Especially as it is on auto out of the box. Contrary to DASH, where you have to initiate the PrivateSend mixing yourself, to give an example. I do not recall any coin wallet that does "things" like this on its own.

**Comment by presstab** [comment]
@Fuzzbawls nobody reads release notes and it is honestly on the border of insane to tell the general public or people that are new to crypto even, that if they use our wallet they have to spend 20 minutes going through and understanding the release notes. Ease of use is a priority.

**Comment by wholewheatbiscuits** [comment]
Thankfully, we now have a notice within the website. I think it will suffice to keep a lot of new users informed about this unique feature.

https://pivx.org/wallet/

**Comment by PIVX-Library** [comment]
can these notifications be held outside the wallet yet be triggered by the wallet? Crazy I know!

**Comment by rejectedpromise** [comment]
moving to project -> https://github.com/PIVX-Project/PIVX/projects/23
