### ISSUE TITLE
[Feature Request] Option for no manual typing/deletion of text in recipient field, only copy+paste

### ISSUE THREAD

**Issue by wholewheatbiscuits** [PIVX-Project/PIVX#434]
Currently, typing in a recipient address to send funds to, can be a very nerve-wrecking experience. A person must take great care not to add or delete any additional text, whether by human error or machine error such as a keyboard that accidentally sends in keys that aren't actually typed (can happen regularly with some keyboards/wireless keyboards), coupled with the task of verifying that the inputted address is correct.

The following option, if enabled, will protect users from the possibility of accidentally adding or deleting text after/before copying recipient address to the Send To field:

Toggle in options that if enabled, will either prevent or warn (only one of the two) users that they have manually inputted text or deleted text via keyboard typing into a Send to address field, and which will neither prevent nor warn users if they use copy and paste to input recipient address into this field. This will protect against fat finger loss of funds, and could probably be enabled by default in the form of PREVENTING (not just warning) manually inputted or deleted text via keyboard, without causing user experience issues, since copy paste is almost always used for the purpose of inputting recipient address.

**Comment by Fuzzbawls** [comment]
Unfortunately, the `paste` event is treated the same as manual input. I don't know of any way to disable one without also disabling the other.

**Comment by wholewheatbiscuits** [comment]
As an alternative, would it be possible to have the wallet detect if there is ever anything but a string of 34 alphanumeric symbols (I think PIVX addresses are always 34 symbols, if not, please let me know, and I can present a different solution) within the input box, and delete the entirely of the text within the input box if so?

For example, when the option is enabled, if the user attempts to type anything in via manual typing, it gets deleted completely and/or users warned, since it won't be 34 alphanumeric symbols all at once. This makes it so the input box always remains empty, unless the user uses copy and paste, and copy+pastes a correct length PIVX address.

If the user inputs a correct string of 34 alphanumeric symbols, and attempts to add or remove anything to the symbols via manual typing, which could be detected by the number of alphanumeric symbols being 33 or less, or 35 or more, then the entire input box can get deleted and/or users warned. Again, only if the option is enabled by the user.

Then as a different alternative to what I just described, how about a Paste button beside the input box, which if pressed, will paste whatever is on the clipboard. And instead of the input box being an input box, it is simply a "Displayed recipient address", which cannot be manually touched or modified by the user, other than by clicking a Paste button. I believe this Paste button should also try to enforce only allowing a correct string of 34 alphanumeric symbols to be used, otherwise it is deleted and/or users warned.

**Comment by rejectedpromise** [comment]
moving to project -> https://github.com/PIVX-Project/PIVX/projects/23
