### ISSUE TITLE
[Feature Request] Protection against CryptoShuffler virus

### ISSUE THREAD

**Issue by wholewheatbiscuits** [PIVX-Project/PIVX#435]
There is a virus that attempts to detect when a user has inputted a Bitcoin address into a Send To address field, and replace what the user has inputted, with the Bitcoin address of the virus maker. This virus has successfully stolen at least $140,000 in Bitcoin (October 31st 2017 prices).

Although a PIVX-specific CryptoShuffler virus probably does not exist right now, it is better to protect against it before we know they exist, if only to deter virus makers from attempting to make PIVX-specific CryptoShuffler viruses, which could harm user experience even if they do not successfully steal PIV.

The following option can offer some protection against CryptoShuffler virus:

Auto-detect sudden override or successive copy pasting of recipient address into Send to field, and warning users they may have the CryptoShuffler virus and to verify the recipient address is correct, if it happens.

https://www.kaspersky.com/blog/cryptoshuffler-bitcoin-stealer/19976/

**Comment by Rock-N-Troll** [comment]
I have already seen this happen to someone on youtube. If this is easy to implement, I agree with you that this should be implemented.

**Comment by Fuzzbawls** [comment]
Monitoring the system's clipboard for changes is a bit out-of-scope for a wallet to be doing, and should instead be handled by antivirus programs which already provide similar functionality.

**Comment by wholewheatbiscuits** [comment]
You're right, sorry. I misunderstood how the CryptoShuffler virus worked.

**Comment by Fuzzbawls** [comment]
closing
