### ISSUE TITLE
"anonymization" is spelled "anonimization" (incorrectly) on 3.0.6

### ISSUE THREAD

**Issue by turnkit** [PIVX-Project/PIVX#437]
English spelling error.  Also the lock is too small - not easily discernable if it's open or closed. Adding some "surprise" / "exclamation" dashes around the lock when it's open - or turning it on it's side and more obviously opening the latch when open, would be a big improvement.

![screen shot 2017-12-13 at 5 59 17 pm](https://user-images.githubusercontent.com/4126167/33972379-3ab4ef46-e043-11e7-8809-df888402fb05.png)

**Comment by Warrows** [comment]
Closed in PR  #452 commit 99a8246f18

**Comment by Fuzzbawls** [comment]
addressed, closing
