### ISSUE TITLE
Feature requests Multisend (% decimals / labels)

### ISSUE THREAD

**Issue by Newar417** [PIVX-Project/PIVX#446]
Would be nice to be able to:

- specify 1.25% for example 

- label the addresses for clarity.

**Comment by blondfrogs** [comment]
labels are now a part of the MultiSend GUI

**Comment by Newar417** [comment]
Thank you for your work! 

Sorry to be a pain, but decimals are not a possibility I suppose?

**Comment by blondfrogs** [comment]
As of right now, we are sticking with whole numbers.
