### ISSUE TITLE
[MultiSig] Numbering Dynamic Screen Elements Issue

### ISSUE THREAD

**Issue by Mrs-X** [PIVX-Project/PIVX#449]
The MultiSignature dialog has several dynamic screen elements (Address/Key, TX Hashes, Destinations, ...) which can be added and deleted if needed.

Newly added elements are numbered, starting with 1, 2, 3, 4, 5...
Adding, deleting and then re-adding confuses this numbering

Steps to reproduce the issue:
1: File -> Multisignature creation...
2: There should by default be 2 Address/Key entries visible, numbered `1:` and `2:`
![multisig1](https://user-images.githubusercontent.com/22873440/34277229-23627800-e6a5-11e7-8053-585742d52aa6.png)

3: Delete the first entry (via the `[-]` symbol)
4: Click on "Add Address / Key" (the `[+]` symbol).

Result:
![multisig2](https://user-images.githubusercontent.com/22873440/34277240-31579fd0-e6a5-11e7-83d8-0f506d4b3179.png)

As you can see, there are 2 lines with the number "2:" now.

**Comment by rejectedpromise** [comment]
Good find! Hopefully this is just a simple change in the logic! I thought it created new list items with list.size() + 1..... but that must not be the case if there are two '2's. I will take a look this weekend!

**Comment by Mrs-X** [comment]
`I thought it created new list items with list.size() + 1`

But that's exactly the problem, when you delete the first entry, the second entry keeps its number (2) and `list.size() == 1`. Adding another entry increases `list.size()` to 2 again :-)

You have to chose the lowest unused(!) number for the new entry.

**Comment by blondfrogs** [comment]
#483
