### ISSUE TITLE
Compilation errors in pivx-3.0.6

### ISSUE THREAD

**Issue by demodun** [PIVX-Project/PIVX#450]
I downloaded pivx-3.0.6.tar.gz

the following error occurs and the compilation stops.

`CXX      test/test_test_pivx-scriptnum_tests.o
test/scriptnum_tests.cpp:13:108: error: narrowing conversion of ‘4294967295u’ from ‘unsigned int’ to ‘long int’ inside { } [-Wnarrowing]
 HAR_MAX, SHRT_MIN, USHRT_MAX, INT_MIN, INT_MAX, UINT_MAX, LONG_MIN, LONG_MAX };
                                                                              ^
Makefile:7238: recipe for target 'test/test_test_pivx-scriptnum_tests.o' failed
make[2]: *** [test/test_test_pivx-scriptnum_tests.o] Error 1
make[2]: Leaving directory '/home/src/compiles/pivx-3.0.6/src'
Makefile:7556: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/src/compiles/pivx-3.0.6/src'
Makefile:611: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1`

**Comment by Fuzzbawls** [comment]
Need information about which OS distro/version this behavior is observed on as per the issue creation guidelines. The fix may be as simple as a precompiler conditional...and actually this looks like a discrepancy in the system's `limits.h` file.

**Comment by demodun** [comment]
I am using lubuntu x86 and my machine is a 32 bit machine.

**Comment by demodun** [comment]
I made the appropriate changes to test_pivx-scriptnum_tests.cpp 
the compilation passed and the 
CXX      test/test_test_pivx-scriptnum_tests.o
has been created.

**Comment by demodun** [comment]
The compilation failed and a new error occured . Maybe it is because I use qt 4.
Here is the error
`qt/multisigdialog.cpp:27:33: fatal error: QtWidgets/QHBoxLayout: No such file or directory
 #include <QtWidgets/QHBoxLayout>
                                 ^
compilation terminated.
Makefile:5495: recipe for target 'qt/qt_libbitcoinqt_a-multisigdialog.o' failed
make[2]: *** [qt/qt_libbitcoinqt_a-multisigdialog.o] Error 1
make[2]: Leaving directory '/home/src/compiles/pivx-3.0.6/src'
Makefile:7556: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/src/compiles/pivx-3.0.6/src'
Makefile:611: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
`

**Comment by Fuzzbawls** [comment]
yes, Qt4 is not supported anymore. Will need to make the configure script more strict about that.

https://github.com/PIVX-Project/PIVX/blob/master/doc/build-unix.md#dependencies-for-the-gui-ubuntu--debian

**Comment by demodun** [comment]
ok... I ll try to intall qt 5 and I will report again.

**Comment by demodun** [comment]
I installed qt 5 and the compilation passed successfully!

Thanks!

The pivx-qt when starting it displays in the console the following warning message (because I use lubuntu)

(pivx-qt:17111): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:23:18: not a number

(pivx-qt:17111): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:23:18: Expected a string.

(pivx-qt:17111): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:815:10: not a number

(pivx-qt:17111): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:815:24: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(pivx-qt:17111): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1953:14: not a number

(pivx-qt:17111): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1953:14: Expected a string.

(pivx-qt:17111): Gtk-WARNING **: Theme parsing error: nautilus.css:50:71: Using one color stop with linear-gradient() is deprecated.

(pivx-qt:17111): Gtk-WARNING **: Theme parsing error: nautilus.css:51:71: Using one color stop with linear-gradient() is deprecated.

(pivx-qt:17111): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:252:14: not a number

(pivx-qt:17111): Gtk-WARNING **: Theme parsing error: gtk-lubuntu.css:252:14: Expected a string.
`

`
