### ISSUE TITLE
PIVX-QT Mac fatal

### ISSUE THREAD

**Issue by yeahoffline** [PIVX-Project/PIVX#451]
#### If so, please list the steps to reproduce below:
1. Download latest PIVX-QT.app for "High Sierra" 
2. Copy it to the Applications folder
3. Start PIVX-QT.app

### Expected behavior
Wallet should open

### Actual behavior
Error: "A fatal error occurred. PIVX can no longer continue safely and will quit.

EXCEPTION: N5boost12interprocess22interprocess_exceptionE       
Permission denied       
pivx in Runaway exception"

### What version of PIVX Core are you using?
pivx-3.0.6.0-High-Sierra-Only

### Machine specs:
- OS: macOS High Sierra
- CPU: 2,8 Ghz Intel Core i7
- RAM: 16 GB 1600 MHz DDR3

**Comment by Fuzzbawls** [comment]
This looks to be an issue with datadir folder permissions

**Comment by Fuzzbawls** [comment]
closing, no further followup
