### ISSUE TITLE
Not staking after computer crash and PIVX core re-indexed database

### ISSUE THREAD

**Issue by AB-Normal1960** [PIVX-Project/PIVX#458]
![not minting zpiv debug_log](https://user-images.githubusercontent.com/29764635/34390529-4cd34152-eb0e-11e7-9669-3641ede544d5.JPG)

![security tab](https://user-images.githubusercontent.com/29764635/34391441-9796aa58-eb13-11e7-9930-2700f4abe39a.JPG)

This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Discord](https://discord.pivx.org).

### Describe the issue:
I was minting zPIV succesfully. Running version 3.0.6. My computer lost power overnight and when I woke up this morning, I restarted PIVX core and it said it had to re-index the database. It did that and re-sync the blockchain, but now the Icon in bottom right of the screen, when I hover over it says, "Staking not active Multisend not active". And I see the error in the debug log (screenshot attached).

### Can you reliably reproduce the issue?
It is happening now.
#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behavior
Tell us what should happen
After it syncs, it should start Staking and the up-arrow icon should not be grey-ed out.

### Actual behavior
Tell us what happens instead
After syncing, the Up-arrow icon is greyed out and when I hover over the icon it says, "Sting not active. Multisend NOT active".

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of PIVX Core are you using? 3.0.6
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.
I installed it from the Windows .exe file.
### Machine specs:
- OS: Windows 10 Pro; Version	10.0.16299 Build 16299
- CPU: Processor	Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz, 2195 Mhz, 2 Core(s), 4 Logical Processor(s)

- RAM: Installed Physical Memory (RAM)	8.00 GB
- Disk size: Size	463.80 GB (497,998,069,760 bytes)
Free Space	70.51 GB (75,708,284,928 bytes)

- Disk Type (HD/SDD): HDD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.
Dropbox ling to Debug.log file:
https://www.dropbox.com/s/r9wvn7ymy19bbdv/debug.log?dl=0

**Comment by Mrs-X** [comment]
The log from your screen-shot refers to zPIV minting, NOT staking (which is something completely different).

Go to "Tools -> Debug Console" and enter the command "getstakingstatus" there and post the result here.

**Comment by AB-Normal1960** [comment]
I followed the advice further another thread. I shut down (gracefully) the
PIVX core program, waited 30 seconds, (actually about 5 minutes), then
restarted the core and after a few minutes it displayed the green arrow and
indicated I am now staking.

Thank you kindly for your time and attention to this matter. Please
consider the issue closed.
I apologize for not updating the status of my issue sooner.

Kind regards,
 John

**Comment by mycoins** [comment]
I am having the same issue and have not been able to stake yet. Here is what the debug message showed
"validtime" : true,
    "haveconnections" : true,
    "walletunlocked" : true,
    "mintablecoins" : true,
    "enoughcoins" : true,
    "mnsync" : true,
    "staking status" : false

**Comment by AB-Normal1960** [comment]
I let it catch up on all the blocks. Then *gracefully* shut down the PIVX
core. Re-booted my computer and re-started the core and after it caught up
again, after about an hour or so, I was staking again.

**Comment by mycoins** [comment]
got it now, thanks so much

**Comment by AB-Normal1960** [comment]
You are very welcome. After this experience I researched how to back-up the
wallet and the Block chain, then saved those files to a separate thumb
drive and to a separate USB hard drive.  I don't have a lot of PIVX now,
But I like this coin.  I would suggest you do your own research on how to
do a proper backup and do that as well. Then, if for some reason your core
program and database crashes, you can rebuild everything and restore it.

Also, When ever you add more PIVX or your zPIV and PIV #'s change, update
your previous backup files where ever you store them.

Cheers! Happy New Year!
