### ISSUE TITLE
Update Readme Needed

### ISSUE THREAD

**Issue by snappysnap** [PIVX-Project/PIVX#470]
### outdated information in the PIVX readme file.
_PIVX is a cutting edge cryptocurrency, with many features not available in most other cryptocurrencies._

- This introduction line could be updated.

**Anonymized transactions using coin mixing technology, we call it Obfuscation.**

- This needs to be updated with Zerocoin (zPIV) information.

**Comment by Warrows** [comment]
@snappysnap I can see what to put about zPIV. What do you envision to replace the introduction line ?

**Comment by danielelis** [comment]
*PIVX is the first of its kind, with many features not available in most other cryptocurrencies.

*Anonymized transactions using zerocoin technology, we call it zPIV.
