### ISSUE TITLE
multisend doesn't work on masternode rewards

### ISSUE THREAD

**Issue by blondfrogs** [PIVX-Project/PIVX#475]

**Comment by EricStanek** [comment]
I've never been able to get it to work either. I presume because the wallet is locked.

**Comment by blondfrogs** [comment]
I will make sure to look into this with a locked and unlocked wallet

**Comment by blondfrogs** [comment]
Results from testing:
In order to get master node rewards to use multisend the following must be true
- The wallet the funds are located must be unlocked
- The wallet the funds are located in must be connected to the pivx network
- The wallet the funds are located in must have multisend enabled

Because most if not all of the pivx masternodes have a controller wallet that holds the funds, and it is not required that this controller wallet be online 24/7, this means that multisends will not occur. In order for the multisends to occur the controller wallet must be connected to the pivx network and unlocked for proof of stake.

**Comment by blondfrogs** [comment]
#477
