### ISSUE TITLE
Move multisignature GUI access from file dropdown to side menu with single button access

### ISSUE THREAD

**Issue by rejectedpromise** [PIVX-Project/PIVX#481]
With the beautiful new GUI merged in, it would be nice to move multisignature access to the side menu. As long as @Mrs-X is in agreement with the move to the side menu. (Not sure if there was other things planned for the extra space or not)

**Comment by Mrs-X** [comment]
Actually that was one of the main reasons to have a vertical menu, more room for stuff.

The question is, will multisig be this wildly use to justify a dedicated menu, and what about signing messages. If we should do this in my opinion both should be on that tab.

But the open question still is, who uses multisig?

**Comment by rejectedpromise** [comment]
@Mrs-X Good point.
I think with that in consideration, I would rather have things like:
* lock/unlock
* backup wallet
* sending/receiving addresses
* some other highly used thing that exists in in the top dropdowns (options?)
