### ISSUE TITLE
Starting Masternode from GUI does not work

### ISSUE THREAD

**Issue by Newar417** [PIVX-Project/PIVX#482]
Tried to start the MN from the GUI. Received a message about invalid IP. 

Started from Debug console, no problem.

### Can you reliably reproduce the issue?
Yes, ever single time when trying to start the MN.

### Expected behavior
The MN should start from GUI.

### Actual behavior
It does not and throws an incorrect error message,

### What version of PIVX Core are you using?
Latest binary

### Machine specs:
Debian stable (remote and local)

**Comment by Sieres** [comment]
Come chat to us on discord https://discord.gg/uAZUhF4

**Comment by rejectedpromise** [comment]
@Sieres has this been resolved through on discord?

**Comment by Mrs-X** [comment]
This is a bug and on my todo-list for ages.
I'll take care of this.

**Comment by Sieres** [comment]
I spoke to him and provided him to the setup guide he should be using, he mentioned he will use that guide and complete the setup. I haven't heard from him since, so I'm going to assume his was able to complete setup of the masternode.

**Comment by Newar417** [comment]
Well, I did not have to start the wallet again, since I started through the console prior to submitting this issue.

If anything, the documentation could be improved. From the main PIVX site, there are eventually two links to setup a MN. Sieres kindly pointed me towards another one in the knowledge base. Those three guides do vary slightly on some points.

**Comment by Fuzzbawls** [comment]
duplicate of #373, going to close this one.
