### ISSUE TITLE
Testnet coins and explorer

### ISSUE THREAD

**Issue by thomsonimjd** [PIVX-Project/PIVX#484]
I would like to know where to request for testnet conis and see  transactions explorer for pivx. I could not join the pivx slack to request for testnet coins due to limit reached.  Please let me know the testnet faucet and it's explorer.

Thanks in advance

**Comment by rejectedpromise** [comment]
@presstab 
[tPIV block explorer](http://www.presstab.pw/phpexplorer/PIVX-T/)
It seems to be down right now, the server just probably need a restart.
I think presstab has access to tPIV as well, but will need to verify with him.

**Comment by thomsonimjd** [comment]
@rejectedpromise thanks, I will request here when I need it.

**Comment by rejectedpromise** [comment]
Closing Issue:
When ready please reach out to us on the [PIVX discord](https://discordapp.com/invite/jzqVsJd) on the development channel when ready for some tPIV.
