### ISSUE TITLE
Missing checksums & signatures for wallet files

### ISSUE THREAD

**Issue by toldenburger** [PIVX-Project/PIVX#486]
I am missing checksums and signatures for the wallet app files.

Possible to add these? 
Would add a lot of security when downloading wallets.

**Comment by Fuzzbawls** [comment]
which download file is this referencing?

**Comment by toldenburger** [comment]
Ah I see now that I totally overlooked the link for the latest release!
My bad.
Installing it as we speak. Love the project!

**Comment by Fuzzbawls** [comment]
forgot this particular issue.

The `SHA256SUMS.asc` file in the release area has been updated to include High Sierra. Closing
