### ISSUE TITLE
Lots of CPU use in the wallet

### ISSUE THREAD

**Issue by Warrows** [PIVX-Project/PIVX#487]
#### If so, please list the steps to reproduce below:
1. Have a few dozens zPIV denominations (several immatures)
1.1. Edit : Enable AutoCombineRewards feature  
2. Close your wallet and wait a few hours
3. Open your wallet

### Expected behavior
Wallet should sync up

### Actual behavior
Wallet sync up to 5 hours late. Then slows down and takes a very long time to catch up. GUI gets to be unresponsive. CPU gets 100% usage on one core.

### What version of PIVX Core are you using?
Master (commit 9e2ed8f).

### Machine specs:
- OS: Debian 9
- CPU: intel i5-4460
- RAM: 8 Go
- Disk size: 1To+
- Disk Type (HD/SDD): HDD

### Any extra information that might be useful in the debugging process.
Opening the wallet with an empty wallet.dat allows to catch up the chain pretty quick. Then, opening the original wallet.dat (with several zPIV denoms) is much less a problem since there is no more synchronization to do.
But the symptoms will come back every minute or so (each block ?). I strongly suspect that it's coming from the wallet checking for zPIV spends or mint in the newer blocks.

**Comment by presstab** [comment]
Anything in the debug log that is relevant?

**Comment by Warrows** [comment]
Ah yes absolutely, I was going after the wrong culprit.
`2018-01-14 11:38:20 ProcessNewBlock : ACCEPTED in 29881 milliseconds with size=494`
`2018-01-14 11:38:20 UpdateTip: new best=d40202aecdb5cb627e56a664206429a16ba6a1aac2f7fa47cd3cb243440af024  height=349096  log2_work=66.576562  tx=915255  date=2018-01-14 05:53:05 progress=0.999935  cache=51`
`2018-01-14 11:38:20 AddToWallet 4d96e036061e5f07e605faa0c25808c798f73646675c00c588f04ab867fe2791  new`
`2018-01-14 11:38:35 keypool reserve 70`
`2018-01-14 11:38:35 keypool return 70`
`2018-01-14 11:38:50 AutoCombineDust createtransaction failed, reason: Transaction too large`
It looks like it has to do with the AutoCombineDust feature I enabled and not zPIV. I have hundreds of relatively small incoming TX.

**Comment by Fuzzbawls** [comment]
Ahh yes, `autocombinedust` is a very busy bee when enabled on a wallet with many many transactions below it's threshold, at least until it can "clean up" all the UTXOs.

**Comment by Warrows** [comment]
@Fuzzbawls in fact we are not talking "busy for some time" but "busy for ever" here. I waited for more than 10 hours for it to stop before posting this issue.
`2018-01-14 11:38:50 AutoCombineDust createtransaction failed, reason: Transaction too large`
The transactions are never created and `autocombinedust` loops for ever trying to make them happen.
I have a fix ready in PR #488.

**Comment by cevap** [comment]
I assume that has to do with qt build, can you reproduce the same with daemon? I assume you did run only QT version. How does your cpu look when running daemon compared to qt?
