### ISSUE TITLE
Scaling issue with Core wallet.

### ISSUE THREAD

**Issue by pivxslimjim** [PIVX-Project/PIVX#489]
This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Discord](https://discord.pivx.org).

### Describe the issue
"Installed the wallet app on my PC, but the application scaling is off - the text throughout the application is way too small, if not unreadable. My computer has a 17", 3820x2160 monitor, and I have application scaling set to 250% in my computer's display settings, but this does not seem to have any effect on the scaling within the main application, minus a few of the dropdown menus and options within the settings window."
### Can you reliably reproduce the issue?
Yes
### Expected behavior
Tell us what should happen
It should scale.

### Actual behavior
Tell us what happens instead
Isn't scaled correctly.
### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of PIVX Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.
306

Please see https://github.com/PIVX-Project/PIVX/issues/228 for same issue in past.

**Comment by danielelis** [comment]
If your using Windows, Control Panel -> Screen Resolution. Adjust accordingly.  
Also for text size, Control Panel -> Fonts, makes font larger in Transactions tab.

**Comment by Mrs-X** [comment]
I just played around with a 4K monitor, no matter what you do there's always something wrong or doesn't have enough space and screen elements are overlapping and issues like this.

Most of it comes from the CSS, but there are other problems also.
Not a quick fix possible, but it should be addressed somewhere in the future.

**Comment by random-zebra** [comment]
Old GUI. Closing
