### ISSUE TITLE
pivx-qt crashed after setting passphrase

### ISSUE THREAD

**Issue by joshpurvis** [PIVX-Project/PIVX#492]
### Describe the issue

I was running the binary (pivx-qt) in the linux release: pivx-3.0.6-i686-pc-linux-gnu.tar.gz. I added some coins to my brand new wallet (also a new blockchain recently sync'd), then proceeded to set a passphrase. I entered the passphrase hit enter, it warned me that if I lost it yatta yatta, when I hit ok to this box, the process abruptly crashed. However, when I opened it again my passphrase had  successfully been set.

### Can you reliably reproduce the issue?

Haven't tried yet, as I now have coins in my wallet, and don't want to risk it.

### What version of PIVX Core are you using?

Official binary: pivx-3.0.6-i686-pc-linux-gnu.tar.gz

### Machine specs:
- OS: Linux ubuntu 14.04
- CPU: AMD FX 8350
- RAM: 32gb crucial
- Disk size: 512Gb
- Disk Type (HD/SDD):  SSD

I'm running i3 window manager and also had google-chrome and urxvt running.

Information that may or may not be relevant: I had `QT_SELECT` env var set to a binary of qt version 5.2.1 when I launched pivx-qt. I don't know if that matters in the case of a binary.

**Comment by joshpurvis** [comment]
Here's the piece of the debug.log file where it crashed:

```
2018-01-17 04:57:22 ProcessNewBlock : ACCEPTED in 20 milliseconds with size=1815
2018-01-17 04:58:23 Encrypting Wallet with an nDeriveIterations of 229591
2018-01-17 04:58:27 CWallet::NewKeyPool wrote 1000 new keys
2018-01-17 04:58:27 CDB::Rewrite : Rewriting wallet.dat...
2018-01-17 04:58:34 opencon thread interrupt
2018-01-17 04:58:34 msghand thread interrupt
2018-01-17 04:58:34 dumpaddr thread stop
2018-01-17 04:58:34 addcon thread interrupt
2018-01-17 04:58:34 ThreadStakeMinter() error 
2018-01-17 04:58:34 ThreadStakeMinter exiting,
2018-01-17 04:58:34 stakemint thread exit
2018-01-17 04:58:34 net thread interrupt
2018-01-17 04:58:34 PrepareShutdown: In progress...
2018-01-17 04:58:34 StopNode()
2018-01-17 04:58:34 tor: Thread interrupt
2018-01-17 04:58:34 torcontrol thread exit
2018-01-17 04:58:34 ERROR: Read : Failed to open file /home/josh/.pivx/mncache.dat
2018-01-17 04:58:34 ERROR: Read : Failed to open file /home/josh/.pivx/budget.dat
2018-01-17 04:58:34 ERROR: Read : Failed to open file /home/josh/.pivx/mnpayments.dat
2018-01-17 04:58:34 Shutdown: done
2018-01-17 04:58:44 
```

**Comment by rejectedpromise** [comment]
```
2018-01-17 04:58:34 ERROR: Read : Failed to open file /home/josh/.pivx/mncache.dat
2018-01-17 04:58:34 ERROR: Read : Failed to open file /home/josh/.pivx/budget.dat
2018-01-17 04:58:34 ERROR: Read : Failed to open file /home/josh/.pivx/mnpayments.dat
```
My initial thoughts would be a permissions issue.
If you issue `ls -al ~/.pivx/` the owner should be `josh`
i.e. :
```
-rw-r-----  1 josh josh  7236268 Jan 17 17:47 budget.dat
-rw-r-----  1 josh josh 11771828 Jan 17 17:47 mncache.dat
-rw-r-----  1 josh josh  4530426 Jan 17 17:47 mnpayments.dat
```
or similar (could potentially be `-rw-r-----  1 josh root` or other)

> I added some coins to my brand new wallet (also a new blockchain recently sync'd)

I often run into this kind of error when using root to move files between users/loading from a chain snapshot. 

Let me know if that helps!

**Comment by rejectedpromise** [comment]
@joshpurvis have you had time to look into/try my comment above?

**Comment by joshpurvis** [comment]
I bootstrapped the long and slow way.. regardless, the permissions look fine:
```
-rw-------   1 josh josh      61 Jan 20 19:13 budget.dat
-rw-------   1 josh josh      86 Jan 20 19:13 fee_estimates.dat
-rw-------   1 josh josh 1908211 Jan 20 19:13 mncache.dat
-rw-------   1 josh josh 3225043 Jan 20 19:13 mnpayments.dat
-rw-------   1 josh josh   88400 Jan 20 19:13 peers.dat
-rw-------   1 josh josh  446464 Jan 20 19:13 wallet.dat
```

I was able to reproduce it though. Try this.. 

1. mkdir temp && mv *.dat temp
2. Start pivx-qt
3. While it's syncing the dat files for the masternode winners, try to encrypt the wallet. 

```
2018-01-21 00:13:36 opencon thread interrupt
2018-01-21 00:13:36 addcon thread interrupt
2018-01-21 00:13:36 dumpaddr thread stop
2018-01-21 00:13:36 ThreadStakeMinter() error 
2018-01-21 00:13:36 ThreadStakeMinter exiting,
2018-01-21 00:13:36 stakemint thread exit
2018-01-21 00:13:36 msghand thread interrupt
2018-01-21 00:13:36 net thread interrupt
2018-01-21 00:13:36 PrepareShutdown: In progress...
2018-01-21 00:13:36 StopNode()
2018-01-21 00:13:36 tor: Thread interrupt
2018-01-21 00:13:36 torcontrol thread exit
2018-01-21 00:13:36 ERROR: Read : Failed to open file /home/josh/.pivx/mncache.dat
2018-01-21 00:13:36 ERROR: Read : Failed to open file /home/josh/.pivx/budget.dat
2018-01-21 00:13:36 ERROR: Read : Failed to open file /home/josh/.pivx/mnpayments.dat
2018-01-21 00:13:36 Shutdown: done
```

Maybe there's two threads trying to get a lock to the same file?

This isn't blocking me in anyway, just wanted to try to help out with the project. So feel free to close this issue whenever you feel necessary.

Thanks!

**Comment by rejectedpromise** [comment]
We definitely appreciate you bringing it up and providing useful information! Rather than simply, the wallet crashed! What do i do?? (you'd be surprised how many of those show up)
I am going to leave this open for the other devs to take a look, since this seems IMO a valid issue. Thank you

**Comment by Sieres** [comment]
That's the normal process when setting a new passphrase for the wallet. 

When you do it via the command line, the yadda yadda you mentioned above actually says the wallet will need to be closed.

**Comment by Sieres** [comment]
Just reread and you did it via the gui. Even still, the same will apply. The wallet will close When you set the paraphrase.

Looking at those logs, it doesn't look very graceful when doing it though.

**Comment by rejectedpromise** [comment]
Sieres is correct. Closing the issue, but am still going to research why the log shows `ERROR` on regular operations. Thanks @sieres

**Comment by joshpurvis** [comment]
@Sieres I understand that if you click "Ok" the wallet restarts per the message. However in the case above, it closes before the message even pops up. It's definitely a crash, and a new user wouldn't understand what happened.

**Comment by vkconsult** [comment]
I'm running pivxd and get a similar error and crash. Not sure if this is the right place thread, but the issue seems similar.
Running PIVX Core 4.3.0 on Linux using WSL2 on a Windows machine, configured for regtest.

```
xxx@xxx:/mnt/c/Users/xxxxxx/pivxtest$ pivxd -datadir=cust/node
PIVX version v4.3.0 (release build) (2020-09-27 02:02:41 -0700)
InitParameterInteraction : parameter interaction: -bind or -whitebind set -> setting -listen=1
Using RdRand as an additional entropy source
Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
Default data directory /home/xxx/.pivx
Using data directory /mnt/c/Users/xxxxxx/pivxtest/cust/node/regtest
Using config file /mnt/c/Users/xxxxxx/pivxtest/cust/node/pivx.conf
Using at most 125 connections (1024 file descriptors available)
Using 32 MiB out of 32 requested for signature cache, able to store 1048576 elements
Using 16 threads for script verification
scheduler thread start
Error: Cannot find the Sapling parameters in the following directory:
"/home/xxx/.pivx-params"
Please run 'sapling-fetch-params' or './util/fetch-params.sh' and then restart.
Error: Cannot find the Sapling parameters in the following directory:
"/home/xxx/.pivx-params"
Please run 'sapling-fetch-params' or './util/fetch-params.sh' and then restart.
Binding RPC on address 0.0.0.0 port 8332 failed.
HTTP: creating work queue of depth 16
HTTP: starting 4 worker threads
Using wallet wallet.dat
init message: Verifying wallet...
CDBEnv::Open: LogDir=/mnt/c/Users/xxxxxx/pivxtest/cust/node/regtest/database ErrorFile=/mnt/c/Users/xxxxxx/pivxtest/cust/node/regtest/db.log
Bound to 0.0.0.0:51476
Cache configuration:
* Using 12.5MiB for block index database
* Using 29.9MiB for chain state database
* Using 57.6MiB for in-memory UTXO set
Shutdown requested. Exiting.
PrepareShutdown: In progress...
ERROR: Read : Failed to open file /mnt/c/Users/xxxxxx/pivxtest/cust/node/regtest/mncache.dat
ERROR: Read : Failed to open file /mnt/c/Users/xxxxxx/pivxtest/cust/node/regtest/budget.dat
ERROR: Read : Failed to open file /mnt/c/Users/xxxxxx/pivxtest/cust/node/regtest/mnpayments.dat
scheduler thread interrupt
Shutdown: done
```
