### ISSUE TITLE
[Qt] Make "For anonymization and staking only" checked by default

### ISSUE THREAD

**Issue by realuser** [PIVX-Project/PIVX#515]
This is a feature request.  In at least a few other staking wallets (Qtum for example), when you click on `Settings->Unlock Wallet...` the checkbox to unlock the wallet only for staking is already pre-checked.

I think this should be pre-checked in PIVX too as it may be the most common behavioral path (it is for me at least).  Also this would make the default more secure than the current default.

### What version of PIVX Core are you using?
PIVX Core version v3.0.6 (64-bit)

**Comment by Mrs-X** [comment]
I'll do that.

**Comment by Fuzzbawls** [comment]
Just so it is documented here:

I think it would be wise to use request state information instead of a blanket "default" when calling the GUI's unlock wallet dialog so that the state of the checkbox can be set programatically.

**Comment by danielelis** [comment]
GUI's unlock wallet dialog with less than 1 PIV 	→ unchecked box
GUI's unlock wallet dialog with more than 1 PIV 	→ checked box 
GUI's unlock wallet dialog with masternodes 	        → unchecked box

**Comment by Warrows** [comment]
I guess we can close this since #521 is merged and #553 tracks the next step?

**Comment by Mrs-X** [comment]
Yep, I'll close it.
