### ISSUE TITLE
[Wallet] Receive address management is not user friendly

### ISSUE THREAD

**Issue by pmatulis** [PIVX-Project/PIVX#516]
Installed v. 3.0.6 of the wallet from https://pivx.org/wallet/ . It looks nice except the bit about receiving addresses. That's absolutely awful:

 1. In every wallet I've used when you click on a Receive tab I see the receive address. But not here. I suggest the wallet stay with expected behaviour.

 1. In the Receiving tab, there are 3 optional fields (?). Fine. Then you can hit 'Request payment'. I did this thinking it would yield my receive address. It **appears** to. But it's not clear (!).

 1. Cancelling out of that dialog I see that the address is now listed, yet with 'no label'; 'no message'; and 'no amount'. This doesn't seem right. I am able to Remove it. I monkey around a few more times thinking I may have done something wrong. No, but I'm able to remove them all. OK.

 1. I then discovered 'File > Receiving addresses...'. There I see I have a default address but it doesn't have a label (suggestion: call it 'default'). Argh. I also see a whole bunch of addresses that I *thought* were removed, but here they are.

 1. In the same dialog, I hit 'New' and the dialog shows two fields: label and then one with the instructions "Enter a PIVX address". Excuse me? I want to make a **new** address! Confusing.

 1. Still in the same place I somehow decide to just put in a label and click 'OK'. It works! Later I discovered that I don't even need a label. Confusing.

 1. Still in the same place, after having clicked 'OK' several times I now have a dozen keys listed, some with the same label: 'new', 'test', 'test', etc. Should it accept duplicate labels? Probably not. Anyway, the worst is that I do not see any way to remove them. Frustrating. And ugly.

**Comment by Fuzzbawls** [comment]
1. This was the behavior of bitcoin prior to version 0.10. The receive tab is now for creating payment requests.

2. Addresses generated by creating a payment request are addresses you can use to receive funds.

3. Payment requests are not required to have a 'label', 'message', nor 'amount'...all 3 fields are optional.

4. 'no label' **is** the default label unless explicitely specified. labels can be changed at any time. Further, receiving addresses are never removed from the wallet. You can remove a payment request from the list, but the address it used is not removed from the wallet.

5. Check the tooltip, it says that the address field can only be modified for **sending** addresses.

6. Labels are always optional

7. Labels aren't required to be unique, nor required at all, they are arbitrary. Again, receiving addresses aren't ever removed from the wallet.

**Comment by pmatulis** [comment]
Yes, you have an answer for everything: "This is the way it is". I'm providing feedback in terms of UX: it's **bad**.

**Comment by Fuzzbawls** [comment]
Just answering your points...no need to be rude

**Comment by rejectedpromise** [comment]
NACK in favor of payment requests over address list
