### ISSUE TITLE
[invalid] Code to mine genesis block not working

### ISSUE THREAD

**Issue by therealredvoid** [PIVX-Project/PIVX#517]
Tried this code from http://dillingers.com/blog/2015/04/18/how-to-make-an-altcoin/  : 
```c++
hashGenesisBlock = uint256("0x01")
if (true && genesis.GetHash() != hashGenesisBlock)
{
     Logprintf("recalculating params for mainnet.\n");
     Logprintf("old mainnet genesis nonce: %s\n", genesis.nNonce.ToString().c_str());
     Logprintf("old mainnet genesis hash:  %s\n", hashGenesisBlock.ToString().c_str());
     // deliberately empty for loop finds nonce value.
     for(genesis.nNonce == 0; genesis.GetHash() > bnProofOfWorkLimit; genesis.nNonce++){ } 
     Logprintf("new mainnet genesis merkle root: %s\n", genesis.hashMerkleRoot.ToString().c_str());
     Logprintf("new mainnet genesis nonce: %s\n", genesis.nNonce.ToString().c_str());
     Logprintf("new mainnet genesis hash: %s\n", genesis.GetHash().ToString().c_str());
}
```

that code gives out this error when i try to  **make** http://prntscr.com/i6ogju

Disclaimer : I'm a student learning crypto. 
### Machine specs:
- OS: Ubuntu 16.04
- CPU: 8 Cores
- RAM: 7.2 GB
- Disk size: 20 GB
- Disk Type (HD/SDD): SDD

**Comment by Mrs-X** [comment]
According to your screenshot you have a very basic syntax error copy and pasted into your new code, means you're most probably not only learning crypto, but also learning C/C++.

Your link to this how-to-make-an-altcoin site is using Bitcoin as example, and PIVX is similar, but often quite different to Bitcoin. And some of those differences are non-trivial, means hard to understand if you're a beginner.

My advice: 

- go through this how-to using Bitcoin, NOT PIVX,  to have a chance to get it running.
- once you get it running try to understand what the code is doing, especially the part where the genesis block is build (it's in chainparams.cpp). Don't just read it, understand it!
- now you're ready to locate the same code in the PIVX repository. It's quite different to Bitcoins code. Try to understand the differences, and adapt what you've learned from Bitcoin.
- now you're ready to actually implement the changes to create a  new altcoin based on PIVX.

It's quite some work, lots of trial and error and often you might be tempted to just ask someone else when you're stuck somewhere.
But it's essential to UNDERSTAND what you're doing, not just copy and paste code from someone else .
I'll leave this issue open for a couple of days or so, so please bookmark it so you can find it again once it's closed.

**Comment by dsqr** [comment]
Kudos to @Mrs-X for such a positive reply to a kind of newb-ish request.

Great spirit. Keep it!

**Comment by therealredvoid** [comment]
Thank you so much for the reply! I am following your advice now. 

P.S ; I found this https://www.dash.org/forum/threads/guide-to-forking-dash-up-to-the-genesis-block.21300/#post-157033 - Since PIVX is a fork of dash. I noticed on the mentioned pull request of devnet as seen here shows the following code around it. Simple question about it however; 

`+        genesis = CreateGenesisBlock(1417713337, 1096447, 0x207fffff, 1, 50 * COIN);  // code to generate genesis block? 
 +        consensus.hashGenesisBlock = genesis.GetHash();
 +        assert(consensus.hashGenesisBlock == uint256S("0x000008ca1832a4baf228eb1553c03d3a2c8e02399550dd6ea8d65cec3ef23d2e"));
 +        assert(genesis.hashMerkleRoot == uint256S("0xe0028eb9648db56b1ac77cf090b99048a8007e2bb64b68f092c03c7f56a662c7"));
 +
 +        devnetGenesis = FindDevNetGenesisBlock(consensus, genesis, 50 * COIN);` // finds the block to store? 

Does this apply? Also the script /lhartikk/GenesisH0/ on github seems to work great for users, however it uses SHA256 algo, and PIVX's algo is different, does this matter? 

I'm learning and understanding, i'm far more interested in PIVX as it is for bitcoin, and will be comparing files further in detail to learn more. Also learn basic C/C++. I really appreciate your positive response @Mrs-X.

**Comment by Mrs-X** [comment]
> Also the script /lhartikk/GenesisH0/ on github seems to work great for users, however it uses SHA256 algo, and PIVX's algo is different, does this matter?

Of course it does matter. 
Bitcoin, Dash and PIVX each have different hashing algorithms, so the hashing results are different.
Just have a closer look at the individual implementations of `GetHash()` for each currency.

**Comment by therealredvoid** [comment]
> Just have a closer look at the individual implementations of GetHash() for each currency.
Didn't help, love.
