### ISSUE TITLE
Incomplete DNS Seeder coding

### ISSUE THREAD

**Issue by Fuzzbawls** [PIVX-Project/PIVX#52]
https://github.com/PIVX-Project/PIVX/blob/master/src/chainparams.cpp#L144-L146

```
        vSeeds.push_back(CDNSSeedData("coin-server.com", ""));
        vSeeds.push_back(CDNSSeedData("s3v3nh4cks.ddns.net", ""));
        vSeeds.push_back(CDNSSeedData("178.254.23.111", ""));
```

The 3 lines referenced here are incomplete. The empty quoted string being pushed to CDNSSeedData is supposed to be the FQDN addresses of the seeder (with the first quoted string acting as an identifier).

Simple enough to fix by filling in the second set of quotes, ex:

```
        vSeeds.push_back(CDNSSeedData("coin-server.com", "coin-server.com"));
        vSeeds.push_back(CDNSSeedData("s3v3nh4cks.ddns.net", "s3v3nh4cks.ddns.net"));
        vSeeds.push_back(CDNSSeedData("178.254.23.111", "178.254.23.111"));
```

*Note: the third entry, while it "works" given an IP address, is considered a non-standard DNS request.

**Comment by PIVX-Project** [comment]
Updated the DNS Seeds.. :P Thanks!!
