### ISSUE TITLE
[Feature Request] Require a fully unlocked wallet to submit budget proposals

### ISSUE THREAD

**Issue by Sieres** [PIVX-Project/PIVX#522]
### Describe the issue
When submitting a proposal, it is possible to do so from a wallet that is partially unlocked (for staking only). 

#### If so, please list the steps to reproduce below:
1. Unlock wallet for staking
2. Submit preparebudget

### Expected behavior
Fully unlocked wallet to spend any piv

### Actual behavior
preparebudget successful with only partially unlocked wallet

### What version of PIVX Core are you using?
3.0.6

**Comment by Mrs-X** [comment]
Yeah, the lock/unlock heuristic is a bit strange to say it nicely.
I'll some changes at that end anyway, so I have a look at this as well.

**Comment by Fuzzbawls** [comment]
This was done in `3.1.0`, closing
