### ISSUE TITLE
Unable to compile wallet in MAC 10.13

### ISSUE THREAD

**Issue by headhunter911** [PIVX-Project/PIVX#527]
Following the directions from the doc's I am unable to compile the Mac wallet in 10.13 I end up with the following error:

configure: error: Detected LibreSSL: This is NOT supported, and may break consensus compatibility!

**Comment by headhunter911** [comment]
Was able to fix it using the following compile command.  Please update docs!

./configure LDFLAGS='-L/usr/local/opt/openssl/lib' CPPFLAGS='-I/usr/local/opt/openssl/include' PKG_CONFIG_PATH='/usr/local/opt/openssl/lib/pkgconfig' --with-gui=qt5

**Comment by Warrows** [comment]
Are you using openssl 1.0 or 1.1 ?
It looks like it's the same issue than #149 which is addressed in PR #447.

**Comment by headhunter911** [comment]
Hmm, I'll try to compile with those and let you know if it fixes it. thanks

**Comment by tofutim** [comment]
@headhunter911 I'm trying to compile in 10.13 as well, but I'm stuck at autogen.sh with glibtoolize issues:

```
/usr/local/bin/glibtoolize: line 406: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 2513: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 2513: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 3601: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 3845: /usr/local/Library/ENV/4.3/sed: No such file or directory
/usr/local/bin/glibtoolize: line 861: /usr/local/Library/ENV/4.3/sed: No such file or directory
: putting auxiliary files in '.'.
: copying file './ltmain.sh'
/usr/local/bin/glibtoolize: line 3771: /usr/local/Library/ENV/4.3/sed: No such file or directory
configure.ac:45: error: required file 'build-aux/ltmain.sh' not found
autoreconf: automake failed with exit status: 1
```
did you ever run into anything like that?

**Comment by tofutim** [comment]
When I check the openssl version on my Mac, I get

![image](https://user-images.githubusercontent.com/157766/35960552-ebb5d782-0c5e-11e8-889f-7f42d013ba0a.png)

configure ends with `configure: error: Detected LibreSSL: This is NOT supported, and may break consensus compatibility!` even with changes from @Warrows pull request.

**Comment by Warrows** [comment]
@tofutim That's strange because this message should not exist after my changes in #447. You should get `configure: error: Detected unsupported SSL version: This is NOT supported, and may break consensus compatibility!` instead.

Anyway, you can compile as you did, using depends, or passing `--with-libressl` argument (`--with-unsupported-ssl` with my changes). But as it's written, this options are possibly risky, so better use depends like you did.

**Comment by tofutim** [comment]
I might not have pulled the first time.
https://github.com/tofutim/pivx/tree/develop

When I run configure, I do see `configure: error: Detected unsupported SSL version: This is NOT supported, and may break consensus compatibility!`

**Comment by Warrows** [comment]
Yeah, that's what you should get. Maybe I should add something about using `--with-unsupported-ssl` argument? Anyway in your case, even without my changes, the message is legit since your system is using libressl. However the changes should make the compilation with this argument possible while it was failing before.

Still, safest option right now: using depends.

**Comment by Fuzzbawls** [comment]
I'm not quite sure compiling `depends` is working under Sierra/High Sierra...I don't have such operating systems on hand to test/verify.

outside of `depends` however, you can install a specific version of OpenSSL via homebrew and pass on the relevant compiler/linker/pkg-config flags to `configure`

```bash
brew install openssl@1.0
```

followed by: 
```bash
LDFLAGS='-L/usr/local/opt/openssl/lib' CPPFLAGS='-I/usr/local/opt/openssl/include' PKG_CONFIG_PATH='/usr/local/opt/openssl/lib/pkgconfig' ./configure
```

should probably do the trick. you can also export those as environment variables by adding them to your `.profile`, `.bash_profile`, or even `.bashrc` files

**Comment by Fuzzbawls** [comment]
closing, no further response
