### ISSUE TITLE
Mac 10.13 warning: 'OSMemoryBarrier' is deprecated

### ISSUE THREAD

**Issue by tofutim** [PIVX-Project/PIVX#534]
### Describe the issue
When compiling for Mac, a warning....
```make
./port/atomic_pointer.h:55:3: warning: 'OSMemoryBarrier' is deprecated: first deprecated in macOS 10.12 - Use
      std::atomic_thread_fence() from <atomic> instead [-Wdeprecated-declarations]
  OSMemoryBarrier();
  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/libkern/OSAtomicDeprecated.h:749:9: note: 
      'OSMemoryBarrier' has been explicitly marked deprecated here
void    OSMemoryBarrier( void );
```

May also want to look here where they deal with it https://github.com/google/leveldb/pull/422

#### If so, please list the steps to reproduce below:
1. autogen
2. configure
3. make!

### Expected behavior
No warnings...

### Actual behavior
Warnings

### Machine specs:
- OS: OSX 10.13

**Comment by Fuzzbawls** [comment]
need to see further up in your compile log

**Comment by sabhiram** [comment]
This is a warning that got patched into OSX 10.12 and above (I think), which nudges the user to move to `std::atomic` in place of the `OSMemoryBarrier()`.

Fixing this needs some cross platform insight as it might affect different platforms differently.

**Comment by mbahfauz** [comment]
no update ?

**Comment by gjhiggins** [comment]
Found elsewhere (can't recall where), contributed _en passant_, prolly best published as a patch.
```
diff --git a/src/leveldb/port/atomic_pointer.h b/src/leveldb/port/atomic_pointer.h
index 9bf091f75..d1698ef30 100644
--- a/src/leveldb/port/atomic_pointer.h
+++ b/src/leveldb/port/atomic_pointer.h
@@ -52,7 +52,10 @@ namespace port {
 // Mac OS
 #elif defined(OS_MACOSX)
 inline void MemoryBarrier() {
-  OSMemoryBarrier();
+#if defined(LEVELDB_ATOMIC_PRESENT)
+  std::atomic_thread_fence(std::memory_order_seq_cst);
+#else  OSMemoryBarrier();
+#endif  // defined(LEVELDB_ATOMIC_PRESENT)
 }
 #define LEVELDB_HAVE_MEMORY_BARRIER
 
```
