### ISSUE TITLE
QT Wallet Build Bombs on Make

### ISSUE THREAD

**Issue by buddilla** [PIVX-Project/PIVX#546]
Following instructions here:
https://github.com/PIVX-Project/PIVX/blob/master/doc/build-osx.md#use-qt-creator-as-ide

I have tried:
./autogen.sh
./configure --with-gui=qt5 --enable-debug

and just:
./configure --with-gui=qt5 --enable-debug

at least 9 times using different clangs and debuggers

I am able to build the daemon and the gui executable, not to be confused with pivx-qt.app, in the terminal. (Before someone asks why don't you use the executable instead? It is not acceptable for deployment.) 

### Expected behavior
builds

### Actual behavior
Starting: "/usr/bin/make" all
make: *** No rule to make target `all'.  Stop.
23:48:14: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project pivx-qt (kit: Desktop Qt 5.10.0 clang 64bit)

Pivx Master src

Self Qt Compile

### Machine specs:
- OS: macOS 10.13
- CPU: 2.6 GHz Intel Core i7
- RAM: 16 GB 1600 MHz DDR3
- Disk size: 1TB
- Disk Type HD/SSD Hybrid

**Comment by Warrows** [comment]
That's `./configure ...` and not `/configure ...`.

**Comment by buddilla** [comment]
yes yes that was a typo in typing the above out. the issue still exists with ./configure

**Comment by Fuzzbawls** [comment]
closing, no further response
