### ISSUE TITLE
3.0.6 wallet windows 10 home fatal error opening wallet

### ISSUE THREAD

**Issue by ethanedison** [PIVX-Project/PIVX#547]
#### If so, please list the steps to reproduce below:
1. open pixv wallet 3.0.6 on windows 10 home and windows defender automatically attaches to wallet to scan for virus
2. pivx wallet is loading and loading block index for a minute and crashes 
3.  pop up says- "fatal internal error occurs".  
4. deleted all wallets and downloaded again.   same issue happens over and over.

 all previous versions of Pivx wallet worked including  other wallets staking 24/7 on blockchain with no issue using the updated windows defender for windows 10 HOME version

### Expected behavior
Tell us what should happen: =  wallet should open and update the blockchain

### Actual behavior
Tell us what happens instead:  wallet crashes  "fatal error"

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of PIVX Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

### Machine specs:
- OS: windows 10 home
- CPU:  Intel core i5 -8250U
- RAM:   12 gb
- Disk size: 1TB
- Disk Type (HD/SDD):  

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by Warrows** [comment]
We are going to need your debug.log. And if you could have a check on your antivirus to see if its forcibly killing pivx that would be nice. 
By the way, have you been running this version of the wallet before without problem?

**Comment by WagerrTor** [comment]
check if it is connected to this [issue](https://github.com/PIVX-Project/PIVX/issues/564). We got reports too that some wallets for some users crash.

**Comment by Warrows** [comment]
No answer for several month and the version used (3.0.6) is no longer supported. Closing the issue.
