### ISSUE TITLE
snap builds

### ISSUE THREAD

**Issue by WagerrTor** [PIVX-Project/PIVX#556]
we can report that [snap](https://github.com/wagerr/wagerr/blob/master/snap/snapcraft.yaml) builds [work](https://build.snapcraft.io/user/wagerr/wagerr), though just to let you know, as for you it should work too. I did not bother to commit it to your git, I guess you will add it by yourself if you find it usefull. Thats all, this issue can be closed. 

Installation is simple and works on many OS's which includes proper installation of icons for different desktops.

PS:
if you build it from master, I guess for pivx this would be the installation command:
```
sudo snap install --edge pivx
```

**Comment by rejectedpromise** [comment]
`this issue can be closed.`
