### ISSUE TITLE
[depends] Compiling for OSX with depends on trusty or El Capitan

### ISSUE THREAD

**Issue by headhunter911** [PIVX-Project/PIVX#560]
I have tried this on Trusty, Artful, and OSX El Capitan and I alway's end up at the same spot.

There must be something I am missing, I am using the gitian osx descriptor as a guide

Steps to reproduce:
1.  Make -C /Users/username/pivx/depends HOST='x86_64-apple-darwin11'
2. ./autogen.sh
3. CONFIG_SITE=/Users/smyers/pivx/depends/x86_64-apple-darwin11/share/config.site ./configure --prefix=/ --disable-ccache --disable-maintainer-mode --disable-dependency-tracking  --with-gui
4. Make
5.  Make deploy

I end up with this message during make deploy:
**+ Deploying frameworks +
Warning: Could not find any external frameworks to deploy in dist/PIVX-Qt.app.
Warning: Could not detect Qt's path, skipping plugin deployment!**

Can someone please point out what I am doing wrong.

**Comment by Mrs-X** [comment]
Question: to you want to cross-compile or do you just want to build OSX-binaries on your Mac?

**Comment by headhunter911** [comment]
I want to cross compile, I've been able to do every other build on trusty except osx

**Comment by Mrs-X** [comment]
So I assume you deployed all dependencies mentioned here: https://github.com/PIVX-Project/PIVX/blob/master/doc/build-osx.md ?

Anyway, the easiest way to cross-compile all platforms is Gitian, see https://github.com/PIVX-Project/PIVX/blob/master/doc/gitian-building.md

**Comment by headhunter911** [comment]
Yep all dependencies are met, I was hoping to learn how to do it manually before moving up to gitian, but I guess if there's nothing obvious I am doing wrong I'll try that and see what happens.

**Comment by rejectedpromise** [comment]
has this been resolved?

**Comment by Mrs-X** [comment]
I guess so :-)
