### ISSUE TITLE
Internal Mining: Errors on setting "setgenerate true"

### ISSUE THREAD

**Issue by mrudav-shukla** [PIVX-Project/PIVX#563]
Hi! I just cloned into v3.0.6 of PIVX and compiled it. It compiles fine and I'm even able to start my server in the daemon. Now using cli when I try to start mining using .`/pivx-cli setgenerate true` and run the command `./pivx-cli getmininginfo`, it shows generate as true. However when I go through my debug.log file it displays the following errors:

```
CreateNewBlock(): total size 1000
ERROR: CheckProofOfWork() : hash doesn't match nBits
ERROR: CheckBlockHeader() : proof of work failed
ERROR: CheckBlock() : CheckBlockHeader failed
CreateNewBlock() : TestBlockValidity failed
```

I've not changed any parameters in the codebase yet. Can anybody please help me figure out what's happening here? I'm actually using a Digital Ocean droplet to do this. Is it because internal mining isn't supported for PoS or any other issues?

> P.S This is my first ever issue raised on GitHub so I might've been a little ambiguous in explaining.

**Comment by Warrows** [comment]
PoW and mining period ended in August 2016. You can't mine PIVX anymore and you'll have to stake if you want to secure the network and earn rewards.

To stake check https://pivx.org/knowledge-base/staking-setup-guide/ If you have any problem following this guide, you can join discord.pivx.org and ask for help in the support channel.

**Comment by mrudav-shukla** [comment]
@Warrows Thanks for the prompt response. 

Ok so I even tried to regenerate the genesis block by changing some parameters in chainparams.cpp and it compiled fine and I ran into the same error.

**Comment by Warrows** [comment]
Playing around with the genesis block and trying to fork PIVX is not an issue with the wallet software. I invite you to seek help elsewhere. Since I answered the mining question I'll close the issue.

**Comment by Carbon-Zero** [comment]
This is an issue for trying to create a testnet.
