### ISSUE TITLE
lock/mutex issues (client crashing), do you have it?

### ISSUE THREAD

**Issue by WagerrTor** [PIVX-Project/PIVX#564]
We had discussion about lock issues. Some pivx holders reported that their wallets crashed and I do not find this issue on your list. We might have [same issue](https://github.com/bitcoin/bitcoin/issues/3997#issuecomment-40173160). One of our devs/contributors has posted some suggestion, you can look up [here](https://github.com/wagerr/wagerr/issues/34). He supposes that during zerocoin implementation you might not have adapted mutexes properly.

We are middle in this discussion and are proposing currently changes but since couple of days there were several people reporting their pivx clients crashed, I have no reports about our clients but if this is issue for you, then it is for us probably too.

**Comment by WagerrTor** [comment]
You can find this [issue on our git](https://github.com/wagerr/wagerr/issues/34) and [here is the commit which we currently test](https://github.com/wagerr/wagerr/commit/33c075be6948613286af3c8b2fc01ebf210e6f4d).

**Comment by ethanedison** [comment]
Issue is fixed by following some recent posts of cleaning up some of the wallet exe commands.

If need more info on how I fixed  ( i am not a developer) I can dig into this and send you the steps on how I solved the crashing issues.

**Comment by Kokary** [comment]
Not sure that's the same issue; we noticed a potential missing lock on cs_main during staking, manifesting itself in the increasingly unlikely scenario that a stake is found at the same time when an incoming block is validated, triggering an assert error with such debug output:
`Error:'Assertion failed: lock cs_main not held in wallet.cpp:4261; locks held:'`

Minting input selection code added with the ZeroCoin code doesn't have the mutex locks that Bitcoin added to similar 'classical' code. Could of course be that you're already addressing this when moving to ZeroMint.

**Comment by Mrs-X** [comment]
@WagerrTor Thanks for the feedback and information, it's very appreciated :+1: 

Did you or one of your users find a reliable way to reproduce those crashes?

**Comment by Kokary** [comment]
Producing many stakes on a low CPU machine should work ;) (It happened when setting up testnet.) Or have a lot of bad luck.. Could be an edge case on large networks.

**Comment by Mrs-X** [comment]
Hmh, I don't have any low CPU computers, but I've tested staking on a (linux-) machine with a load of > 80 which was swapping like hell, means the CPU didn't get much cycles to run.
But I'll ask around if one of the other devs can reproduce it.

**Comment by WagerrTor** [comment]
As I said, sadly we did not have real opportunity to look very deep into that and are currently testing what @Kokary  suggested. It is very fresh issue and we had to rub our heads first to see if this is at all an issue and if it is, does it affect us too. So far, after 1 night I am reported that the error does not happen anymore.

It happend like @Kokary explained on non main network. I was not able to reproduce it as I did not have any as addition, like I said, it is very fresh issue for us where it came up not by our own wallets directly but by users reporting their pivx wallet crashes (_hope they will create issues here, otherwise you probably will have not enough input for that_).

**Comment by ethanedison** [comment]
Here is what I did to fix my issue:


1) go to  PIVX data directory :

2) deleted  these files:

blocks, chain state, .lock, budget.dat, db.log, debug.log, fee_estimates.dat, mncache.dat, peers.dat, 

3) deleted the folders called: zerocoin & sporks 

4)) Relaunched wallet and sync with network after deleted files

**Comment by WagerrTor** [comment]
@ethanedison thanks for suggestion. Your suggestion is actually more a workaround which can be applied when your wallet crashes, you could achieve the same by simply resyncing too, which would not require data folder deletion. Point is, wallet should not crash and we try to find out the reason why it crashed in first place which requires additional steps and we think we found it, at least having no crashes/errors looks like if it had some positive effect if not a fix.

**Comment by ethanedison** [comment]
Hello,

thanks for your email.

ISSUE:

I am now trying to convert (as you requested today)  my zPIV back to PIV but my wallet continues to automatically convert back to zPiv after several block confirmations.

How to disable this and be prepared for wallet upgrades?

There must be an easier way in the GUI to disable automint?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Mrs-X** [comment]
@ethanedison Add `enablezeromint=0` to your pivx.conf and restart the wallet.

(yes, the  next release will have this setting available from the GUI)

**Comment by ethanedison** [comment]
Thanks for your email Mrs-x

  Tried to delete all Piv wallet files and download new and start over again.  NO LUCK

1) went to "tools" to open "wallet config file"--only video on youtube to teach how to disable zpiv

2) nothing

3) went to wallet file folder and tapped on Pivx.conf     added enablezeromint=0

4) closed wallet and opened again---moved zPiv to PIV   and NOW it continues to change 10% of my total balance back to zPIV   (argggggggggg)

This is frustrating and I dont have time to deal with as I run a company but like to support the Pivx blockchain.    Hope your team can make this easy for people or you will lose them :(

I HIGHLY suggest you get your marketing team to tweet and socialize HOW TO steps for wallet holders on how to disable zPiv .

I cannot find much or the information is not easily accessible.

I know you are very busy however, this is very important to keep your community happy which in this competitive space is most important!

regards,

gary

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by WagerrTor** [comment]
@ethanedison my best advice to you is, trust that in 9 of 10 cases it is always users fault. I would think in your case it is the same. Before you use any software, you should probably read first the documentation about it and maybe running `help` in your debug console of your gui or daemon is also not bad idea, it does show description of different commands. In case of `enablezeromint`, you would have found it if you would have tried to run the daemon with `--help` switch. You might want to know about those commands too and yes, you can place them in your config too:

```
Zerocoin options:

  -enablezeromint=<n>
       Enable automatic Zerocoin minting (0-1, default: 1)

  -zeromintpercentage=<n>
       Percentage of automatically minted Zerocoin (10-100, default: 0)

  -preferredDenom=<n>
       Preferred Denomination for automatically minted Zerocoin
       (1/5/10/50/100/500/1000/5000), 0 for no preference. default: 0)

  -backupzwgr=<n>
       Enable automatic wallet backups triggered after each zWgr minting (0-1,
       default: 1)

```

What you probably would not have found out by `--help` is about `zeromint=0`. @Mrs-X probably help and description should be added for zeromint. 

My suggestion to you would be to disable zeromint in general and you can do so by placing in your config: `zeromint=0` or by starting your client with the same switch.

If you want to be really 100% sure, you should disable automint for gui as well to disable zeromint:
```
zeromint=0
enablezeromint=0
```

Now your wallet will not automint anymore.

I hope my reply can help you solving your problem, I would suggest you to open separte issue about it, as here it is totaly offtopic and actually has nothing to do with the issue discussed here.

**Comment by Fuzzbawls** [comment]
@WagerrTor we don't have a runtime option called `zeromint`

**Comment by cevap** [comment]
I cant find zeromint
`bool fEnableZeromint = true;`

, but enablezeromint still has no description. enablezeromint should be the same as zeromint.

```
help: unknown command: enablezeromint
```

**Comment by rejectedpromise** [comment]
Is this still an active issue?

**Comment by Kokary** [comment]
I didn't dig into what was and wasn't addressed in the very nice, large update, however, at least partially the issue still persist. E.g.:

https://github.com/PIVX-Project/PIVX/blob/master/src/wallet.cpp#L2093
`out.tx->IsInMainChain()` calls `return GetDepthInMainChainINTERNAL(pindexRet) > 0;`, which has:
```
int CMerkleTx::GetDepthInMainChainINTERNAL(const CBlockIndex*& pindexRet) const
{
    if (hashBlock == 0 || nIndex == -1)
        return 0;
    AssertLockHeld(cs_main);
```
More importantly, the same happens in CWallet::AutoCombineDust() :
https://github.com/PIVX-Project/PIVX/blob/master/src/wallet.cpp#L4099

And finally (in what I observed), void CWallet::UnlockCoin(COutPoint& output) has `AssertLockHeld(cs_wallet); ` but is called on several locations without acquiring that lock, e.g.:

https://github.com/PIVX-Project/PIVX/blob/master/src/activemasternode.cpp#L444

I'd be happy to submit a PR for these at least, but I don't know if and how anyone else is looking at this.

**Comment by Mrs-X** [comment]
I guess when our latest release has stabilized we will have more time to look into this.

A PR would be highly appreciated of course :+1:
