### ISSUE TITLE
[Trivial] Incorrect Tool Tips for PR#445

### ISSUE THREAD

**Issue by Sieres** [PIVX-Project/PIVX#573]
### Describe the issue
PR #445 requires only 1 zPIV mint before being spendable. Tool tips are misaligned.
Overview tab, hover over immature balance, tooltip mentions that there are less than 3 mints since zPIV creation.
Privacy tab, hover over immature denomination, tooltip mentions that there are less than 2 additional zPIV mints since the denomination was minted.

#### If so, please list the steps to reproduce below:
1. Mint zPIV
2. Hover over immature zPIV balances in the overview tab and privacy tab

### Expected behavior
In line with PR #445, have an updated tooltip that mentions that there has not been an additional zPIV mint.

### Screenshots.
![incorrect tool tip](https://user-images.githubusercontent.com/31386038/38175764-fc3c8232-3624-11e8-919b-970181d77cb4.PNG)

### What version of PIVX Core are you using?
Dev build - 3.1.0 pre-release

**Comment by rejectedpromise** [comment]
@Sieres was this resolved in 445?
if so please close :)

**Comment by Fuzzbawls** [comment]
This has been resolved, closing
