### ISSUE TITLE
Listtransactions not updating after transaction

### ISSUE THREAD

**Issue by FornaxA** [PIVX-Project/PIVX#578]
### Describe the issue

The command `listtransactions` doesn't return up-to-date transaction information, unless the client is restarted - even though the transaction overview in the GUI is correct, and the balance returned by `getinfo` is correct.
This behavior occurs with regular transactions, stakes, MN rewards etc.

#### If so, please list the steps to reproduce below:
1. Note recent incoming transactions in the GUI, the balance returned by `getinfo` and the last transaction returned by `listtransactions` from the command line.
2. Send a transaction to your wallet. 
3. Again note recent incoming transactions in the GUI, the balance returned by `getinfo` and the last transaction returned by `listtransactions` from the command line.
4. Shut down and restart wallet.
5. Again note recent incoming transactions in the GUI, the balance returned by `getinfo` and the last transaction returned by `listtransactions` from the command line.

### Expected behavior
The incoming transaction is expected to show in step 3 - and that list is expected to be identical to the list returned in step 5.

### Actual behavior
The transaction does not show in step 3. The transaction does show in step 5.

### Screenshots.
![screenshot from 2018-04-10 11-42-31](https://user-images.githubusercontent.com/25762277/38551823-785c30a6-3cba-11e8-958c-d2855c2afebc.png)
![screenshot from 2018-04-10 11-44-37](https://user-images.githubusercontent.com/25762277/38551821-7836352c-3cba-11e8-8130-1bb5491a33ca.png)
![screenshot from 2018-04-10 12-06-36](https://user-images.githubusercontent.com/25762277/38551819-7819ce96-3cba-11e8-89d8-611da383ae70.png)
![screenshot from 2018-04-10 12-15-51](https://user-images.githubusercontent.com/25762277/38551818-77ff741a-3cba-11e8-8c14-3cf2bbd81b9e.png)
![screenshot from 2018-04-10 12-16-55](https://user-images.githubusercontent.com/25762277/38551817-77e3e2fe-3cba-11e8-8377-55379a942f33.png)
![screenshot from 2018-04-10 12-26-01](https://user-images.githubusercontent.com/25762277/38551816-77c241da-3cba-11e8-81d7-1e5e0dde5f64.png)

### What version of PIVX Core are you using?
Compiled from commit aedf80b07dcee5935b6ab01086481a7bb52b4ed3

### Any extra information that might be useful in the debugging process.
Bitcoin has the following line, which isn't present in PIVX:
https://github.com/bitcoin/bitcoin/blob/master/src/wallet/wallet.cpp#L904

You could cherry-pick https://github.com/cevap/ion/commit/5491b06ab33046dec298b68307a1e834a93f3b0b to amend it that way.

PIVX itself uses slightly different inserts during startup etc, and to stay closer to PIVX practice you coud cherry-pick this: https://github.com/wagerr/wagerr/commit/8f5c430f4535c8cad6f10128329385947c4785b1

**Comment by wqking** [comment]
This is because of the new transactions are not added to internal orders.
I fixed in ICH coin, you may reference to it.

https://github.com/wqking/instacash/commit/77faad2a5ad7930fda5ae79f0ee7bd21126e2b94
