### ISSUE TITLE
Feature request: risk-free, proxy staking

### ISSUE THREAD

**Issue by bathrobehero** [PIVX-Project/PIVX#579]
I know this is not the right place to do proposals but I don't care for slack and discord and it seems like a good start to gauge interest.

Anyway, I'd like to suggest implementing a staking method that would allow staking contents of an offline wallet with funds through an empty online wallet running 0-24h. Almost like how remote masternodes work.

That way even if someone's computer with the staking wallet would be compromised, their funds cannot possibly be stolen as those would be in a cold wallet (offline PC, paper or now even a Ledger Nano S).

This would likely make PIVX the most secure staking coin there is.

**Comment by Rock-N-Troll** [comment]
This has been mentioned and is potentially going to be implemented later this year . It is called "permissioned staking" and is essentially exactly what you're saying.
