### ISSUE TITLE
Useless help [?] button on 'Tools window' title bar

### ISSUE THREAD

**Issue by PIVXStrontium** [PIVX-Project/PIVX#614]
### Describe the issue
Tools window has a help button [?] that serves no purpose due to apparent lack of help entries.
### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. Select Tools from toolbar
2. Select any of the first five entries before division
3. Look to title bar near terminate [X]

### Expected behavior
User pressing this expects the feature to provide help on aspects of the live window when selecting this tool.

### Actual behavior
No entries appear to exist, making the tool useless.
### Screenshots.
![image](https://user-images.githubusercontent.com/38264865/39982524-9f1fa250-578f-11e8-87de-a983c0d470e1.png)

### What version of PIVX Core are you using?
3.1.0.2 win 64

**Comment by Warrows** [comment]
I'll have a look.
