### ISSUE TITLE
1366x768 resolution usability on Gnome Debian 9

### ISSUE THREAD

**Issue by StrontiumZ38** [PIVX-Project/PIVX#615]
### Describe the issue
Inability to scale wallet to a workable size under particular resolution settings due to option being cropped and maximise being disabled.

### Can you reliably reproduce the issue?
No, due to lack of hardware. Report sourced from Discord.

### Expected behavior
Window should be able to be maximised for use and the availability of all workable sections of the wallet.

### Actual behavior
'Maximize' is greyed and disabled, and vertical sizing is not adjustable, and so the sync bar + status indicators aren't visible within working screen-space.

### What version of PIVX Core are you using?
3.1.0.2

### Machine specs:
- OS: Gnome // Debian 9

### Any extra information that might be useful in the debugging process.
This is from a user on Discord (lordg2009). I hope they will add to this issue if I have no properly represented it.

**Comment by random-zebra** [comment]
Issue related to old GUI.
