### ISSUE TITLE
listtransactions misses entries

### ISSUE THREAD

**Issue by khelle** [PIVX-Project/PIVX#616]
Hello,
I have a problem operating PIVX full-node. I have been using v2.2.0 for some time, having few addresses I totally had 21 transactions made (send and receive ones). Today strange thing happened to me as I received a transaction that is not visible in my `listtransactions` RPC call. This transactions was made to address I have already received transaction on (the previous one is visible) and was counted in block lesser than my current height (blockchain is fully synced and up to date). I thought this might be the issue of using old software version, so just in case I removed blockchain from my machine, updated node to v3 let it resync from the scratch. It synced once again, but it still see only 21 transacitons, and still misses the one I received today. What's more the `listunspent` RPC call sees that missing transaction, and `get_info` also returns me balance including it. What can I do to fix the issue?

**Comment by Warrows** [comment]
Hello @khelle.
2.2 has been deprecated for several months, your node was surely running on a forked chain. Updating to 3.1.0.2 (all earlier versions, like 3.0 are deprecated too) and then resynchronizing the blockchain is the way to go. 
However, there is a small mishap in 3.1.0.2 and `listtransactions` might not be working properly. I suggest you self compile the tag v3.1.0.3 to get the fix if you need to use this command.

**Comment by Warrows** [comment]
I'm gonna close the issue since it's been answered. Feel free to reopen it if you need more info.
