### ISSUE TITLE
Send coins to binance but not receiving

### ISSUE THREAD

**Issue by Pele51** [PIVX-Project/PIVX#618]
Hi there today i send some coins from my wallet to the binance pivx adress, but they are not receiving for hours

![pivx issue binance](https://user-images.githubusercontent.com/35359689/40079349-e48e744e-5887-11e8-90a0-ad58fbc4a812.png)

They are also not on the blockchain, what can i do?

**Comment by cryptomark** [comment]
Upgrade your wallet to 3.0.1.2.
It looks like you're on the old wallet and therefore not "on chain".  This
means you did not send anything.  Upgrade and re-send!

**Comment by VTHokiEE** [comment]
You most likely need to resync your block chain. Go to tools then wallet repair and select delete local blockchain files. This will restart your wallet and you will resync. When that is complete your coins should reappear in your wallet.

**Comment by Warrows** [comment]
Hi @Pele51, how is the resolution of this issue going?

**Comment by Pele51** [comment]
I fixed the problem with the new wallet and synching the whole bl8ckchain thx!
