### ISSUE TITLE
Increase the amount of automatic backups that are stored.

### ISSUE THREAD

**Issue by givanse** [PIVX-Project/PIVX#620]
Right now only the last 10 automatic backups will be stored in `.pivx/backups`, on the eleventh, it rotates the files.

When you are troubleshooting a problem with your wallet or trying the different wallet recovery tools you'll very quickly rotate through the 10 backups. If you are not careful and haven't backed up the folder `.pivx/backups`, you might lose old backups that could still be useful.

The current number 10 seems very arbitrary, why not make it 50? 2.9Mb * 50 = 140Mb doesn't seem like a big deal.

Maybe keep it at 10. Instead of rotating the files, make a gzip of the backups folders and start with an empty backups for the next 10?

**Comment by Mrs-X** [comment]
Add `createwalletbackups=50` (or whatever is sufficient for you) to pivx.conf and restart your wallet.

**Comment by givanse** [comment]
Oh, thanks! 👌
