### ISSUE TITLE
Build issue: custom boost directory is not found

### ISSUE THREAD

**Issue by osnwt** [PIVX-Project/PIVX#621]
Error building the code on MacOS with custom boost version:
`./configure --with-boost=/usr/local/Cellar/boost@1.60/1.60.0`

When building in src/libzerocoin/, in includes util.h which requires boost include. But compiler command line does not include -I/path/to/custom/boost/include/directory. Result: header not found.

<img width="748" alt="2018-05-17 12 20 59" src="https://user-images.githubusercontent.com/1081613/40168699-cf410872-59cc-11e8-93d7-48eb7d146b42.png">

Other source files are fine, proper -I option is given:

<img width="747" alt="2018-05-17 12 21 51" src="https://user-images.githubusercontent.com/1081613/40168759-f6f59590-59cc-11e8-9d0a-806410344b43.png">

**Comment by Fuzzbawls** [comment]
@osnwt have a look at #622

**Comment by osnwt** [comment]
Thanks! While pivx does not require old boost (like many other coins still do), always good to support all options if they provided by the configure. That was the purpose of posting it.
