### ISSUE TITLE
Change to connection handling to allow correct connection count when using maxconnections=

### ISSUE THREAD

**Issue by jk9694** [PIVX-Project/PIVX#635]
https://github.com/PIVX-Project/PIVX/blob/6b525f0dfc5f46bef132560cb138846f65c878bd/src/net.cpp#L983-L1027

**Add**

int nOutbound = 0;

**Change**

bool whitelisted = hListenSocket.whitelisted || CNode::IsWhitelistedRange(addr);
                {
                    LOCK(cs_vNodes);
                    BOOST_FOREACH (CNode* pnode, vNodes)
                        if (pnode->fInbound){
                            nInbound++;
                        } else{
                            nOutbound++;
                        }
                }

**Change**
}
 //if the total connections is greater than max connections, drop due to max connections reached
else if ((nInbound + nOutbound ) >= nMaxConnections) {
                    LogPrint("net", "connection from %s dropped (max connections reached)\n", addr.ToString());
                    CloseSocket(hSocket);
} 
//since we havent reached the maxconnections, check to ensure that the outbound connections max are not reached
else if (nOutbound >= MAX_OUTBOUND_CONNECTIONS) {
                    LogPrint("net", "connection from %s dropped (max  outbound connections reached)\n", addr.ToString());
                    CloseSocket(hSocket);
 }
//now because we have checked inbound + outbound in relation to nMaxConnections and outbound to
//MAX_OUTBOUND_CONNECTIONS we should be fine to allow the connection to this point and it 
//should behave better

**Reasoning**

nMaxConnections = 10

10 inbound, you have reached the max no outbound would be allowed new
5 inbound, and 5 outbound, you have reached the max no inbound would be allowed

nMaxConnections=20

16 outbound, and 1 inbound is allow, but will not allow another outbound

**Comment by Warrows** [comment]
Hi, thanks for this input, but would you care to make a pull request instead of an issue? That's the most correct way to discuss code changes.

**Comment by jk9694** [comment]
I don't have a code environment to work with to put it in place and test it.  Just looking at it from the logic perspective.
