### ISSUE TITLE
Scaling issue 3840x2160(16:9)

### ISSUE THREAD

**Issue by borris345** [PIVX-Project/PIVX#638]
scaling issue.

see picture. Looks better on screenshot than it actually is. either that or my eyesight getting bad.

Latest master compiled.

![screenshot from 2018-06-17 20-30-43](https://user-images.githubusercontent.com/27918951/41511362-6b14d72a-726d-11e8-85ed-e1de436e48f5.png)

![screenshot from 2018-06-17 20-33-41](https://user-images.githubusercontent.com/27918951/41511385-c422d858-726d-11e8-98a3-f592a5eaa627.png)

**Comment by EvertonMelo** [comment]
@borris345 
you give more information:

OS ( linux mint ? ) 
kernel version. 
WIndowManager. 
Video Driver installed.

**Comment by borris345** [comment]
Linux mint 18.3 cinnamon 64bit 3.6.7
Kernal 4.15.0.30
Nvidia driver version 384.130

**Comment by borris345** [comment]
Even knocking it down it's still hard to see with my old eyes 😂

**Comment by EvertonMelo** [comment]
@borris345 

I'm guessing it's something between what your environment is integrated with GTK +
is there a possibility for you to test another version of linux with QT only?.

**Comment by Warrows** [comment]
What size is your monitor? Is it hdpi?

**Comment by borris345** [comment]
It's a laptop. 4k screen

**Comment by Warrows** [comment]
This is probably the same as #489 and #228. #233 was supposed to help address this. I'd like to tell you we will fix it shortly, unfortunately I don't think any core dev has the hardware to reproduce the problem.
Right now you will have to knock it down all the way to 1920x1080 I guess.

**Comment by cevap** [comment]
I have no scaling issues with `3840 x 1080` resolution on [this screen](https://www.samsung.com/ch/business/monitors/curved-business-lc49j890dkuxen/lc49j890dkuxen/), as well as no troubles with nvidia 3xx or 4xx drivers. I see that height is different, probably heights over 1080 should be checked

**Comment by Carbon-Zero** [comment]
I believe the correct fix to this is to right click on the icon, go into the compatibility and select change high dpi settings.  Then Under high DPI scaling behavior override, select the check box and select System (Enhanced).  You'll have to restart for the new settings to take effect.

**Comment by Redsandro** [comment]
PivX-core really is a bit of a freak.

![image](https://user-images.githubusercontent.com/1702193/56204133-ff607700-6046-11e9-9501-637f10b5ebcd.png)

* **Menu-items:** Good
* **Button-text:** too small
* **Logo and icons:** pixelated, high resolution assets missing
* **Main screen options or transactions:** huge

This is Linux Mint on a UHD monitor. Also connected is an old 1280 monitor and a 1920 HD TV.

**Comment by Warrows** [comment]
Is that still a problem with the new GUI?

**Comment by borris345** [comment]
Not as bad but yes. Some text on loading screen is to large and I hope you have good eyes to see it all but it is readable

**Comment by akshaynexus** [comment]
should be fixed with https://github.com/PIVX-Project/PIVX/pull/1057 being merged .

**Comment by random-zebra** [comment]
Old GUI. Closing
