### ISSUE TITLE
replace instance COINBASE_MATURITY with Params().COINBASE_MATURITY()

### ISSUE THREAD

**Issue by bumbacoin** [PIVX-Project/PIVX#642]
https://github.com/PIVX-Project/PIVX/blob/master/src/wallet.cpp#L4106

replace
            if (out.tx->IsCoinStake() && out.tx->GetDepthInMainChain() < COINBASE_MATURITY + 1)
with
            if (out.tx->IsCoinStake() && out.tx->GetDepthInMainChain() < Params().COINBASE_MATURITY() + 1)

apologies
i can't fork and pull because i already have a further upstream fork.

**Comment by Alko89** [comment]
Is this the only occurence? I fixed it and am trying to build now.

**Comment by bumbacoin** [comment]
i had a look, and most occurrences seem to have been changed already, so that was the only one i found

**Comment by Alko89** [comment]
I greped the src dir and seems that others are fixed already. Should I just commit and create a pull request?
