### ISSUE TITLE
Locked balance being double counted

### ISSUE THREAD

**Issue by Fuzzbawls** [PIVX-Project/PIVX#654]
### Describe the issue
Locked PIV balances are being "double counted" on the overview tab such that they cause the "Available" and "Total" values to be incorrect/over calculated.

#### If so, please list the steps to reproduce below:
1. Run GUI wallet
2. Have locked coins (MN collateral or otherwise locked UTXO)

### Expected behavior
Locked coins should not be reflected as "Available", and the calculation of "Total" represented as `available + pending + immature + locked` (this is currently the case, but with locked coins being included in `available` already, they are double counted)

### Actual behavior
#598, while intending to clear up a separate calculation error, instead introduced another resulting in locked funds to be included as "Available"

### What version of PIVX Core are you using?
PIVX Core v3.1.1 distribution package

### Machine specs:
N/A (Applies to all)

**Comment by tofutim** [comment]
This happens when the wallet and the masternode are on the same machine. I'll have a PR for you in a moment.

**Comment by tofutim** [comment]
I found another double counting scenario (PR above).
