### ISSUE TITLE
atomic swap support?

### ISSUE THREAD

**Issue by tofutim** [PIVX-Project/PIVX#663]
Is it possible to support atomic swaps with Bitcoin, Decred, Litecoin, etc.?  Seems that the only thing missing would be BPI68 (time locking)

**Comment by BTC2CoreDevs** [comment]
+1, atomic swap support would be great for decentralized exchanges.

**Comment by Fuzzbawls** [comment]
BIP65 is already planned to support the forthcoming zDEX. BIP68 and BIP112 may be future considerations.

**Comment by Fuzzbawls** [comment]
Closing, basic support was included with #705 (CLTV - BIP65)
