### ISSUE TITLE
I would like to add a proposal tab to the pivx wallet more info ...

### ISSUE THREAD

**Issue by mrmetech** [PIVX-Project/PIVX#665]
https://forum.pivx.org/t/i-would-like-to-add-a-proposal-tab-to-the-pivx-wallet-for-some-pivx-could-i-talk-to-admins/4295

their is a link to my forum post i would like to talk to a few of the pivx team if i could about this.

**Comment by Warrows** [comment]
Usually, the process to add new features you can code yourself is to submit a Pull Request. If you want to discuss your idea before starting implementation, you can give more details and ask questions here.

**Comment by Mrs-X** [comment]
There is an update in the making which will add a proposal tab where you can see and (if you're a masternode) vote for a proposal.
It will be released (most probably) with the next major release.

**Comment by mrmetech** [comment]
Ok well no point for me to do it then :P

**Comment by Mrs-X** [comment]
Yep.
But still a big "thank you" for your proposal and your time :+1:
