### ISSUE TITLE
Debian version for gitian build

### ISSUE THREAD

**Issue by aigon1989** [PIVX-Project/PIVX#670]
Hello all,

I know this is not an issue but an information request, but I don't know exactly where to ask.

I have been trying to build the wallet for linux, windows and mac myself as a challenge and as an experiment but I can't make it work.

Following the guides in /doc I have been able to download gitian-builder, gitian-sigs, pivx, the inputs, prepare an lxc image but when I try to compile the sources with:

./bin/gbuild --memory 3000 --commit pivx=v3.1.1 ../pivx/contrib/gitian-descriptors/gitian-linux.yml

It won't work, and apparently it's an lxc issue booting the image generated with:

bin/make-base-vm --lxc --arch amd64 --suite precise

(And the documentation is deprecated because it needs trusty and not precise acording to the gitian-linux.yml)

I have been trying with different versions of debian (7.4.0 as shown in the guide, 8.11.0 (Jessie), 9.5.0, and also the latest Ubuntu version) because I had problems following the guides such as not being able to configure a bridge (br0) for lxc.

I've even tryied to use gitian-build.sh script (which is broken, i've created a pull request to fix the lack of a "fi" statement on the build block) on pivx/contrib but also with no luck.

I don't think I really need the documentation to be updated (which will be also great), just the debian version currently at use by the official builders and some small guidelines in order to tackle this problems.

I would really appreciate if someone with a bit of time could help me, I can even update the building guides if needed and wanted.

Thanks in advance,

Best regards, 

Aitor

**Comment by Fuzzbawls** [comment]
Hey there,

I've been working on a complete update to this entire process lately. Debian 8 or 9 will suffice for now, but will likely become a "pain" very soon as the distribution repos are holding onto an outdated version of lxc that is now deprecated in itself (even in the current debian-unstable branch).

Moving forward, after the updates, using ubuntu 18.04 will likely be a more appropriate gitian host OS, as it offers native distro package support for lxc3. Alternatively you could continue using debain 9, and compile the latest lxc2 (or lxc3) version yourself.

I'm also working on getting everything updated to introduce gitian support for docker build targets (as an additional option to KVM and LXC), which may become the gold standard in the near future.

**Comment by aigon1989** [comment]
Hi!

I do not wanted to seem rude on the first message, but it was a desperate cry, I was really, really lost.

Seems like Ubuntu 18.04 is the right host OS, I can't tell you if I was able to compile the wallets but I've went some steps further after fixing my own mistakes configuring the br0 bridge and all and now it seems to be compiling as I can see at the gitian-builder/var/build.log

I will tell you  if it ends up compiling and signing valid wallets.

And really, If I can help with anything I am eager to help anybody in anything, I feel really grateful.

Thanks,

Aitor

**Comment by aigon1989** [comment]
Hello @Fuzzbawls ,

Althought I am being able to compile some unsigned versions of the wallet, I am getting some errors that I am not able to overcome, one on the build process and another in what I guess is the sign step, but I can't get any log file to try and guess what is it about, can you help me?

I'm uploading screenshots regarding the compiled wallets and also the errors as shown on console and also the logs.

Many thanks!

Best regards,

Aitor
![error2](https://user-images.githubusercontent.com/35709753/43564203-fdd4b590-9625-11e8-9620-e2a9bc2ada6e.png)
![error1](https://user-images.githubusercontent.com/35709753/43564204-fdf0b3ee-9625-11e8-8581-b6654fa57e07.png)
[install.log](https://github.com/PIVX-Project/PIVX/files/2252216/install.log)
[build.log](https://github.com/PIVX-Project/PIVX/files/2252217/build.log)
![compiled](https://user-images.githubusercontent.com/35709753/43564217-0dc0a2a2-9626-11e8-926b-4e71d57d46aa.png)

**Comment by giaki3003** [comment]
This seems like an environment issue. Do you have the variables set properly? Remember the ip changed from the latest release

**Comment by aigon1989** [comment]
giaki3003 what do you mean?

**Comment by giaki3003** [comment]
The internal LXC container IP changed on LXC 3.x

**Comment by aigon1989** [comment]
@giaki3003 I will look it up.

I have spent some time without replying because I was busy by the time and also my computer died two days ago and now I can't even compile anything... 

Can you tell me which version of Debian/Ubuntu you use and which is your configuration? 

I have been trying with Ubuntu Server 18.4 but apt-cacher-ng package is missing and it is needed to create the lxc container properly, and if I add the ubuntu source where the package can be found it breaks lxc dependencies...

And also I have been trying to use Debian 8.5 following the next tutorial:

https://www.youtube.com/watch?v=_ti-d5t1WX8&t=1082s

But when I finally run the build command, on the "install" step, apparently the lxc instance cannot find any of the packages defined on the gitian descriptor to install, and the build fails...

I don't know why this apparently simple task is getting so complicated, but thankfully and luckily there is a helpful community.

Thank you

**Comment by aigon1989** [comment]
Apparently, I think I did it (at least, building the Linux ones):

![image](https://user-images.githubusercontent.com/35709753/45733900-b6486180-bbe2-11e8-9a96-dc4bf9575914.png)

(Yes, I'm trying to fork pivx)

The Linux distro I am using is Ubuntu Server 18.4 (Bionic), but if someone is trying to replicate what I did has to be careful because there are two ISO's for Ubuntu Server 18.4, a live version and an installation ISO. 

The live version caused me some problems because it doesn't have all the package sources needed to install, for example, apt-cacher-ng or python-cheetah and more.

The right link to get the right version of ubuntu server is the following:

http://cdimage.ubuntu.com/releases/18.04.1/release/ubuntu-18.04.1-server-amd64.iso

Then, once installed, the steps to follow are the same ones as in gitian-building.md and release-process.md with some exceptions:

First, the content on /etc/rc.local and /home/debian/.profile that worked for me is as follows:

**/etc/rc.local:**

```
#!/bin/sh -e
/sbin/brctl addbr lxcbr0
ifconfig lxcbr0 10.0.2.2/24 up
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
echo 1 > /proc/sys/net/ipv4/ip_fordward
exit 0
```

**/home/debian/.profile:**
```
export USE_LXC=1
export GITIAN_HOST_IP=10.0.2.2
export LXC_GUEST_IP=10.0.3.5
export LXC_BRIDGE=lxcbr0
```
Then when running:

`./bin/gbuild --memory 3000 --commit pivx=v${VERSION} ../pivx/contrib/gitian-descriptors/gitian-linux.yml
`
I have faced a problem, and it was that the lxc container wasn't able to download the build dependencies so what I did is run the optional step of downloading the dependencies with:

```
pushd ./gitian-builder
make -C ../pivx/depends download SOURCES_PATH=`pwd`/cache/common
popd
```

But I do not needed to use the --url flag on the ./bin/gbuild instruction

Maybe there is a way to fix the dependency download issue and maybe it is related to the lxc bridge but I will focus on build and run everything in order to provide fixes/help to the people who needs to build and then I will try to solve the minor issues to automate the process as much as possible.

Again, thank you all for your help

**Comment by aigon1989** [comment]
In order to sign the package, you'll need to generate a key. This is never explained, but is really easy:

Just follow this:

https://help.github.com/articles/generating-a-new-gpg-key/

And then this, in order to generate entropy using ssh:

https://serverfault.com/questions/214605/gpg-does-not-have-enough-entropy

**Comment by cevap** [comment]
@algon1989 you might want to check this pull #786 and use gitian-build.py script with bionic or latest debian with lxc.

**Comment by random-zebra** [comment]
Gitian script/docs updated in https://github.com/PIVX-Project/PIVX/pull/1176
