### ISSUE TITLE
[Usability] SwiftX - intuitiveness

### ISSUE THREAD

**Issue by PIVXStrontium** [PIVX-Project/PIVX#672]
### Describe the issue
The SwiftX checkbox on SEND tab is isolated save for being paired by balance. It features no tooltip or explanation, and has no interactivity with PIV balance despite what visual grouping may imply.

### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. Visible on SEND tab in bottom right

### Expected behavior
The SwiftX checkbox should have a tooltip with a brief explanation. The SwiftX checkbox should be within the transaction speed cluster rather than by the PIV balance. When checked, the SwiftX transaction should be reflected in confirm time and PIV cost.

### Actual behavior
The SwiftX checkbox is simply a checkbox with no clear purpose, explanation, or impact upon send settings from a user perspective.

### What version of PIVX Core are you using?
PIVX Core Windows 64bit v 3.1.1

**Comment by random-zebra** [comment]
in https://github.com/PIVX-Project/PIVX/pull/675
