### ISSUE TITLE
[UX] PRIVACY tab displayed info

### ISSUE THREAD

**Issue by PIVXStrontium** [PIVX-Project/PIVX#676]
### Describe the issue
PRIVACY tab is too bloated and busy, overwhelming users.

### Suggested fix
The right-hand side of the PRIVACY tab lists the user's current zPIV denominations, Automint status, and global zPIV supply by denomination. I propose hiding the denomination info by default, instead replacing it with a button to enable display. This could be also be accompanied by a setting in the wallet options to instead display this info by default for advanced users,

### Screenshots.
![image](https://user-images.githubusercontent.com/38264865/43353316-31ac3dde-9270-11e8-9847-8665fac430f6.png)
Current right-hand display
![image](https://user-images.githubusercontent.com/38264865/43353317-3f18dfc2-9270-11e8-9cb8-6d20de974089.png)
With suggested change (note I've also removed privacy level in anticipation of that change to better reflect how a future release's PRIVACY tab would appear).

**Comment by random-zebra** [comment]
I like the idea.
When the denominations are hidden, that whole widget could be minimized. And then would be expanded clicking the "show" button.

**Comment by random-zebra** [comment]
in https://github.com/PIVX-Project/PIVX/pull/680
