### ISSUE TITLE
[Intuitiveness][UX] - Receiving tab

### ISSUE THREAD

**Issue by PIVXStrontium** [PIVX-Project/PIVX#678]
### Describe the issue
When compared to something like Jaxx wallet, PIVX Core presents quite a task when the user seeks their receiving address.
Jaxx, with the added layer of currency choice, requires the input
Click currency icon > click copy address > paste address as needed
PIVX in comparison requires
Click File > Click receiving addresses > select an address > click copy > (close additional window) > paste address as needed.

### Suggested solution
- The RECEIVE tab should prominently feature the user's primary receiving address (top of the address list) with a button to copy the address to clipboard without first selecting it.
- A second button to open the same 'receiving addresses' window that can be found in File.
- The Requested payments history record should be down-sized to allow more visual attention to the receiving address fields above it (with I assume a scrollbar ensuring no access to this data is lost in the process)
This will reduce the user input process to 
click receive tab > click copy > paste address as needed
matching Jaxx.
Where alternate addresses are needed the process is still longer, but at least it will be intuitive.

### Screenshots.
![image](https://user-images.githubusercontent.com/38264865/43354459-208d9ecc-9288-11e8-825c-75240bae5146.png)
![image](https://user-images.githubusercontent.com/38264865/43354528-de6d02ca-9288-11e8-98a3-d6f39a86f16a.png)

**Comment by Fuzzbawls** [comment]
It is not advised to re-use receiving addresses, and as such I don't see any real need to make their display more "center stage" as it were. The suggestion here is also a partial regression to how bitcoin and bitcoin-like clients operated many years ago.

The receive tab already supports "one click" **new** receiving address generation, which also provides a cross platform QR code at the same time.

Accessing previously used receiving addresses is also already a simple 2-click operation (first click on `File`, second click on `Receiving addresses...`.

**Comment by PIVXStrontium** [comment]
Fair enough Fuzzbawls. Thanks for the feedback.

It's rare people are wanting to make receive requests. Things like exchanges ask only for 'receiving address' and yet no such feature currently exists on the Receive tab, or anywhere outside of the File menu (not somewhere most people will choose to look for basic features) hence why I made it large and first in the hierarchy. The only mention of 'receiving address' is
![image](https://user-images.githubusercontent.com/38264865/43368049-b9a30dd6-9391-11e8-8048-1290ad1ce9a6.png)
which does nothing when clicked by itself, and is accompanied by a negative message.

How about a similar setup to the mock-up image, only it has a 'generate new' button? 

**Alternative 1**
![image](https://user-images.githubusercontent.com/38264865/43367714-a0731c52-938c-11e8-82b6-ceb4453289fc.png)

**Tooltips**
Copy - Copy address to clipboard
New - Generate a new receiving address (it's strongly recommended you do this regularly)
Receiving addresses - View and manage receiving addresses

**Alternative 2**
![image](https://user-images.githubusercontent.com/38264865/43367921-d48cd886-938f-11e8-85f8-681b2fc97120.png)
More explicit, but starting to get quite busy. It may be possible to remove the reuse checkbox in this variant as the warning is already highly visible.

At the least 'File' is a far less intuitive place to find receiving addresses than 'Receive' is, so I feel the the 'Receiving addresses' window should be accessible from the Receive tab if nothing else. This is particularly important as receiving is essentially the first, and (preferably) the most commonly used basic feature of the wallet in terms of user interactions, so shouldn't be intimidating and unintuitive as it is now.

I hope all this better explains my position :)
