### ISSUE TITLE
[UI] Presentation Qt wallet

### ISSUE THREAD

**Issue by StrontiumZ38** [PIVX-Project/PIVX#684]
### Describe the issue
The pivx_logo_horizontal.png in the Qt wallet header, although positioned correctly, visually looks off due to the white menu bar above it and close proximity of the grey border beneath it.

### Suggested fix
Either the image file is adjusted to space the logo away from the grey border, or the buffer is spaced via code to achieve the same result.

### Screenshots.
![image](https://user-images.githubusercontent.com/38264865/43552765-d3c46830-9626-11e8-9cad-cff1f0c51f1c.png)
Original
![image](https://user-images.githubusercontent.com/38264865/43552777-e4c8c6c6-9626-11e8-9317-c8c20c0d51aa.png)
With spacing

The image could be even more visually centered vertically in the white header space, but doing so would likely risk losing fidelity on the logo and accompanying text if done via image, or needlessly enlarging the header space if done by code. It would probably need a bit of playing around for the best result regardless.

### What version of PIVX Core are you using?
Qt Core wallet (image from in-development build on Testnet.

**Comment by akshaynexus** [comment]
i guess the fix is to add padding to bottom of the hader image

**Comment by Carbon-Zero** [comment]
I think it looks fine the way it is. I mean, I could understand if someone wanted to do a PR and make the change themselves and see if it gets accepted, but to open it as an issue?

**Comment by furszy** [comment]
This doesn't exists anymore in the new wallet #954, closing it.
