### ISSUE TITLE
[Intuitiveness][UX] - Overview tab - Qt wallet

### ISSUE THREAD

**Issue by StrontiumZ38** [PIVX-Project/PIVX#685]
### Describe the issue
Currently, the overview tab's _Recent transaction_ section will direct the user to the transaction history tab and relevant transaction when clicked by the user. No indication of this feature exists, either in text form or in user feedback.

### Expected behavior
Interaction with the Recent transactions section of the Overview tab should give the user knowledge that it can be interacted with either explicitly (via text indication) or, preferably, implicitly via UI features.

### Suggested solution
When mousing over a transaction in the Recent transactions section, the transaction gains a highlight background colour, and the icon of the transaction increases in size. This would indicate to the user that they're able to interact with said element, and clicking will then take them to the details of the transaction in the list as always.

Ideally for the sake of UX this solution would involve subtle animations such as the icon easing to its new size and the background highlight colour fading in/out over a fraction of a second with mouse-over/mouse-off. i understand this is not an easy implementation however, so a static change (binary states) should suffice.

### Screenshots.
![image](https://user-images.githubusercontent.com/38264865/43619402-8941d59e-9708-11e8-982b-685e28b87f6a.png)

The top images represent the neutral state, and those beneath the blue arrows the moused-over state.
![image](https://user-images.githubusercontent.com/38264865/43620343-2b344d1a-970d-11e8-931f-ce0ffaf65962.png)
In this alternative version for orphan above, the reward gift image is a faded grey to imply no reward was received with the orphan. 

_NOTE_ the images above uses colouration from a separate issue and PR on orphan presentation.

**Comment by furszy** [comment]
This doesn't exists anymore, closing it.
