### ISSUE TITLE
ERROR: Wallet keypool empty (code -32603)

### ISSUE THREAD

**Issue by AugerSoft** [PIVX-Project/PIVX#686]
Dear developer,
I'm making fork of PIVX, but i can't to mine first block. (genesis block i'm generated) ((
I'm geting this error message (Wallet keypool empty (code -32603)), when i trying execute 'setgenerate true 2'

fMiningRequiresPeers = false;
fMineBlocksOnDemand = true;

Can you help me? :(

**Comment by Fuzzbawls** [comment]
This issue tracker is only for PIVX related issues and not forked projects.

**Comment by aries1504** [comment]
Hey AugerSoft, were you able to solve the error - "Wallet keypool empty (code -32603)" ?

**Comment by aries1504** [comment]
Hey AugerSoft, were you able to solve the error - "Wallet keypool empty (code -32603)" ? If yes, how?

> Dear developer,
> I'm making fork of PIVX, but i can't to mine first block. (genesis block i'm generated) ((
> I'm geting this error message (Wallet keypool empty (code -32603)), when i trying execute 'setgenerate true 2'
> 
> fMiningRequiresPeers = false;
> fMineBlocksOnDemand = true;
> 
> Can you help me? :(
