### ISSUE TITLE
Reindex always fails with segfault

### ISSUE THREAD

**Issue by Fuzzbawls** [PIVX-Project/PIVX#70]
Currently, attempting a reindex causes an immediate segfault, making the intended functionality useless, and resulting in an unusable block index on disk.

Initial review has discovered that unprotected function calls may be to blame, specifically in ProcessNewBlock() and CheckWork()

**Comment by N1ghtly** [comment]
Any progress on this issue? I can't use my wallet currently...

**Comment by presstab** [comment]
See https://github.com/PIVX-Project/PIVX/pull/71
