### ISSUE TITLE
Bump minimum supported MacOS version to 10.10

### ISSUE THREAD

**Issue by Fuzzbawls** [PIVX-Project/PIVX#707]
Currently we support MacOS (OS X) down to version [10.8](https://github.com/pivx-project/pivx/blob/master/depends/hosts/darwin.mk#L1), which has worked fine so far but has required some code work arounds.

However a planned update to the version of Qt we use for release builds (Qt 5.9.6), which only supports MacOS [10.10+](https://wiki.qt.io/Qt_5.9_Tools_and_Versions#osx_10.10_x86_64), means that users will need to update their OS version to continue using the wallet.

At the time of writing this, all Mac computers that are capable of running 10.8 are also capable of running 10.10, and updates are free of charge. Because of this, I don't see any reason to hold back the Qt update or to continue supporting MacOS versions prior to 10.10.

For Reference:
- MacOS (OS X) 10.10 was released in 2014, with official support ending in 2017 (Security updates **MAY** still be released, but unlikely).
- Qt 5.9 update resolves a long running issue of needing to compile separate binaries for MacOS High Sierra, which will result in once again having only a single download file that covers the entire range of supported MacOS versions.

**Comment by Warrows** [comment]
Not using MacOS myself, I can't provide a wheighted point of view but this sounds like a sensible thing to do.

**Comment by Mrs-X** [comment]
I'll test it tomorrow, I'm in the middle of moving a need to find my Mac first :-)

**Comment by flyinghuman** [comment]
this would be real good.
