### ISSUE TITLE
Setgenerate True Crashes

### ISSUE THREAD

**Issue by mhannigan** [PIVX-Project/PIVX#709]
This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Discord](https://discord.pivx.org).

### Describe the issue
Setting SetGenerate True causes the wallet to crash
### Can you reliably reproduce the issue?
Yes. Setup the wallet in Linux or Windows and use "setgenerate true" in either  client and the client immediate crashes
#### If so, please list the steps to reproduce below:
1. Open Windows version
2. Go to debug console and type "setgenerate true"
3. Client crashes

On Linux
1. type pivx-cli setgenerate true
2. server crashes

### Expected behavior
new blocks should be created in POW stage.  This does not apply to current production but it DOES apply to creating a new testnet.

### Actual behavior
Crash. No log information. Possible segmentation fault.  But very little information is provided.

### Screenshots.
The issue happens equally in the GUI and in the Linux Command Line interfaces.

### What version of PIVX Core are you using?
Original compiled version AND self-compiled version.  Any variation of self-compiled version - same result.

### Machine specs:
- OS: Linux 16, Windows 10
- CPU: Quad core intel, 8 core intel, single core intel, quad core amd
- RAM: 2, 4 and 8
- Disk size:  40 GB
- Disk Type (HD/SDD):  SSD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

This seems to happen during ANY use of the setgenerate command.  It is noted that forked coins are not supported and if that is the stance of PIVX, so be it.  BUT, the process also cannot be used to create a new testnet network which IS within the area of responsibility of PIVX.  In any case, the setgenerate command causes both the Linux daemon and the Windows wallet to throw exceptions and shut down ungracefully.  No information is provided int the logs about the cause of the shut down.

**Comment by giaki3003** [comment]
Can confirm this issue, freshly created testnet, didn't change anything, removed checkpoints+accumulators and wanted to do some intensive use scenarios, next thing I know the miner crashes.
Ubuntu 16.04/Windows 10.
Extra: Also  
```
./pivx-cli generate 1 
```
crashes the same way

**Comment by beetledev** [comment]
![bug](https://user-images.githubusercontent.com/35567589/45081655-4342e380-b12a-11e8-9258-6e2ba3321fc9.png)
I can also confirm this issue on windows. setgenerate true crashes the wallet.

**Comment by Carbon-Zero** [comment]
It looks like RPC mining has been disabled as well - I thought that might be a viable workaround, but it no longer seems to work.

**Comment by giaki3003** [comment]
So I guess we need to go through all the commits till we find the one which removed it? And maybe revert it on a "testnet" branch so it still can be used

**Comment by Carbon-Zero** [comment]
I've tried going back to version 3.0 and it seemed to have the same problem.  It's a lot of work to go through each and test.  I'm surprised this was missed since it's the only way to create a testnet.  What's worse is that there's no sign whatsoever of what causes it - it just exits and the logging stops.  Do you have anything in your logs that would give any indication?

**Comment by giaki3003** [comment]
Will check commits regarding this and report. Debug.log over here just stops, doesn't even throw out an error. Very strange indeed. I also have debug executables which I have to analyse. Will keep this updated

**Comment by Carbon-Zero** [comment]
Correction to what I said earlier.  I've tried version 3.1, not 3.0.

**Comment by Carbon-Zero** [comment]
In syslog I was able to gain a LITTLE more information about what is  happening:.. even though I'm not sure what it means:

```ep  7 03:34:50 ip-172-31-30-236 kernel: [261704.327308] carbonzero-mine[9533]: segfault at 0 ip 000000000050454a sp 00007f2309bd7480 error 4 in carbonzerod[400000+6f6$
Sep  7 03:49:09 ip-172-31-30-236 systemd[1]: Starting Daily apt download activities...
Sep  7 03:49:15 ip-172-31-30-236 systemd[1]: Started Daily apt download activities.
Sep  7 03:53:23 ip-172-31-30-236 dhclient[883]: DHCPREQUEST of 172.31.30.236 on eth0 to 172.31.16.1 port 67 (xid=0x302804fe)
Sep  7 03:53:23 ip-172-31-30-236 dhclient[883]: DHCPACK of 172.31.30.236 from 172.31.16.1
Sep  7 03:53:23 ip-172-31-30-236 dhclient[883]: bound to 172.31.30.236 -- renewal in 1770 seconds.
Sep  7 04:17:01 ip-172-31-30-236 CRON[9873]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Sep  7 04:22:53 ip-172-31-30-236 dhclient[883]: DHCPREQUEST of 172.31.30.236 on eth0 to 172.31.16.1 port 67 (xid=0x302804fe)
Sep  7 04:22:53 ip-172-31-30-236 dhclient[883]: DHCPACK of 172.31.30.236 from 172.31.16.1
Sep  7 04:22:53 ip-172-31-30-236 dhclient[883]: bound to 172.31.30.236 -- renewal in 1414 seconds.
Sep  7 04:46:27 ip-172-31-30-236 dhclient[883]: DHCPREQUEST of 172.31.30.236 on eth0 to 172.31.16.1 port 67 (xid=0x302804fe)
Sep  7 04:46:27 ip-172-31-30-236 dhclient[883]: DHCPACK of 172.31.30.236 from 172.31.16.1
Sep  7 04:46:27 ip-172-31-30-236 dhclient[883]: bound to 172.31.30.236 -- renewal in 1739 seconds.
Sep  7 04:52:16 ip-172-31-30-236 kernel: [266350.606547] pivx-miner[24091]: segfault at 0 ip 000000000050463a sp 00007faf24ff7480 error 4 in pivxd[400000+6f6000]
Sep  7 04:57:39 ip-172-31-30-236 kernel: [266674.098445] pivx-miner[24157]: segfault at 0 ip 000000000050463a sp 00007f31fa7fa480 error 4 in pivxd[400000+6f6000]
```
'

**Comment by giaki3003** [comment]
Yes, already looked around and this definitely looks like a seg fault.

**Comment by giaki3003** [comment]
If you're able to generate with the changes you added, then it's definetely negative arrays. But I don't think that's the issue. I'll try later and let you know, thanks for the info

**Comment by Carbon-Zero** [comment]
Actually, I think this might be right, at least partially.  The segfault doesn't happen when you setgenerate true and there are already more than [some] number of blocks.

**Comment by Carbon-Zero** [comment]
If I comment out that section of code altogether, the setgenerate true no longer crashes the client, but I get this repeated in the debug logs:

2018-09-07 20:27:34 CreateNewBlock(): total size 1000
2018-09-07 20:27:34 ERROR: CheckTransaction() : txout.nValue negative
2018-09-07 20:27:34 ERROR: CheckBlock() : CheckTransaction failed

**Comment by Carbon-Zero** [comment]
Adding the line from the old miner:
```pblock->vtx[0].vout[0].nValue = GetBlockValue(pindexPrev->nHeight);```
DOES solve the problem of the txout.nValue negative, but now says the coinbase script size is 0...

```ERROR: CheckTransaction() : coinbase script size=0
2018-09-07 21:55:44 ERROR: CheckBlock() : CheckTransaction failed
2018-09-07 21:55:44 CreateNewBlock() : TestBlockValidity failed
```

**Comment by whidrasl** [comment]
@Carbon-Zero have you seen my comment?
I suppose, that next your step (and last step before generation can start) is to move this line:
`pblock->vtx[0].vin[0].scriptSig = CScript() << nHeight << OP_0;`

but this is not the full solution, because 'getblocktemplate' calls this function and fails if block can't pass check (for example, hash is bigger, than nBits). I suppose that block template must not be checked for hash, but when it was broken - I haven't found yet.

**Comment by giaki3003** [comment]
"...the PIVX code causes a segmentation fault when trying to get the hash of block -10 - *because this code doesn't ever expect the block height to be less than the chain length at the time of writing the code* and it's not the only example in the PIVX codebase."

Found this online, and it was stated by some PIVX dev. This mean this doesn't belong here, since there's no need for a miner (their words) and whoever is working on a testnet/regtest/fork/clone can go and fuck himself. lol

**Comment by giaki3003** [comment]
For some reason i had to go through this regardless, here's the fix 

``` c
	uint256 hashBlockLastAccumulated = chainActive[nHeight - (nHeight % 10) - 10]->GetBlockHash();
 	LogPrintf("CreateNewBlock hashBlockLastAccumulated \n");
	if (nHeight >= pCheckpointCache.first || pCheckpointCache.second.first != hashBlockLastAccumulated) {
	    LogPrintf("CreateNewBlock pCheckpointCache \n");
 	    //For the period before v2 activation, zPIV will be disabled and previous block's checkpoint is all that will be needed
	    pCheckpointCache.second.second = pindexPrev->nAccumulatorCheckpoint;
	    if (pindexPrev->nHeight + 1 >= Params().Zerocoin_Block_V2_Start()) {
	        LogPrintf("CreateNewBlock Zerocoin_Block_V2_Start \n");
 	        AccumulatorMap mapAccumulators(Params().Zerocoin_Params(false));
	        if (fZerocoinActive && !CalculateAccumulatorCheckpoint(nHeight, nCheckpoint, mapAccumulators)) {
	            LogPrintf("%s: failed to get accumulator checkpoint\n", __func__);
	        } else {
		    LogPrintf("CreateNewBlock pCheckpointCache \n"); 	
	            // the next time the accumulator checkpoint should be recalculated ( the next height that is multiple of 10)
	            pCheckpointCache.first = nHeight + (10 - (nHeight % 10));
 	            // the block hash of the last block used in the accumulator checkpoint calc. This will handle reorg situations.
	            pCheckpointCache.second.first = hashBlockLastAccumulated;
	            pCheckpointCache.second.second = nCheckpoint;
	        }
	    }
	}
	
	LogPrintf("CreateNewBlock nAccumulatorCheckpoint \n"); 	
```

Still a lot has to be done, such as accumulators and Zerocoin checkpointing. So i suggest you fork something else till the source doesn't get easier to work on. 

Regardless, good luck you forkers!

**Comment by Carbon-Zero** [comment]
This code is exactly the same as the original.

**Comment by giaki3003** [comment]
@Carbon-Zero grab a diff of the EAZYCommunity repo.

**Comment by Carbon-Zero** [comment]
@giaki3003 It's exactly the same as the original.  No difference at all.
