### ISSUE TITLE
Problem when creating a coin stake

### ISSUE THREAD

**Issue by licobc** [PIVX-Project/PIVX#728]
I believe there is a problem for the method CreateCoinStake (wallet.cpp)

my question is regarding line 2993
nCredit += stakeInput->GetValue();
Shouldn´t it be only:
nCredit = stakeInput->GetValue();
I see a problem when the line 3002 fails
if (!stakeInput->CreateTxOuts(this, vout, nCredit))

**Comment by Warrows** [comment]
nCredit is initialized to 0 a few lines above. So in this case doing either is functionally the same. Your problem is most likely unrelated to this. And we can't help you without more information.

**Comment by Warrows** [comment]
Indeed, you might be onto something. I'll have a look at this more in depth.
Have you been encountering any bug or just found this while reading the code?

**Comment by Fuzzbawls** [comment]
AFAIK, it is extremely rare that one valid kernel fails to produce a valid or accepted block, but another **does**...in the same iteration of the overall loop.

Still...something worth looking at.

**Comment by random-zebra** [comment]
Agreed it is something worth looking into.
Thanks @licobc for pointing this out.

**Comment by licobc** [comment]
you´re welcome, I am happy that I was correct in my assumptions!
I have found doing a code review.
