### ISSUE TITLE
aarch64 builds don't produce the Qt GUI wallet

### ISSUE THREAD

**Issue by Fuzzbawls** [PIVX-Project/PIVX#74]
aarch64 builds need special hand-holding for Qt and supporting libs.

**Comment by patcheen** [comment]
Is there an alternative method for launching the Wallet on RPi3 without the QT executable?

**Comment by Fuzzbawls** [comment]
@patcheen `pivxd` and `pivx-cli`

but keep in mind that aarch64 requires both a 64-bit processor (which the RPi3 has) AND a 64-bit OS, which raspbian is not.

**Comment by Fuzzbawls** [comment]
Problem discovered to be an ICE (Internal Compiler Error) with the cross toolchain available for Ubuntu 14.04 (gcc 4.8 based). 

Alternative solution would be to use the gcc 4.9 based cross toolchain, but it is not available on Ubuntu 14.04 (which is used by Travis and Gitian currently)

**Comment by Fuzzbawls** [comment]
fixed with v3.0.0
