### ISSUE TITLE
overflow in spork rpc system using int64

### ISSUE THREAD

**Issue by bumbacoin** [PIVX-Project/PIVX#746]
### Describe the issue

overflow issue with spork rpc message.
it uses int64 which will overflow at 2147483647

or GMT: Tuesday, January 19, 2038 3:14:07 AM

#### If so, please list the steps to reproduce below:

with correct sporkkey.

send spork message 
spork SPORK_8_MASTERNODE_PAYMENT_ENFORCEMENT 2147483648

results in -ve time value
  "SPORK_8_MASTERNODE_PAYMENT_ENFORCEMENT" : -2147483648,

https://github.com/PIVX-Project/PIVX/blob/master/src/spork.cpp#L233

**Comment by Fuzzbawls** [comment]
which version of PIVX Core are you using? or is this from a forked project?

**Comment by bumbacoin** [comment]
my mistake,
it was on a recent(ish) clone and the code looked similar on first inspection.
i just tested and it current source does not have same issue.

closing
