### ISSUE TITLE
 error: Detected unsupported SSL version

### ISSUE THREAD

**Issue by Loonie-Network** [PIVX-Project/PIVX#748]
This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Discord](https://discord.pivx.org).

### Describe the issue
So I downloaded the source code and all the dependencies required for Unix machines.
I then ran the build commands as follows:
./autogen.sh
./configure
make

It begins the compilation process and then suddenly stops with the following error.

**error: Detected unsupported SSL version: This is NOT supported, and may break consensus compatibility! Use '--with-unsupported-ssl' if you don't care**

### Actual behavior
error: Detected unsupported SSL version: This is NOT supported, and may break consensus compatibility! Use '--with-unsupported-ssl' if you don't care

### What version of PIVX Core are you using?
commit ID, 916d332. Self-build.

### Machine specs:
- OS: Ubuntu 18.04
- CPU: intel core i5
- RAM: 4GB
- Disk size: 500GB
- Disk Type (HD/SDD): HSDD

**Comment by Warrows** [comment]
Details and solution are in the error message.
Your system is most probably using openssl 1.1 which is not the officialy supported version. Either use 1.0.1 or run again configure with the given option.

**Comment by Fuzzbawls** [comment]
As previously mentioned, this is an intended behavior as OpenSSL 1.1.x isn't supported. Seems that newer versions of Ubuntu (Bionic) ship with 1.1 by default, so you may need to instead do an `apt-get install libssl1.0-dev` **instead** of the standard `libssl-dev` as outlined in the docs.

**Comment by Loonie-Network** [comment]
I installed openssl1.0 and it's fine now. You may close this issue. Thank you.
