### ISSUE TITLE
how to get testnet coin

### ISSUE THREAD

**Issue by chengmiaook** [PIVX-Project/PIVX#753]
i am not know to get pivx testcoin,how can i get it, i use pivx core wallet(testnet) my testnet address is 
yJSSBWrV2VCa6xTwiFeNCpeXeWTVMHoD2u
help me please

**Comment by Fuzzbawls** [comment]
are you still in need of testnet coins? typically one would ask on discord but I can send you some.

**Comment by chengmiaook** [comment]
yes I need please ,my address is yGBkBpzcGvZN4pnCB6kyvFgmkBBAUAFGny ,thank you very much!

**Comment by chengmiaook** [comment]
i find it long time ,but not find it

**Comment by Fuzzbawls** [comment]
cheers, enjoy.

closing this now.

**Comment by BernandoLR** [comment]
Hello Mr.Fuzzbawls
i want to implementatio POS using Pivx but i want to try in testnet network. 
can i get pivx coin for testnet ?
Please send pivx coin to my wallet y57e5gmtjkbwSy1K47cFN7zaJJRKxCyRRV  about 10.000

**Comment by Warrows** [comment]
https://faucet.pivx.link/

**Comment by BernandoLR** [comment]
it's long time to enter to my walllet?
how long the estimation to enter my wallet?

Thank you

**Comment by foxrtb** [comment]
can i get some coins to for testnet pivx wallet ?

thanks
y1TwuKBejW3dJqbG6uj2W7EWsRcWcjrQfu

**Comment by Warrows** [comment]
Any user looking for testnet coins should first try https://faucet.pivx.link/.
If it happens to be empty or under maintenance, head over to https://discordapp.com/invite/jzqVsJd and ask there.
