### ISSUE TITLE
new code doensn't use qt translation - tr()

### ISSUE THREAD

**Issue by bitnukl** [PIVX-Project/PIVX#76]
The pivx only features can't be translated like the rest of the project.
Any planes on addressing the code for the trading window, obfuscation, masternodes and so on?

**Comment by Fuzzbawls** [comment]
This will be addressed eventually, yes.

**Comment by Fuzzbawls** [comment]
@bitnukl please head on over to https://www.transifex.com/pivx-project/pivx-project-translations

source strings were updated a few days ago

**Comment by bitnukl** [comment]
Thanks @Fuzzbawls good to see some progress there.
Any chance to save the "old" translated strings? Some languages were near 100% complete and are back to 0% now.

**Comment by Fuzzbawls** [comment]
unfortunately, the "old" strings were done in a way that was/is not compatible with the wallet update process. This was an oversight in how the transifex project was initially setup and not something that translators did wrong.

**Comment by bitnukl** [comment]
Of course its not the translators fault. But they might not be very happy if all their work is "gone".

Perhaps you could help them and link the old translations files (https://github.com/PIVX-Project/PIVX/tree/master/src/qt/locale) in the transifex teams sites. So at least its possible to copy some of the strings via hand.

**Comment by Fuzzbawls** [comment]
all strings should now be running through transifex. There is nothing we can do about previous improperly uploaded strings (which weren't translated by anyone on transifex anyways).

Closing
