### ISSUE TITLE
Minning

### ISSUE THREAD

**Issue by DanielAbsi** [PIVX-Project/PIVX#765]
Hi I creat a wallet but I am on the new verson of the PIVIX and I don't know how to start minging I meen I don't have anny start button on the 3.1.1
Thank you.

**Comment by Fuzzbawls** [comment]
PIVX is no longer a PoW coin.

**Comment by Warrows** [comment]
Like Fuzzbawls said, there is no mining in PIVX anymore. Have a look at staking instead: https://pivx.freshdesk.com/support/solutions/articles/30000024636-staking-faq
