### ISSUE TITLE
pivxd RAM usage / RPi support

### ISSUE THREAD

**Issue by givanse** [PIVX-Project/PIVX#766]
### Describe the issue

Hi, is anyone running a node on a Raspberry Pi? **Consistently**? Last time I tried it kept dying after a few ours, the RPi crashed. Pretty sure due to a lack of RAM.

Right now I have a node running on a beefy machine. The pivxd process is using about 1.7GB of RAM. No way I can squeeze that into a RPi without some meaningful optimizations.

### What version of PIVX Core are you using?
```
pivxd --version
Pivx Core Daemon version v3.1.1
```

### Machine specs:
- OS: Ubuntu 18.04.1 LTS
- CPU: AMD Ryzen 7 1700 Eight-Core Processor
- RAM: 16GB
- Disk size: 256GB
- Disk Type (HD/SDD): SDD

**Comment by Fuzzbawls** [comment]
No details, closing.
