### ISSUE TITLE
rpc listtransaction not get watch-only transaction

### ISSUE THREAD

**Issue by chengmiaook** [PIVX-Project/PIVX#773]
### Describe the issue
importaddress "xyTzPQesWZQ3KXFXat3PcgZ5an934K1Zuh"
i import my address "xyTzPQesWZQ3KXFXat3PcgZ5an934K1Zuh" into pivx core, it is a watchonly address,
then i send the address 2 tpivx, the transaction id is "695b4e4e2024755f2ab52f64c7c69b2051e2e257770a65b007c61bf62553d613"
then i use 
listtransaction  "" 200 0 true in the pivx core ,but i get none, why? how can i get it please!

**Comment by chengmiaook** [comment]
i use the testnet

**Comment by Fuzzbawls** [comment]
which version of the wallet are you using? just repeated the commands you used and it returned a single receive transaction as expected (the spend transaction doesn't show because the wallet doesn't have knowledge of all the keys used in the transaction).

**Comment by Fuzzbawls** [comment]
closing, no further information
