### ISSUE TITLE
Getting error:  "Calculated accumulator checkpoint is not what is recorded by block index" when opening wallet.

### ISSUE THREAD

**Issue by combstraight** [PIVX-Project/PIVX#780]
When I open the wallet, I get this error pop-up message:  

"Calculated accumulator checkpoint is not what is recorded by block index"

PIVX-qt shuts down after error message.

I am using PIVX Core v3.0.6 on Mac OSX

**Comment by Warrows** [comment]
3.0.6 is outdated. You have to upgrade your walllet. And most likely you are on a fork and you'll have to resync the chain.
