### ISSUE TITLE
MacOS compile error fixes

### ISSUE THREAD

**Issue by pav-hash** [PIVX-Project/PIVX#784]
src/accumulators.cpp  -  line 24
change:  int post = distance(...
to:  int post std::distance(....

src/qt/multisenddialog.cpp  -  line 14
add:  #include <QStyle>

**Comment by suryakss** [comment]
small correction:
change: int post = distance(...
to: int post; std::distance(....

**Comment by Fuzzbawls** [comment]
This is an incomplete issue report. please re-submit following the issue template's guidelines, or submit a pull request if you have code changes you'd like to propose.
