### ISSUE TITLE
Bring PIVX random on par with bitcoin

### ISSUE THREAD

**Issue by Warrows** [PIVX-Project/PIVX#799]
This issue is dedicated to keeping track of progress for the process of bringing random.cpp file up to the latest bitcoin version. It's related to #643 and aims to keep info on the WIP updated without crowding the PR with "useless" info.

- [X]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/8c1dbc5e9ddbafb77e60e8c4e6eb275a3a76ac12 (https://github.com/PIVX-Project/PIVX/pull/802)
- [x] Merge https://github.com/PIVX-Project/PIVX/pull/643
  - [X] Cherry-pick https://github.com/bitcoin/bitcoin/pull/9821 (in https://github.com/PIVX-Project/PIVX/pull/643)
    - [X]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/224e6eb089a0f4977d22f3803fc27e44b5e7eea5
    - [X]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/7cad84929907c4294f07377453aa77887911b486
    - [X]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/7e6dcd9995b99e894b8017f09016c405b066ca36
  - [X]  Cherry-pick https://github.com/bitcoin/bitcoin/pull/8914 (in https://github.com/PIVX-Project/PIVX/pull/643)
    - [x] Merge #902 (Backport https://github.com/bitcoin/bitcoin/pull/6720 and https://github.com/bitcoin/bitcoin/pull/7212)
      - [x] Merge #806 (Backport https://github.com/bitcoin/bitcoin/pull/5883 and https://github.com/bitcoin/bitcoin/pull/5852)
      - [X] Merge #800
      - [X] Merge #798
  - [x] Cherry-pick https://github.com/bitcoin/bitcoin/pull/9792
    - [x]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/16329224e70d0525208f6b0ba00c5e1531a4f5ea
  - [x]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/97477c537e9e9d9b9a14ec2f965c9c6121ac818b
  - [x]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/f544094d5e1ee627ebd34542aead7bf1241fae19
  - [x]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/33f853d8d88917b145e2793bf8eb1b4e3790e7e7
  - [x]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/2c0a6f157da3c6bb3b0a1e77f003caf0d9cb9d6c
  - [X]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/399fb8f2d0fa9cff2f461ef2c0da5b91765987f1
  - [X]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/888cce57a67c901b89c86cc645f275071d021285
  - [x] Backport https://github.com/bitcoin/bitcoin/pull/10321
    - [x]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/37e864eb9fee4b592bd61c5ec3555b00a2de2cf7
  - [x]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/cb24c8539d1098d1a61605b452ecfa11a693320d
  - [x]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/9af207c810b5c4b09ccbdec75582b3e34e32e8cc
  - [x]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/a9e82f6512662054f64ed2bde590b2bb0831fc9d
  - [x]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/674848fe1c43fb88870cf5ba16fca4e2524da793
  - [x]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/a8ae0b252a2007568e77f5aca1c7fa3ec5941b72
  - [x]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/b82c55af78738258b56bd8fe7b5f8d5ccf85f832
  - [x]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/077d01f2fcc305809f084ccc34badc531ae2f30a
  - [x]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/ee2d10ad0c0e04d0b9da4535a6fff265ac2501e5
  - [x]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/8d98d426116f0178612f14d1874d331042c4c4b7
  - [x]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/e414486d56b9f06af7aeb07ce13e3c3780c2b69b
- [x]  Backport https://github.com/bitcoin/bitcoin/pull/14955
- [ ]  Backport https://github.com/bitcoin/bitcoin/pull/15224
- [ ]  Backport https://github.com/bitcoin/bitcoin/pull/15250
- [ ]  Backport https://github.com/bitcoin/bitcoin/pull/15324
- [ ]  Backport https://github.com/bitcoin/bitcoin/pull/15512
- [ ]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/84f41946b9026e8bf7bc44ed848dfb945394b693
- [ ]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/c865ee1e73b65fa2e0283e386a9ab35d83f7af99
- [ ]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/9c4dc597ddc66acfd58a945a5ab11f833731abba
- [ ]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/385ad110400bc9646dcf2e38b64b7080182a7344
- [ ]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/190bf62be1214b072513c7fd7e01cc191723967c
- [ ]  Cherry-pick https://github.com/bitcoin/bitcoin/commit/2068f089c8b7b90eb4557d3f67ea0f0ed2059a23

**Comment by furszy** [comment]
Completed merging 2278, closing.
