### ISSUE TITLE
Building PIX on windows 10 under WSL

### ISSUE THREAD

**Issue by sepavel** [PIVX-Project/PIVX#801]
I have trying to build PIX on Windows under WSL using instruction from 
[here](https://github.com/PIVX-Project/PIVX/issues/640)

I have on WSL

> gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)

(should I use gcc 5.3?)
and latest Win SDK

> "C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0" 

And I got error during "depends" compilation

> compiling qwin10helpers.cpp
> qwin10helpers.cpp:60:37: fatal error: uiviewsettingsinterop.h: No such file or folder

What is the reason of error? How can I provide this file?

**Comment by Warrows** [comment]
I think you need Ubuntu 18.04 or higher now.

**Comment by sepavel** [comment]
thank you

I have updated WSL to Ubuntu 18.04 and have compiled "depends"

**Comment by Warrows** [comment]
Is everything good then? If so please close the issue, if not let us know what's still amiss.
