### ISSUE TITLE
How to get coin on regtest mode?

### ISSUE THREAD

**Issue by viettienbk** [PIVX-Project/PIVX#805]
### Describe the issue
- I started PIVX node on regtest mode: `pivxd -regtest -printtoconsole`
- I want to use PIVX cli to get coin to test: `pivx-cli -regtest setgenerate true`, but it failed: `error: couldn't connect to server`
So, please help me to get coins on regtest mode?

### What version of PIVX Core are you using?
PIVX Core version 3.1.1

### Machine specs:
- OS: Ubuntu 16.04
- CPU: 2
- RAM: 8GB
- Disk size: 1TB
- Disk Type (HD/SDD): HD

**Comment by lightingcoders** [comment]
do you have firewall enabled ?

**Comment by viettienbk** [comment]
> do you have firewall enabled ?
No, I don't

**Comment by viettienbk** [comment]
@lightingcoders : I disabled firewall
