### ISSUE TITLE
Right clicks on Governance tab causing hard crash of wallet with no debug.log entries

### ISSUE THREAD

**Issue by CryptoDev-Project** [PIVX-Project/PIVX#823]
The wallet crashes when on the new Governance tab and right clicking on a specific proposal. At times, the first right click will not cause a crash - but the second, almost certainly, will.

 Can you reliably reproduce the issue? Yes

1. Update Proposals
2. Right click on the top 1-2 times

### Expected behavior
Depending on the developers intentions, it may be to have a right click function in the same way as a left click. However, the likely desire is to have right clicks perform no function in this area. As such, addition of the three lines of code shown below (to src/qt/proposalframe.cpp) is one option that should do the trick.

```
#include <QMouseEvent>
..
..
..
void ProposalFrame::mouseReleaseEvent(QMouseEvent* event)
{
    if (!governancePage) //TODO implement an error
        return;

    if (event->button() == Qt::RightButton)
        return;

    extended = !extended;
    if (extended)
        governancePage->setExtendedProposal(proposal);
    else
        governancePage->setExtendedProposal(nullptr);
}
```
### Actual behavior
The wallet crashes.

### What version of PIVX Core are you using?
Self compiled from master

**Comment by Warrows** [comment]
Thanks for the report, I'll have a look today. Which os are you using ?

**Comment by CryptoDev-Project** [comment]
Apologies, it's Windows 10 version I'm using.

**Comment by Fuzzbawls** [comment]
macOS seems to not suffer from this, just FYI

**Comment by Warrows** [comment]
No apparent problem with Debian either. I can indeed reproduce on windows, I didn't test the proposed fix yet because while investigating I found a possible stack corruption issue with Qt. Might be related to the windows 64 bits toolchain. 
@CryptoDev-Project Are you using 64 or 32 bit windows. Did you compile with wsl? With depends? Is your exe 32 or 64 bits?

**Comment by CryptoDev-Project** [comment]
@Warrows It wasn't a wsl compile. It was just a standard gbuild and it was 64 bit used. I didn't test the 32 bit exe.
