### ISSUE TITLE
wrong design colour of frames

### ISSUE THREAD

**Issue by TGW69** [PIVX-Project/PIVX#853]
In the mac version, the inside frames are colored pink instead of purple which gives the impression of a test version not the final product!

**Comment by Fuzzbawls** [comment]
please follow the issue template guidelines and provide complete details. Since this is about the GUI, also include a screenshot of the issue.

**Comment by TGW69** [comment]
See attached


Verstuurd vanaf mijn iPhone

**Comment by Fuzzbawls** [comment]
going to have to close this as incomplete. replying by email with attachments doesn't actually update the issue on github. If you want to create a new issue report or edit this one's original description, then it can be looked at.
