### ISSUE TITLE
 Illegal instruction - in ARM binaries

### ISSUE THREAD

**Issue by grigio** [PIVX-Project/PIVX#86]
i don't know, are these bins for raspberry pi 2, 3 or both? I have rpi 2
```
$ uname -a
Linux raspberrypi 4.4.50+ #970 Mon Feb 20 19:12:50 GMT 2017 armv6l GNU/Linux
$ file pivxd
pivxd: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, BuildID[sha1]=219665deddfb094eaa28c775e682b8d3af6251ab, stripped
$ ./pivxd
Illegal instruction
```

**Comment by grigio** [comment]
I think it's related to this http://stackoverflow.com/questions/20961862/flag-for-cross-compiling-for-armv6l-with-arm-linux-gnueabi-gcc
is possible to provide binaries also for the architecture `arm-none-linux-gnueabi-gcc` ?

**Comment by Fuzzbawls** [comment]
Raspberry Pi A/B/B+ are extremely outdated and outclassed now days and are not on our list of supported devices for distribution binaries.

I don't have the device on hand to do proper testing for this, so you will likely need to do self-compiles or drop $30 USD to get a newer Pi.

**Comment by grigio** [comment]
ok, thanks for the advices. Just a little OT are there any guides about `pivx-cli/pivxd`  / command line usage? I tried several arguments but I'm not able to know if i'm in `staking mode` or not.

**Comment by Fuzzbawls** [comment]
running `pivxd -help` or `pivx-cli help` will get you more information about available options/commands, in addition `pivx-cli help <command>` will give you help specific to the command
