### ISSUE TITLE
Deamon conflicts with other wallets. 

### ISSUE THREAD

**Issue by Byrd1083** [PIVX-Project/PIVX#871]
Windows 10 pro
Xeon 12 core
48gb ram
4x nvidia gtx 1070 
Main ssd 150gb

External sata drives:
1 - 80gb
1 - 3tb
8 - 10tb

My issue is as follows. I currently run Siawallet with 10tb and hard drive mine burst coin with 70tb. 

My siacoin wallet is installed on 80gb and allocated space to 1 - 10tb drive. 

My blocknet wallet is installed to 80gb. 

Burst coin is installed on 150gb main but allocate to 7 - 10tb. 

I ruled out drive conflicts or space sharing issues. Now my Siawallet runs stable with all my other wallets no errors or crashes ever occur. 

Siawallet must run 24x7 to be connected for their cloud storage network. 

Now, I downloaded pivx wallet v3. 2.0 and installed to 80gb since the block is so large it even said that there was not enough space on the 150gb main choose another place to install. 

I owned about $150 worth and wanted to stake them with the wallet. 

Therefore, I did just that and installed it to the free 80gb. The wallet opened and crashed several times. 

I finally just closed everything running and tried to open again to just get wierd errors and crash. 

I then rebooted the pc. 

Now, fresh boot, opened pivx. It opens correctly and begins to sync blocks. It shows the large size to be synced but no estimated time to complete other then a purple bar 👎. 

Would be better to say approximately how long to finished and a note not to do anything until complete and backup wallet first. These ques were not there for me. 

So after waiting a full 24 hours of syncing and only getting 30% synced or whatever who knows right purple bar 👎?  I was trusting the purple bar to complete correctly so I jumped the gun and created a receiving address for transfer. Then made my withdraw from my exchange to the pivx wallet. 

Now, another day goes by and the transaction has not showed up. The wallet has only synced about 75% purple bar estimate 👎. 

I get docked reputation points for being offline with Siawallet. 

Therfore, 48 hours after loading pivx wallet a decided to run my Siawallet. Guess what? Instant deamon crash. Both wallets crash. Both will not restart as they just throw service errors. Have to restart pc. 

Now, reboot, load pivx wallet. Pivx wallet errors out and it says wallet is corrupted. I hit a brick wall and can not open the pivx wallet anymore regardless. 

I have to Uninstall erase everything and reinstall to get working but I do still have my wallet backups and the first wallet created. 

Now, fresh install. Try to load backup wallets, error says wallets corrupt force close. 

I run new wallet and start syncing. Now, I let it go for 3 1/2 days and it finally syncs all blocks. Have access to wallet finally. Backup everything.

Have not ran sia this whole time. 

My transaction is now missing and the receiving wallet address I made the $150 withdraw to is gone. 

I try to rebuild the original wallet through options, says wallet corrupt can not rebuild. 

I try and load debug consol and run dump "wallet" and choose that first wallet. 

Closed wallet then moved first backup wallet that I dumped to main dir and reopened wallet. 

It accepted it and resynced. Now I'm back to having the address I sent the funds to back later under receiving address which tells me it worked. 

However, the transaction is not there. I run the find missing transactions. Restart wallet, no transactions appers. 

I have my wallet loaded, synced, stable, backup, no transaction lost my funds the end, brick wall 🤗

**Comment by Byrd1083** [comment]
Any ideas at this point on how to get my transaction back?

**Comment by Byrd1083** [comment]
I just updated my wallet to v3.2.1
So I have got my wallet to fully sync.
I have successfully loaded my first wallet that was corrupt as explained above.
I still am missing the transaction and need help getting it back.

![image](https://user-images.githubusercontent.com/42227809/56429088-80518580-6276-11e9-9119-3d6024d2e926.png)
![image](https://user-images.githubusercontent.com/42227809/56429151-c1e23080-6276-11e9-83f8-c5e98e373c5b.png)

**Comment by Warrows** [comment]
Thank you very much for your report. We will have a look at the smashing with Sia. However I think discord will be better suited to help you through the steps of getting your funds back now.

**Comment by Byrd1083** [comment]
Ah, I lost my transaction and my sanity with this error that completely ruined my perception of your product and pivx. Regardless of me losing my wallet key, the software should not have allowed this type of crashing and corruption of my data to just get installed. After 6 days of trying to work this out, support on discord has not came up with a viable solution. I completely deleted your product, I'm chucking up the loss so big pat on your back 🤗. I'm just going to share my experience across all your platforms until your product is fixed and operates as a new user would expect it to. I should not need an IT degree to stake your coin. It is completely rediculous. You have taught me a $150 lesson. That is to download and pretest wallets before I decide to contribute to that product. As this time I went in trusting your name and in the end I have a gigantic let down with no light at the end of the tunnel. Get it together guys! Good luck!

**Comment by Byrd1083** [comment]
No need to try to fix this this late in the game for me. I've already deleted everything including my wallets. IM DONE YO! keep the money as a donation. Delete discord server as I don't even want to here the bs.

**Comment by Nakamoto-san** [comment]
110% echo your sentiment – censorship happening here on the Github as well. After this experience, prefer projects that utilize zero coin protocol without the proof of stake 👀

**Comment by Nakamoto-san** [comment]
110% echo your sentiment – censorship happening here on the Github as well. Makes the PIVX project look sloppy. This coming from an outsider interested in participating in your network. Have been in crypto since the beginning and this takes the cake for worst experience with a wallet. Period.

**Comment by Warrows** [comment]
Gosh, you overwrote your wallet file. Don't try to pin this on us.

**Comment by CaveSpectre11** [comment]
@Byrd1083 ; "keep the money as a donation"...  it's in the wallet; you can see it with your screengrab of your qt... as "watch only".  Without the private key, no one can get to it.  Which means you added the address; but you didn't add the private key.  If you kept the wallet.dat file (or one of the backups) that you had when you restarted the system after creating the receive address; it may be possible to extract the private key from the wallet.

However if you did delete it in a rage after less than a day of posting; then you're pretty much out of luck.
