### ISSUE TITLE
insane fees

### ISSUE THREAD

**Issue by piratoskratos** [PIVX-Project/PIVX#881]
Sending tx by rpc (sendtoaddress) and did not set anything about the fees. Funds are provided by 1 or 2 addresses max.

Get error "insane fees" when sending small amount (under 2pivx) and the fees for any tx are someting like 0.1 pivx and up to 0.6 pivx that's way too high when we know that 0.0001 pivx are enough... So I guess we can lower these fees by /100 or /1000.

**Comment by Warrows** [comment]
How old are the input transactions you want to spend? Maybe simply waiting a few blocks will improve your situation.

**Comment by piratoskratos** [comment]
Same result with old (weeks) or recent input (mintutes). This is not better in time as this behavior is happened since weeks and with all versions (same on 3.1.0.2 to 3.2.1)

estimatefee(1) -> 0.61773275

**Comment by Warrows** [comment]
I've yet to witness this kind of behavior. Regardless of the amount, how many transactions are you trying to use as input?

**Comment by piratoskratos** [comment]
1 or 2 input max.

**Comment by Warrows** [comment]
You're sure about that, 1 or 2 inputs, not more inputs from one or two addresses?
Anyway, could you provide the content of debug.log when that happens (maybe remove transactions id and other identifying data) please?

**Comment by piratoskratos** [comment]
Yes I'm sure.

Apparently tx works since yesterday with sendtoaddress (not sendmany) : 1 input, 1(+1) output, fees ~ 0.13/0.14 pivx.
It still too high and could be way less.

EDIT : there is an old log entry
keypool added key 1514, size=1001
init message: Loading wallet... (151.25 %)
keypool reserve 514
CWallet::SelectCoinsMinConf best subset: 0.23990247 0.06377615 0.0401819 0.01015527  - total 0.35401579
CommitTransaction:
CTransaction(hash=xxx, ver=1, vin.size=1, vout.size=2, nLockTime=0)
    CTxIn(COutPoint(xxx, 8), scriptSig=xxx)
    CTxOut(nValue=0.2, scriptPubKey=OP_DUP OP_HASH160 xxx)
    CTxOut(nValue=0.3, scriptPubKey=OP_DUP OP_HASH160 xxx)
keypool keep 514
AddToWallet xxx  new
ERROR: AcceptToMemoryPool: : insane fees xxx, 40431953 > 22500000
AcceptToMemoryPool :
CommitTransaction() : Error: Transaction not valid

**Comment by Warrows** [comment]
What's your value for ``paytxfee``? (You can get it from ``pivx-cli getinfo``). Have you tried changing it with ``pivx-cli settxfee``?

**Comment by piratoskratos** [comment]
0.

'paytxfee' => 0.0,
'relayfee' => 0.0001,
