### ISSUE TITLE
Unable to sync

### ISSUE THREAD

**Issue by niex2** [PIVX-Project/PIVX#892]
When I try to sync the blockchain (I tried with bootstrap file as well) the process reaches a point where I get the error "Segmentation Fault", after I restart, I will get the error:

pivx-qt: main.cpp:2757: void RecalculateZPIVMinted(): Assertion ReadBlockFromDisk(block, pindex)' failed. Aborted

The memory usage is really high (program will quite at 4 GB)
This is a VM, based on Debian-9.

**Comment by niex2** [comment]
I will quote from **vereten** from issue #764 

> 

    I think my problem is related to this, but I'm not sure.
    When I try to sync the blockchain (I tried with bootstrap file as well) the process reaches a point where I get the error "Segmentation Fault", after I restart, I will get the error:

    pivx-qt: main.cpp:2757: void RecalculateZPIVMinted(): Assertion ReadBlockFromDisk(block, pindex)' failed. Aborted

    The memory usage is really high (program will quite at 4 GB)
    This is a VM, based on Debian-9.

Seems your issue is another issue. I was experiencing same issue when i was syncing blockchain from scratch. My workaround for your issue was: to not use pivx-qt, instead to use pivxd and wait for full sync. pivxd will crash same as pivx-qt but pivxd is able to recover from that error after restart. Then please make snapshot of whole .pivx folder for functional backup. then you can use pivx-qt.
I was syncing with this script to autorestart pivxd after any crash. Before using script please update <pivxd_path> with your latest pivxd version 3.2.2 path. Good luck.
`#!/bin/bash

while true

do

cd <pivxd_path> && ./pivxd -printtoconsole -enablezeromint=0 -staking=0

sleep 3

`
push this to file.sh than start by sh file.sh

>

**Comment by niex2** [comment]
restarting pivxd didn't solve my problem, it will always quit at block 892000

**Comment by Warrows** [comment]
Which PIVX version are you using? How much RAM do you have on your VM? How much disk space available?

**Comment by vereten** [comment]
Did you started sync from scratch by pivxd? Or you trying to continue after pivx-qt sync? For me continuing sync with pivxd after pivx-qt was not able to. i was forced to delete whole blockchain and start fresh sync again with pivxd.

**Comment by niex2** [comment]
pivx version 3.2.2
VM could have 7200 MB of RAM allocated (dynamic). 4 GB was the max I see
7.2 GB free space

**Comment by niex2** [comment]
no, I tried to continue it. I'll try to delete the blockchain.

**Comment by Warrows** [comment]
The blockchain is something like 16GB. So you're living on the edge with 7.2 GB of free space. If it's after deleting blockchain data, it is clearly not enough.

**Comment by niex2** [comment]
After deleting the blockchain I was able to sync my wallet. Synchronization was really slow, approximately 2 days.
Thanks for your help!

I don't know if I should close this issue or not, because this is still a bug, without the script that @vereten provided I couldn't sync.

**Comment by vereten** [comment]
> After deleting the blockchain I was able to sync my wallet. Synchronization was really slow, approximately 2 days.
> Thanks for your help!
> 
> I don't know if I should close this issue or not, because this is still a bug, without the script that @vereten provided I couldn't sync.

Great to hear I helped :)

**Comment by tperalta82** [comment]
Also having the same issue, at the same block, using pivxd only, the script did not work for me.
Also tried from bootstrapping, exactly same issue.

**Comment by random-zebra** [comment]
`RecalculateZPIVMinted` has been removed (ref #1359 )
