### ISSUE TITLE
Automatic fee calculation

### ISSUE THREAD

**Issue by vampyren** [PIVX-Project/PIVX#894]
This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Discord](https://discord.pivx.org).

### Describe the issue
This is actually about an improvement for the wallet. 

#### If so, please list the steps to reproduce below:
1. Lets say i have 10 PIVX in my wallet
2. Go to the SEND tab
3. Fill in 10 PIVX in the amount
4. Send

### Expected behavior
I expect the wallet to withdraw the fee from the amount automatically or give me the option to do so. 
Also it would be great if i there was a "max" link next to the "amount" field so that i can automatically fill the the max amount of PIVX i have in the wallet. Now i have to copy paste each time i want to send my mn rewards.  
### Actual behavior
The wallet tells me that there is "Insufficient funds!"

### What version of PIVX Core are you using?
3.2.2

**Comment by furszy** [comment]
The "max" button is already on the new wallet GUI, deduce the transaction fee from the value could work fine only when you are sending to a single address, when the wallet is sending to several outputs it's not possible and will cause more confusion to our users (the wallet will not know from which output value needs to deduce the fee).

Saying that, you can use the MultiSend dialog to automatic send you MN rewards.

**Comment by Warrows** [comment]
Concerning the current GUI:
The value you input in the amount field is the amount the recipient will get. So it wouldn't make sense for most users and use cases to remove the fee from this amount.
However, you can click the button ``choose...`` to open fee options and then tick the zero fee box. It should work to send a simple paiement from one single address (and UTXO) to an other.

**Comment by vampyren** [comment]
@furszy 
> The "max" button is already on the new wallet GUI, 
I dont see this, i'm using windows version. Can you maybe give some hint? i clicked on anything i can find :)
I think the most common usecase for normal users are to open the wallet and do a simple send. So this feature is very helpful in my opinion still. Having used many wallets i see this option on most of them.

@Warrows Thanks for the tips, i am aware of the 0 fee option but usually i like to pay the fee for both supporting the network and faster transaction. 

I hope you guys can consider this feature even if there are corner cases that might not be valid for this feature. Mostly users open the wallet , put in an address and want to send (i think).
