### ISSUE TITLE
Tor masternode expired/removed after restart

### ISSUE THREAD

**Issue by borris345** [PIVX-Project/PIVX#907]
Masternode resets tor advertising address and kicks out of active nodes on computer restart.

Masternode conf is setup correctly and is bind to a tor address already created using torrc.

Even with bind in the conf and torrc setup correctly wallet creates another advertising address by default. Assume this is why it gets kicked out?

Does the wallet when restarted delete the tor config file in the pivx folder and reset the IP for another advertising tor address? If so is there away to disable this so even with computer restart it will keep the same ip which should keep me in the q.

**Comment by Fuzzbawls** [comment]
not able to reproduce this. i've a few nodes running on tor who have maintained the same onion address for over a year (across multiple wallet updates). They're all using the auto-allocation of hidden service.

**Comment by borris345** [comment]
Can you copy and paste what should be in the pivx.conf please.

**Comment by Fuzzbawls** [comment]
nothing tor related in the `pivx.conf` file other than the `masternodeaddr` being set to the `.onion` address I first received...using the wallet's ability to automatically detect and integrate into the Tor service via it's control port and auth cookie.

See section 3 of the [tor.md](https://github.com/PIVX-Project/PIVX/blob/master/doc/tor.md#3-automatically-listen-on-tor) file for details on this functionality.

Note: my setup results in a triple-stack node, being available and reachable on IPv4, IPv6, and Tor. The above linked doc outlines some startup/conf switches you can use to limit this if you wish, but has no effect on the MN status.
