### ISSUE TITLE
Many Conflicts for Minted Transactions after Staking for 3 days

### ISSUE THREAD

**Issue by vzool** [PIVX-Project/PIVX#91]
Hi,
I have a weird situation  that I staked my coins for 3 days and I have mined twice successfully. but after that all minted transactions are in conflicts mode, I don't know what is going on !!!

Here is the pictures for the wallet.

![screenshot from 2017-04-05 11-17-04](https://cloud.githubusercontent.com/assets/4952736/24696449/2ddaad46-19f2-11e7-90fa-b6d9aa3ffbc9.png)

The Transactions:
![screenshot from 2017-04-05 11-18-15](https://cloud.githubusercontent.com/assets/4952736/24696428/1b96d79a-19f2-11e7-9d3b-c1a28509d095.png)

### Conflicted Minted Address
 
- DNh899QUfpDjcTHxFQr2ardaNxmMbMzS2H
- DTX6jQQ8CaLg9obWHjk9TE6YqEyLfbP79A
- DDkS3T1f6hbXF6ydF2uZy6kULmLCbEAzTE

### Transactions

- 954e9bf08726ae5641a328c93ebcb867127e8077b27043588204d9c4fb032052-000
- 61ef36f3fb7c12535b87bcad58871d087f46f0818bb40b1867b1fbbecd39056a-000
- 2a0b67e95bcacebca0be30cd0e7deb5f9bb9a82f2eb2377e3153be639a93a1a0-000
- 0e8a10c551abcecc945e93cc51bf55872fba8d20bc0cd5fe40c40c358eabc376-000

Even so, I delete all blockchain and download the backup again, same issue still exists !!!

What do you think?

Thanks

**Comment by Fuzzbawls** [comment]
Those are known as Orphans: You minted a block at a similar time as someone else. Because both you and another were proposing the same block height, only one can be accepted by the network.
