### ISSUE TITLE
[UI] Minor - Bad order when sorting by "Active" in the Masternodes tab

### ISSUE THREAD

**Issue by sabhiram** [PIVX-Project/PIVX#92]
If you sort the MNs by "Active" time, it will place `9d` as older than `99d`. This should be super easy to fix :)

**Comment by sabhiram** [comment]
Could someone point me out to where `ui_masternodelist.h` is included from? Also do we have a coding standard document?

**Comment by Fuzzbawls** [comment]
https://github.com/PIVX-Project/PIVX/blob/master/src/qt/masternodelist.cpp#L2

Current coding standards doc: https://github.com/PIVX-Project/PIVX/blob/master/doc/coding.md (this will be changing to a different filename shortly)

**Comment by sabhiram** [comment]
The simple way to fix this would be to fix DurationToDHMS to pad days like we do hours, but thats icky.

The right way to fix this is to probably subclass `QTableWidgetItem` to something like DHMSTableWidgetItem which is constructed using the duration in seconds and automagically uses that private member to do the comparison while displaying some nicely human friendli-ized text. 

If this is not fixed in the next few days, and I find myself wanting to compile my wallet - ill take a stab at this :)
