### ISSUE TITLE
Windows 64 GUI wallet, missing Exit icon.

### ISSUE THREAD

**Issue by RottenCoin** [PIVX-Project/PIVX#931]
Windows 64 GUI wallet.
 File/Exit Icon missing.
![pivx](https://user-images.githubusercontent.com/38838284/59758364-ad75e080-9285-11e9-9462-0bc60c4ed5ff.jpg)

**Comment by Fuzzbawls** [comment]
it isn't missing, that **IS** the icon.

https://github.com/PIVX-Project/PIVX/blob/master/src/qt/res/icons/quit.png
