### ISSUE TITLE
Previously rejected SwiftX lock causing conflict with newer valid lock

### ISSUE THREAD

**Issue by Fuzzbawls** [PIVX-Project/PIVX#942]
A potential race condition exists wherein a rejected SwiftX transaction input is added to `mapLockedInputs`, which is checked during `AcceptToMemoryPool()` and `CheckBlock()`.

If a new SwiftX transaction is initiated using the same input **PRIOR** to the default 1 hour "timeout" for retaining the record in `mapLockedInputs`, acceptance will fail again, even if the SwiftX transaction is otherwise valid.

**Comment by furszy** [comment]
No swiftX for now, closing.
