### ISSUE TITLE
Update Gitian Build Guide

### ISSUE THREAD

**Issue by Fuzzbawls** [PIVX-Project/PIVX#945]
The Gitian build guide is quite outdated now and is in need of updating.

Goals for new documentation:

- Migrate from using VirtualBox to Docker in guide examples
- Tighter integration with the `gitian-build.py` script (less reliance on multiple commands)
- (re)write concise and complete instructions for the following host OSes:
  - Ubuntu/Debian
  - Fedora/CentOS
  - Windows 10
  - macOS

Rationale for migrating to Docker: Gitian added native docker support in June of 2018, which provides a much easier solution when compared to LXC and KVM virtualization options (less to setup/configure). Docker is also universally available outside of linux distributions, which allows us to cut out an intermediary virtual machine setup.

**Comment by random-zebra** [comment]
In #1176
