### ISSUE TITLE
Wallet crashes while in governance tab

### ISSUE THREAD

**Issue by Warrows** [PIVX-Project/PIVX#946]
Issue submitted on behalf of ICTJ user of the discord.

### Describe the issue
Engaging with governance tab freezees and crashes the wallet.

### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. Start the wallet
2. Open governance tab
3. Start using it

### Expected behavior
Nothing

### Actual behavior
Wallet crashes

### Screenshots.
![unknown](https://user-images.githubusercontent.com/835098/61032449-c32c8080-a3c1-11e9-92e4-fefdef10a4bb.png)

### What version of PIVX Core are you using?
Release 3.3. Was working fine before

**Comment by Fuzzbawls** [comment]
no problems on macOS. need to know what version of Windows (and if it is 32-bit or 64-bit) this error is from.

**Comment by Warrows** [comment]
English wallet interface, Win7 x64.

**Comment by akshaynexus** [comment]
I've seen this issue happen on only windows 7 users,afaik probably a platform issue as on macos it works fine and Linux aswell.

**Comment by CaveSpectre11** [comment]
Fairly certain it was W7 I was trying to reproduce on; but maybe I didn't click around enough.

**Comment by akshaynexus** [comment]
From another PIVX fork, what i've seen causing the crash is clicking the vote buttons, the hyperlink to the proposal  works, but voting buttons sometimes crashes the wallet in windows 7.

**Comment by Warrows** [comment]
Invalid since the governance tab has been removed and is scheduled to be redone from scratch in the new GUI.
