### ISSUE TITLE
[Tests] Add regtest tests for budget RPC commands

### ISSUE THREAD

**Issue by Fuzzbawls** [PIVX-Project/PIVX#966]
Currently, none of the budget RPC commands are checked in the test suite. Since #950, #964, and #965 all aim to improve areas of the budget RPC code, it would make sense to top it off with some regression testing.

ToDo:
- [x] Finalize and merge #950, #964, and #965 
- [x] Review error return types for all budget related commands
- [x] Write regtest script

This issue is for tracking purposes, and will be updated as work progresses.

**Comment by random-zebra** [comment]
Addressed in #981
