### ISSUE TITLE
[TODO] Wallet startup taking too long (Review).

### ISSUE THREAD

**Issue by furszy** [PIVX-Project/PIVX#969]
This issue tracker is only for tracking purpose and surely will encompass several commits in different areas of our product.

Basically, the startup is taking too long. Needs a full code review, cleanup and possibly work parallelization.

**Comment by borris345** [comment]
This one is definitely needed. If you have alot of transactions and use a really old backup it takes forever

**Comment by akshaynexus** [comment]
can a debug log be provided to understand the cause of this slow startup?or maybe a way to reproduce this issue

**Comment by borris345** [comment]
It's the rescan. Haven't got a wallet you can use to reproduce it.

**Comment by CaveSpectre11** [comment]
For a basic wallet; it looks like about 75% of the startup is grinding through `LoadBlockIndexGuts()`

**Comment by borris345** [comment]
Anything been looked into?

**Comment by akshaynexus** [comment]
I'll be looking into it this week once I have some free time, looks like the problem is more noticeable when loading a new wallet with the HD addition I have, compared to the normal wallet creation.

**Comment by furszy** [comment]
#1012 will improve this. Still lot of work to do in many areas, not one final solution.

**Comment by furszy** [comment]
Have started a new project to organize the work (review, refactor, cleanup and improvements) of the whole initialization process. https://github.com/PIVX-Project/PIVX/projects/27 .
Started moving there with #1029.

I will be organizing all of the efforts in the area. If anyone want to be part of it, please create an issue of the problem that want to solve (independently if can solve it or not) and/or the back port that want to do and will add it to the kanban board. Be technical and specific on the description.

More hands are more than welcome, meanwhile will continue advancing alone on the area.

**Comment by furszy** [comment]
Closing, after all of the improvements the past year + 2209 this is not a problem anymore.
